package gehos.autenticacion.entity;

// Generated 31-ene-2009 13:29:41 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Servicio implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String nombre;
	private Long idDepartamento;
	private Boolean eliminado;
	private Long cid;

	public Servicio() {
	}

	public Servicio(Long id, String nombre, Long idDepartamento) {
		this.id = id;
		this.nombre = nombre;
		this.idDepartamento = idDepartamento;
	}

	public Servicio(Long id, String nombre, Long idDepartamento,
			Boolean eliminado, Long cid, Boolean tieneConsultaExterna,
			Boolean tieneHospitalizacion, Boolean activo, Set<Usuario> usuarios) {
		this.id = id;
		this.nombre = nombre;
		this.idDepartamento = idDepartamento;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", unique = true, nullable = false)
	@NotNull
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "id_departamento", nullable = false)
	@NotNull
	public Long getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(Long idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
