package clasificacionSegunEdad

#list any import classes here.
import gehos.emergencias.entity.auto.HojaFrontal_emergencias;
import gehos.reglasdelnegocio.test.RuleResult;
#declare any global variables here

rule "Niño"
	when
		HojaFrontal_emergencias(edad <= 12)		
		$result : RuleResult()
	then 
        $result.setValue("niño");
end

rule "Adulto"
	when
		HojaFrontal_emergencias(edad > 12)		
		$result : RuleResult()
	then 
        $result.setValue("adulto");
end
