//package gehos.comun.util.errorTraces.entity;
//
//// Generated Nov 5, 2013 11:12:16 AM by Hibernate Tools 3.4.0.CR1
//
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//import org.hibernate.validator.Length;
//import org.hibernate.validator.NotNull;
//
///**
// * ErrorTrace generated by hbm2java
// */
//@Entity
//@Table(name = "error_trace", schema = "incidencias")
//public class ErrorTrace implements java.io.Serializable {
//
//	private long id;
//	private ErrorTrace errorTrace;
//	private ErrorType errorType;
//	private String errorClass;
//	private String localizedMessage;
//	private String message;
//	private String rootcauseClass;
//	private String ipAddress;
//	private String username;
//	private String modulo;
//	private Date fecha;
//	private Date hora;
//	private Set<ErrorTrace> errorTraces = new HashSet<ErrorTrace>(
//			0);
//	private Set<StackTrace> stackTraces = new HashSet<StackTrace>(
//			0);
//
//	public ErrorTrace() {
//	}
//
//	public ErrorTrace(long id,
//			ErrorType errorType) {
//		this.id = id;
//		this.errorType = errorType;
//	}
//
//	public ErrorTrace(long id,
//			ErrorTrace errorTrace,
//			ErrorType errorType, String errorClass,
//			String localizedMessage, String message, String rootcauseClass,
//			String ipAddress, String username, String modulo, Date fecha,
//			Date hora, Set<ErrorTrace> errorTraces,
//			Set<StackTrace> stackTraces) {
//		this.id = id;
//		this.errorTrace = errorTrace;
//		this.errorType = errorType;
//		this.errorClass = errorClass;
//		this.localizedMessage = localizedMessage;
//		this.message = message;
//		this.rootcauseClass = rootcauseClass;
//		this.ipAddress = ipAddress;
//		this.username = username;
//		this.modulo = modulo;
//		this.fecha = fecha;
//		this.hora = hora;
//		this.errorTraces = errorTraces;
//		this.stackTraces = stackTraces;
//	}
//
//	@Id
//	@Column(name = "id", unique = true, nullable = false)
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	public long getId() {
//		return this.id;
//	}
//
//	public void setId(long id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "id_root_cause")
//	public ErrorTrace getErrorTrace() {
//		return this.errorTrace;
//	}
//
//	public void setErrorTrace(ErrorTrace errorTrace) {
//		this.errorTrace = errorTrace;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "id_error_type")
//	public ErrorType getErrorType() {
//		return this.errorType;
//	}
//
//	public void setErrorType(ErrorType errorType) {
//		this.errorType = errorType;
//	}
//
//	@Column(name = "error_class", length = 500)
//	@Length(max = 500)
//	public String getErrorClass() {
//		return this.errorClass;
//	}
//
//	public void setErrorClass(String errorClass) {
//		if (errorClass != null)
//			errorClass = errorClass.trim();
//		this.errorClass = errorClass;
//	}
//
//	@Column(name = "localized_message", length = 500)
//	@Length(max = 500)
//	public String getLocalizedMessage() {
//		return this.localizedMessage;
//	}
//
//	public void setLocalizedMessage(String localizedMessage) {
//		if (localizedMessage != null)
//			localizedMessage = localizedMessage.trim();
//		this.localizedMessage = localizedMessage;
//	}
//
//	@Column(name = "message", length = 500)
//	@Length(max = 500)
//	public String getMessage() {
//		return this.message;
//	}
//
//	public void setMessage(String message) {
//		if (message != null)
//			message = message.trim();
//		this.message = message;
//	}
//
//	@Column(name = "rootcause_class", length = 500)
//	@Length(max = 500)
//	public String getRootcauseClass() {
//		return this.rootcauseClass;
//	}
//
//	public void setRootcauseClass(String rootcauseClass) {
//		if (rootcauseClass != null)
//			rootcauseClass = rootcauseClass.trim();
//		this.rootcauseClass = rootcauseClass;
//	}
//
//	@Column(name = "ip_address", length = 20)
//	@Length(max = 20)
//	public String getIpAddress() {
//		return this.ipAddress;
//	}
//
//	public void setIpAddress(String ipAddress) {
//		if (ipAddress != null)
//			ipAddress = ipAddress.trim();
//		this.ipAddress = ipAddress;
//	}
//
//	@Column(name = "username", length = 20)
//	@Length(max = 20)
//	public String getUsername() {
//		return this.username;
//	}
//
//	public void setUsername(String username) {
//		if (username != null)
//			username = username.trim();
//		this.username = username;
//	}
//
//	@Column(name = "modulo", length = 50)
//	@Length(max = 50)
//	public String getModulo() {
//		return this.modulo;
//	}
//
//	public void setModulo(String modulo) {
//		if (modulo != null)
//			modulo = modulo.trim();
//		this.modulo = modulo;
//	}
//
//	@Temporal(TemporalType.DATE)
//	@Column(name = "fecha", length = 13)
//	public Date getFecha() {
//		return this.fecha;
//	}
//
//	public void setFecha(Date fecha) {
//		this.fecha = fecha;
//	}
//
//	@Temporal(TemporalType.TIME)
//	@Column(name = "hora", length = 15)
//	public Date getHora() {
//		return this.hora;
//	}
//
//	public void setHora(Date hora) {
//		this.hora = hora;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "errorTrace")
//	public Set<ErrorTrace> getErrorTraces() {
//		return this.errorTraces;
//	}
//
//	public void setErrorTraces(Set<ErrorTrace> errorTraces) {
//		this.errorTraces = errorTraces;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "errorTrace")
//	public Set<StackTrace> getStackTraces() {
//		return this.stackTraces;
//	}
//
//	public void setStackTraces(Set<StackTrace> stackTraces) {
//		this.stackTraces = stackTraces;
//	}
//
//}
