//package gehos.comun.util.errorTraces.entity;
//
//// Generated Nov 5, 2013 11:12:16 AM by Hibernate Tools 3.4.0.CR1
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import org.hibernate.validator.Length;
//import org.hibernate.validator.NotNull;
//
///**
// * StackTrace generated by hbm2java
// */
//@Entity
//@Table(name = "stack_trace", schema = "incidencias")
//public class StackTrace implements java.io.Serializable {
//
//	private long id;
//	private ErrorTrace errorTrace;
//	private String className;
//	private String fileName;
//	private Long lineNumber;
//	private String methodName;
//
//	public StackTrace() {
//	}
//
//	public StackTrace(long id,
//			ErrorTrace errorTrace) {
//		this.id = id;
//		this.errorTrace = errorTrace;
//	}
//
//	public StackTrace(long id,
//			ErrorTrace errorTrace, String className,
//			String fileName, Long lineNumber, String methodName) {
//		this.id = id;
//		this.errorTrace = errorTrace;
//		this.className = className;
//		this.fileName = fileName;
//		this.lineNumber = lineNumber;
//		this.methodName = methodName;
//	}
//
//	@Id
//	@Column(name = "id", unique = true, nullable = false)
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	public long getId() {
//		return this.id;
//	}
//
//	public void setId(long id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "id_error", nullable = false)
//	@NotNull
//	public ErrorTrace getErrorTrace() {
//		return this.errorTrace;
//	}
//
//	public void setErrorTrace(ErrorTrace errorTrace) {
//		this.errorTrace = errorTrace;
//	}
//
//	@Column(name = "class_name", length = 500)
//	@Length(max = 500)
//	public String getClassName() {
//		return this.className;
//	}
//
//	public void setClassName(String className) {
//		if (className != null)
//			className = className.trim();
//		this.className = className;
//	}
//
//	@Column(name = "file_name", length = 500)
//	@Length(max = 500)
//	public String getFileName() {
//		return this.fileName;
//	}
//
//	public void setFileName(String fileName) {
//		if (fileName != null)
//			fileName = fileName.trim();
//		this.fileName = fileName;
//	}
//
//	@Column(name = "line_number")
//	public Long getLineNumber() {
//		return this.lineNumber;
//	}
//
//	public void setLineNumber(Long lineNumber) {
//		this.lineNumber = lineNumber;
//	}
//
//	@Column(name = "method_name", length = 100)
//	@Length(max = 100)
//	public String getMethodName() {
//		return this.methodName;
//	}
//
//	public void setMethodName(String methodName) {
//		if (methodName != null)
//			methodName = methodName.trim();
//		this.methodName = methodName;
//	}
//
//}
