package gehos.comun.reportes.entity;

public enum ChartParameters {
	PIE_SECTION_LABEL_GENERATOR, CATEGORY_LABEL_POSITIONS, CATEGORY_ITEM_LABEL_GENERATOR,
	TICK_UNIT_SOURCE, ITEM_LABELS_VISIBLE, BASE_ITEM_LABELS_VISIBLE, ROW_ORDER, COLUMN_ORDER,
	BASE_LINES_VISIBLE, SHAPES_VISIBLE, SHAPES_FILLED, ITEM_LABEL_POSITIONS, HIDEAXISX, HIDEAXISY
}

