package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.NotNull;

/**
 * ActividadInvestigacionDocencia generated by hbm2java
 */
@Entity
@Table(name = "actividad_investigacion_docencia", schema = "comun")
public class ActividadInvestigacionDocencia_configuracion implements
		java.io.Serializable {
	
	private Long id;
    private Integer version;
    private TipoActividadInvestigacionDocencia_configuracion tipoActividadInvestigacionDocencia;
    private String valor;
    private Boolean eliminado;
    private Long cid;
    private boolean activa;
    private String descripcion; 

	private Set<Entidad_configuracion> entidads = new HashSet<Entidad_configuracion>(
			0);
	
	
	
	public ActividadInvestigacionDocencia_configuracion() {
    }

    public ActividadInvestigacionDocencia_configuracion(
            long id,
            TipoActividadInvestigacionDocencia_configuracion tipoActividadInvestigacionDocencia,
            boolean activa) {
        this.id = id;
        this.tipoActividadInvestigacionDocencia = tipoActividadInvestigacionDocencia;
        this.activa = activa;
    }

    public ActividadInvestigacionDocencia_configuracion(
            long id,
            TipoActividadInvestigacionDocencia_configuracion tipoActividadInvestigacionDocencia,
            String valor, Boolean eliminado, Long cid, boolean activa,
            String descripcion) {
        this.id = id;
      
        this.tipoActividadInvestigacionDocencia = tipoActividadInvestigacionDocencia;
        this.valor = valor;
        this.eliminado = eliminado;
        this.cid = cid;
        this.activa = activa;
        this.descripcion = descripcion;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo", nullable = false)
    @NotNull
    public TipoActividadInvestigacionDocencia_configuracion getTipoActividadInvestigacionDocencia() {
        return this.tipoActividadInvestigacionDocencia;
    }

    public void setTipoActividadInvestigacionDocencia(
            TipoActividadInvestigacionDocencia_configuracion tipoActividadInvestigacionDocencia) {
        this.tipoActividadInvestigacionDocencia = tipoActividadInvestigacionDocencia;
    }

    @Column(name = "valor")
    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        if (valor != null)
            valor = valor.trim();
        this.valor = valor;
    }

    @Column(name = "eliminado")
    public Boolean getEliminado() {
        return this.eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    @Column(name = "cid")
    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    @Column(name = "activa", nullable = false)
    @NotNull
    public boolean isActiva() {
        return this.activa;
    }

    public void setActiva(boolean activa) {
        this.activa = activa;
    }

    @Column(name = "descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        if (descripcion != null)
            descripcion = descripcion.trim();
        this.descripcion = descripcion;
    } 
	
	

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "actividad_investigacion_in_entidad", schema = "comun", joinColumns = { @JoinColumn(name = "id_actividad", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_entidad", nullable = false, updatable = false) })
	public Set<Entidad_configuracion> getEntidads() {
		return entidads;
	}

	public void setEntidads(Set<Entidad_configuracion> entidads) {
		this.entidads = entidads;
	}

}
