package gehos.configuracion.management.entity;

// Generated 15/07/2011 04:26:18 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * BioanalistaInEntidad generated by hbm2java
 */
@Entity
@Table(name = "bioanalista_in_entidad", schema = "comun")
public class BioanalistaInEntidad_configuracion implements java.io.Serializable {

	private long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Bioanalista_configuracion bioanalista;
	private Boolean eliminado;
	private Long cid;

	public BioanalistaInEntidad_configuracion() {
	}

	public BioanalistaInEntidad_configuracion(long id) {
		this.id = id;
	}

	public BioanalistaInEntidad_configuracion(long id, Entidad_configuracion entidad,
			Bioanalista_configuracion bioanalista, Boolean eliminado, Long cid) {
		this.id = id;
		this.entidad = entidad;
		this.bioanalista = bioanalista;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bioanalista")
	public Bioanalista_configuracion getBioanalista() {
		return this.bioanalista;
	}

	public void setBioanalista(Bioanalista_configuracion bioanalista) {
		this.bioanalista = bioanalista;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
