package gehos.configuracion.management.entity;

// Generated 15/07/2011 04:26:18 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Bioanalista generated by hbm2java
 */
@Entity
@Table(name = "bioanalista", schema = "comun")
public class Bioanalista_configuracion implements java.io.Serializable {

	private long id;
	private Integer version;
	private Usuario_configuracion usuario;
	private String matriculaColegio;
	private Boolean eliminado;
	private Long cid;
	private Set<BioanalistaInEntidad_configuracion> bioanalistaInEntidads = new HashSet<BioanalistaInEntidad_configuracion>(
			0);

	public Bioanalista_configuracion() {
	}

	public Bioanalista_configuracion(Usuario_configuracion usuario) {
		this.usuario = usuario;
	}

	public Bioanalista_configuracion(Usuario_configuracion usuario, String matriculaColegio,
			Boolean eliminado, Long cid,
			Set<BioanalistaInEntidad_configuracion> bioanalistaInEntidads) {
		this.usuario = usuario;
		this.matriculaColegio = matriculaColegio;
		this.eliminado = eliminado;
		this.cid = cid;
		this.bioanalistaInEntidads = bioanalistaInEntidads;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "gen_bioanalista", sequenceName = "comun.bioanalista_id_seq", allocationSize = 1)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Usuario_configuracion getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_configuracion usuario) {
		this.usuario = usuario;
	}

	@Column(name = "matricula_colegio", length = 20)
	@Length(max = 20)
	public String getMatriculaColegio() {
		return this.matriculaColegio;
	}

	public void setMatriculaColegio(String matriculaColegio) {
		this.matriculaColegio = matriculaColegio;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bioanalista")
	public Set<BioanalistaInEntidad_configuracion> getBioanalistaInEntidads() {
		return this.bioanalistaInEntidads;
	}

	public void setBioanalistaInEntidads(
			Set<BioanalistaInEntidad_configuracion> bioanalistaInEntidads) {
		this.bioanalistaInEntidads = bioanalistaInEntidads;
	}

}
