package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Cama generated by hbm2java
 */
@Entity
@Table(name = "cama", schema = "comun")
public class Cama_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;

	private Ubicacion_configuracion ubicacion;
	private ServicioInEntidad_configuracion servicioInEntidadByIdServicioFlotante;
	private TipoCama_configuracion tipoCama;
	private ServicioInEntidad_configuracion servicioInEntidadByIdServicio;
	private CategoriaCama_configuracion categoriaCama;
	private EstadoCama_configuracion estadoCama;
	private String descripcion;
	private Boolean eliminado;
	private Long cid;
	private Long idAdmision;
	private Integer x;
	private Integer y;

	public Cama_configuracion() {
	}

	public Cama_configuracion(Long id, TipoCama_configuracion tipoCama,
			ServicioInEntidad_configuracion servicioInEntidadByIdServicio,
			CategoriaCama_configuracion categoriaCama,
			EstadoCama_configuracion estadoCama, String descripcion) {
		this.id = id;
		this.tipoCama = tipoCama;
		this.servicioInEntidadByIdServicio = servicioInEntidadByIdServicio;
		this.categoriaCama = categoriaCama;
		this.estadoCama = estadoCama;
		this.descripcion = descripcion;
	}

	public Cama_configuracion(
			Long id,

			Ubicacion_configuracion ubicacion,
			ServicioInEntidad_configuracion servicioInEntidadByIdServicioFlotante,
			TipoCama_configuracion tipoCama,
			ServicioInEntidad_configuracion servicioInEntidadByIdServicio,
			CategoriaCama_configuracion categoriaCama,
			EstadoCama_configuracion estadoCama, String descripcion,
			Boolean eliminado, Long cid, Long idAdmision, Integer x,
			Integer y) {
		this.id = id;

		this.ubicacion = ubicacion;
		this.servicioInEntidadByIdServicioFlotante = servicioInEntidadByIdServicioFlotante;
		this.tipoCama = tipoCama;
		this.servicioInEntidadByIdServicio = servicioInEntidadByIdServicio;
		this.categoriaCama = categoriaCama;
		this.estadoCama = estadoCama;
		this.descripcion = descripcion;
		this.eliminado = eliminado;
		this.cid = cid;
		this.idAdmision = idAdmision;
		this.x = x;
		this.y = y;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	//@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY/*, generator = "gen_cama"*/)
	//@SequenceGenerator(name = "gen_cama", sequenceName = "comun.cama_id_seq", allocationSize = 1)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ubicacion")
	public Ubicacion_configuracion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion_configuracion ubicacion) {
		this.ubicacion = ubicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio_flotante")
	public ServicioInEntidad_configuracion getServicioInEntidadByIdServicioFlotante() {
		return this.servicioInEntidadByIdServicioFlotante;
	}

	public void setServicioInEntidadByIdServicioFlotante(
			ServicioInEntidad_configuracion servicioInEntidadByIdServicioFlotante) {
		this.servicioInEntidadByIdServicioFlotante = servicioInEntidadByIdServicioFlotante;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tipo_cama", nullable = false)
	@NotNull
	public TipoCama_configuracion getTipoCama() {
		return this.tipoCama;
	}

	public void setTipoCama(TipoCama_configuracion tipoCama) {
		this.tipoCama = tipoCama;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio", nullable = false)
	@NotNull
	public ServicioInEntidad_configuracion getServicioInEntidadByIdServicio() {
		return this.servicioInEntidadByIdServicio;
	}

	public void setServicioInEntidadByIdServicio(
			ServicioInEntidad_configuracion servicioInEntidadByIdServicio) {
		this.servicioInEntidadByIdServicio = servicioInEntidadByIdServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria_cama", nullable = false)
	@NotNull
	public CategoriaCama_configuracion getCategoriaCama() {
		return this.categoriaCama;
	}

	public void setCategoriaCama(CategoriaCama_configuracion categoriaCama) {
		this.categoriaCama = categoriaCama;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	@NotNull
	public EstadoCama_configuracion getEstadoCama() {
		return this.estadoCama;
	}

	public void setEstadoCama(EstadoCama_configuracion estadoCama) {
		this.estadoCama = estadoCama;
	}

	@Column(name = "descripcion", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "id_admision")
	public Long getIdAdmision() {
		return this.idAdmision;
	}

	public void setIdAdmision(Long idAdmision) {
		this.idAdmision = idAdmision;
	}

	@Column(name = "x")
	public Integer getX() {
		return this.x;
	}

	public void setX(Integer x) {
		this.x = x;
	}

	@Column(name = "y")
	public Integer getY() {
		return this.y;
	}

	public void setY(Integer y) {
		this.y = y;
	}

}
