package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * CargoFuncionario generated by hbm2java
 */
@Entity
@Table(name = "cargo_funcionario", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "valor"))
public class CargoFuncionario_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private TipoFuncionario_configuracion tipoFuncionario;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private Set<Usuario_configuracion> usuarios = new HashSet<Usuario_configuracion>(
			0);

	public CargoFuncionario_configuracion() {
	}

	public CargoFuncionario_configuracion(Long id,
			TipoFuncionario_configuracion tipoFuncionario, String valor) {
		this.id = id;
		this.tipoFuncionario = tipoFuncionario;
		this.valor = valor;
	}

	public CargoFuncionario_configuracion(Long id,
			TipoFuncionario_configuracion tipoFuncionario, String valor,
			Boolean eliminado, Long cid, Set<Usuario_configuracion> usuarios) {
		this.id = id;
		this.tipoFuncionario = tipoFuncionario;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_funcionario", nullable = false)
	@NotNull
	public TipoFuncionario_configuracion getTipoFuncionario() {
		return this.tipoFuncionario;
	}

	public void setTipoFuncionario(TipoFuncionario_configuracion tipoFuncionario) {
		this.tipoFuncionario = tipoFuncionario;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_in_cargo", schema = "comun", joinColumns = { @JoinColumn(name = "id_cargo", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) })
	public Set<Usuario_configuracion> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario_configuracion> usuarios) {
		this.usuarios = usuarios;
	}

}
