package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Departamento_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String nombre;
	private Boolean eliminado;
	private Long cid;
	private Boolean esClinico;
	private Set<DepartamentoInEntidad_configuracion> departamentoInEntidads = new HashSet<DepartamentoInEntidad_configuracion>(
			0);
	private Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals = new HashSet<PartidaPresupuestariaHospital_configuracion>(
			0);
	private Set<Servicio_configuracion> servicios = new HashSet<Servicio_configuracion>(
			0);

	public Departamento_configuracion() {
	}

	public Departamento_configuracion(Long id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Departamento_configuracion(
			Long id,
			String nombre,
			Boolean eliminado,
			Long cid,
			Boolean esClinico,
			Set<DepartamentoInEntidad_configuracion> departamentoInEntidads,
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals,
			Set<Servicio_configuracion> servicios) {
		this.id = id;
		this.nombre = nombre;
		this.eliminado = eliminado;
		this.cid = cid;
		this.esClinico = esClinico;
		this.departamentoInEntidads = departamentoInEntidads;
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
		this.servicios = servicios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", unique = true, nullable = false)
	@NotNull
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "es_clinico")
	public Boolean getEsClinico() {
		return this.esClinico;
	}

	public void setEsClinico(Boolean esClinico) {
		this.esClinico = esClinico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<DepartamentoInEntidad_configuracion> getDepartamentoInEntidads() {
		return this.departamentoInEntidads;
	}

	public void setDepartamentoInEntidads(
			Set<DepartamentoInEntidad_configuracion> departamentoInEntidads) {
		this.departamentoInEntidads = departamentoInEntidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<PartidaPresupuestariaHospital_configuracion> getPartidaPresupuestariaHospitals() {
		return this.partidaPresupuestariaHospitals;
	}

	public void setPartidaPresupuestariaHospitals(
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals) {
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Servicio_configuracion> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set<Servicio_configuracion> servicios) {
		this.servicios = servicios;
	}

}
