package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * DepartamentoInEntidad generated by hbm2java
 */
@Entity
@Table(name = "departamento_in_entidad", schema = "comun")
public class DepartamentoInEntidad_configuracion implements
		java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Departamento_configuracion departamento;
	private Long cid;
	private Boolean eliminado;

	public DepartamentoInEntidad_configuracion() {
	}

	public DepartamentoInEntidad_configuracion(Long id,
			Entidad_configuracion entidad,
			Departamento_configuracion departamento) {
		this.id = id;
		this.entidad = entidad;
		this.departamento = departamento;
	}

	public DepartamentoInEntidad_configuracion(Long id,
			Entidad_configuracion entidad,
			Departamento_configuracion departamento, Long cid,
			Boolean eliminado) {
		this.id = id;
		this.entidad = entidad;
		this.departamento = departamento;
		this.cid = cid;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad", nullable = false)
	@NotNull
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento", nullable = false)
	@NotNull
	public Departamento_configuracion getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento_configuracion departamento) {
		this.departamento = departamento;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
