package gehos.configuracion.management.entity;

// Generated 10-jun-2010 12:46:26 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * EnfermeraInEntidad generated by hbm2java
 */
@Entity
@Table(name = "enfermera_in_entidad", schema = "comun")
public class EnfermeraInEntidad implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Enfermera_configuracion enfermera;
	private Boolean eliminado;
	private Long cid;

	public EnfermeraInEntidad() {
	}

	public EnfermeraInEntidad(Long id,
			Entidad_configuracion entidad, Enfermera_configuracion enfermera) {
		this.id = id;
		this.entidad = entidad;
		this.enfermera = enfermera;
	}

	public EnfermeraInEntidad(Long id,
			Entidad_configuracion entidad, Enfermera_configuracion enfermera,
			Boolean eliminado, Long cid) {
		this.id = id;
		this.entidad = entidad;
		this.enfermera = enfermera;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad", nullable = false)
	@NotNull
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_enfermero", nullable = false)
	@NotNull
	public Enfermera_configuracion getEnfermera() {
		return this.enfermera;
	}

	public void setEnfermera(Enfermera_configuracion enfermera) {
		this.enfermera = enfermera;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
