package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Enfermera generated by hbm2java
 */
@Entity
@Table(name = "enfermera", schema = "comun")
public class Enfermera_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Usuario_configuracion usuario;
	private String matriculaColegioEnfermeria;
	private Boolean eliminado;
	private Long cid;

	public Enfermera_configuracion() {
	}

	public Enfermera_configuracion(Usuario_configuracion usuario,
			String matriculaColegioEnfermeria) {
		this.usuario = usuario;
		this.matriculaColegioEnfermeria = matriculaColegioEnfermeria;
	}

	public Enfermera_configuracion(Usuario_configuracion usuario,
			String matriculaColegioEnfermeria, Boolean eliminado, Long cid) {
		this.usuario = usuario;
		this.matriculaColegioEnfermeria = matriculaColegioEnfermeria;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Usuario_configuracion getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_configuracion usuario) {
		this.usuario = usuario;
	}

	@Column(name = "matricula_colegio_enfermeria", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getMatriculaColegioEnfermeria() {
		return this.matriculaColegioEnfermeria;
	}

	public void setMatriculaColegioEnfermeria(String matriculaColegioEnfermeria) {
		this.matriculaColegioEnfermeria = matriculaColegioEnfermeria;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
