package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import gehos.autorizacion.entity.UserEntityPermission;
import gehos.comun.funcionalidades.entity.custom.Favoritos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name = "entidad", schema = "comun")
public class Entidad_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	//eliminar
	//private TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud;
	
	private Integer camasFuncionales;
	private Integer cantidadMedicos;
	private Integer cantidadEnfermeros;
	private Integer cantidadTrabajadores;
	
	private TipoEntidad_configuracion tipoEntidad;
	private Municipio_configuracion municipio;
	private Localidad_configuracion localidad;
	private Estado_configuracion estado;
	private String nombre;
	// eliminar
	//private Integer poblacionAreaInfluencia;
	private String direccion;
	private String telefonos;
	private String fax;
	private String correo;
	private Date fechaApertura;
	private Integer camasArquitectonicas;
	private Integer camasPresupuestadas;
	private boolean esPublico;
	private Boolean eliminado;
	private Long cid;
	//private boolean actual;
	private String logo;
	private String rif;
	private boolean pertenece_a_rhio;
	
	private String codigoReeup;
	private Organismo_configuracion organismo;
	private String siglas;
	private String observaciones;
	
	
	/**
	 * @author yurien 17/03/2014
	 * Se agrega la referencia a la instancia del HIS a la que pertenece la entidad
	 * **/
	private InstanciaHis_configuracion instanciaHis;
	
	private String idInstanciaHis;
	
	private Set<ServicioInEntidad_configuracion> servicioInEntidads = new HashSet<ServicioInEntidad_configuracion>(
			0);
	// ponerle la fecha a la poblacion YAA
	private Set<PoblacionAreaInfluencia_configuracion> poblacionAreaInfluencias = new HashSet<PoblacionAreaInfluencia_configuracion>(
			0);
	/////////arreglar estas dos tablas y hacerlas una sola
	private Set<MedicoInEntidad_configuracion> medicoInEntidads = new HashSet<MedicoInEntidad_configuracion>(
			0);
	///////////hacer mucho a muchos YAAA
	private Set<EstablecimientoAreaInfluenciaHospital_configuracion> establecimientoAreaInfluenciaHospitals = new HashSet<EstablecimientoAreaInfluenciaHospital_configuracion>(
			0);
	private Set<DepartamentoInEntidad_configuracion> departamentoInEntidads = new HashSet<DepartamentoInEntidad_configuracion>(
			0);
	private Set<EspecialidadInEntidad_configuracion> especialidadInEntidads = new HashSet<EspecialidadInEntidad_configuracion>(
			0);
	///////////hacer mucho a muchos YAAA
	private Set<ActividadInvestigacionDocencia_configuracion> actividadInvestigacionDocencias = new HashSet<ActividadInvestigacionDocencia_configuracion>(
			0);
	private Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals = new HashSet<PartidaPresupuestariaHospital_configuracion>(
			0);
	private Set<Referencia_configuracion> referenciasForIdEntidadDestino = new HashSet<Referencia_configuracion>(
			0);
	private Set<Funcionalidad_configuracion> modulos = new HashSet<Funcionalidad_configuracion>(
			0);
	private Set<Referencia_configuracion> referenciasForIdEntidadOrigen = new HashSet<Referencia_configuracion>(
			0);
	private Set<AsignacionFinancieraHospital_configuracion> asignacionFinancieraHospitals = new HashSet<AsignacionFinancieraHospital_configuracion>(
			0);
	private Set<Favoritos> favoritos = new HashSet<Favoritos>(
			0);
	/////////////////////eliminar
/*	private Set<EntidadOrganizacional_configuracion> entidadOrganizacionals = new HashSet<EntidadOrganizacional_configuracion>(
			0);*/
	private Set<Ubicacion_configuracion> ubicacions = new HashSet<Ubicacion_configuracion>(
			0);
	
	private Set<UserEntityPermission> userEntityPermissions = new HashSet<UserEntityPermission>(
			0);

	public Entidad_configuracion() {
	}

	public Entidad_configuracion(Long id, TipoEntidad_configuracion tipoEntidad,
			Municipio_configuracion municipio,
			Localidad_configuracion localidad, Estado_configuracion estado,
			boolean esPublico, boolean actual, boolean pertenece_a_rhio) {
		this.id = id;
		this.tipoEntidad = tipoEntidad;
		this.municipio = municipio;
		this.localidad = localidad;
		this.estado = estado;
		this.esPublico = esPublico;
		/*this.actual = actual;*/
		this.pertenece_a_rhio = pertenece_a_rhio;
	}

	public Entidad_configuracion(
			Long id,
			TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud,
			TipoEntidad_configuracion tipoEntidad,
			Municipio_configuracion municipio,
			Localidad_configuracion localidad,
			Estado_configuracion estado,
			String nombre,
			Integer poblacionAreaInfluencia,
			String direccion,
			String telefonos,
			String fax,
			String correo,
			Date fechaApertura,
			Integer camasArquitectonicas,
			Integer camasPresupuestadas,
			boolean esPublico,
			Boolean eliminado,
			Long cid,
			boolean actual,
			String logo,
			boolean pertenece_a_rhio,
			Set<ServicioInEntidad_configuracion> servicioInEntidads,
			Set<PoblacionAreaInfluencia_configuracion> poblacionAreaInfluencias,
			Set<MedicoInEntidad_configuracion> medicoInEntidads,
			Set<EstablecimientoAreaInfluenciaHospital_configuracion> establecimientoAreaInfluenciaHospitals,
			Set<DepartamentoInEntidad_configuracion> departamentoInEntidads,
			Set<EspecialidadInEntidad_configuracion> especialidadInEntidads,
			Set<ActividadInvestigacionDocencia_configuracion> actividadInvestigacionDocencias,
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals,
			Set<Referencia_configuracion> referenciasForIdEntidadDestino,
			Set<Funcionalidad_configuracion> funcionalidads,
			Set<Referencia_configuracion> referenciasForIdEntidadOrigen,
			Set<AsignacionFinancieraHospital_configuracion> asignacionFinancieraHospitals,
			Set<EntidadOrganizacional_configuracion> entidadOrganizacionals,
			Set<Ubicacion_configuracion> ubicacions,InstanciaHis_configuracion instanciaHis) {
		this.id = id;
		//this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
		this.tipoEntidad = tipoEntidad;
		this.municipio = municipio;
		this.localidad = localidad;
		this.estado = estado;
		this.nombre = nombre;
		//this.poblacionAreaInfluencia = poblacionAreaInfluencia;
		this.direccion = direccion;
		this.telefonos = telefonos;
		this.fax = fax;
		this.correo = correo;
		this.fechaApertura = fechaApertura;
		this.camasArquitectonicas = camasArquitectonicas;
		this.camasPresupuestadas = camasPresupuestadas;
		this.esPublico = esPublico;
		this.eliminado = eliminado;
		this.cid = cid;
		/*this.actual = actual;*/
		this.logo = logo;
		this.pertenece_a_rhio = pertenece_a_rhio;
		this.servicioInEntidads = servicioInEntidads;
		this.poblacionAreaInfluencias = poblacionAreaInfluencias;
		this.medicoInEntidads = medicoInEntidads;
		this.establecimientoAreaInfluenciaHospitals = establecimientoAreaInfluenciaHospitals;
		this.departamentoInEntidads = departamentoInEntidads;
		this.especialidadInEntidads = especialidadInEntidads;
		this.actividadInvestigacionDocencias = actividadInvestigacionDocencias;
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
		this.referenciasForIdEntidadDestino = referenciasForIdEntidadDestino;
		this.modulos = funcionalidads;
		this.referenciasForIdEntidadOrigen = referenciasForIdEntidadOrigen;
		this.asignacionFinancieraHospitals = asignacionFinancieraHospitals;
	/*	this.entidadOrganizacionals = entidadOrganizacionals;*/
		this.ubicacions = ubicacions;
		this.instanciaHis = instanciaHis;
	}



	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_clasificacion_hospital")
	public TipoEstablecimientoSalud_configuracion getTipoEstablecimientoSalud() {
		return this.tipoEstablecimientoSalud;
	}

	public void setTipoEstablecimientoSalud(
			TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud) {
		this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_hospital", nullable = false)
	@NotNull
	public TipoEntidad_configuracion getTipoEntidad() {
		return this.tipoEntidad;
	}

	public void setTipoEntidad(TipoEntidad_configuracion tipoEntidad) {
		this.tipoEntidad = tipoEntidad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_municipio", nullable = false)
	@NotNull
	public Municipio_configuracion getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio_configuracion municipio) {
		this.municipio = municipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_localidad")
	public Localidad_configuracion getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad_configuracion localidad) {
		this.localidad = localidad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_estado", nullable = false)
	@NotNull
	public Estado_configuracion getEstado() {
		return this.estado;
	}

	public void setEstado(Estado_configuracion estado) {
		this.estado = estado;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

/*	@Column(name = "poblacion_area_influencia")
	public Integer getPoblacionAreaInfluencia() {
		return this.poblacionAreaInfluencia;
	}

	public void setPoblacionAreaInfluencia(Integer poblacionAreaInfluencia) {
		this.poblacionAreaInfluencia = poblacionAreaInfluencia;
	}*/

	@Column(name = "direccion", length = 100)
	@Length(max = 100)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefonos", length = 15)
	@Length(max = 15)
	public String getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(String telefonos) {
		this.telefonos = telefonos;
	}

	@Column(name = "fax", length = 15)
	@Length(max = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * @author yurien 20/05/2014 Se modifica la cantidad de caracteres que
	 *         admite el correo de 25 a 100
	 * **/
	@Column(name = "correo", length = 100)
	@Length(max = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_apertura", length = 13)
	public Date getFechaApertura() {
		return this.fechaApertura;
	}

	public void setFechaApertura(Date fechaApertura) {
		this.fechaApertura = fechaApertura;
	}

	@Column(name = "camas_arquitectonicas")
	public Integer getCamasArquitectonicas() {
		return this.camasArquitectonicas;
	}

	public void setCamasArquitectonicas(Integer camasArquitectonicas) {
		this.camasArquitectonicas = camasArquitectonicas;
	}

	@Column(name = "camas_presupuestadas")
	public Integer getCamasPresupuestadas() {
		return this.camasPresupuestadas;
	}

	public void setCamasPresupuestadas(Integer camasPresupuestadas) {
		this.camasPresupuestadas = camasPresupuestadas;
	}

	@Column(name = "es_publico", nullable = false)
	@NotNull
	public boolean isEsPublico() {
		return this.esPublico;
	}

	public void setEsPublico(boolean esPublico) {
		this.esPublico = esPublico;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

/*	@Column(name = "actual", nullable = false)
	@NotNull
	public boolean isActual() {
		return this.actual;
	}

	public void setActual(boolean actual) {
		this.actual = actual;
	}*/

	@Column(name = "logo", length = 30)
	@Length(max = 30)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "pertenece_a_rhio", nullable = false)
	@NotNull
	public boolean isPerteneceARhio() {
		return this.pertenece_a_rhio;
	}

	public void setPerteneceARhio(boolean pertenece_a_rhio) {
		this.pertenece_a_rhio = pertenece_a_rhio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<ServicioInEntidad_configuracion> getServicioInEntidads() {
		return this.servicioInEntidads;
	}

	public void setServicioInEntidads(
			Set<ServicioInEntidad_configuracion> servicioInEntidads) {
		this.servicioInEntidads = servicioInEntidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<PoblacionAreaInfluencia_configuracion> getPoblacionAreaInfluencias() {
		return this.poblacionAreaInfluencias;
	}

	public void setPoblacionAreaInfluencias(
			Set<PoblacionAreaInfluencia_configuracion> poblacionAreaInfluencias) {
		this.poblacionAreaInfluencias = poblacionAreaInfluencias;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<Favoritos> getFavoritos() {
		return favoritos;
	}

	public void setFavoritos(Set<Favoritos> favoritos) {
		this.favoritos = favoritos;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<MedicoInEntidad_configuracion> getMedicoInEntidads() {
		return this.medicoInEntidads;
	}

	public void setMedicoInEntidads(
			Set<MedicoInEntidad_configuracion> medicoInEntidads) {
		this.medicoInEntidads = medicoInEntidads;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "establecimiento_in_entidad", schema = "comun", 
			joinColumns = { @JoinColumn(name = "id_entidad", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "id_establecimiento", nullable = false, updatable = false) })
	public Set<EstablecimientoAreaInfluenciaHospital_configuracion> getEstablecimientoAreaInfluenciaHospitals() {
		return this.establecimientoAreaInfluenciaHospitals;
	}

	public void setEstablecimientoAreaInfluenciaHospitals(
			Set<EstablecimientoAreaInfluenciaHospital_configuracion> establecimientoAreaInfluenciaHospitals) {
		this.establecimientoAreaInfluenciaHospitals = establecimientoAreaInfluenciaHospitals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<DepartamentoInEntidad_configuracion> getDepartamentoInEntidads() {
		return this.departamentoInEntidads;
	}

	public void setDepartamentoInEntidads(
			Set<DepartamentoInEntidad_configuracion> departamentoInEntidads) {
		this.departamentoInEntidads = departamentoInEntidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<EspecialidadInEntidad_configuracion> getEspecialidadInEntidads() {
		return this.especialidadInEntidads;
	}

	public void setEspecialidadInEntidads(
			Set<EspecialidadInEntidad_configuracion> especialidadInEntidads) {
		this.especialidadInEntidads = especialidadInEntidads;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "actividad_investigacion_in_entidad", schema = "comun", 
			joinColumns = { @JoinColumn(name = "id_entidad", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "id_actividad", nullable = false, updatable = false) })
	public Set<ActividadInvestigacionDocencia_configuracion> getActividadInvestigacionDocencias() {
		return this.actividadInvestigacionDocencias;
	}

	public void setActividadInvestigacionDocencias(
			Set<ActividadInvestigacionDocencia_configuracion> actividadInvestigacionDocencias) {
		this.actividadInvestigacionDocencias = actividadInvestigacionDocencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<PartidaPresupuestariaHospital_configuracion> getPartidaPresupuestariaHospitals() {
		return this.partidaPresupuestariaHospitals;
	}

	public void setPartidaPresupuestariaHospitals(
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals) {
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadByIdEntidadDestino")
	public Set<Referencia_configuracion> getReferenciasForIdEntidadDestino() {
		return this.referenciasForIdEntidadDestino;
	}

	public void setReferenciasForIdEntidadDestino(
			Set<Referencia_configuracion> referenciasForIdEntidadDestino) {
		this.referenciasForIdEntidadDestino = referenciasForIdEntidadDestino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<Funcionalidad_configuracion> getModulos() {
		return this.modulos;
	}

	public void setModulos(
			Set<Funcionalidad_configuracion> funcionalidads) {
		this.modulos = funcionalidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadByIdEntidadOrigen")
	public Set<Referencia_configuracion> getReferenciasForIdEntidadOrigen() {
		return this.referenciasForIdEntidadOrigen;
	}

	public void setReferenciasForIdEntidadOrigen(
			Set<Referencia_configuracion> referenciasForIdEntidadOrigen) {
		this.referenciasForIdEntidadOrigen = referenciasForIdEntidadOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<AsignacionFinancieraHospital_configuracion> getAsignacionFinancieraHospitals() {
		return this.asignacionFinancieraHospitals;
	}

	public void setAsignacionFinancieraHospitals(
			Set<AsignacionFinancieraHospital_configuracion> asignacionFinancieraHospitals) {
		this.asignacionFinancieraHospitals = asignacionFinancieraHospitals;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<EntidadOrganizacional_configuracion> getEntidadOrganizacionals() {
		return this.entidadOrganizacionals;
	}

	public void setEntidadOrganizacionals(
			Set<EntidadOrganizacional_configuracion> entidadOrganizacionals) {
		this.entidadOrganizacionals = entidadOrganizacionals;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<Ubicacion_configuracion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(Set<Ubicacion_configuracion> ubicacions) {
		this.ubicacions = ubicacions;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<UserEntityPermission> getUserEntityPermissions() {
		return userEntityPermissions;
	}

	public void setUserEntityPermissions(
			Set<UserEntityPermission> userEntityPermissions) {
		this.userEntityPermissions = userEntityPermissions;
	}

	@Column(name = "camas_funcionales")
	public Integer getCamasFuncionales() {
		return camasFuncionales;
	}

	public void setCamasFuncionales(Integer camasFuncionales) {
		this.camasFuncionales = camasFuncionales;
	}

	@Column(name = "cantidad_medicos")
	public Integer getCantidadMedicos() {
		return cantidadMedicos;
	}

	public void setCantidadMedicos(Integer cantidadMedicos) {
		this.cantidadMedicos = cantidadMedicos;
	}

	@Column(name = "cantidad_enfermeros")
	public Integer getCantidadEnfermeros() {
		return cantidadEnfermeros;
	}

	public void setCantidadEnfermeros(Integer cantidadEnfermeros) {
		this.cantidadEnfermeros = cantidadEnfermeros;
	}

	@Column(name = "cantidad_trabajadores")
	public Integer getCantidadTrabajadores() {
		return cantidadTrabajadores;
	}

	public void setCantidadTrabajadores(Integer cantidadTrabajadores) {
		this.cantidadTrabajadores = cantidadTrabajadores;
	}
	
	@Column(name = "rif", length = 20)
	@Length(max = 20)
	public String getRif() {
		return rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}
	
	@Column(name = "codigo_reeup")
	public String getCodigoReeup(){
		return this.codigoReeup;
	}

	public void setCodigoReeup(String codigoReeup){
		this.codigoReeup = codigoReeup;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_organismo")
	public Organismo_configuracion getOrganismo(){
		return this.organismo;
	}

	public void setOrganismo(Organismo_configuracion organismo){
		this.organismo = organismo;
	}
	
	@Column(name = "siglas")
	public String getSiglas(){
		return this.siglas;
	}

	public void setSiglas(String siglas){
		this.siglas = siglas;
	}
	
	@Column(name = "observaciones")
	public String getObservaciones(){
		return this.observaciones;
	}

	public void setObservaciones(String observaciones){
		this.observaciones = observaciones;
	}
	
	/**
	 * @author yurien 17/03/2014
	 * Se agrega la referencia a la instancia del HIS a la que pertenece la entidad
	 * **/
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_anillo_his")
	public InstanciaHis_configuracion getInstanciaHis() {
		return this.instanciaHis;
	}

	public void setInstanciaHis(InstanciaHis_configuracion instanciaHis) {
		this.instanciaHis = instanciaHis;
	}
	/*******************************************************************************/
	@Column(name = "id_instancia_his")
	public String getIdInstanciaHis() {
		return this.idInstanciaHis;
	}

	public void setIdInstanciaHis(String idInstanciaHis) {
		if (idInstanciaHis != null)
			idInstanciaHis = idInstanciaHis.trim();
		this.idInstanciaHis = idInstanciaHis;
	}


}
