package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * EntidadOrganizacional generated by hbm2java
 */
@Entity
@Table(name = "entidad_organizacional", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "valor"))
public class EntidadOrganizacional_configuracion implements
		java.io.Serializable {

	private Long id;
	private Integer version;
	/*private Entidad_configuracion entidad;*/
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private Set<AsignacionFinancieraHospital_configuracion> asignacionFinancieraHospitals = new HashSet<AsignacionFinancieraHospital_configuracion>(
			0);
	private Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals = new HashSet<PartidaPresupuestariaHospital_configuracion>(
			0);

	public EntidadOrganizacional_configuracion() {
	}

	public EntidadOrganizacional_configuracion(Long id, String valor) {
		this.id = id;
		this.valor = valor;
	}

	public EntidadOrganizacional_configuracion(
			Long id,
			Entidad_configuracion entidad,
			String valor,
			Boolean eliminado,
			Long cid,
			Set<AsignacionFinancieraHospital_configuracion> asignacionFinancieraHospitals,
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals) {
		this.id = id;
		/*this.entidad = entidad;*/
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.asignacionFinancieraHospitals = asignacionFinancieraHospitals;
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hospital")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}*/

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadOrganizacional")
	public Set<AsignacionFinancieraHospital_configuracion> getAsignacionFinancieraHospitals() {
		return this.asignacionFinancieraHospitals;
	}

	public void setAsignacionFinancieraHospitals(
			Set<AsignacionFinancieraHospital_configuracion> asignacionFinancieraHospitals) {
		this.asignacionFinancieraHospitals = asignacionFinancieraHospitals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadOrganizacional")
	public Set<PartidaPresupuestariaHospital_configuracion> getPartidaPresupuestariaHospitals() {
		return this.partidaPresupuestariaHospitals;
	}

	public void setPartidaPresupuestariaHospitals(
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals) {
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
	}

}
