package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Especialidad generated by hbm2java
 */
@Entity
@Table(name = "especialidad", schema = "comun")
public class Especialidad_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Servicio_configuracion servicio;
	private String nombre;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private boolean quirurgica;
	private Set<Medico_configuracion> medicos = new HashSet<Medico_configuracion>(
			0);
/*	private Set<MedicoInEntidad_configuracion> medicoInEntidads = new HashSet<MedicoInEntidad_configuracion>(
			0);*/
	private Set<EspecialidadInEntidad_configuracion> especialidadInEntidads = new HashSet<EspecialidadInEntidad_configuracion>(
			0);

	public Especialidad_configuracion() {
	}

	public Especialidad_configuracion(Long id, Servicio_configuracion servicio,
			String nombre, boolean quirurgica) {
		this.id = id;
		this.servicio = servicio;
		this.nombre = nombre;
		this.quirurgica = quirurgica;
	}

	public Especialidad_configuracion(Long id, Servicio_configuracion servicio,
			String nombre, Boolean eliminado, Long cid, String codigo,
			boolean quirurgica, Set<Medico_configuracion> medicos,
			Set<MedicoInEntidad_configuracion> medicoInEntidads,
			Set<EspecialidadInEntidad_configuracion> especialidadInEntidads) {
		this.id = id;
		this.servicio = servicio;
		this.nombre = nombre;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.quirurgica = quirurgica;
		this.medicos = medicos;
		/*this.medicoInEntidads = medicoInEntidads;*/
		this.especialidadInEntidads = especialidadInEntidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio", nullable = false)
	@NotNull
	public Servicio_configuracion getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio_configuracion servicio) {
		this.servicio = servicio;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	@NotNull
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "quirurgica", nullable = false)
	@NotNull
	public boolean isQuirurgica() {
		return this.quirurgica;
	}

	public void setQuirurgica(boolean quirurgica) {
		this.quirurgica = quirurgica;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "medico_in_especialidad", schema = "comun", 
			joinColumns = { @JoinColumn(name = "id_especialidad", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "id_medico", nullable = false, updatable = false) })
	public Set<Medico_configuracion> getMedicos() {
		return this.medicos;
	}

	public void setMedicos(Set<Medico_configuracion> medicos) {
		this.medicos = medicos;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidad")	
	public Set<MedicoInEntidad_configuracion> getMedicoInEntidads() {
		return this.medicoInEntidads;
	}

	public void setMedicoInEntidads(
			Set<MedicoInEntidad_configuracion> medicoInEntidads) {
		this.medicoInEntidads = medicoInEntidads;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidad")
	public Set<EspecialidadInEntidad_configuracion> getEspecialidadInEntidads() {
		return this.especialidadInEntidads;
	}

	public void setEspecialidadInEntidads(
			Set<EspecialidadInEntidad_configuracion> especialidadInEntidads) {
		this.especialidadInEntidads = especialidadInEntidads;
	}

}
