package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * EspecialidadInEntidad generated by hbm2java
 */
@Entity
@Table(name = "especialidad_in_entidad", schema = "comun")
public class EspecialidadInEntidad_configuracion implements
		java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Especialidad_configuracion especialidad;
	private Long cid;
	private Boolean eliminado;
	private Set<MedicoInEntidad_configuracion> medicos = new HashSet<MedicoInEntidad_configuracion>(
			0);

	public EspecialidadInEntidad_configuracion() {
	}

	public EspecialidadInEntidad_configuracion(Long id) {
		this.id = id;
	}

	public EspecialidadInEntidad_configuracion(Long id,
			Entidad_configuracion entidad,
			Especialidad_configuracion especialidad, Long cid,
			Boolean eliminado) {
		this.id = id;
		this.entidad = entidad;
		this.especialidad = especialidad;
		this.cid = cid;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_especialidad")
	public Especialidad_configuracion getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(Especialidad_configuracion especialidad) {
		this.especialidad = especialidad;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "medico_in_entidad_in_especialidads", schema = "comun", 
			joinColumns = { @JoinColumn(name = "id_especialidad_in_entidad", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "id_medico_in_entidad", nullable = false, updatable = false) })
	public Set<MedicoInEntidad_configuracion> getMedicos() {
		return medicos;
	}

	public void setMedicos(Set<MedicoInEntidad_configuracion> medicos) {
		this.medicos = medicos;
	}

}
