package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", schema = "nomencladores", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Estado_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Nacion_configuracion nacion;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private Set<Municipio_configuracion> municipios = new HashSet<Municipio_configuracion>(
			0);
	private Set<Entidad_configuracion> entidads = new HashSet<Entidad_configuracion>(
			0);

	public Estado_configuracion() {
	}

	public Estado_configuracion(Long id, Nacion_configuracion nacion,
			String valor) {
		this.id = id;
		this.nacion = nacion;
		this.valor = valor;
	}

	public Estado_configuracion(Long id, Nacion_configuracion nacion,
			String valor, Boolean eliminado, Long cid, String codigo,
			Set<Municipio_configuracion> municipios,
			Set<Entidad_configuracion> entidads) {
		this.id = id;
		this.nacion = nacion;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.municipios = municipios;
		this.entidads = entidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_nacion", nullable = false)
	@NotNull
	public Nacion_configuracion getNacion() {
		return this.nacion;
	}

	public void setNacion(Nacion_configuracion nacion) {
		this.nacion = nacion;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo", unique = true)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Municipio_configuracion> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio_configuracion> municipios) {
		this.municipios = municipios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Entidad_configuracion> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_configuracion> entidads) {
		this.entidads = entidads;
	}

}
