package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstablecimientoAreaInfluenciaHospital generated by hbm2java
 */
@Entity
@Table(name = "establecimiento_area_influencia_hospital", schema = "comun")
public class EstablecimientoAreaInfluenciaHospital_configuracion implements
		java.io.Serializable {

	private Long id;
	private Integer version;
	private Set<Entidad_configuracion> entidads = new HashSet<Entidad_configuracion>(
			0);
	//private Entidad_configuracion entidad;
	private TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud;
	private String nombre;
	private Boolean eliminado;
	private Long cid;

	public EstablecimientoAreaInfluenciaHospital_configuracion() {
	}

	public EstablecimientoAreaInfluenciaHospital_configuracion(Long id,
			Entidad_configuracion entidad,
			TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud) {
		this.id = id;
		//this.entidad = entidad;
		this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
	}

	public EstablecimientoAreaInfluenciaHospital_configuracion(Long id,
			Entidad_configuracion entidad,
			TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud,
			String nombre, Boolean eliminado, Long cid) {
		this.id = id;
		//this.entidad = entidad;
		this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
		this.nombre = nombre;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
/*
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hospital", nullable = false)
	@NotNull
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_establecimiento_salud", nullable = false)
	@NotNull
	public TipoEstablecimientoSalud_configuracion getTipoEstablecimientoSalud() {
		return this.tipoEstablecimientoSalud;
	}

	public void setTipoEstablecimientoSalud(
			TipoEstablecimientoSalud_configuracion tipoEstablecimientoSalud) {
		this.tipoEstablecimientoSalud = tipoEstablecimientoSalud;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "establecimiento_in_entidad", schema = "comun", 
			joinColumns = { @JoinColumn(name = "id_establecimiento", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "id_entidad", nullable = false, updatable = false) })
	public Set<Entidad_configuracion> getEntidads() {
		return entidads;
	}

	public void setEntidads(Set<Entidad_configuracion> entidads) {
		this.entidads = entidads;
	}

}
