package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Funcionalidad generated by hbm2java
 */
@Entity
@Table(name = "funcionalidad", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Funcionalidad_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private String label;
	private String url;
	private Boolean eliminado;
	private Long cid;
	private int orden;
	private String imagen;
	private boolean esModulo;
	private Long idFuncionalidadPadre;
	private Integer labelSize;
	private String nombre;
	private Boolean moduloFisico;
	private boolean contenedorIconos;
	private String codebase;
	private String descripcion;
	private String grupo;
	private Set<ServicioSubmodulo_configuracion> servicioSubmodulos = new HashSet<ServicioSubmodulo_configuracion>(
			0);

	public Funcionalidad_configuracion() {
	}

	public Funcionalidad_configuracion(Long id, int orden, String imagen,
			boolean esModulo, boolean contenedorIconos) {
		this.id = id;
		this.orden = orden;
		this.imagen = imagen;
		this.esModulo = esModulo;
		this.contenedorIconos = contenedorIconos;
	}

	public Funcionalidad_configuracion(Long id, Entidad_configuracion entidad,
			String label, String url, Boolean eliminado, Long cid,
			int orden, String imagen, boolean esModulo,
			Long idFuncionalidadPadre, Integer labelSize, String nombre,
			Boolean moduloFisico, boolean contenedorIconos, String codebase,
			String descripcion, String grupo,
			Set<ServicioSubmodulo_configuracion> servicioSubmodulos) {
		this.id = id;
		this.entidad = entidad;
		this.label = label;
		this.url = url;
		this.eliminado = eliminado;
		this.cid = cid;
		this.orden = orden;
		this.imagen = imagen;
		this.esModulo = esModulo;
		this.idFuncionalidadPadre = idFuncionalidadPadre;
		this.labelSize = labelSize;
		this.nombre = nombre;
		this.moduloFisico = moduloFisico;
		this.contenedorIconos = contenedorIconos;
		this.codebase = codebase;
		this.descripcion = descripcion;
		this.grupo = grupo;
		this.servicioSubmodulos = servicioSubmodulos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@Column(name = "label", length = 150)
	@Length(max = 150)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "orden", nullable = false)
	@NotNull
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "imagen", nullable = false)
	@NotNull
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "es_modulo", nullable = false)
	@NotNull
	public boolean isEsModulo() {
		return this.esModulo;
	}

	public void setEsModulo(boolean esModulo) {
		this.esModulo = esModulo;
	}

	@Column(name = "id_funcionalidad_padre")
	public Long getIdFuncionalidadPadre() {
		return this.idFuncionalidadPadre;
	}

	public void setIdFuncionalidadPadre(Long idFuncionalidadPadre) {
		this.idFuncionalidadPadre = idFuncionalidadPadre;
	}

	@Column(name = "label_size")
	public Integer getLabelSize() {
		return this.labelSize;
	}

	public void setLabelSize(Integer labelSize) {
		this.labelSize = labelSize;
	}

	@Column(name = "nombre", unique = true)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "modulo_fisico")
	public Boolean getModuloFisico() {
		return this.moduloFisico;
	}

	public void setModuloFisico(Boolean moduloFisico) {
		this.moduloFisico = moduloFisico;
	}

	@Column(name = "contenedor_iconos", nullable = false)
	@NotNull
	public boolean isContenedorIconos() {
		return this.contenedorIconos;
	}

	public void setContenedorIconos(boolean contenedorIconos) {
		this.contenedorIconos = contenedorIconos;
	}

	@Column(name = "codebase")
	public String getCodebase() {
		return this.codebase;
	}

	public void setCodebase(String codebase) {
		this.codebase = codebase;
	}

	@Column(name = "descripcion")
	@Length(max = 300)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "grupo")
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionalidad")
	public Set<ServicioSubmodulo_configuracion> getServicioSubmodulos() {
		return this.servicioSubmodulos;
	}

	public void setServicioSubmodulos(
			Set<ServicioSubmodulo_configuracion> servicioSubmodulos) {
		this.servicioSubmodulos = servicioSubmodulos;
	}

}
