package gehos.configuracion.management.entity;

// Generated Mar 17, 2014 1:13:56 PM by Hibernate Tools 3.4.0.CR1

import gehos.configuracion.management.entity.Entidad_configuracion;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * InstanciaHis generated by hbm2java
 */
@Entity
@Table(name = "instancia_his", schema = "comun")
public class InstanciaHis_configuracion implements java.io.Serializable,Cloneable {

	private long id;
	private String nombreInstancia;
	private Long cid;
	private Integer version;
	private Set<Entidad_configuracion> entidads = new HashSet<Entidad_configuracion>(
			0);

	public InstanciaHis_configuracion() {
	}
	

	public InstanciaHis_configuracion(long id) {
		this.id = id;
	}

	public InstanciaHis_configuracion(long id, String nombreInstancia,
			 Long cid, Set<Entidad_configuracion> entidads) {
		this.id = id;
		this.nombreInstancia = nombreInstancia;
		this.cid = cid;
		this.entidads = entidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "nombre_instancia")
	public String getNombreInstancia() {
		return this.nombreInstancia;
	}

	public void setNombreInstancia(String nombreInstancia) {
		if (nombreInstancia != null)
			nombreInstancia = nombreInstancia.trim();
		this.nombreInstancia = nombreInstancia;
	}

	
	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instanciaHis")
	public Set<Entidad_configuracion> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_configuracion> entidads) {
		this.entidads = entidads;
	}
	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	

}
