package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name = "localidad", schema = "nomencladores")
public class Localidad_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Municipio_configuracion municipio;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private Set<Entidad_configuracion> entidads = new HashSet<Entidad_configuracion>(
			0);

	public Localidad_configuracion() {
	}

	public Localidad_configuracion(Long id, Municipio_configuracion municipio,
			String valor) {
		this.id = id;
		this.municipio = municipio;
		this.valor = valor;
	}

	public Localidad_configuracion(Long id, Municipio_configuracion municipio,
			String valor, Boolean eliminado, Long cid, String codigo,
			Set<Entidad_configuracion> entidads) {
		this.id = id;
		this.municipio = municipio;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.entidads = entidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio", nullable = false)
	@NotNull
	public Municipio_configuracion getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio_configuracion municipio) {
		this.municipio = municipio;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
	public Set<Entidad_configuracion> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_configuracion> entidads) {
		this.entidads = entidads;
	}

}
