package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * MedicoInEntidad generated by hbm2java
 */
@Entity
@Table(name = "medico_in_entidad", schema = "comun")
public class MedicoInEntidad_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Medico_configuracion medico;
	/*private Especialidad_configuracion especialidad;*/
	private Long cid;
	private Boolean eliminado;
	private Set<EspecialidadInEntidad_configuracion> especialidads = new HashSet<EspecialidadInEntidad_configuracion>(
			0);

	public MedicoInEntidad_configuracion() {
	}

	public MedicoInEntidad_configuracion(Long id) {
		this.id = id;
	}

	public MedicoInEntidad_configuracion(Long id, Entidad_configuracion entidad,
			Medico_configuracion medico, Long cid, Boolean eliminado,
			Set<Especialidad_configuracion> especialidads) {
		this.id = id;
		this.entidad = entidad;
		this.medico = medico;
		this.cid = cid;
		this.eliminado = eliminado;
		// this.especialidads = especialidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_medico")
	public Medico_configuracion getMedico() {
		return this.medico;
	}

	public void setMedico(Medico_configuracion medico) {
		this.medico = medico;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_especialidad")
	public Especialidad_configuracion getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(Especialidad_configuracion especialidad) {
		this.especialidad = especialidad;
	}*/

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "medico_in_entidad_in_especialidads", schema = "comun", 
			joinColumns = { @JoinColumn(name = "id_medico_in_entidad", nullable = false, updatable = false) }, 
			inverseJoinColumns = { @JoinColumn(name = "id_especialidad_in_entidad", nullable = false, updatable = false) })
	public Set<EspecialidadInEntidad_configuracion> getEspecialidads() {
		return this.especialidads;
	}

	public void setEspecialidads(Set<EspecialidadInEntidad_configuracion> especialidads) {
		this.especialidads = especialidads;
	}

}
