package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MedicoExterno generated by hbm2java
 */
@Entity
@Table(name = "medico_externo", schema = "comun")
public class MedicoExterno_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String cedula;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String matriculaColegioMedico;
	private String matriculaMinisterio;
	private String nombreClinica;
	private Boolean eliminado;
	private Long cid;

	public MedicoExterno_configuracion() {
	}

	public MedicoExterno_configuracion(Long id) {
		this.id = id;
	}

	public MedicoExterno_configuracion(Long id, String cedula, String nombre,
			String apellido1, String apellido2, String matriculaColegioMedico,
			String matriculaMinisterio, String nombreClinica,
			Boolean eliminado, Long cid) {
		this.id = id;
		this.cedula = cedula;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.matriculaColegioMedico = matriculaColegioMedico;
		this.matriculaMinisterio = matriculaMinisterio;
		this.nombreClinica = nombreClinica;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1")
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2")
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "matricula_colegio_medico", length = 20)
	@Length(max = 20)
	public String getMatriculaColegioMedico() {
		return this.matriculaColegioMedico;
	}

	public void setMatriculaColegioMedico(String matriculaColegioMedico) {
		this.matriculaColegioMedico = matriculaColegioMedico;
	}

	@Column(name = "matricula_ministerio", length = 20)
	@Length(max = 20)
	public String getMatriculaMinisterio() {
		return this.matriculaMinisterio;
	}

	public void setMatriculaMinisterio(String matriculaMinisterio) {
		this.matriculaMinisterio = matriculaMinisterio;
	}

	@Column(name = "nombre_clinica")
	public String getNombreClinica() {
		return this.nombreClinica;
	}

	public void setNombreClinica(String nombreClinica) {
		this.nombreClinica = nombreClinica;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
