package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name = "medico", schema = "comun", uniqueConstraints = {
		@UniqueConstraint(columnNames = "matricula_ministerio"),
		@UniqueConstraint(columnNames = "matricula_colegio_medico") })
public class Medico_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Usuario_configuracion usuario;
	private String matriculaMinisterio;
	private Boolean eliminado;
	private Long cid;
	private String matriculaColegioMedico;
	private Date fechaGraduacion;
	private Set<MedicoInEntidad_configuracion> medicoInEntidads = new HashSet<MedicoInEntidad_configuracion>(
			0);
	private Set<Especialidad_configuracion> especialidads = new HashSet<Especialidad_configuracion>(
			0);

	public Medico_configuracion() {
	}

	public Medico_configuracion(Usuario_configuracion usuario,
			String matriculaMinisterio, String matriculaColegioMedico,
			Date fechaGraduacion) {
		this.usuario = usuario;
		this.matriculaMinisterio = matriculaMinisterio;
		this.matriculaColegioMedico = matriculaColegioMedico;
		this.fechaGraduacion = fechaGraduacion;
	}

	public Medico_configuracion(Usuario_configuracion usuario,
			String matriculaMinisterio, Boolean eliminado, Long cid,
			String matriculaColegioMedico, Date fechaGraduacion,
			Set<MedicoInEntidad_configuracion> medicoInEntidads,
			Set<Especialidad_configuracion> especialidads) {
		this.usuario = usuario;
		this.matriculaMinisterio = matriculaMinisterio;
		this.eliminado = eliminado;
		this.cid = cid;
		this.matriculaColegioMedico = matriculaColegioMedico;
		this.fechaGraduacion = fechaGraduacion;
		this.medicoInEntidads = medicoInEntidads;
		this.especialidads = especialidads;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Usuario_configuracion getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_configuracion usuario) {
		this.usuario = usuario;
	}

	@Column(name = "matricula_ministerio", unique = true, length = 20)
	@Length(max = 20)
	public String getMatriculaMinisterio() {
		return this.matriculaMinisterio;
	}

	public void setMatriculaMinisterio(String matriculaMinisterio) {
		this.matriculaMinisterio = matriculaMinisterio;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "matricula_colegio_medico", unique = true, length = 20)
	@Length(max = 20)
	public String getMatriculaColegioMedico() {
		return this.matriculaColegioMedico;
	}

	public void setMatriculaColegioMedico(String matriculaColegioMedico) {
		this.matriculaColegioMedico = matriculaColegioMedico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_graduacion", length = 13)
	public Date getFechaGraduacion() {
		return this.fechaGraduacion;
	}

	public void setFechaGraduacion(Date fechaGraduacion) {
		this.fechaGraduacion = fechaGraduacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medico")
	public Set<MedicoInEntidad_configuracion> getMedicoInEntidads() {
		return this.medicoInEntidads;
	}

	public void setMedicoInEntidads(
			Set<MedicoInEntidad_configuracion> medicoInEntidads) {
		this.medicoInEntidads = medicoInEntidads;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "medico_in_especialidad", schema = "comun", joinColumns = { @JoinColumn(name = "id_medico", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_especialidad", nullable = false, updatable = false) })
	public Set<Especialidad_configuracion> getEspecialidads() {
		return this.especialidads;
	}

	public void setEspecialidads(Set<Especialidad_configuracion> especialidads) {
		this.especialidads = especialidads;
	}

}
