package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "municipio", schema = "nomencladores", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Municipio_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Estado_configuracion estado;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private Set<Localidad_configuracion> localidads = new HashSet<Localidad_configuracion>(
			0);
	private Set<Entidad_configuracion> entidads = new HashSet<Entidad_configuracion>(
			0);

	public Municipio_configuracion() {
	}

	public Municipio_configuracion(Long id, Estado_configuracion estado,
			String valor) {
		this.id = id;
		this.estado = estado;
		this.valor = valor;
	}

	public Municipio_configuracion(Long id, Estado_configuracion estado,
			String valor, Boolean eliminado, Long cid, String codigo,
			Set<Localidad_configuracion> localidads,
			Set<Entidad_configuracion> entidads) {
		this.id = id;
		this.estado = estado;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.localidads = localidads;
		this.entidads = entidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	@NotNull
	public Estado_configuracion getEstado() {
		return this.estado;
	}

	public void setEstado(Estado_configuracion estado) {
		this.estado = estado;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo", unique = true)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public Set<Localidad_configuracion> getLocalidads() {
		return this.localidads;
	}

	public void setLocalidads(Set<Localidad_configuracion> localidads) {
		this.localidads = localidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public Set<Entidad_configuracion> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_configuracion> entidads) {
		this.entidads = entidads;
	}

}
