package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Nacion generated by hbm2java
 */
@Entity
@Table(name = "nacion", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "valor"),
		@UniqueConstraint(columnNames = "nacionalidad") })
public class Nacion_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String valor;
	private String nacionalidad;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private Set<Estado_configuracion> estados = new HashSet<Estado_configuracion>(
			0);

	public Nacion_configuracion() {
	}

	public Nacion_configuracion(Long id, String valor, String nacionalidad) {
		this.id = id;
		this.valor = valor;
		this.nacionalidad = nacionalidad;
	}

	public Nacion_configuracion(Long id, String valor, String nacionalidad,
			Boolean eliminado, Long cid, String codigo,
			Set<Estado_configuracion> estados) {
		this.id = id;
		this.valor = valor;
		this.nacionalidad = nacionalidad;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.estados = estados;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "nacionalidad", unique = true, nullable = false)
	@NotNull
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nacion")
	public Set<Estado_configuracion> getEstados() {
		return this.estados;
	}

	public void setEstados(Set<Estado_configuracion> estados) {
		this.estados = estados;
	}

}
