package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import gehos.ensayo.entity.Entidad_ensayo;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.NotNull;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "organismo", schema = "nomencladores")
public class Organismo_configuracion implements java.io.Serializable {

	private Long id;
	private String valor;
	private String codigo;
	private Integer version;
	private Long cid;
	private Boolean eliminado;
	private Set<Entidad_ensayo> entidads = new HashSet<Entidad_ensayo>(
			0);
	
	public Organismo_configuracion(){
	}

	public Organismo_configuracion(Long id, String valor, String codigo){
		this.id = id;
		this.valor = valor;
		this.codigo = codigo;
	}

	public Organismo_configuracion(Long id, String valor, String codigo, Long cid, Boolean eliminado, Set<Entidad_ensayo> entidads){
		this.id = id;
		this.valor = valor;
		this.codigo = codigo;
		this.cid = cid;
		this.eliminado = eliminado;
		this.entidads = entidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id){
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion(){
		return this.version;
	}

	public void setVersion(Integer version){
		this.version = version;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor(){
		return this.valor;
	}

	public void setValor(String valor){
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado(){
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado){
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid(){
		return this.cid;
	}

	public void setCid(Long cid){
		this.cid = cid;
	}

	@Column(name = "codigo", unique = true)
	public String getCodigo(){
		return this.codigo;
	}

	public void setCodigo(String codigo){
		this.codigo = codigo;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organismo")
	public Set<Entidad_ensayo> getEntidads(){
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_ensayo> entidads){
		this.entidads = entidads;
	}

}