package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * PartidaPresupuestariaHospital generated by hbm2java
 */
@Entity
@Table(name = "partida_presupuestaria_hospital", schema = "comun")
public class PartidaPresupuestariaHospital_configuracion implements
		java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Servicio_configuracion servicio;
	private Departamento_configuracion departamento;
	private EntidadOrganizacional_configuracion entidadOrganizacional;
	private Integer cantidad;
	private Boolean eliminado;
	private Long cid;

	public PartidaPresupuestariaHospital_configuracion() {
	}

	public PartidaPresupuestariaHospital_configuracion(Long id,
			Entidad_configuracion entidad, Integer cantidad) {
		this.id = id;
		this.entidad = entidad;
		this.cantidad = cantidad;
	}

	public PartidaPresupuestariaHospital_configuracion(Long id,
			Entidad_configuracion entidad, Servicio_configuracion servicio,
			Departamento_configuracion departamento,
			EntidadOrganizacional_configuracion entidadOrganizacional,
			Integer cantidad, Boolean eliminado, Long cid) {
		this.id = id;
		this.entidad = entidad;
		this.servicio = servicio;
		this.departamento = departamento;
		this.entidadOrganizacional = entidadOrganizacional;
		this.cantidad = cantidad;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hospital", nullable = false)
	@NotNull
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_destino_servicio")
	public Servicio_configuracion getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio_configuracion servicio) {
		this.servicio = servicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_destino_departamento")
	public Departamento_configuracion getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento_configuracion departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad_organizacional")
	public EntidadOrganizacional_configuracion getEntidadOrganizacional() {
		return this.entidadOrganizacional;
	}

	public void setEntidadOrganizacional(
			EntidadOrganizacional_configuracion entidadOrganizacional) {
		this.entidadOrganizacional = entidadOrganizacional;
	}

	@Column(name = "cantidad")
	@NotNull
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
