package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * PoblacionAreaInfluencia generated by hbm2java
 */
@Entity
@Table(name = "poblacion_area_influencia", schema = "comun")
public class PoblacionAreaInfluencia_configuracion implements
		java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Integer valor;
	private Boolean eliminado;
	private Long cid;
	private Date fecha;

	public PoblacionAreaInfluencia_configuracion() {
	}

	public PoblacionAreaInfluencia_configuracion(Long id,
			Entidad_configuracion entidad) {
		this.id = id;
		this.entidad = entidad;
	}

	public PoblacionAreaInfluencia_configuracion(Long id,
			Entidad_configuracion entidad, Integer valor, Boolean eliminado,
			Long cid) {
		this.id = id;
		this.entidad = entidad;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad", nullable = false)
	@NotNull
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@Column(name = "valor")
	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
