package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", schema = "seguridad")
public class Profile_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Usuario_configuracion usuario;
	private String localeString;
	private String theme;
	private Boolean eliminado;
	private Long cid;
	private Boolean treeLikeMenu;

	public Profile_configuracion() {
	}

	public Profile_configuracion(Usuario_configuracion usuario) {
		this.usuario = usuario;
	}

	public Profile_configuracion(Usuario_configuracion usuario,
			String localeString, String theme, Boolean eliminado, Long cid,
			Boolean treeLikeMenu) {
		this.usuario = usuario;
		this.localeString = localeString;
		this.theme = theme;
		this.eliminado = eliminado;
		this.cid = cid;
		this.treeLikeMenu = treeLikeMenu;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Usuario_configuracion getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_configuracion usuario) {
		this.usuario = usuario;
	}

	@Column(name = "locale_string")
	public String getLocaleString() {
		return this.localeString;
	}

	public void setLocaleString(String localeString) {
		this.localeString = localeString;
	}

	@Column(name = "theme")
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "tree_like_menu")
	public Boolean getTreeLikeMenu() {
		return this.treeLikeMenu;
	}

	public void setTreeLikeMenu(Boolean treeLikeMenu) {
		this.treeLikeMenu = treeLikeMenu;
	}

}
