package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Referencia generated by hbm2java
 */
@Entity
@Table(name = "referencia", schema = "comun")
public class Referencia_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidadByIdEntidadOrigen;
	private Entidad_configuracion entidadByIdEntidadDestino;
	private Servicio_configuracion servicio;
	private Long cid;
	private Boolean eliminado;

	public Referencia_configuracion() {
	}

	public Referencia_configuracion(Long id) {
		this.id = id;
	}

	public Referencia_configuracion(Long id,
			Entidad_configuracion entidadByIdEntidadOrigen,
			Entidad_configuracion entidadByIdEntidadDestino,
			Servicio_configuracion servicio, Long cid, Boolean eliminado) {
		this.id = id;
		this.entidadByIdEntidadOrigen = entidadByIdEntidadOrigen;
		this.entidadByIdEntidadDestino = entidadByIdEntidadDestino;
		this.servicio = servicio;
		this.cid = cid;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad_origen")
	public Entidad_configuracion getEntidadByIdEntidadOrigen() {
		return this.entidadByIdEntidadOrigen;
	}

	public void setEntidadByIdEntidadOrigen(
			Entidad_configuracion entidadByIdEntidadOrigen) {
		this.entidadByIdEntidadOrigen = entidadByIdEntidadOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad_destino")
	public Entidad_configuracion getEntidadByIdEntidadDestino() {
		return this.entidadByIdEntidadDestino;
	}

	public void setEntidadByIdEntidadDestino(
			Entidad_configuracion entidadByIdEntidadDestino) {
		this.entidadByIdEntidadDestino = entidadByIdEntidadDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio")
	public Servicio_configuracion getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio_configuracion servicio) {
		this.servicio = servicio;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
