package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Role_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String name;
	private Boolean eliminado;
	private String codigo;
	private Long cid;
	private Set<Usuario_configuracion> usuarios = new HashSet<Usuario_configuracion>(
			0);

	@Column(name = "codigo", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Role_configuracion() {
	}

	public Role_configuracion(Long id, String name, String codigo) {
		this.id = id;
		this.name = name;
		this.codigo = codigo;
	}

	public Role_configuracion(Long id, String name, Boolean eliminado,
			Long cid, Set<Usuario_configuracion> usuarios) {
		this.id = id;
		this.name = name;
		this.eliminado = eliminado;
		this.cid = cid;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_in_role", schema = "seguridad", joinColumns = { @JoinColumn(name = "id_role", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) })
	public Set<Usuario_configuracion> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario_configuracion> usuarios) {
		this.usuarios = usuarios;
	}

}
