package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import gehos.comun.funcionalidades.entity.Funcionalidad;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.NotNull;

/**
 * ServicioSubmodulo generated by hbm2java
 */
@Entity
@Table(name = "servicio_submodulo", schema = "comun")
public class ServicioSubmodulo_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Funcionalidad funcionalidad;
	private ServicioInEntidad_configuracion servicioInEntidad;
	private Boolean eliminado;
	private Long cid;

	public ServicioSubmodulo_configuracion() {
	}

	public ServicioSubmodulo_configuracion(Long id,
			Funcionalidad funcionalidad,
			ServicioInEntidad_configuracion servicioInEntidad) {
		this.id = id;
		this.funcionalidad = funcionalidad;
		this.servicioInEntidad = servicioInEntidad;
	}

	public ServicioSubmodulo_configuracion(Long id,
			Funcionalidad funcionalidad,
			ServicioInEntidad_configuracion servicioInEntidad,
			Boolean eliminado, Long cid) {
		this.id = id;
		this.funcionalidad = funcionalidad;
		this.servicioInEntidad = servicioInEntidad;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_funcionalidad", nullable = false)
	@NotNull
	public Funcionalidad getFuncionalidad() {
		return this.funcionalidad;
	}

	public void setFuncionalidad(Funcionalidad funcionalidad) {
		this.funcionalidad = funcionalidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio", nullable = false)
	@NotNull
	public ServicioInEntidad_configuracion getServicioInEntidad() {
		return this.servicioInEntidad;
	}

	public void setServicioInEntidad(
			ServicioInEntidad_configuracion servicioInEntidad) {
		this.servicioInEntidad = servicioInEntidad;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
