package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.validator.NotNull;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", schema = "comun")
public class Servicio_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Departamento_configuracion departamento;
	private Servicio_configuracion servicio;
	private String nombre;
	private Boolean eliminado;
	private Long cid;
	
	private String codigo;
	private Boolean servicioFisico;
	private Set<Especialidad_configuracion> especialidads = new HashSet<Especialidad_configuracion>(
			0);
	private Set<Servicio_configuracion> servicios = new HashSet<Servicio_configuracion>(
			0);
	private Set<ServicioInEntidad_configuracion> servicioInEntidads = new HashSet<ServicioInEntidad_configuracion>(
			0);
	private Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals = new HashSet<PartidaPresupuestariaHospital_configuracion>(
			0);
	private Set<Referencia_configuracion> referencias = new HashSet<Referencia_configuracion>(
			0);

	public Servicio_configuracion() {
	}

	public Servicio_configuracion(Long id,
			Departamento_configuracion departamento, String nombre,
			String codigo) {
		this.id = id;
		this.departamento = departamento;
		this.nombre = nombre;
		this.codigo = codigo;
	}

	public Servicio_configuracion(
			Long id,
			Departamento_configuracion departamento,
			Servicio_configuracion servicio,
			String nombre,
			Boolean eliminado,
			Long cid,
			Boolean tieneConsultaExterna,
			Boolean tieneHospitalizacion,
			String codigo,
			Boolean servicioFisico,
			Set<Especialidad_configuracion> especialidads,
			Set<Servicio_configuracion> servicios,
			
			Set<ServicioInEntidad_configuracion> servicioInEntidads,
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals,
			Set<Referencia_configuracion> referencias) {
		this.id = id;
		this.departamento = departamento;
		this.servicio = servicio;
		this.nombre = nombre;
		this.eliminado = eliminado;
		this.cid = cid;
		/*this.tieneConsultaExterna = tieneConsultaExterna;
		this.tieneHospitalizacion = tieneHospitalizacion;*/
		this.codigo = codigo;
		this.servicioFisico = servicioFisico;
		this.especialidads = especialidads;
		this.servicios = servicios;
	
		this.servicioInEntidads = servicioInEntidads;
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
		this.referencias = referencias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento", nullable = false)
	@NotNull
	public Departamento_configuracion getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento_configuracion departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio_padre")
	public Servicio_configuracion getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio_configuracion servicio) {
		this.servicio = servicio;
	}

	@Column(name = "nombre", nullable = false)
	@NotNull
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "servicio_fisico")
	public Boolean getServicioFisico() {
		return this.servicioFisico;
	}

	public void setServicioFisico(Boolean servicioFisico) {
		this.servicioFisico = servicioFisico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Especialidad_configuracion> getEspecialidads() {
		return this.especialidads;
	}

	public void setEspecialidads(Set<Especialidad_configuracion> especialidads) {
		this.especialidads = especialidads;
	}

	//@Fetch(FetchMode.SUBSELECT)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Servicio_configuracion> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set<Servicio_configuracion> servicios) {
		this.servicios = servicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<ServicioInEntidad_configuracion> getServicioInEntidads() {
		return this.servicioInEntidads;
	}

	public void setServicioInEntidads(
			Set<ServicioInEntidad_configuracion> servicioInEntidads) {
		this.servicioInEntidads = servicioInEntidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<PartidaPresupuestariaHospital_configuracion> getPartidaPresupuestariaHospitals() {
		return this.partidaPresupuestariaHospitals;
	}

	public void setPartidaPresupuestariaHospitals(
			Set<PartidaPresupuestariaHospital_configuracion> partidaPresupuestariaHospitals) {
		this.partidaPresupuestariaHospitals = partidaPresupuestariaHospitals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<Referencia_configuracion> getReferencias() {
		return this.referencias;
	}

	public void setReferencias(Set<Referencia_configuracion> referencias) {
		this.referencias = referencias;
	}

}
