package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * ServicioInEntidad generated by hbm2java
 */
@Entity
@Table(name = "servicio_in_entidad", schema = "comun")
public class ServicioInEntidad_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private Servicio_configuracion servicio;
	private Boolean tieneConsultaExterna;
	private Boolean tieneHospitalizacion;
	private Boolean tieneEmergencia;
	private Long cid;
	private Boolean eliminado;
	private Set<ServicioSubmodulo_configuracion> servicioSubmodulos = new HashSet<ServicioSubmodulo_configuracion>(
			0);
	private Set<Usuario_configuracion> usuarios = new HashSet<Usuario_configuracion>(
			0);
	private Set<Ubicacion_configuracion> ubicacions = new HashSet<Ubicacion_configuracion>(
			0);
	private Set<Cama_configuracion> camasForIdServicioFlotante = new HashSet<Cama_configuracion>(
			0);
	private Set<Cama_configuracion> camasForIdServicio = new HashSet<Cama_configuracion>(
			0);

	public ServicioInEntidad_configuracion() {
	}

	public ServicioInEntidad_configuracion(Long id) {
		this.id = id;
	}

	public ServicioInEntidad_configuracion(Long id,
			Entidad_configuracion entidad, Servicio_configuracion servicio,
			Long cid, Boolean eliminado,
			Set<ServicioSubmodulo_configuracion> servicioSubmodulos,
			Set<Usuario_configuracion> usuarios,
			Set<Ubicacion_configuracion> ubicacions,
			Set<Cama_configuracion> camasForIdServicioFlotante,
			Set<Cama_configuracion> camasForIdServicio) {
		this.id = id;
		this.entidad = entidad;
		this.servicio = servicio;
		this.cid = cid;
		this.eliminado = eliminado;
		this.servicioSubmodulos = servicioSubmodulos;
		this.usuarios = usuarios;
		this.ubicacions = ubicacions;
		this.camasForIdServicioFlotante = camasForIdServicioFlotante;
		this.camasForIdServicio = camasForIdServicio;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio")
	public Servicio_configuracion getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio_configuracion servicio) {
		this.servicio = servicio;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioInEntidad")
	public Set<ServicioSubmodulo_configuracion> getServicioSubmodulos() {
		return this.servicioSubmodulos;
	}

	public void setServicioSubmodulos(
			Set<ServicioSubmodulo_configuracion> servicioSubmodulos) {
		this.servicioSubmodulos = servicioSubmodulos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_in_servicio", schema = "comun", joinColumns = { @JoinColumn(name = "id_servicio", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) })
	public Set<Usuario_configuracion> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario_configuracion> usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ubicacion_in_servicio", schema = "comun", joinColumns = { @JoinColumn(name = "id_servicio", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_ubicacion", nullable = false, updatable = false) })
	public Set<Ubicacion_configuracion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(Set<Ubicacion_configuracion> ubicacions) {
		this.ubicacions = ubicacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioInEntidadByIdServicioFlotante")
	public Set<Cama_configuracion> getCamasForIdServicioFlotante() {
		return this.camasForIdServicioFlotante;
	}

	public void setCamasForIdServicioFlotante(
			Set<Cama_configuracion> camasForIdServicioFlotante) {
		this.camasForIdServicioFlotante = camasForIdServicioFlotante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicioInEntidadByIdServicio")
	public Set<Cama_configuracion> getCamasForIdServicio() {
		return this.camasForIdServicio;
	}

	public void setCamasForIdServicio(Set<Cama_configuracion> camasForIdServicio) {
		this.camasForIdServicio = camasForIdServicio;
	}

	@Column(name = "tiene_consulta_externa")
	public Boolean getTieneConsultaExterna() {
		return this.tieneConsultaExterna;
	}

	public void setTieneConsultaExterna(Boolean tieneConsultaExterna) {
		this.tieneConsultaExterna = tieneConsultaExterna;
	}

	@Column(name = "tiene_hospitalizacion")
	public Boolean getTieneHospitalizacion() {
		return this.tieneHospitalizacion;
	}

	public void setTieneHospitalizacion(Boolean tieneHospitalizacion) {
		this.tieneHospitalizacion = tieneHospitalizacion;
	}

	@Column(name = "tiene_emergencia")
	public Boolean getTieneEmergencia() {
		return tieneEmergencia;
	}

	public void setTieneEmergencia(Boolean tieneEmergencia) {
		this.tieneEmergencia = tieneEmergencia;
	}

}
