package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * TipoEstablecimientoSalud generated by hbm2java
 */
@Entity
@Table(name = "tipo_establecimiento_salud", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "valor"))
public class TipoEstablecimientoSalud_configuracion implements
		java.io.Serializable {

	private Long id;
	private Integer version;
	private String valor;
	private Boolean eliminado;
	private Long cid;
/*	private Set<Entidad_configuracion> entidads = new HashSet<Entidad_configuracion>(
			0);*/
	private Set<EstablecimientoAreaInfluenciaHospital_configuracion> establecimientoAreaInfluenciaHospitals = new HashSet<EstablecimientoAreaInfluenciaHospital_configuracion>(
			0);

	public TipoEstablecimientoSalud_configuracion() {
	}

	public TipoEstablecimientoSalud_configuracion(Long id, String valor) {
		this.id = id;
		this.valor = valor;
	}

	public TipoEstablecimientoSalud_configuracion(
			Long id,
			String valor,
			Boolean eliminado,
			Long cid,
			Set<Entidad_configuracion> entidads,
			Set<EstablecimientoAreaInfluenciaHospital_configuracion> establecimientoAreaInfluenciaHospitals) {
		this.id = id;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		//this.entidads = entidads;
		this.establecimientoAreaInfluenciaHospitals = establecimientoAreaInfluenciaHospitals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEstablecimientoSalud")
	public Set<Entidad_configuracion> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_configuracion> entidads) {
		this.entidads = entidads;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEstablecimientoSalud")
	public Set<EstablecimientoAreaInfluenciaHospital_configuracion> getEstablecimientoAreaInfluenciaHospitals() {
		return this.establecimientoAreaInfluenciaHospitals;
	}

	public void setEstablecimientoAreaInfluenciaHospitals(
			Set<EstablecimientoAreaInfluenciaHospital_configuracion> establecimientoAreaInfluenciaHospitals) {
		this.establecimientoAreaInfluenciaHospitals = establecimientoAreaInfluenciaHospitals;
	}

}
