package gehos.configuracion.management.entity;

// Generated 18-mar-2010 2:54:01 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * TipoCama generated by hbm2java
 */
@Entity
@Table(name = "tipo_cama", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "valor"))
public class TipoCama_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private String icono;
	private Set<Cama_configuracion> camas = new HashSet<Cama_configuracion>(0);

	public TipoCama_configuracion() {
	}

	public TipoCama_configuracion(Long id, String valor) {
		this.id = id;
		this.valor = valor;
	}

	public TipoCama_configuracion(Long id, String valor, Boolean eliminado,
			Long cid, String codigo, String icono,
			Set<Cama_configuracion> camas) {
		this.id = id;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.icono = icono;
		this.camas = camas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "icono")
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCama")
	public Set<Cama_configuracion> getCamas() {
		return this.camas;
	}

	public void setCamas(Set<Cama_configuracion> camas) {
		this.camas = camas;
	}

}
