package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * TipoUbicacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_ubicacion", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "descripcion"))
public class TipoUbicacion_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String codigo;
	private Boolean eliminado;
	private Long cid;
	private String descripcion;
	private String icono;
	private Boolean motrar;
	private Set<Ubicacion_configuracion> ubicacions = new HashSet<Ubicacion_configuracion>(
			0);

	public TipoUbicacion_configuracion() {
	}

	public TipoUbicacion_configuracion(Long id, String codigo, String descripcion) {
		this.id = id;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public TipoUbicacion_configuracion(Long id, String codigo,
			Boolean eliminado, Long cid, String descripcion, String icono,
			Boolean motrar, Set<Ubicacion_configuracion> ubicacions) {
		this.id = id;
		this.codigo = codigo;
		this.eliminado = eliminado;
		this.cid = cid;
		this.descripcion = descripcion;
		this.icono = icono;
		this.motrar = motrar;
		this.ubicacions = ubicacions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "codigo", nullable = false)
	@NotNull
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "descripcion", unique = true, nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "icono")
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@Column(name = "motrar")
	public Boolean getMotrar() {
		return this.motrar;
	}

	public void setMotrar(Boolean motrar) {
		this.motrar = motrar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUbicacion")
	public Set<Ubicacion_configuracion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(Set<Ubicacion_configuracion> ubicacions) {
		this.ubicacions = ubicacions;
	}

}
