package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Ubicacion generated by hbm2java
 */
@Entity
@Table(name = "ubicacion", schema = "comun")
public class Ubicacion_configuracion implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Entidad_configuracion entidad;
	private TipoUbicacion_configuracion tipoUbicacion;
	private Ubicacion_configuracion ubicacion;
	private Boolean eliminado;
	private Long cid;
	private String identificador;
	private Set<Cama_configuracion> camas = new HashSet<Cama_configuracion>(0);
	private Set<Ubicacion_configuracion> ubicacions = new HashSet<Ubicacion_configuracion>(
			0);
	private Set<ServicioInEntidad_configuracion> servicioInEntidads = new HashSet<ServicioInEntidad_configuracion>(
			0);

	public Ubicacion_configuracion() {
	}

	public Ubicacion_configuracion(Long id,
			TipoUbicacion_configuracion tipoUbicacion, String identificador) {
		this.id = id;
		this.tipoUbicacion = tipoUbicacion;
		this.identificador = identificador;
	}

	public Ubicacion_configuracion(Long id, Entidad_configuracion entidad,
			TipoUbicacion_configuracion tipoUbicacion,
			Ubicacion_configuracion ubicacion, Boolean eliminado, Long cid,
			String identificador, Set<Cama_configuracion> camas,
			Set<Ubicacion_configuracion> ubicacions,
			Set<ServicioInEntidad_configuracion> servicioInEntidads) {
		this.id = id;
		this.entidad = entidad;
		this.tipoUbicacion = tipoUbicacion;
		this.ubicacion = ubicacion;
		this.eliminado = eliminado;
		this.cid = cid;
		this.identificador = identificador;
		this.camas = camas;
		this.ubicacions = ubicacions;
		this.servicioInEntidads = servicioInEntidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_ubicacion", nullable = false)
	@NotNull
	public TipoUbicacion_configuracion getTipoUbicacion() {
		return this.tipoUbicacion;
	}

	public void setTipoUbicacion(TipoUbicacion_configuracion tipoUbicacion) {
		this.tipoUbicacion = tipoUbicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ubicacion_padre")
	public Ubicacion_configuracion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion_configuracion ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "identificador", nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "gen_ubicacion_identificador")
	@SequenceGenerator(name = "gen_ubicacion_identificador", sequenceName = "comun.ubicacion_identificador_seq", allocationSize = 1)
	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicacion")
	public Set<Cama_configuracion> getCamas() {
		return this.camas;
	}

	public void setCamas(Set<Cama_configuracion> camas) {
		this.camas = camas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicacion")
	public Set<Ubicacion_configuracion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(Set<Ubicacion_configuracion> ubicacions) {
		this.ubicacions = ubicacions;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ubicacion_in_servicio", schema = "comun", joinColumns = { @JoinColumn(name = "id_ubicacion", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_servicio", nullable = false, updatable = false) })
	public Set<ServicioInEntidad_configuracion> getServicioInEntidads() {
		return this.servicioInEntidads;
	}

	public void setServicioInEntidads(
			Set<ServicioInEntidad_configuracion> servicioInEntidads) {
		this.servicioInEntidads = servicioInEntidads;
	}

}
