package gehos.configuracion.management.entity;

// Generated 22-ene-2010 11:07:30 by Hibernate Tools 3.2.4.GA

import gehos.comun.datoslab.entity.Persona;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "comun")
public class Usuario_configuracion implements java.io.Serializable {

	private Persona persona;
	private Long id;
	private Integer version;
	private String nombre;
	private String username;
	private String password;
	private Date fechaNacimiento;
	private Boolean eliminado;
	private Long cid;
	private Boolean cuentaHabilitada;
	private String primerApellido;
	private String segundoApellido;
	private String direccionParticular;
	private String cedula;
	private String pasaporte;
	private String telefono;
	private Long idTipoIdentidad;
	private Long idProfile;
	private String idRis;
	private String email;
	private int failedAccessAttemptCount;
	private Date passwordDate;
	private Set<ServicioInEntidad_configuracion> servicioInEntidads = new HashSet<ServicioInEntidad_configuracion>(
			0);
	private Set<TipoFuncionario_configuracion> tipoFuncionarios = new HashSet<TipoFuncionario_configuracion>(
			0);
	private Medico_configuracion medico;
	private Set<Role_configuracion> roles = new HashSet<Role_configuracion>(0);
	private Enfermera_configuracion enfermera;
	private Profile_configuracion profile;
	private Set<CargoFuncionario_configuracion> cargoFuncionarios = new HashSet<CargoFuncionario_configuracion>(
			0);

	public Usuario_configuracion() {
	}

	public Usuario_configuracion(Long id, String nombre, String username,
			String password) {
		this.id = id;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
	}

	public Usuario_configuracion(Long id, String nombre, String username,
			String password, Date fechaNacimiento, Boolean eliminado, Long cid,
			Boolean cuentaHabilitada, String primerApellido,
			String segundoApellido, String direccionParticular, String cedula,
			String pasaporte, String telefono, Long idTipoIdentidad,
			Long idProfile,
			Set<ServicioInEntidad_configuracion> servicioInEntidads,
			Set<TipoFuncionario_configuracion> tipoFuncionarios,
			Medico_configuracion medico, Set<Role_configuracion> roles,
			Enfermera_configuracion enfermera, Profile_configuracion profile, String email,
			Set<CargoFuncionario_configuracion> cargoFuncionarios) {
		this.id = id;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
		this.fechaNacimiento = fechaNacimiento;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cuentaHabilitada = cuentaHabilitada;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.direccionParticular = direccionParticular;
		this.cedula = cedula;
		this.pasaporte = pasaporte;
		this.telefono = telefono;
		this.idTipoIdentidad = idTipoIdentidad;
		this.idProfile = idProfile;
		this.servicioInEntidads = servicioInEntidads;
		this.tipoFuncionarios = tipoFuncionarios;
		this.medico = medico;
		this.roles = roles;
		this.enfermera = enfermera;
		this.profile = profile;
		this.cargoFuncionarios = cargoFuncionarios;
		this.email = email;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "username", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "cuenta_habilitada")
	public Boolean getCuentaHabilitada() {
		return this.cuentaHabilitada;
	}

	public void setCuentaHabilitada(Boolean cuentaHabilitada) {
		this.cuentaHabilitada = cuentaHabilitada;
	}

	@Column(name = "primer_apellido")
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido")
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "direccion_particular")
	public String getDireccionParticular() {
		return this.direccionParticular;
	}

	public void setDireccionParticular(String direccionParticular) {
		this.direccionParticular = direccionParticular;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "pasaporte")
	public String getPasaporte() {
		return this.pasaporte;
	}

	public void setPasaporte(String pasaporte) {
		this.pasaporte = pasaporte;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "id_tipo_identidad")
	public Long getIdTipoIdentidad() {
		return this.idTipoIdentidad;
	}

	public void setIdTipoIdentidad(Long idTipoIdentidad) {
		this.idTipoIdentidad = idTipoIdentidad;
	}

	@Column(name = "id_profile")
	public Long getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(Long idProfile) {
		this.idProfile = idProfile;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_in_servicio", schema = "comun", joinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_servicio", nullable = false, updatable = false) })
	public Set<ServicioInEntidad_configuracion> getServicioInEntidads() {
		return this.servicioInEntidads;
	}

	public void setServicioInEntidads(
			Set<ServicioInEntidad_configuracion> servicioInEntidads) {
		this.servicioInEntidads = servicioInEntidads;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_in_tipo_funcionario", schema = "comun", joinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_tipo_funcionario", nullable = false, updatable = false) })
	public Set<TipoFuncionario_configuracion> getTipoFuncionarios() {
		return this.tipoFuncionarios;
	}

	public void setTipoFuncionarios(
			Set<TipoFuncionario_configuracion> tipoFuncionarios) {
		this.tipoFuncionarios = tipoFuncionarios;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Medico_configuracion getMedico() {
		return this.medico;
	}

	public void setMedico(Medico_configuracion medico) {
		this.medico = medico;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_in_role", schema = "seguridad", joinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_role", nullable = false, updatable = false) })
	public Set<Role_configuracion> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role_configuracion> roles) {
		this.roles = roles;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Enfermera_configuracion getEnfermera() {
		return this.enfermera;
	}

	public void setEnfermera(Enfermera_configuracion enfermera) {
		this.enfermera = enfermera;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Profile_configuracion getProfile() {
		return this.profile;
	}

	public void setProfile(Profile_configuracion profile) {
		this.profile = profile;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_in_cargo", schema = "comun", joinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_cargo", nullable = false, updatable = false) })
	public Set<CargoFuncionario_configuracion> getCargoFuncionarios() {
		return this.cargoFuncionarios;
	}

	public void setCargoFuncionarios(
			Set<CargoFuncionario_configuracion> cargoFuncionarios) {
		this.cargoFuncionarios = cargoFuncionarios;
	}

	@Column(name = "id_ris")
	public String getIdRis() {
		return idRis;
	}

	public void setIdRis(String idRis) {
		this.idRis = idRis;
	}

	@Column(name = "failed_access_attempt_count")
	public int getFailedAccessAttemptCount() {
		return this.failedAccessAttemptCount;
	}

	public void setFailedAccessAttemptCount(int failedAccessAttemptCount) {
		this.failedAccessAttemptCount = failedAccessAttemptCount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "password_date", length = 13)
	public Date getPasswordDate() {
		return this.passwordDate;
	}

	public void setPasswordDate(Date passwordDate) {
		this.passwordDate = passwordDate;
	}

	@Column(name = "email")
	public String getEmail(){
		return this.email;
	}

	public void setEmail(String email){
		this.email = email;
	}

	

}
