package gehos.bitacora.entity;

// Generated 06-sep-2008 12:42:23 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.hibernate.annotations.Proxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Funcionalidad generated by hbm2java
 */
@Entity
@Table(name = "funcionalidad", schema = "seguridad")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE, include="non-lazy")
public class Funcionalidad_Bitacora implements java.io.Serializable {

	private static final Long serialVersionUID = 6334639677372932667L;
	private Long id;
	private Integer version;
	
	private Boolean esModulo;
	private Boolean moduloFisico;
	private Boolean contenedorIconos;
	private String label;
	private String url;
	private Boolean eliminado;
	private Long cid;
	private Integer orden;
	private String imagen;
	private String nombre;
	private Integer labelSize;
	private Funcionalidad_Bitacora funcionalidadPadre;
	private Set<Funcionalidad_Bitacora> funcionalidadesHijas = new HashSet<Funcionalidad_Bitacora>(0);
	private Set<TrazaModuloAccedido> trazaModuloAccedidos = new HashSet<TrazaModuloAccedido>(
			0);
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "modulo")
	public Set<TrazaModuloAccedido> getTrazaModuloAccedidos() {
		return this.trazaModuloAccedidos;
	}

	public void setTrazaModuloAccedidos(
			Set<TrazaModuloAccedido> trazaModuloAccedidos) {
		this.trazaModuloAccedidos = trazaModuloAccedidos;
	}
	
	
	@Column(name = "label_size")
	public Integer getLabelSize() {
		return labelSize;
	}
	public void setLabelSize(Integer labelSize) {
		this.labelSize = labelSize;
	}
	@Column(name = "nombre", unique = true)
	public String getNombre() {
		return this.nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_funcionalidad_padre")
	public Funcionalidad_Bitacora getFuncionalidadPadre() {
		return this.funcionalidadPadre;
	}

	public void setFuncionalidadPadre(Funcionalidad_Bitacora fun) {
		this.funcionalidadPadre = fun;
	}
	
	@Fetch(FetchMode.SUBSELECT)
	@OrderBy("id")
	@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "funcionalidadPadre")
	public Set<Funcionalidad_Bitacora> getFuncionalidadesHijas() {
		return this.funcionalidadesHijas;
	}

	public void setFuncionalidadesHijas(Set<Funcionalidad_Bitacora> funs) {
		this.funcionalidadesHijas = funs;
	}

	public Funcionalidad_Bitacora() {
	}

	public Funcionalidad_Bitacora(Long id) {
		this.id = id;
	}

	public Funcionalidad_Bitacora(Long id, String label, String url,
			Boolean eliminado, Long cid, Integer order, String imagen,
			Set<Funcionalidad_Bitacora> funcionalidadsForFuncionalidadId,
			
			Set<Funcionalidad_Bitacora> funcionalidadsForCategoryId) {
		this.id = id;
		
		this.label = label;
		this.url = url;
		this.eliminado = eliminado;
		this.cid = cid;
		this.orden = order;
		this.imagen = imagen;
		
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "es_modulo")
	public Boolean getEsModulo() {
		return esModulo;
	}

	public void setEsModulo(Boolean esModulo) {
		this.esModulo = esModulo;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	@Column(name = "label", length = 70)
	@Length(max = 70)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "url", length = 200)
	@Length(max = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "imagen")
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "modulo_fisico")
	public Boolean getModuloFisico() {
		return moduloFisico;
	}
	public void setModuloFisico(Boolean moduloFisico) {
		this.moduloFisico = moduloFisico;
	}
	@Column(name = "contenedor_iconos")
	public Boolean getContenedorIconos() {
		return contenedorIconos;
	}
	public void setContenedorIconos(Boolean contenedorIconos) {
		this.contenedorIconos = contenedorIconos;
	}


}
