package gehos.bitacora.entity;

// Generated Apr 29, 2008 5:58:19 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * TrazaModuloAccedido generated by hbm2java
 */
@Entity
@Table(name = "traza_modulo_accedido", schema = "bitacora")
public class TrazaModuloAccedido implements java.io.Serializable {

	private Long id;
	private Funcionalidad_Bitacora modulo;
	private TrazaSession trazaSession;
	private Date hora;
	private Set<TrazaAccion> trazaAccions = new HashSet<TrazaAccion>(0);

	public TrazaModuloAccedido() {
	}

	public TrazaModuloAccedido(Long id) {
		this.id = id;
	}

	public TrazaModuloAccedido(Long id, Funcionalidad_Bitacora modulo,
			TrazaSession trazaSession, Date hora, Set<TrazaAccion> trazaAccions) {
		this.id = id;
		this.modulo = modulo;
		this.trazaSession = trazaSession;
		this.hora = hora;
		this.trazaAccions = trazaAccions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modulo")
	public Funcionalidad_Bitacora getModulo() {
		return this.modulo;
	}

	public void setModulo(Funcionalidad_Bitacora modulo) {
		this.modulo = modulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session")
	public TrazaSession getTrazaSession() {
		return this.trazaSession;
	}

	public void setTrazaSession(TrazaSession trazaSession) {
		this.trazaSession = trazaSession;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "trazaModuloAccedido")
	public Set<TrazaAccion> getTrazaAccions() {
		return this.trazaAccions;
	}

	public void setTrazaAccions(Set<TrazaAccion> trazaAccions) {
		this.trazaAccions = trazaAccions;
	}

}
