package gehos.bitacora.entity;

// Generated Apr 29, 2008 5:58:19 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TrazaAccion generated by hbm2java
 */
@Entity
@Table(name = "traza_accion", schema = "bitacora")
public class TrazaAccion implements java.io.Serializable {

	private Long id;
	private TrazaModuloAccedido trazaModuloAccedido;
	private Date horaInicio;
	private Date horaFin;
	private String accionRealizada;
	private Set<TrazaAtributoModificado> trazaAtributoModificados = new HashSet<TrazaAtributoModificado>(
			0);

	public TrazaAccion() {
	}

	public TrazaAccion(Long id) {
		this.id = id;
	}

	public TrazaAccion(Long id, TrazaModuloAccedido trazaModuloAccedido,
			Date horaInicio, String accionRealizada,
			Set<TrazaAtributoModificado> trazaAtributoModificados, Date horaFin) {
		this.id = id;
		this.trazaModuloAccedido = trazaModuloAccedido;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.accionRealizada = accionRealizada;
		this.trazaAtributoModificados = trazaAtributoModificados;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modulo_accedido")
	public TrazaModuloAccedido getTrazaModuloAccedido() {
		return this.trazaModuloAccedido;
	}

	public void setTrazaModuloAccedido(TrazaModuloAccedido trazaModuloAccedido) {
		this.trazaModuloAccedido = trazaModuloAccedido;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date hora) {
		this.horaInicio = hora;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date hora) {
		this.horaFin = hora;
	}

	@Column(name = "accion_realizada")
	public String getAccionRealizada() {
		return this.accionRealizada;
	}

	public void setAccionRealizada(String accionRealizada) {
		this.accionRealizada = accionRealizada;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "trazaAccion")
	public Set<TrazaAtributoModificado> getTrazaAtributoModificados() {
		return this.trazaAtributoModificados;
	}

	public void setTrazaAtributoModificados(
			Set<TrazaAtributoModificado> trazaAtributoModificados) {
		this.trazaAtributoModificados = trazaAtributoModificados;
	}

}
