package gehos.bitacora.entity;

// Generated Apr 29, 2008 5:58:19 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TrazaSession generated by hbm2java
 */
@Entity
@Table(name = "traza_session", schema = "bitacora")
public class TrazaSession implements java.io.Serializable {

	private Long id;
	private User_Bitacora user;
	private Date fechaInicio;
	private Date horaInicio;
	private String direccionIp;
	private Integer anno;
	private Integer mes;
	private Integer dia;
	private Set<TrazaModuloAccedido> trazaModuloAccedidos = new HashSet<TrazaModuloAccedido>(
			0);

	public TrazaSession() {
	}

	public TrazaSession(Long id) {
		this.id = id;
	}

	public TrazaSession(Long id, User_Bitacora user, Date fechaInicio, Date horaInicio,
			String direccionIp, Integer anno, Integer mes, Integer dia,
			Set<TrazaModuloAccedido> trazaModuloAccedidos) {
		this.id = id;
		this.user = user;
		this.fechaInicio = fechaInicio;
		this.horaInicio = horaInicio;
		this.direccionIp = direccionIp;
		this.anno = anno;
		this.mes = mes;
		this.dia = dia;
		this.trazaModuloAccedidos = trazaModuloAccedidos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public User_Bitacora getUser() {
		return this.user;
	}

	public void setUser(User_Bitacora user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Column(name = "direccion_ip", length = 23)
	@Length(max = 23)
	public String getDireccionIp() {
		return this.direccionIp;
	}

	public void setDireccionIp(String direccionIp) {
		this.direccionIp = direccionIp;
	}

	@Column(name = "anno")
	public Integer getAnno() {
		return this.anno;
	}

	public void setAnno(Integer anno) {
		this.anno = anno;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "dia")
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "trazaSession")
	public Set<TrazaModuloAccedido> getTrazaModuloAccedidos() {
		return this.trazaModuloAccedidos;
	}

	public void setTrazaModuloAccedidos(
			Set<TrazaModuloAccedido> trazaModuloAccedidos) {
		this.trazaModuloAccedidos = trazaModuloAccedidos;
	}

}
