package gehos.bitacora.entity;

// Generated Apr 29, 2008 5:58:19 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "comun", uniqueConstraints = {
		@UniqueConstraint(columnNames = "nombre") })
public class User_Bitacora implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String name;
	private String username;
	private String password;
	//private Date registrationDate;
/*	private String occupation;
	private String localeString;
	private String theme;*/
	private Boolean eliminado;
	private Long cid;
	private Set<TrazaSession> trazaSessions = new HashSet<TrazaSession>(0);

	public User_Bitacora() {
	}

	public User_Bitacora(Long id, String name, String username, String password,
			Date registrationDate, String occupation) {
		this.id = id;
		this.name = name;
		this.username = username;
		this.password = password;
		//this.registrationDate = registrationDate;
		//this.occupation = occupation;
	}
	
	

	public User_Bitacora(Long id, Integer version, String name,
			String username, String password, Boolean eliminado, Long cid,
			Set<TrazaSession> trazaSessions) {
		super();
		this.id = id;
		this.version = version;
		this.name = name;
		this.username = username;
		this.password = password;
		this.eliminado = eliminado;
		this.cid = cid;
		this.trazaSessions = trazaSessions;
	}

	public User_Bitacora(Long id, String name, String username, String password,
			Date registrationDate, String occupation, String localeString,
			String theme, Boolean eliminado, Long cid,
			Set<TrazaSession> trazaSessions) {
		this.id = id;
		this.name = name;
		this.username = username;
		this.password = password;
		//this.registrationDate = registrationDate;
/*		this.occupation = occupation;
		this.localeString = localeString;
		this.theme = theme;
		this.eliminado = eliminado;*/
		this.cid = cid;
		this.trazaSessions = trazaSessions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "username", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

/*	@Temporal(TemporalType.DATE)
	@Column(name = "registration_date", nullable = false, length = 13)
	@NotNull
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}*/

/*	@Column(name = "occupation", nullable = false)
	@NotNull
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "locale_string")
	public String getLocaleString() {
		return this.localeString;
	}

	public void setLocaleString(String localeString) {
		this.localeString = localeString;
	}

	@Column(name = "theme")
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}
 	*/
	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<TrazaSession> getTrazaSessions() {
		return this.trazaSessions;
	}

	public void setTrazaSessions(Set<TrazaSession> trazaSessions) {
		this.trazaSessions = trazaSessions;
	}

}
