package gehos.comun.funcionalidades.entity;

// Generated 06-sep-2008 12:42:23 by Hibernate Tools 3.2.2.GA

import gehos.configuracion.management.entity.Entidad_configuracion;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.validator.Length;

/**
 * Funcionalidad generated by hbm2java
 */
@Entity
@Table(name = "funcionalidad", schema = "seguridad")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE, include = "non-lazy")
public class Funcionalidad implements java.io.Serializable {
	private static final long serialVersionUID = -395670853978340951L;
	
	private Long id;
	//private Integer version;

	private Boolean esModulo;
	private Boolean moduloFisico;
	private Boolean contenedorIconos;
	private String label;
	private String descripcion;
	private String url;
	private String grupo;
	private Boolean eliminado;
	private Boolean necesitaActivacion;
	private Boolean activo;
	private Long cid;
	private Integer orden;
	private String imagen;
	private String nombre;
	private String codebase;
	private Integer labelSize;
	private Funcionalidad funcionalidadPadre;
	private Set<Funcionalidad> funcionalidadesHijas = new HashSet<Funcionalidad>(
			0);
	private Entidad_configuracion entidad;

	@Column(name = "label_size")
	public Integer getLabelSize() {
		return labelSize;
	}

	public void setLabelSize(Integer labelSize) {
		this.labelSize = labelSize;
	}

	@Column(name = "nombre", unique = true)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_funcionalidad_padre")
	public Funcionalidad getFuncionalidadPadre() {
		return this.funcionalidadPadre;
	}

	public void setFuncionalidadPadre(Funcionalidad fun) {
		this.funcionalidadPadre = fun;
	}

	@OrderBy("orden")
	@Fetch(FetchMode.SUBSELECT)
	@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "funcionalidadPadre")
	public Set<Funcionalidad> getFuncionalidadesHijas() {
		return this.funcionalidadesHijas;
	}

	public void setFuncionalidadesHijas(Set<Funcionalidad> funs) {
		this.funcionalidadesHijas = funs;
	}

	public Funcionalidad() {
	}

	public Funcionalidad(Long id) {
		this.id = id;
	}

	public Funcionalidad(Long id, String label, String url, Boolean eliminado,
			Long cid, Integer order, String imagen,
			Set<Funcionalidad> funcionalidadsForFuncionalidadId,
			Set<Role_comun> roles, Set<User_comun> users,
			Set<Funcionalidad> funcionalidadsForCategoryId) {
		this.id = id;

		this.label = label;
		this.url = url;
		this.eliminado = eliminado;
		this.cid = cid;
		this.orden = order;
		this.imagen = imagen;

	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "es_modulo")
	public Boolean getEsModulo() {
		return esModulo;
	}

	public void setEsModulo(Boolean esModulo) {
		this.esModulo = esModulo;
	}

	/*@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}*/

	@Column(name = "label", length = 70)
	@Length(max = 70)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "descripcion")	
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "url", length = 200)
	@Length(max = 200)	
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "imagen")
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "modulo_fisico")
	public Boolean getModuloFisico() {
		return moduloFisico;
	}

	public void setModuloFisico(Boolean moduloFisico) {
		this.moduloFisico = moduloFisico;
	}

	@Column(name = "contenedor_iconos")
	public Boolean getContenedorIconos() {
		return contenedorIconos;
	}

	public void setContenedorIconos(Boolean contenedorIconos) {
		this.contenedorIconos = contenedorIconos;
	}

	@Column(name = "codebase")
	public String getCodebase() {
		return codebase;
	}

	public void setCodebase(String codebase) {
		this.codebase = codebase;
	}

	@Column(name = "grupo")
	public String getGrupo() {
		return grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@Column(name = "necesita_activacion")
	public Boolean getNecesitaActivacion() {
		return necesitaActivacion;
	}

	public void setNecesitaActivacion(Boolean necesitaActivacion) {
		this.necesitaActivacion = necesitaActivacion;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

}
