package gehos.comun.funcionalidades.entity;

// Generated Apr 22, 2008 8:21:38 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Role_comun implements java.io.Serializable {

	private Long id;
	private String name;
	/*private Set<Funcionalidad> funcionalidads = new HashSet<Funcionalidad>(0);*/

	public Role_comun() {
	}

	public Role_comun(Long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Role_comun(Long id, String name, Set<Funcionalidad> funcionalidads) {
		this.id = id;
		this.name = name;
		/*this.funcionalidads = funcionalidads;*/
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

/*	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "funcionalidad_in_role", schema = "seguridad", joinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "funcionalidad_id", nullable = false, updatable = false) })
	public Set<Funcionalidad> getFuncionalidads() {
		return this.funcionalidads;
	}

	public void setFuncionalidads(Set<Funcionalidad> funcionalidads) {
		this.funcionalidads = funcionalidads;
	}*/

}
