package gehos.comun.funcionalidades.entity;

// Generated 06-sep-2008 12:42:23 by Hibernate Tools 3.2.2.GA



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "comun", uniqueConstraints = {
		@UniqueConstraint(columnNames = "username"),
		@UniqueConstraint(columnNames = "nombre") })
public class User_comun implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String name;
	private String username;
	private String password;
	//private Date registrationDate;
/*	private String occupation;
	private String localeString;*/
/*	private String theme;*/
	private Boolean eliminado;
	private Long cid;
/*	private String skin;
	private String descripcion;*/
	private Boolean cuentaHabilitada;
	//private Set<Funcionalidad> funcionalidads = new HashSet<Funcionalidad>(0);
	private Set<Role_comun> roles = new HashSet<Role_comun>(0);

	public User_comun() {
	}

	public User_comun(Long id, String name, String username, String password,
			Date registrationDate, String occupation) {
		this.id = id;
		this.name = name;
		this.username = username;
		this.password = password;
		//this.registrationDate = registrationDate;
		/*this.occupation = occupation;*/
	}

	public User_comun(Long id, String name, String username, String password,
			Date registrationDate, String occupation, String localeString,
			String theme, Boolean eliminado, Long cid, String skin,
			String descripcion, Boolean cuentaHabilitada,
			Set<Funcionalidad> funcionalidads) {
		this.id = id;
		this.name = name;
		this.username = username;
		this.password = password;
		//this.registrationDate = registrationDate;
/*		this.occupation = occupation;
		this.localeString = localeString;
		this.theme = theme;*/
		this.eliminado = eliminado;
		this.cid = cid;
/*		this.skin = skin;
		this.descripcion = descripcion;*/
		this.cuentaHabilitada = cuentaHabilitada;
		//this.funcionalidads = funcionalidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "username", unique = true, nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

/*	@Temporal(TemporalType.DATE)
	@Column(name = "registration_date", nullable = false, length = 13)
	@NotNull
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}*/

/*	@Column(name = "cargo", nullable = false)
	@NotNull
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "locale_string")
	public String getLocaleString() {
		return this.localeString;
	}

	public void setLocaleString(String localeString) {
		this.localeString = localeString;
	}

	@Column(name = "theme")
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}*/

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

/*	@Column(name = "skin")
	public String getSkin() {
		return this.skin;
	}

	public void setSkin(String skin) {
		this.skin = skin;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}*/

	@Column(name = "cuenta_habilitada")
	public Boolean getCuentaHabilitada() {
		return this.cuentaHabilitada;
	}

	public void setCuentaHabilitada(Boolean cuentaHabilitada) {
		this.cuentaHabilitada = cuentaHabilitada;
	}

/*	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "favoritos", schema = "seguridad", joinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_funcionalidad", nullable = false, updatable = false) })
	public Set<Funcionalidad> getFuncionalidads() {
		return this.funcionalidads;
	}

	public void setFuncionalidads(Set<Funcionalidad> funcionalidads) {
		this.funcionalidads = funcionalidads;
	}*/

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "user_in_role", schema = "seguridad", joinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_role", nullable = false, updatable = false) })
	public Set<Role_comun> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role_comun> roles) {
		this.roles = roles;
	}
	
}
