package gehos.ensayo.entity;

// Generated 06-mar-2017 16:39:14 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * Causa generated by hbm2java
 */
@Entity
@Table(name = "causa", schema = "ensayo")
public class Causa_ensayo implements java.io.Serializable {

	private long id;
	private Sujeto_ensayo sujeto;
	private MomentoSeguimientoEspecifico_ensayo momentoSeguimientoEspecifico;
	private CrdEspecifico_ensayo crdEspecifico;
	private Cronograma_ensayo cronograma;
	private Estudio_ensayo estudio;
	private Usuario_ensayo usuario;
	private String descripcion;
	private String tipoCausa;
	private Long cid;
	private Date fecha;

	public Causa_ensayo() {
	}

	public Causa_ensayo(long id) {
		this.id = id;
	}

	public Causa_ensayo(long id, Sujeto_ensayo sujeto,
			MomentoSeguimientoEspecifico_ensayo momentoSeguimientoEspecifico,
			Cronograma_ensayo cronograma, String descripcion, String tipoCausa, Date fecha, Usuario_ensayo usuario,
	 Estudio_ensayo estudio,
	 CrdEspecifico_ensayo crdEspecifico) {
		this.id = id;
		this.sujeto = sujeto;
		this.momentoSeguimientoEspecifico = momentoSeguimientoEspecifico;
		this.cronograma = cronograma;
		this.descripcion = descripcion;
		this.tipoCausa = tipoCausa;
		this.fecha = fecha;
		this.usuario = usuario;
		this.estudio = estudio;
		this.crdEspecifico = crdEspecifico;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sujeto")
	public Sujeto_ensayo getSujeto() {
		return this.sujeto;
	}

	public void setSujeto(Sujeto_ensayo sujeto) {
		this.sujeto = sujeto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_momento_especifico")
	public MomentoSeguimientoEspecifico_ensayo getMomentoSeguimientoEspecifico() {
		return this.momentoSeguimientoEspecifico;
	}

	public void setMomentoSeguimientoEspecifico(
			MomentoSeguimientoEspecifico_ensayo momentoSeguimientoEspecifico) {
		this.momentoSeguimientoEspecifico = momentoSeguimientoEspecifico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cronograma_general")
	public Cronograma_ensayo getCronograma() {
		return this.cronograma;
	}

	public void setCronograma(Cronograma_ensayo cronograma) {
		this.cronograma = cronograma;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "tipo_causa")
	public String getTipoCausa() {
		return this.tipoCausa;
	}

	public void setTipoCausa(String tipoCausa) {
		if (tipoCausa != null)
			tipoCausa = tipoCausa.trim();
		this.tipoCausa = tipoCausa;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudio")
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_crd_especifico")
	public CrdEspecifico_ensayo getCrdEspecifico() {
		return this.crdEspecifico;
	}

	public void setCrdEspecifico(CrdEspecifico_ensayo crdEspecifico) {
		this.crdEspecifico = crdEspecifico;
	}

	public void setEstudio(Diccionarios_ensayo getdiccionario) {
		// TODO Auto-generated method stub
		
	}

	public void setEstudio(long id2) {
		// TODO Auto-generated method stub
		
	}

}
