package gehos.ensayo.entity;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cie generated by hbm2java
 */
@Entity
@Table(name = "cie", schema = "estandares")
public class Cie_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Cie_ensayo cie;
	private TipoCie_ensayo tipoCie;
	private String codigo;
	private String descripcion;
	private String incluye;
	private String excluye;
	private Diccionarios_ensayo diccionario;
	private String observaciones;
	private Boolean eliminado;
	private Long cid;
	private Set<Cie_ensayo> cies = new HashSet<Cie_ensayo>(0);

	public Cie_ensayo() {
	}

	public Cie_ensayo(long id, String codigo, String descripcion) {
		this.id = id;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Cie_ensayo(long id, Cie_ensayo cie, TipoCie_ensayo tipoCie, Diccionarios_ensayo diccionario,
			String codigo, String descripcion, String incluye, String excluye,
			String observaciones, Boolean eliminado, Long cid,
			Set<Cie_ensayo> cies) {
		this.id = id;
		this.cie = cie;
		this.tipoCie = tipoCie;
		this.diccionario = diccionario;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.incluye = incluye;
		this.excluye = excluye;
		this.observaciones = observaciones;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cies = cies;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cie_padre")
	public Cie_ensayo getCie() {
		return this.cie;
	}

	public void setCie(Cie_ensayo cie) {
		this.cie = cie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cie")
	public TipoCie_ensayo getTipoCie() {
		return this.tipoCie;
	}

	public void setTipoCie(TipoCie_ensayo tipoCie) {
		this.tipoCie = tipoCie;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_diccionarios")
	public Diccionarios_ensayo getDiccionario() {
		return this.diccionario;
	}
	
	public void setDiccionario(Diccionarios_ensayo diccionario) {
		this.diccionario = diccionario;
	}
	
	@Column(name = "codigo", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@Column(name = "descripcion", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "incluye")
	public String getIncluye() {
		return this.incluye;
	}

	public void setIncluye(String incluye) {
		if (incluye != null)
			incluye = incluye.trim();
		this.incluye = incluye;
	}

	@Column(name = "excluye")
	public String getExcluye() {
		return this.excluye;
	}

	public void setExcluye(String excluye) {
		if (excluye != null)
			excluye = excluye.trim();
		this.excluye = excluye;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		if (observaciones != null)
			observaciones = observaciones.trim();
		this.observaciones = observaciones;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cie")
	public Set<Cie_ensayo> getCies() {
		return this.cies;
	}

	public void setCies(Set<Cie_ensayo> cies) {
		this.cies = cies;
	}

}
