package gehos.ensayo.entity;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CieCategoria generated by hbm2java
 */
@Entity
@Table(name = "cie_categoria", schema = "estandares", uniqueConstraints = {
		@UniqueConstraint(columnNames = "codigo_categoria"),
		@UniqueConstraint(columnNames = "descripcion") })
public class CieCategoria_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private CieGrupo_ensayo cieGrupo;
	private String codigoCategoria;
	private String descripcion;
	private String incluye;
	private String excluye;
	private String observaciones;
	private Boolean eliminado;
	private Long cid;
	private Set<CieSubcategoria_ensayo> cieSubcategorias = new HashSet<CieSubcategoria_ensayo>(
			0);

	public CieCategoria_ensayo() {
	}

	public CieCategoria_ensayo(long id, CieGrupo_ensayo cieGrupo,
			String codigoCategoria, String descripcion) {
		this.id = id;
		this.cieGrupo = cieGrupo;
		this.codigoCategoria = codigoCategoria;
		this.descripcion = descripcion;
	}

	public CieCategoria_ensayo(long id, CieGrupo_ensayo cieGrupo,
			String codigoCategoria, String descripcion, String incluye,
			String excluye, String observaciones, Boolean eliminado, Long cid,
			Set<CieSubcategoria_ensayo> cieSubcategorias) {
		this.id = id;
		this.cieGrupo = cieGrupo;
		this.codigoCategoria = codigoCategoria;
		this.descripcion = descripcion;
		this.incluye = incluye;
		this.excluye = excluye;
		this.observaciones = observaciones;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cieSubcategorias = cieSubcategorias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo", nullable = false)
	@NotNull
	public CieGrupo_ensayo getCieGrupo() {
		return this.cieGrupo;
	}

	public void setCieGrupo(CieGrupo_ensayo cieGrupo) {
		this.cieGrupo = cieGrupo;
	}

	@Column(name = "codigo_categoria", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodigoCategoria() {
		return this.codigoCategoria;
	}

	public void setCodigoCategoria(String codigoCategoria) {
		if (codigoCategoria != null)
			codigoCategoria = codigoCategoria.trim();
		this.codigoCategoria = codigoCategoria;
	}

	@Column(name = "descripcion", unique = true, nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "incluye")
	public String getIncluye() {
		return this.incluye;
	}

	public void setIncluye(String incluye) {
		if (incluye != null)
			incluye = incluye.trim();
		this.incluye = incluye;
	}

	@Column(name = "excluye")
	public String getExcluye() {
		return this.excluye;
	}

	public void setExcluye(String excluye) {
		if (excluye != null)
			excluye = excluye.trim();
		this.excluye = excluye;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		if (observaciones != null)
			observaciones = observaciones.trim();
		this.observaciones = observaciones;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cieCategoria")
	public Set<CieSubcategoria_ensayo> getCieSubcategorias() {
		return this.cieSubcategorias;
	}

	public void setCieSubcategorias(Set<CieSubcategoria_ensayo> cieSubcategorias) {
		this.cieSubcategorias = cieSubcategorias;
	}

}
