package gehos.ensayo.entity;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CieCapitulo generated by hbm2java
 */
@Entity
@Table(name = "cie_capitulo", schema = "estandares", uniqueConstraints = {
		@UniqueConstraint(columnNames = "descripcion"),
		@UniqueConstraint(columnNames = "codigo_capitulo") })
public class CieCapitulo_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String codigoCapitulo;
	private String descripcion;
	private String incluye;
	private String excluye;
	private String observaciones;
	private Boolean eliminado;
	private Long cid;
	private Set<CieGrupo_ensayo> cieGrupos = new HashSet<CieGrupo_ensayo>(0);

	public CieCapitulo_ensayo() {
	}

	public CieCapitulo_ensayo(long id, String codigoCapitulo, String descripcion) {
		this.id = id;
		this.codigoCapitulo = codigoCapitulo;
		this.descripcion = descripcion;
	}

	public CieCapitulo_ensayo(long id, String codigoCapitulo,
			String descripcion, String incluye, String excluye,
			String observaciones, Boolean eliminado, Long cid,
			Set<CieGrupo_ensayo> cieGrupos) {
		this.id = id;
		this.codigoCapitulo = codigoCapitulo;
		this.descripcion = descripcion;
		this.incluye = incluye;
		this.excluye = excluye;
		this.observaciones = observaciones;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cieGrupos = cieGrupos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "codigo_capitulo", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodigoCapitulo() {
		return this.codigoCapitulo;
	}

	public void setCodigoCapitulo(String codigoCapitulo) {
		if (codigoCapitulo != null)
			codigoCapitulo = codigoCapitulo.trim();
		this.codigoCapitulo = codigoCapitulo;
	}

	@Column(name = "descripcion", unique = true, nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "incluye")
	public String getIncluye() {
		return this.incluye;
	}

	public void setIncluye(String incluye) {
		if (incluye != null)
			incluye = incluye.trim();
		this.incluye = incluye;
	}

	@Column(name = "excluye")
	public String getExcluye() {
		return this.excluye;
	}

	public void setExcluye(String excluye) {
		if (excluye != null)
			excluye = excluye.trim();
		this.excluye = excluye;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		if (observaciones != null)
			observaciones = observaciones.trim();
		this.observaciones = observaciones;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cieCapitulo")
	public Set<CieGrupo_ensayo> getCieGrupos() {
		return this.cieGrupos;
	}

	public void setCieGrupos(Set<CieGrupo_ensayo> cieGrupos) {
		this.cieGrupos = cieGrupos;
	}

}
