package gehos.ensayo.entity;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CieEnfermedad generated by hbm2java
 */
@Entity
@Table(name = "cie_enfermedad", schema = "estandares", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_enfermedad"))
public class CieEnfermedad_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private CieSubcategoria_ensayo cieSubcategoria;
	private String codigoEnfermedad;
	private String descripcion;
	private Boolean eliminado;
	private Long cid;

	public CieEnfermedad_ensayo() {
	}

	public CieEnfermedad_ensayo(long id,
			CieSubcategoria_ensayo cieSubcategoria, String codigoEnfermedad,
			String descripcion) {
		this.id = id;
		this.cieSubcategoria = cieSubcategoria;
		this.codigoEnfermedad = codigoEnfermedad;
		this.descripcion = descripcion;
	}

	public CieEnfermedad_ensayo(long id,
			CieSubcategoria_ensayo cieSubcategoria, String codigoEnfermedad,
			String descripcion, Boolean eliminado, Long cid) {
		this.id = id;
		this.cieSubcategoria = cieSubcategoria;
		this.codigoEnfermedad = codigoEnfermedad;
		this.descripcion = descripcion;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_subcategoria", nullable = false)
	@NotNull
	public CieSubcategoria_ensayo getCieSubcategoria() {
		return this.cieSubcategoria;
	}

	public void setCieSubcategoria(CieSubcategoria_ensayo cieSubcategoria) {
		this.cieSubcategoria = cieSubcategoria;
	}

	@Column(name = "codigo_enfermedad", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodigoEnfermedad() {
		return this.codigoEnfermedad;
	}

	public void setCodigoEnfermedad(String codigoEnfermedad) {
		if (codigoEnfermedad != null)
			codigoEnfermedad = codigoEnfermedad.trim();
		this.codigoEnfermedad = codigoEnfermedad;
	}

	@Column(name = "descripcion", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
