package gehos.ensayo.entity;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CieGrupo generated by hbm2java
 */
@Entity
@Table(name = "cie_grupo", schema = "estandares", uniqueConstraints = {
		@UniqueConstraint(columnNames = "codigo_grupo"),
		@UniqueConstraint(columnNames = "descripcion") })
public class CieGrupo_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private CieCapitulo_ensayo cieCapitulo;
	private String codigoGrupo;
	private String descripcion;
	private String incluye;
	private String excluye;
	private String observaciones;
	private Boolean eliminado;
	private Long cid;
	private Set<CieCategoria_ensayo> cieCategorias = new HashSet<CieCategoria_ensayo>(
			0);

	public CieGrupo_ensayo() {
	}

	public CieGrupo_ensayo(long id, CieCapitulo_ensayo cieCapitulo,
			String codigoGrupo, String descripcion) {
		this.id = id;
		this.cieCapitulo = cieCapitulo;
		this.codigoGrupo = codigoGrupo;
		this.descripcion = descripcion;
	}

	public CieGrupo_ensayo(long id, CieCapitulo_ensayo cieCapitulo,
			String codigoGrupo, String descripcion, String incluye,
			String excluye, String observaciones, Boolean eliminado, Long cid,
			Set<CieCategoria_ensayo> cieCategorias) {
		this.id = id;
		this.cieCapitulo = cieCapitulo;
		this.codigoGrupo = codigoGrupo;
		this.descripcion = descripcion;
		this.incluye = incluye;
		this.excluye = excluye;
		this.observaciones = observaciones;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cieCategorias = cieCategorias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_capitulo", nullable = false)
	@NotNull
	public CieCapitulo_ensayo getCieCapitulo() {
		return this.cieCapitulo;
	}

	public void setCieCapitulo(CieCapitulo_ensayo cieCapitulo) {
		this.cieCapitulo = cieCapitulo;
	}

	@Column(name = "codigo_grupo", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodigoGrupo() {
		return this.codigoGrupo;
	}

	public void setCodigoGrupo(String codigoGrupo) {
		if (codigoGrupo != null)
			codigoGrupo = codigoGrupo.trim();
		this.codigoGrupo = codigoGrupo;
	}

	@Column(name = "descripcion", unique = true, nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "incluye")
	public String getIncluye() {
		return this.incluye;
	}

	public void setIncluye(String incluye) {
		if (incluye != null)
			incluye = incluye.trim();
		this.incluye = incluye;
	}

	@Column(name = "excluye")
	public String getExcluye() {
		return this.excluye;
	}

	public void setExcluye(String excluye) {
		if (excluye != null)
			excluye = excluye.trim();
		this.excluye = excluye;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		if (observaciones != null)
			observaciones = observaciones.trim();
		this.observaciones = observaciones;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cieGrupo")
	public Set<CieCategoria_ensayo> getCieCategorias() {
		return this.cieCategorias;
	}

	public void setCieCategorias(Set<CieCategoria_ensayo> cieCategorias) {
		this.cieCategorias = cieCategorias;
	}

}
