package gehos.ensayo.entity;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CieSubcategoria generated by hbm2java
 */
@Entity
@Table(name = "cie_subcategoria", schema = "estandares", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_subcategoria"))
public class CieSubcategoria_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private CieCategoria_ensayo cieCategoria;
	private String codigoSubcategoria;
	private String descripcion;
	private String incluye;
	private String excluye;
	private String observaciones;
	private Boolean eliminado;
	private Long cid;
	private Set<CieEnfermedad_ensayo> cieEnfermedads = new HashSet<CieEnfermedad_ensayo>(
			0);

	public CieSubcategoria_ensayo() {
	}

	public CieSubcategoria_ensayo(long id, CieCategoria_ensayo cieCategoria,
			String codigoSubcategoria, String descripcion) {
		this.id = id;
		this.cieCategoria = cieCategoria;
		this.codigoSubcategoria = codigoSubcategoria;
		this.descripcion = descripcion;
	}

	public CieSubcategoria_ensayo(long id, CieCategoria_ensayo cieCategoria,
			String codigoSubcategoria, String descripcion, String incluye,
			String excluye, String observaciones, Boolean eliminado, Long cid,
			Set<CieEnfermedad_ensayo> cieEnfermedads) {
		this.id = id;
		this.cieCategoria = cieCategoria;
		this.codigoSubcategoria = codigoSubcategoria;
		this.descripcion = descripcion;
		this.incluye = incluye;
		this.excluye = excluye;
		this.observaciones = observaciones;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cieEnfermedads = cieEnfermedads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria", nullable = false)
	@NotNull
	public CieCategoria_ensayo getCieCategoria() {
		return this.cieCategoria;
	}

	public void setCieCategoria(CieCategoria_ensayo cieCategoria) {
		this.cieCategoria = cieCategoria;
	}

	@Column(name = "codigo_subcategoria", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodigoSubcategoria() {
		return this.codigoSubcategoria;
	}

	public void setCodigoSubcategoria(String codigoSubcategoria) {
		if (codigoSubcategoria != null)
			codigoSubcategoria = codigoSubcategoria.trim();
		this.codigoSubcategoria = codigoSubcategoria;
	}

	@Column(name = "descripcion", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "incluye")
	public String getIncluye() {
		return this.incluye;
	}

	public void setIncluye(String incluye) {
		if (incluye != null)
			incluye = incluye.trim();
		this.incluye = incluye;
	}

	@Column(name = "excluye")
	public String getExcluye() {
		return this.excluye;
	}

	public void setExcluye(String excluye) {
		if (excluye != null)
			excluye = excluye.trim();
		this.excluye = excluye;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		if (observaciones != null)
			observaciones = observaciones.trim();
		this.observaciones = observaciones;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cieSubcategoria")
	public Set<CieEnfermedad_ensayo> getCieEnfermedads() {
		return this.cieEnfermedads;
	}

	public void setCieEnfermedads(Set<CieEnfermedad_ensayo> cieEnfermedads) {
		this.cieEnfermedads = cieEnfermedads;
	}

}
