package gehos.ensayo.entity;

// Generated 01-abr-2017 16:55:18 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConjuntoDatos generated by hbm2java
 */
@Entity
@Table(name = "conjunto_datos", schema = "ensayo")
public class ConjuntoDatos_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Long cid;
	private Boolean eliminado;
	private String nombre;
	private String descripcion;
	private String declaracionHql;
	private Date fechaInicio;
	private Date fechaFin;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Estudio_ensayo estudio;
	private Usuario_ensayo usuario;	
	private Boolean mostrarEstadoSujeto;
	private Boolean pesquisaje;
	private Boolean vertical;
	private Boolean mostrarFechaInclusionSujeto;
	private Boolean mostrarHoraInclusionSujeto;
	private Boolean mostrarInicialesSujeto;
	private Boolean mostrarNumeroInclusionSujeto;
	private Boolean mostrarSitioClinicaSujeto;
	private Boolean mostrarFechaInicioMs;
	private Boolean mostrarFechaFinMs;
	private Boolean mostrarEstadoMs;
	private Boolean mostrarNombreEntrevistadorCrdEspecifico;
	private Boolean mostrarFechaEntrevistaCrdEspecifico;
	private Boolean mostrarEstadoCrdEspecifico;
	private Boolean mostrarEstadoMonitoreoCrdEspecifico;
	private Entidad_ensayo entidad;

	public ConjuntoDatos_ensayo() {
	}

	public ConjuntoDatos_ensayo(Long id) {
		this.id = id;
	}

	public ConjuntoDatos_ensayo(Long id, Long cid, Boolean eliminado,
			String nombre, String descripcion, String declaracionHql,
			Date fechaInicio, Date fechaFin, Date fechaCreacion,
			Date fechaActualizacion, Estudio_ensayo estudio,
			Usuario_ensayo usuario, 
			Boolean mostrarEstadoSujeto, 		
			Boolean pesquisaje,
			Boolean vertical,
			Boolean mostrarFechaInclusionSujeto, 
			Boolean mostrarInicialesSujeto,
			Boolean mostrarNumeroInclusionSujeto,
			Boolean mostrarSitioClinicaSujeto,
			Boolean mostrarFechaInicioMs, Boolean mostrarFechaFinMs,
			Boolean mostrarEstadoMs,
			Boolean mostrarNombreEntrevistadorCrdEspecifico,
			Boolean mostrarFechaEntrevistaCrdEspecifico,
			Boolean mostrarEstadoCrdEspecifico,
			Boolean mostrarEstadoMonitoreoCrdEspecifico, Entidad_ensayo entidad) {
		this.id = id;
		this.cid = cid;
		this.eliminado = eliminado;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.declaracionHql = declaracionHql;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.estudio = estudio;
		this.usuario = usuario;		
		this.mostrarEstadoSujeto = mostrarEstadoSujeto;
		this.pesquisaje = pesquisaje;
		this.vertical = vertical!=null?vertical:false;
		this.mostrarFechaInclusionSujeto = mostrarFechaInclusionSujeto;
		this.mostrarInicialesSujeto = mostrarInicialesSujeto;
		this.mostrarNumeroInclusionSujeto = mostrarNumeroInclusionSujeto;
		this.mostrarSitioClinicaSujeto = mostrarSitioClinicaSujeto;
		this.mostrarFechaInicioMs = mostrarFechaInicioMs;
		this.mostrarFechaFinMs = mostrarFechaFinMs;
		this.mostrarEstadoMs = mostrarEstadoMs;
		this.mostrarNombreEntrevistadorCrdEspecifico = mostrarNombreEntrevistadorCrdEspecifico;
		this.mostrarFechaEntrevistaCrdEspecifico = mostrarFechaEntrevistaCrdEspecifico;
		this.mostrarEstadoCrdEspecifico = mostrarEstadoCrdEspecifico;
		this.mostrarEstadoMonitoreoCrdEspecifico = mostrarEstadoMonitoreoCrdEspecifico;
		this.entidad = entidad;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_ensayo getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_ensayo entidad) {
		this.entidad = entidad;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "nombre", length = 500)
	@Length(max = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "declaracion_hql", length = 1000000)
	@Length(max = 1000000)
	public String getDeclaracionHql() {
		return this.declaracionHql;
	}

	public void setDeclaracionHql(String declaracionHql) {
		if (declaracionHql != null)
			declaracionHql = declaracionHql.trim();
		this.declaracionHql = declaracionHql;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudio")
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@Column(name = "mostrar_estado_sujeto")
	public Boolean getMostrarEstadoSujeto() {
		return this.mostrarEstadoSujeto;
	}

	public void setMostrarEstadoSujeto(Boolean mostrarEstadoSujeto) {
		this.mostrarEstadoSujeto = mostrarEstadoSujeto;
	}

	@Column(name = "mostrar_fecha_inclusion_sujeto")
	public Boolean getMostrarFechaInclusionSujeto() {
		return this.mostrarFechaInclusionSujeto;
	}

	public void setMostrarFechaInclusionSujeto(
			Boolean mostrarFechaInclusionSujeto) {
		this.mostrarFechaInclusionSujeto = mostrarFechaInclusionSujeto;
	}
	
	@Column(name = "mostrar_hora_inclusion_sujeto")
	public Boolean getMostrarHoraInclusionSujeto() {
		return mostrarHoraInclusionSujeto;
	}

	public void setMostrarHoraInclusionSujeto(Boolean mostrarHoraInclusionSujeto) {
		this.mostrarHoraInclusionSujeto = mostrarHoraInclusionSujeto;
	}

	@Column(name = "mostrar_iniciales_sujeto")
	public Boolean getMostrarInicialesSujeto() {
		return this.mostrarInicialesSujeto;
	}

	public void setMostrarInicialesSujeto(Boolean mostrarInicialesSujeto) {
		this.mostrarInicialesSujeto = mostrarInicialesSujeto;
	}
	
	@Column(name = "mostrar_numero_inclusion_sujeto")
	public Boolean getMostrarNumeroInclusionSujeto() {
		return this.mostrarNumeroInclusionSujeto;
	}

	public void setMostrarNumeroInclusionSujeto(Boolean mostrarNumeroInclusionSujeto) {
		this.mostrarNumeroInclusionSujeto = mostrarNumeroInclusionSujeto;
	}
	
	@Column(name = "mostrar_sitio_clinica_sujeto")
	public Boolean getMostrarSitioClinicaSujeto() {
		return this.mostrarSitioClinicaSujeto;
	}

	public void setMostrarSitioClinicaSujeto(Boolean mostrarSitioClinicaSujeto) {
		this.mostrarSitioClinicaSujeto = mostrarSitioClinicaSujeto;
	}

	@Column(name = "mostrar_fecha_inicio_ms")
	public Boolean getMostrarFechaInicioMs() {
		return this.mostrarFechaInicioMs;
	}

	public void setMostrarFechaInicioMs(Boolean mostrarFechaInicioMs) {
		this.mostrarFechaInicioMs = mostrarFechaInicioMs;
	}

	@Column(name = "mostrar_fecha_fin_ms")
	public Boolean getMostrarFechaFinMs() {
		return this.mostrarFechaFinMs;
	}

	public void setMostrarFechaFinMs(Boolean mostrarFechaFinMs) {
		this.mostrarFechaFinMs = mostrarFechaFinMs;
	}
	
	@Column(name = "pesquisaje")
	public Boolean getPesquisaje() {
		return this.pesquisaje;
	}

	public void setPesquisaje(Boolean pesquisaje) {
		this.pesquisaje = pesquisaje;
	}
	
	@Column(name = "vertical")
	public Boolean getVertical() {
		return this.vertical;
	}

	public void setVertical(Boolean vertical) {
		this.vertical = vertical!=null?vertical:false;
	}

	

	@Column(name = "mostrar_estado_ms")
	public Boolean getMostrarEstadoMs() {
		return this.mostrarEstadoMs;
	}

	public void setMostrarEstadoMs(Boolean mostrarEstadoMs) {
		this.mostrarEstadoMs = mostrarEstadoMs;
	}

	@Column(name = "mostrar_nombre_entrevistador_crd_especifico")
	public Boolean getMostrarNombreEntrevistadorCrdEspecifico() {
		return this.mostrarNombreEntrevistadorCrdEspecifico;
	}

	public void setMostrarNombreEntrevistadorCrdEspecifico(
			Boolean mostrarNombreEntrevistadorCrdEspecifico) {
		this.mostrarNombreEntrevistadorCrdEspecifico = mostrarNombreEntrevistadorCrdEspecifico;
	}

	@Column(name = "mostrar_fecha_entrevista_crd_especifico")
	public Boolean getMostrarFechaEntrevistaCrdEspecifico() {
		return this.mostrarFechaEntrevistaCrdEspecifico;
	}

	public void setMostrarFechaEntrevistaCrdEspecifico(
			Boolean mostrarFechaEntrevistaCrdEspecifico) {
		this.mostrarFechaEntrevistaCrdEspecifico = mostrarFechaEntrevistaCrdEspecifico;
	}

	@Column(name = "mostrar_estado_crd_especifico")
	public Boolean getMostrarEstadoCrdEspecifico() {
		return this.mostrarEstadoCrdEspecifico;
	}

	public void setMostrarEstadoCrdEspecifico(Boolean mostrarEstadoCrdEspecifico) {
		this.mostrarEstadoCrdEspecifico = mostrarEstadoCrdEspecifico;
	}
	
	@Column(name = "mostrar_estado_monitoreo_crd_especifico")
	public Boolean getMostrarEstadoMonitoreoCrdEspecifico() {
		return this.mostrarEstadoMonitoreoCrdEspecifico;
	}

	public void setMostrarEstadoMonitoreoCrdEspecifico(Boolean mostrarEstadoMonitoreoCrdEspecifico) {
		this.mostrarEstadoMonitoreoCrdEspecifico = mostrarEstadoMonitoreoCrdEspecifico;
	}

}
