package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.NotNull;

/**
 * CrdEspecifico generated by hbm2java
 */
@Entity
@Table(name = "crd_especifico", schema = "ensayo")
public class CrdEspecifico_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private MomentoSeguimientoEspecifico_ensayo momentoSeguimientoEspecifico;
	private HojaCrd_ensayo hojaCrd;
	private Usuario_ensayo usuario;
	private EstadoMonitoreo_ensayo estadoMonitoreo;
	private EstadoHojaCrd_ensayo estadoHojaCrd;
	private Long cid;
	private Boolean eliminado;
	private Set<VariableDato_ensayo> variableDatos = new HashSet<VariableDato_ensayo>(
			0);
	private Set<Nota_ensayo> notas = new HashSet<Nota_ensayo>(0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);
	private Set<Causa_ensayo> causas = new HashSet<Causa_ensayo>(
			0);

	public CrdEspecifico_ensayo() {
	}

	public CrdEspecifico_ensayo(long id) {
		this.id = id;
	}

	public CrdEspecifico_ensayo(long id,
			MomentoSeguimientoEspecifico_ensayo momentoSeguimientoEspecifico,
			HojaCrd_ensayo hojaCrd, Usuario_ensayo usuario,
			EstadoMonitoreo_ensayo estadoMonitoreo,
			EstadoHojaCrd_ensayo estadoHojaCrd, Long cid, Boolean eliminado,
			Set<VariableDato_ensayo> variableDatos, Set<Nota_ensayo> notas,
			Set<CrdEspecifico_ensayo> crdEspecificos,
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria,
			Set<Causa_ensayo> causas) {
		this.id = id;
		this.momentoSeguimientoEspecifico = momentoSeguimientoEspecifico;
		this.hojaCrd = hojaCrd;
		this.estadoMonitoreo = estadoMonitoreo;
		this.estadoHojaCrd = estadoHojaCrd;
		this.cid = cid;
		this.eliminado = eliminado;
		this.variableDatos = variableDatos;
		this.notas = notas;
		this.usuario = usuario;
		this.logEventosAuditoria = logEventosAuditoria;
		this.causas = causas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crdEspecifico")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_momento_seg_especifico")
	public MomentoSeguimientoEspecifico_ensayo getMomentoSeguimientoEspecifico() {
		return this.momentoSeguimientoEspecifico;
	}

	public void setMomentoSeguimientoEspecifico(
			MomentoSeguimientoEspecifico_ensayo momentoSeguimientoEspecifico) {
		this.momentoSeguimientoEspecifico = momentoSeguimientoEspecifico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hoja_crd")
	public HojaCrd_ensayo getHojaCrd() {
		return this.hojaCrd;
	}

	public void setHojaCrd(HojaCrd_ensayo hojaCrd) {
		this.hojaCrd = hojaCrd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_monitoreo")
	public EstadoMonitoreo_ensayo getEstadoMonitoreo() {
		return this.estadoMonitoreo;
	}

	public void setEstadoMonitoreo(EstadoMonitoreo_ensayo estadoMonitoreo) {
		this.estadoMonitoreo = estadoMonitoreo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_hoja_crd")
	public EstadoHojaCrd_ensayo getEstadoHojaCrd() {
		return this.estadoHojaCrd;
	}

	public void setEstadoHojaCrd(EstadoHojaCrd_ensayo estadoHojaCrd) {
		this.estadoHojaCrd = estadoHojaCrd;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crdEspecifico")
	public Set<VariableDato_ensayo> getVariableDatos() {
		return this.variableDatos;
	}

	public void setVariableDatos(Set<VariableDato_ensayo> variableDatos) {
		this.variableDatos = variableDatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crdEspecifico")
	public Set<Nota_ensayo> getNotas() {
		return this.notas;
	}

	public void setNotas(Set<Nota_ensayo> notas) {
		this.notas = notas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crdEspecifico")
	public Set<Causa_ensayo> getCausas() {
		return this.causas;
	}

	public void setCausas(Set<Causa_ensayo> causas) {
		this.causas = causas;
	}

}
