package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cronograma generated by hbm2java
 */
@Entity
@Table(name = "cronograma", schema = "ensayo")
public class Cronograma_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private EstadoCronograma_ensayo estadoCronograma;
	private EstadoRegla_ensayo estadoReglas;
	private GrupoSujetos_ensayo grupoSujetos;
	private Usuario_ensayo usuario;
	private Integer tiempoDuracion;
	private String descripcion;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Long cid;
	private Boolean eliminado;
	private Set<Etapa_ensayo> etapas = new HashSet<Etapa_ensayo>(0);
	private Set<MomentoSeguimientoGeneral_ensayo> momentoSeguimientoGenerals = new HashSet<MomentoSeguimientoGeneral_ensayo>(
			0);
	private Set<Causa_ensayo> causas = new HashSet<Causa_ensayo>(0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);

	public Cronograma_ensayo() {
	}

	public Cronograma_ensayo(long id, GrupoSujetos_ensayo grupoSujetos) {
		this.id = id;
		this.grupoSujetos = grupoSujetos;
	}

	public Cronograma_ensayo(long id, EstadoCronograma_ensayo estadoCronograma,
			GrupoSujetos_ensayo grupoSujetos, Integer tiempoDuracion,
			String descripcion, Usuario_ensayo usuario, Date fechaCreacion,
			EstadoRegla_ensayo estadoReglas, Date fechaActualizacion, Long cid,
			Boolean eliminado, Set<Etapa_ensayo> etapas,
			Set<MomentoSeguimientoGeneral_ensayo> momentoSeguimientoGenerals,
			Set<Causa_ensayo> causas) {
		this.id = id;
		this.estadoCronograma = estadoCronograma;
		this.grupoSujetos = grupoSujetos;
		this.tiempoDuracion = tiempoDuracion;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.cid = cid;
		this.usuario = usuario;
		this.estadoReglas = estadoReglas;
		this.eliminado = eliminado;
		this.etapas = etapas;
		this.momentoSeguimientoGenerals = momentoSeguimientoGenerals;
		this.causas = causas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_estadoReglas_cronograma")
	public EstadoRegla_ensayo getEstadoReglas() {
		return this.estadoReglas;
	}

	public void setEstadoReglas(EstadoRegla_ensayo estadoReglas) {
		this.estadoReglas = estadoReglas;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_estado_cronograma")
	public EstadoCronograma_ensayo getEstadoCronograma() {
		return this.estadoCronograma;
	}

	public void setEstadoCronograma(EstadoCronograma_ensayo estadoCronograma) {
		this.estadoCronograma = estadoCronograma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_sujetos", nullable = false)
	@NotNull
	public GrupoSujetos_ensayo getGrupoSujetos() {
		return this.grupoSujetos;
	}

	public void setGrupoSujetos(GrupoSujetos_ensayo grupoSujetos) {
		this.grupoSujetos = grupoSujetos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@Column(name = "tiempo_duracion")
	public Integer getTiempoDuracion() {
		return this.tiempoDuracion;
	}

	public void setTiempoDuracion(Integer tiempoDuracion) {
		this.tiempoDuracion = tiempoDuracion;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cronograma")
	public Set<Etapa_ensayo> getEtapas() {
		return this.etapas;
	}

	public void setEtapas(Set<Etapa_ensayo> etapas) {
		this.etapas = etapas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cronograma")
	public Set<MomentoSeguimientoGeneral_ensayo> getMomentoSeguimientoGenerals() {
		return this.momentoSeguimientoGenerals;
	}

	public void setMomentoSeguimientoGenerals(
			Set<MomentoSeguimientoGeneral_ensayo> momentoSeguimientoGenerals) {
		this.momentoSeguimientoGenerals = momentoSeguimientoGenerals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cronograma")
	public Set<Causa_ensayo> getCausas() {
		return this.causas;
	}

	public void setCausas(Set<Causa_ensayo> causas) {
		this.causas = causas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cronograma")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}
}