package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.validator.NotNull;

/**
 * Ctc generated by hbm2java
 */
@Entity
@Table(name = "ctc", schema = "ensayo", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_medra"))
public class Ctc_ensayo implements java.io.Serializable {

	private long id;
	private int codigoMedra;
	private String eventoAdverso;
	private CtcCategoria_ensayo ctcCategoria;
	private String descripcion;
	private Long cid;
	
	private Set<Relacion_cat_metra_ensayo> cat_codMetra_ensayo = new HashSet<Relacion_cat_metra_ensayo>(0);

	public Ctc_ensayo() {
	}

	public Ctc_ensayo(long id, int codigoMedra) {
		this.id = id;
		this.codigoMedra = codigoMedra;
	}

	public Ctc_ensayo(long id, CtcCategoria_ensayo ctcCategoria,
			int codigoMedra, String eventoAdverso, Long cid, String descripcion) {
		this.id = id;
		this.codigoMedra = codigoMedra;
		this.eventoAdverso = eventoAdverso;
		this.descripcion = descripcion;
		this.cid = cid;
		this.ctcCategoria = ctcCategoria;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "codigo_medra", unique = true, nullable = false)
	@NotNull
	public int getCodigoMedra() {
		return this.codigoMedra;
	}

	public void setCodigoMedra(int codigoMedra) {
		this.codigoMedra = codigoMedra;
	}

	@Column(name = "evento_adverso")
	public String getEventoAdverso() {
		return this.eventoAdverso;
	}

	public void setEventoAdverso(String eventoAdverso) {
		if (eventoAdverso != null)
			eventoAdverso = eventoAdverso.trim();
		this.eventoAdverso = eventoAdverso;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ctc")
	public Set<Relacion_cat_metra_ensayo> getCat_codMetra_ensayo() {
		return this.cat_codMetra_ensayo;
	}

	public void setCat_codMetra_ensayo(Set<Relacion_cat_metra_ensayo> cat_codMetra_ensayo) {
		this.cat_codMetra_ensayo = cat_codMetra_ensayo;
	}
	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria")
	public CtcCategoria_ensayo getCtcCategoria() {
		return ctcCategoria;
	}

	public void setCtcCategoria(CtcCategoria_ensayo ctcCategoria) {
		this.ctcCategoria = ctcCategoria;
	}
	
	
}
