package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * DireccionIp generated by hbm2java
 */
@Entity
@Table(name = "direccion_ip", schema = "ensayo")
public class DireccionIp_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Entidad_ensayo entidad;
	private String ip;
	private Boolean eliminado;
	private String ipFinal;
	private Long cid;

	public DireccionIp_ensayo() {
	}

	public DireccionIp_ensayo(long id) {
		this.id = id;
	}

	public DireccionIp_ensayo(long id, Entidad_ensayo entidad, String ip,
			Boolean eliminado, String ipFinal, Long cid) {
		this.id = id;
		this.entidad = entidad;
		this.ip = ip;
		this.eliminado = eliminado;
		this.ipFinal = ipFinal;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entidad_ensayo")
	public Entidad_ensayo getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_ensayo entidad) {
		this.entidad = entidad;
	}

	@Column(name = "ip")
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		if (ip != null)
			ip = ip.trim();
		this.ip = ip;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "ip_final")
	public String getIpFinal() {
		return this.ipFinal;
	}

	public void setIpFinal(String ipFinal) {
		if (ipFinal != null)
			ipFinal = ipFinal.trim();
		this.ipFinal = ipFinal;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
