package gehos.ensayo.entity;

// Generated 07-jun-2017 13:48:11 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EEnfermedadCie generated by hbm2java
 */
@Entity
@Table(name = "e_enfermedad_cie", schema = "ensayo")
public class EEnfermedadCie_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Estudio_ensayo estudio;
	private String codigoEnfermedad;
	private String descripcionEnfermedad;
	private Boolean eliminado;
	private Long cid;

	public EEnfermedadCie_ensayo() {
	}

	public EEnfermedadCie_ensayo(long id, String codigoEnfermedad,
			String descripcionEnfermedad) {
		this.id = id;
		this.codigoEnfermedad = codigoEnfermedad;
		this.descripcionEnfermedad = descripcionEnfermedad;
	}

	public EEnfermedadCie_ensayo(long id, Estudio_ensayo estudio,
			String codigoEnfermedad, String descripcionEnfermedad,
			Boolean eliminado, Long cid) {
		this.id = id;
		this.estudio = estudio;
		this.codigoEnfermedad = codigoEnfermedad;
		this.descripcionEnfermedad = descripcionEnfermedad;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudio", nullable = false)
	@NotNull
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@Column(name = "codigo_enfermedad", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodigoEnfermedad() {
		return this.codigoEnfermedad;
	}

	public void setCodigoEnfermedad(String codigoEnfermedad) {
		if (codigoEnfermedad != null)
			codigoEnfermedad = codigoEnfermedad.trim();
		this.codigoEnfermedad = codigoEnfermedad;
	}

	@Column(name = "descripcion_enfermedad", nullable = false)
	@NotNull
	public String getDescripcionEnfermedad() {
		return this.descripcionEnfermedad;
	}

	public void setDescripcionEnfermedad(String descripcionEnfermedad) {
		if (descripcionEnfermedad != null)
			descripcionEnfermedad = descripcionEnfermedad.trim();
		this.descripcionEnfermedad = descripcionEnfermedad;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
