package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EIntervencion generated by hbm2java
 */
@Entity
@Table(name = "e_intervencion", schema = "ensayo")
public class EIntervencion_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Estudio_ensayo estudio;
	private ETipoIntervencion_ensayo ETipoIntervencion;
	private String nombre;
	private String descripcion;
	private Boolean eliminado;
	private Long cid;
	private Long codigo;

	public EIntervencion_ensayo() {
	}

	public EIntervencion_ensayo(long id, Estudio_ensayo estudio) {
		this.id = id;
		this.estudio = estudio;
	}

	public EIntervencion_ensayo(long id, Estudio_ensayo estudio,
			ETipoIntervencion_ensayo ETipoIntervencion, String nombre,
			String descripcion, Boolean eliminado, Long cid, Long codigo) {
		this.id = id;
		this.estudio = estudio;
		this.ETipoIntervencion = ETipoIntervencion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estudio_id", nullable = false)
	@NotNull
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_intervencion_id")
	public ETipoIntervencion_ensayo getETipoIntervencion() {
		return this.ETipoIntervencion;
	}

	public void setETipoIntervencion(ETipoIntervencion_ensayo ETipoIntervencion) {
		this.ETipoIntervencion = ETipoIntervencion;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	@Length(max = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

}
