package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import gehos.configuracion.management.entity.Organismo_configuracion;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name = "entidad", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Entidad_ensayo implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Estado_ensayo estado;
	private Municipio_ensayo municipio;
	private TipoEntidad_ensayo tipoEntidad;
	private String nombre;
	private String direccion;
	private String telefonos;
	private String fax;
	private String correo;
	private Date fechaApertura;
	private Long idLocalidad;
	private Integer camasArquitectonicas;
	private Integer camasPresupuestadas;
	private boolean esPublico;
	private Boolean eliminado;
	private Long cid;
	private String logo;
	private boolean perteneceARhio;
	private Long idCategoriaEntidad;
	private String idInstanciaHis;
	private Integer camasFuncionales;
	private Integer cantidadMedicos;
	private Integer cantidadEnfermeros;
	private Integer cantidadTrabajadores;
	private Long idRis;
	private String rif;
	private Long idAnilloHis;
	private String codigoReeup;
	private Organismo_configuracion organismo;
	private String siglas;
	private String observaciones;
	private Set<EstudioEntidad_ensayo> estudioEntidads = new HashSet<EstudioEntidad_ensayo>(
			0);
	private Set<Sujeto_ensayo> sujetos = new HashSet<Sujeto_ensayo>(0);
	private Set<DireccionIp_ensayo> direccionIps = new HashSet<DireccionIp_ensayo>(
			0);
	private Set<NotaGeneral_ensayo> notaGenerals = new HashSet<NotaGeneral_ensayo>(
			0);
	private Set<Estudio_ensayo> estudios = new HashSet<Estudio_ensayo>(0);
	private Set<ConjuntoDatos_ensayo> conjuntoDatoses = new HashSet<ConjuntoDatos_ensayo>(
			0);

	public Entidad_ensayo() {
	}

	public Entidad_ensayo(long id, Estado_ensayo estado,
			Municipio_ensayo municipio, TipoEntidad_ensayo tipoEntidad,
			boolean esPublico, boolean perteneceARhio) {
		this.id = id;
		this.estado = estado;
		this.municipio = municipio;
		this.tipoEntidad = tipoEntidad;
		this.esPublico = esPublico;
		this.perteneceARhio = perteneceARhio;
	}

	public Entidad_ensayo(long id, Estado_ensayo estado,
			Municipio_ensayo municipio, TipoEntidad_ensayo tipoEntidad,
			String nombre, String direccion, String telefonos, String fax,
			String correo, Date fechaApertura, Long idLocalidad,
			Integer camasArquitectonicas, Integer camasPresupuestadas,
			boolean esPublico, Boolean eliminado, Long cid, String logo,
			boolean perteneceARhio, Long idCategoriaEntidad,
			String idInstanciaHis, Integer camasFuncionales,
			Integer cantidadMedicos, Integer cantidadEnfermeros,
			Integer cantidadTrabajadores, Long idRis,
			String rif, Long idAnilloHis,
			Set<EstudioEntidad_ensayo> estudioEntidads,
			Set<Sujeto_ensayo> sujetos, Set<DireccionIp_ensayo> direccionIps,
			Set<NotaGeneral_ensayo> notaGenerals, Set<Estudio_ensayo> estudios,
			Set<ConjuntoDatos_ensayo> conjuntoDatoses) {
		this.id = id;
		this.estado = estado;
		this.municipio = municipio;
		this.tipoEntidad = tipoEntidad;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefonos = telefonos;
		this.fax = fax;
		this.correo = correo;
		this.fechaApertura = fechaApertura;
		this.idLocalidad = idLocalidad;
		this.camasArquitectonicas = camasArquitectonicas;
		this.camasPresupuestadas = camasPresupuestadas;
		this.esPublico = esPublico;
		this.eliminado = eliminado;
		this.cid = cid;
		this.logo = logo;
		this.perteneceARhio = perteneceARhio;
		this.idCategoriaEntidad = idCategoriaEntidad;
		this.idInstanciaHis = idInstanciaHis;
		this.camasFuncionales = camasFuncionales;
		this.cantidadMedicos = cantidadMedicos;
		this.cantidadEnfermeros = cantidadEnfermeros;
		this.cantidadTrabajadores = cantidadTrabajadores;
		this.idRis = idRis;
		this.rif = rif;
		this.idAnilloHis = idAnilloHis;
		this.estudioEntidads = estudioEntidads;
		this.sujetos = sujetos;
		this.direccionIps = direccionIps;
		this.notaGenerals = notaGenerals;
		this.estudios = estudios;
		this.conjuntoDatoses = conjuntoDatoses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	@NotNull
	public Estado_ensayo getEstado() {
		return this.estado;
	}

	public void setEstado(Estado_ensayo estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio", nullable = false)
	@NotNull
	public Municipio_ensayo getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio_ensayo municipio) {
		this.municipio = municipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_hospital", nullable = false)
	@NotNull
	public TipoEntidad_ensayo getTipoEntidad() {
		return this.tipoEntidad;
	}

	public void setTipoEntidad(TipoEntidad_ensayo tipoEntidad) {
		this.tipoEntidad = tipoEntidad;
	}

	@Column(name = "nombre", unique = true)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "direccion", length = 50)
	@Length(max = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		if (direccion != null)
			direccion = direccion.trim();
		this.direccion = direccion;
	}

	@Column(name = "telefonos", length = 15)
	@Length(max = 15)
	public String getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(String telefonos) {
		if (telefonos != null)
			telefonos = telefonos.trim();
		this.telefonos = telefonos;
	}

	@Column(name = "fax", length = 15)
	@Length(max = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		if (fax != null)
			fax = fax.trim();
		this.fax = fax;
	}

	@Column(name = "correo", length = 100)
	@Length(max = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		if (correo != null)
			correo = correo.trim();
		this.correo = correo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_apertura", length = 13)
	public Date getFechaApertura() {
		return this.fechaApertura;
	}

	public void setFechaApertura(Date fechaApertura) {
		this.fechaApertura = fechaApertura;
	}

	@Column(name = "id_localidad")
	public Long getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(Long idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@Column(name = "camas_arquitectonicas")
	public Integer getCamasArquitectonicas() {
		return this.camasArquitectonicas;
	}

	public void setCamasArquitectonicas(Integer camasArquitectonicas) {
		this.camasArquitectonicas = camasArquitectonicas;
	}

	@Column(name = "camas_presupuestadas")
	public Integer getCamasPresupuestadas() {
		return this.camasPresupuestadas;
	}

	public void setCamasPresupuestadas(Integer camasPresupuestadas) {
		this.camasPresupuestadas = camasPresupuestadas;
	}

	@Column(name = "es_publico", nullable = false)
	@NotNull
	public boolean isEsPublico() {
		return this.esPublico;
	}

	public void setEsPublico(boolean esPublico) {
		this.esPublico = esPublico;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "logo", length = 30)
	@Length(max = 30)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		if (logo != null)
			logo = logo.trim();
		this.logo = logo;
	}

	@Column(name = "pertenece_a_rhio", nullable = false)
	@NotNull
	public boolean isPerteneceARhio() {
		return this.perteneceARhio;
	}

	public void setPerteneceARhio(boolean perteneceARhio) {
		this.perteneceARhio = perteneceARhio;
	}

	@Column(name = "id_categoria_entidad")
	public Long getIdCategoriaEntidad() {
		return this.idCategoriaEntidad;
	}

	public void setIdCategoriaEntidad(Long idCategoriaEntidad) {
		this.idCategoriaEntidad = idCategoriaEntidad;
	}

	@Column(name = "id_instancia_his")
	public String getIdInstanciaHis() {
		return this.idInstanciaHis;
	}

	public void setIdInstanciaHis(String idInstanciaHis) {
		if (idInstanciaHis != null)
			idInstanciaHis = idInstanciaHis.trim();
		this.idInstanciaHis = idInstanciaHis;
	}

	@Column(name = "camas_funcionales")
	public Integer getCamasFuncionales() {
		return this.camasFuncionales;
	}

	public void setCamasFuncionales(Integer camasFuncionales) {
		this.camasFuncionales = camasFuncionales;
	}

	@Column(name = "cantidad_medicos")
	public Integer getCantidadMedicos() {
		return this.cantidadMedicos;
	}

	public void setCantidadMedicos(Integer cantidadMedicos) {
		this.cantidadMedicos = cantidadMedicos;
	}

	@Column(name = "cantidad_enfermeros")
	public Integer getCantidadEnfermeros() {
		return this.cantidadEnfermeros;
	}

	public void setCantidadEnfermeros(Integer cantidadEnfermeros) {
		this.cantidadEnfermeros = cantidadEnfermeros;
	}

	@Column(name = "cantidad_trabajadores")
	public Integer getCantidadTrabajadores() {
		return this.cantidadTrabajadores;
	}

	public void setCantidadTrabajadores(Integer cantidadTrabajadores) {
		this.cantidadTrabajadores = cantidadTrabajadores;
	}

	@Column(name = "id_ris")
	public Long getIdRis() {
		return this.idRis;
	}

	public void setIdRis(Long idRis) {
		this.idRis = idRis;
	}

	@Column(name = "rif", length = 20)
	@Length(max = 20)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		if (rif != null)
			rif = rif.trim();
		this.rif = rif;
	}

	@Column(name = "id_anillo_his")
	public Long getIdAnilloHis() {
		return this.idAnilloHis;
	}

	public void setIdAnilloHis(Long idAnilloHis) {
		this.idAnilloHis = idAnilloHis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<EstudioEntidad_ensayo> getEstudioEntidads() {
		return this.estudioEntidads;
	}

	public void setEstudioEntidads(Set<EstudioEntidad_ensayo> estudioEntidads) {
		this.estudioEntidads = estudioEntidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<Sujeto_ensayo> getSujetos() {
		return this.sujetos;
	}

	public void setSujetos(Set<Sujeto_ensayo> sujetos) {
		this.sujetos = sujetos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<DireccionIp_ensayo> getDireccionIps() {
		return this.direccionIps;
	}

	public void setDireccionIps(Set<DireccionIp_ensayo> direccionIps) {
		this.direccionIps = direccionIps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<NotaGeneral_ensayo> getNotaGenerals() {
		return this.notaGenerals;
	}

	public void setNotaGenerals(Set<NotaGeneral_ensayo> notaGenerals) {
		this.notaGenerals = notaGenerals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<Estudio_ensayo> getEstudios() {
		return this.estudios;
	}

	public void setEstudios(Set<Estudio_ensayo> estudios) {
		this.estudios = estudios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidad")
	public Set<ConjuntoDatos_ensayo> getConjuntoDatoses() {
		return this.conjuntoDatoses;
	}

	public void setConjuntoDatoses(Set<ConjuntoDatos_ensayo> conjuntoDatoses) {
		this.conjuntoDatoses = conjuntoDatoses;
	}
	
	@Column(name = "codigo_reeup")
	public String getCodigoReeup(){
		return this.codigoReeup;
	}

	public void setCodigoReeup(String codigoReeup){
		this.codigoReeup = codigoReeup;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_organismo")
	public Organismo_configuracion getOrganismo(){
		return this.organismo;
	}

	public void setOrganismo(Organismo_configuracion organismo){
		this.organismo = organismo;
	}
	
	@Column(name = "siglas")
	public String getSiglas(){
		return this.siglas;
	}

	public void setSiglas(String siglas){
		this.siglas = siglas;
	}
	
	@Column(name = "observaciones")
	public String getObservaciones(){
		return this.observaciones;
	}

	public void setObservaciones(String observaciones){
		this.observaciones = observaciones;
	}
}
