package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ESexo generated by hbm2java
 */
@Entity
@Table(name = "e_sexo", schema = "ensayo")
public class ESexo_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String valor;
	private String abreviatura;
	private Boolean eliminado;
	private Long cid;
	private Long codigo;
	private Set<Estudio_ensayo> estudios = new HashSet<Estudio_ensayo>(0);

	public ESexo_ensayo() {
	}

	public ESexo_ensayo(long id, String valor, String abreviatura) {
		this.id = id;
		this.valor = valor;
		this.abreviatura = abreviatura;
	}

	public ESexo_ensayo(long id, String valor, String abreviatura,
			Boolean eliminado, Long cid, Long codigo,
			Set<Estudio_ensayo> estudios) {
		this.id = id;
		this.valor = valor;
		this.abreviatura = abreviatura;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.estudios = estudios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "abreviatura", nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		if (abreviatura != null)
			abreviatura = abreviatura.trim();
		this.abreviatura = abreviatura;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ESexo")
	public Set<Estudio_ensayo> getEstudios() {
		return this.estudios;
	}

	public void setEstudios(Set<Estudio_ensayo> estudios) {
		this.estudios = estudios;
	}

}
