package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstadoEstudio generated by hbm2java
 */
@Entity
@Table(name = "estado_estudio", schema = "ensayo")
public class EstadoEstudio_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String nombre;
	private String descripcion;
	private Long cid;
	private Long codigo;
	private Set<Estudio_ensayo> estudios = new HashSet<Estudio_ensayo>(0);

	public EstadoEstudio_ensayo() {
	}

	public EstadoEstudio_ensayo(long id) {
		this.id = id;
	}

	public EstadoEstudio_ensayo(long id, String nombre, String descripcion,
			Long cid, Long codigo, Set<Estudio_ensayo> estudios) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.cid = cid;
		this.codigo = codigo;
		this.estudios = estudios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoEstudio")
	public Set<Estudio_ensayo> getEstudios() {
		return this.estudios;
	}

	public void setEstudios(Set<Estudio_ensayo> estudios) {
		this.estudios = estudios;
	}

}
