package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * EstadoMomentoSeguimiento generated by hbm2java
 */
@Entity
@Table(name = "estado_momento_seguimiento", schema = "ensayo")
public class EstadoMomentoSeguimiento_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String nombre;
	private Long cid;
	private String descripcion;
	private Long codigo;
	private Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos = new HashSet<MomentoSeguimientoEspecifico_ensayo>(
			0);

	public EstadoMomentoSeguimiento_ensayo() {
	}

	public EstadoMomentoSeguimiento_ensayo(long id) {
		this.id = id;
	}

	public EstadoMomentoSeguimiento_ensayo(
			long id,
			String nombre,
			Long cid,
			String descripcion,
			Long codigo,
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos) {
		this.id = id;
		this.nombre = nombre;
		this.cid = cid;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "codigo")
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoMomentoSeguimiento")
	public Set<MomentoSeguimientoEspecifico_ensayo> getMomentoSeguimientoEspecificos() {
		return this.momentoSeguimientoEspecificos;
	}

	public void setMomentoSeguimientoEspecificos(
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos) {
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
	}

}
