package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Estudio generated by hbm2java
 */
@Entity
@Table(name = "estudio", schema = "ensayo")
public class Estudio_ensayo implements java.io.Serializable {

	private long id;
	private EAsignacion_ensayo EAsignacion;
	private EEnmascaramiento_ensayo EEnmascaramiento;
	private EFaseEstudio_ensayo EFaseEstudio;
	private Entidad_ensayo entidad;
	private EControl_ensayo EControl;
	private ESeleccion_ensayo ESeleccion;
	private EAjusteTemporal_ensayo EAjusteTemporal;
	private EstadoEstudio_ensayo estadoEstudio;
	private EPuntoFinal_ensayo EPuntoFinal;
	private EAleatorizacion_ensayo EAleatorizacion;
	private EPatologias_ensayo EPatologias;
	private EProposito_ensayo EProposito;
	private ETipoProtocolo_ensayo ETipoProtocolo;
	private ESexo_ensayo ESexo;
	private Diccionarios_ensayo diccionario;
	private String identificador;
	private String tituloOficial;
	private String tituloAbreviado;
	private String nombre;
	private String investigadorPrincipal;
	private Date fechaAprobacionCecmec;
	private String resumen;
	private String descripcion;
	private String patrocinador;
	private String colaboradores;
	private String otrosFase;
	private Date fechaInicio;
	private Date fechaFin;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private String otroProposito;
	private String nombrePromotor;
	private String rolContacto;
	private Long telefonoContacto;
	private String emailContacto;
	private BigDecimal cantidadSujetosEsperado;
	private String palabrasClaves;
	private BigDecimal edadMinima;
	private BigDecimal edadMaxima;
	private String duracion;
	private Boolean resultadoReferencia;
	private BigDecimal cantidadDiaMonitoreo;
	private Long cid;
	private Usuario_ensayo usuario;
	private Boolean eliminado;
	private Boolean habilitado;
	private String sumarioBreve;
	private String otrasPatologias;
	private Boolean voluntariosSanos;
	private String tipofase;
	private String tipoproposito;
	private String tipoEdadMin;
	private String tipoEdadMax;
	private Set<EIntervencion_ensayo> EIntervencions = new HashSet<EIntervencion_ensayo>(
			0);
	private Set<EProducto_ensayo> EProductos = new HashSet<EProducto_ensayo>(
			0);
	private Set<GrupoSujetos_ensayo> grupoSujetoses = new HashSet<GrupoSujetos_ensayo>(
			0);
	private Set<EEnfermedadCie_ensayo> eEnfermedadCies = new HashSet<EEnfermedadCie_ensayo>(
			0);
	private Set<HojaCrd_ensayo> hojaCrds = new HashSet<HojaCrd_ensayo>(0);
	private Set<EstudioEntidad_ensayo> estudioEntidads = new HashSet<EstudioEntidad_ensayo>(
			0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);
	private Set<ConjuntoDatos_ensayo> conjuntoDatoses = new HashSet<ConjuntoDatos_ensayo>(
			0);
	private Set<Causa_ensayo> causas = new HashSet<Causa_ensayo>(0);
	public Estudio_ensayo() {
	}

	public Estudio_ensayo(long id) {
		this.id = id;
	}

	public Estudio_ensayo(long id, EAsignacion_ensayo EAsignacion,
			EEnmascaramiento_ensayo EEnmascaramiento,
			EFaseEstudio_ensayo EFaseEstudio, Entidad_ensayo entidad,
			EControl_ensayo EControl, Usuario_ensayo usuario,
			ESeleccion_ensayo ESeleccion,
			EAjusteTemporal_ensayo EAjusteTemporal,
			EstadoEstudio_ensayo estadoEstudio, EPuntoFinal_ensayo EPuntoFinal,
			EAleatorizacion_ensayo EAleatorizacion,
			EPatologias_ensayo EPatologias, EProposito_ensayo EProposito,
			ETipoProtocolo_ensayo ETipoProtocolo, ESexo_ensayo ESexo,
			String identificador, String tituloOficial, String tituloAbreviado,
			String nombre, String investigadorPrincipal,
			Date fechaAprobacionCecmec, String resumen, String descripcion,
			String patrocinador, String colaboradores, String otrosFase,
			Date fechaInicio, Date fechaFin, Date fechaCreacion,
			Date fechaActualizacion, String otroProposito,
			String nombrePromotor, String rolContacto, Long telefonoContacto,
			String emailContacto, BigDecimal cantidadSujetosEsperado,
			String palabrasClaves, BigDecimal edadMinima,
			BigDecimal edadMaxima, String duracion,
			Boolean resultadoReferencia, BigDecimal cantidadDiaMonitoreo,
			Long cid, Boolean eliminado, Boolean habilitado,
			String sumarioBreve, String otrasPatologias,
			Boolean voluntariosSanos, String tipofase, String tipoproposito,
			String tipoEdadMin, String tipoEdadMax,
			Set<EIntervencion_ensayo> EIntervencions,
			Set<EProducto_ensayo> EProductos,
			Set<GrupoSujetos_ensayo> grupoSujetoses,
			Set<HojaCrd_ensayo> hojaCrds,
			Set<EEnfermedadCie_ensayo> eEnfermedadCies,
			Set<EstudioEntidad_ensayo> estudioEntidads,
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria,
			Set<ConjuntoDatos_ensayo> conjuntoDatoses,
			Set<Causa_ensayo> causas, Diccionarios_ensayo diccionario) {
		this.id = id;
		this.EAsignacion = EAsignacion;
		this.EEnmascaramiento = EEnmascaramiento;
		this.EFaseEstudio = EFaseEstudio;
		this.entidad = entidad;
		this.EControl = EControl;
		this.ESeleccion = ESeleccion;
		this.EAjusteTemporal = EAjusteTemporal;
		this.estadoEstudio = estadoEstudio;
		this.EPuntoFinal = EPuntoFinal;
		this.EAleatorizacion = EAleatorizacion;
		this.EPatologias = EPatologias;
		this.EProposito = EProposito;
		this.ETipoProtocolo = ETipoProtocolo;
		this.ESexo = ESexo;
		this.diccionario = diccionario;
		this.identificador = identificador;
		this.tituloOficial = tituloOficial;
		this.tituloAbreviado = tituloAbreviado;
		this.nombre = nombre;
		this.investigadorPrincipal = investigadorPrincipal;
		this.fechaAprobacionCecmec = fechaAprobacionCecmec;
		this.resumen = resumen;
		this.descripcion = descripcion;
		this.patrocinador = patrocinador;
		this.colaboradores = colaboradores;
		this.otrosFase = otrosFase;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.otroProposito = otroProposito;
		this.nombrePromotor = nombrePromotor;
		this.rolContacto = rolContacto;
		this.telefonoContacto = telefonoContacto;
		this.emailContacto = emailContacto;
		this.cantidadSujetosEsperado = cantidadSujetosEsperado;
		this.palabrasClaves = palabrasClaves;
		this.edadMinima = edadMinima;
		this.edadMaxima = edadMaxima;
		this.duracion = duracion;
		this.resultadoReferencia = resultadoReferencia;
		this.cantidadDiaMonitoreo = cantidadDiaMonitoreo;
		this.cid = cid;
		this.usuario = usuario;
		this.eliminado = eliminado;
		this.habilitado = habilitado;
		this.sumarioBreve = sumarioBreve;
		this.otrasPatologias = otrasPatologias;
		this.voluntariosSanos = voluntariosSanos;
		this.tipofase = tipofase;
		this.tipoproposito = tipoproposito;
		this.tipoEdadMin = tipoEdadMin;
		this.tipoEdadMax = tipoEdadMax;
		this.EIntervencions = EIntervencions;
		this.EProductos = EProductos;
		this.grupoSujetoses = grupoSujetoses;
		this.hojaCrds = hojaCrds;
		this.estudioEntidads = estudioEntidads;
		this.logEventosAuditoria = logEventosAuditoria;
		this.conjuntoDatoses = conjuntoDatoses;
		this.eEnfermedadCies=eEnfermedadCies;
		this.causas=causas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "asignacion_id")
	public EAsignacion_ensayo getEAsignacion() {
		return this.EAsignacion;
	}

	public void setEAsignacion(EAsignacion_ensayo EAsignacion) {
		this.EAsignacion = EAsignacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enmascaramiento_id")
	public EEnmascaramiento_ensayo getEEnmascaramiento() {
		return this.EEnmascaramiento;
	}

	public void setEEnmascaramiento(EEnmascaramiento_ensayo EEnmascaramiento) {
		this.EEnmascaramiento = EEnmascaramiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fase_id")
	public EFaseEstudio_ensayo getEFaseEstudio() {
		return this.EFaseEstudio;
	}

	public void setEFaseEstudio(EFaseEstudio_ensayo EFaseEstudio) {
		this.EFaseEstudio = EFaseEstudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entidad_id")
	public Entidad_ensayo getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_ensayo entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "control_id")
	public EControl_ensayo getEControl() {
		return this.EControl;
	}

	public void setEControl(EControl_ensayo EControl) {
		this.EControl = EControl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seleccion_id")
	public ESeleccion_ensayo getESeleccion() {
		return this.ESeleccion;
	}

	public void setESeleccion(ESeleccion_ensayo ESeleccion) {
		this.ESeleccion = ESeleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ajuste_temporal_id")
	public EAjusteTemporal_ensayo getEAjusteTemporal() {
		return this.EAjusteTemporal;
	}

	public void setEAjusteTemporal(EAjusteTemporal_ensayo EAjusteTemporal) {
		this.EAjusteTemporal = EAjusteTemporal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado")
	public EstadoEstudio_ensayo getEstadoEstudio() {
		return this.estadoEstudio;
	}

	public void setEstadoEstudio(EstadoEstudio_ensayo estadoEstudio) {
		this.estadoEstudio = estadoEstudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "punto_final_id")
	public EPuntoFinal_ensayo getEPuntoFinal() {
		return this.EPuntoFinal;
	}

	public void setEPuntoFinal(EPuntoFinal_ensayo EPuntoFinal) {
		this.EPuntoFinal = EPuntoFinal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aleatorizacion_id")
	public EAleatorizacion_ensayo getEAleatorizacion() {
		return this.EAleatorizacion;
	}

	public void setEAleatorizacion(EAleatorizacion_ensayo EAleatorizacion) {
		this.EAleatorizacion = EAleatorizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patologia_id")
	public EPatologias_ensayo getEPatologias() {
		return this.EPatologias;
	}

	public void setEPatologias(EPatologias_ensayo EPatologias) {
		this.EPatologias = EPatologias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proposito_id")
	public EProposito_ensayo getEProposito() {
		return this.EProposito;
	}

	public void setEProposito(EProposito_ensayo EProposito) {
		this.EProposito = EProposito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_protocolo_id")
	public ETipoProtocolo_ensayo getETipoProtocolo() {
		return this.ETipoProtocolo;
	}

	public void setETipoProtocolo(ETipoProtocolo_ensayo ETipoProtocolo) {
		this.ETipoProtocolo = ETipoProtocolo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sexo_id")
	public ESexo_ensayo getESexo() {
		return this.ESexo;
	}

	public void setESexo(ESexo_ensayo ESexo) {
		this.ESexo = ESexo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_diccionarios")
	public Diccionarios_ensayo getDiccionario() {
		return diccionario;
	}

	public void setDiccionario(Diccionarios_ensayo diccionario) {
		this.diccionario = diccionario;
	}

	@Column(name = "identificador", length = 50)
	@Length(max = 50)
	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		if (identificador != null)
			identificador = identificador.trim();
		this.identificador = identificador;
	}

	@Column(name = "titulo_oficial")
	public String getTituloOficial() {
		return this.tituloOficial;
	}

	public void setTituloOficial(String tituloOficial) {
		if (tituloOficial != null)
			tituloOficial = tituloOficial.trim();
		this.tituloOficial = tituloOficial;
	}

	@Column(name = "titulo_abreviado")
	public String getTituloAbreviado() {
		return this.tituloAbreviado;
	}

	public void setTituloAbreviado(String tituloAbreviado) {
		if (tituloAbreviado != null)
			tituloAbreviado = tituloAbreviado.trim();
		this.tituloAbreviado = tituloAbreviado;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "investigador_principal")
	public String getInvestigadorPrincipal() {
		return this.investigadorPrincipal;
	}

	public void setInvestigadorPrincipal(String investigadorPrincipal) {
		if (investigadorPrincipal != null)
			investigadorPrincipal = investigadorPrincipal.trim();
		this.investigadorPrincipal = investigadorPrincipal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_aprobacion_cecmec", length = 13)
	public Date getFechaAprobacionCecmec() {
		return this.fechaAprobacionCecmec;
	}

	public void setFechaAprobacionCecmec(Date fechaAprobacionCecmec) {
		this.fechaAprobacionCecmec = fechaAprobacionCecmec;
	}

	@Column(name = "resumen")
	public String getResumen() {
		return this.resumen;
	}

	public void setResumen(String resumen) {
		if (resumen != null)
			resumen = resumen.trim();
		this.resumen = resumen;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "patrocinador")
	public String getPatrocinador() {
		return this.patrocinador;
	}

	public void setPatrocinador(String patrocinador) {
		if (patrocinador != null)
			patrocinador = patrocinador.trim();
		this.patrocinador = patrocinador;
	}

	@Column(name = "colaboradores")
	public String getColaboradores() {
		return this.colaboradores;
	}

	public void setColaboradores(String colaboradores) {
		if (colaboradores != null)
			colaboradores = colaboradores.trim();
		this.colaboradores = colaboradores;
	}

	@Column(name = "otros_fase")
	public String getOtrosFase() {
		return this.otrosFase;
	}

	public void setOtrosFase(String otrosFase) {
		if (otrosFase != null)
			otrosFase = otrosFase.trim();
		this.otrosFase = otrosFase;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "otro_proposito")
	public String getOtroProposito() {
		return this.otroProposito;
	}

	public void setOtroProposito(String otroProposito) {
		if (otroProposito != null)
			otroProposito = otroProposito.trim();
		this.otroProposito = otroProposito;
	}

	@Column(name = "nombre_promotor")
	public String getNombrePromotor() {
		return this.nombrePromotor;
	}

	public void setNombrePromotor(String nombrePromotor) {
		if (nombrePromotor != null)
			nombrePromotor = nombrePromotor.trim();
		this.nombrePromotor = nombrePromotor;
	}

	@Column(name = "rol_contacto")
	public String getRolContacto() {
		return this.rolContacto;
	}

	public void setRolContacto(String rolContacto) {
		if (rolContacto != null)
			rolContacto = rolContacto.trim();
		this.rolContacto = rolContacto;
	}

	@Column(name = "telefono_contacto")
	public Long getTelefonoContacto() {
		return this.telefonoContacto;
	}

	public void setTelefonoContacto(Long telefonoContacto) {
		this.telefonoContacto = telefonoContacto;
	}

	@Column(name = "email_contacto")
	public String getEmailContacto() {
		return this.emailContacto;
	}

	public void setEmailContacto(String emailContacto) {
		if (emailContacto != null)
			emailContacto = emailContacto.trim();
		this.emailContacto = emailContacto;
	}

	@Column(name = "cantidad_sujetos_esperado", scale = 0)
	public BigDecimal getCantidadSujetosEsperado() {
		return this.cantidadSujetosEsperado;
	}

	public void setCantidadSujetosEsperado(BigDecimal cantidadSujetosEsperado) {
		this.cantidadSujetosEsperado = cantidadSujetosEsperado;
	}

	@Column(name = "palabras_claves")
	public String getPalabrasClaves() {
		return this.palabrasClaves;
	}

	public void setPalabrasClaves(String palabrasClaves) {
		if (palabrasClaves != null)
			palabrasClaves = palabrasClaves.trim();
		this.palabrasClaves = palabrasClaves;
	}

	@Column(name = "edad_minima", scale = 0)
	public BigDecimal getEdadMinima() {
		return this.edadMinima;
	}

	public void setEdadMinima(BigDecimal edadMinima) {
		this.edadMinima = edadMinima;
	}

	@Column(name = "edad_maxima", scale = 0)
	public BigDecimal getEdadMaxima() {
		return this.edadMaxima;
	}

	public void setEdadMaxima(BigDecimal edadMaxima) {
		this.edadMaxima = edadMaxima;
	}

	@Column(name = "duracion", length = 30)
	@Length(max = 30)
	public String getDuracion() {
		return this.duracion;
	}

	public void setDuracion(String duracion) {
		if (duracion != null)
			duracion = duracion.trim();
		this.duracion = duracion;
	}

	@Column(name = "resultado_referencia")
	public Boolean getResultadoReferencia() {
		return this.resultadoReferencia;
	}

	public void setResultadoReferencia(Boolean resultadoReferencia) {
		this.resultadoReferencia = resultadoReferencia;
	}

	@Column(name = "cantidad_dia_monitoreo", scale = 0)
	public BigDecimal getCantidadDiaMonitoreo() {
		return this.cantidadDiaMonitoreo;
	}

	public void setCantidadDiaMonitoreo(BigDecimal cantidadDiaMonitoreo) {
		this.cantidadDiaMonitoreo = cantidadDiaMonitoreo;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "habilitado")
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@Column(name = "sumario_breve")
	public String getSumarioBreve() {
		return this.sumarioBreve;
	}

	public void setSumarioBreve(String sumarioBreve) {
		if (sumarioBreve != null)
			sumarioBreve = sumarioBreve.trim();
		this.sumarioBreve = sumarioBreve;
	}

	@Column(name = "otras_patologias")
	public String getOtrasPatologias() {
		return this.otrasPatologias;
	}

	public void setOtrasPatologias(String otrasPatologias) {
		if (otrasPatologias != null)
			otrasPatologias = otrasPatologias.trim();
		this.otrasPatologias = otrasPatologias;
	}

	@Column(name = "voluntarios_sanos")
	public Boolean getVoluntariosSanos() {
		return this.voluntariosSanos;
	}

	public void setVoluntariosSanos(Boolean voluntariosSanos) {
		this.voluntariosSanos = voluntariosSanos;
	}

	@Column(name = "tipofase", length = 50)
	@Length(max = 50)
	public String getTipofase() {
		return this.tipofase;
	}

	public void setTipofase(String tipofase) {
		if (tipofase != null)
			tipofase = tipofase.trim();
		this.tipofase = tipofase;
	}

	@Column(name = "tipoproposito", length = 50)
	@Length(max = 50)
	public String getTipoproposito() {
		return this.tipoproposito;
	}

	public void setTipoproposito(String tipoproposito) {
		if (tipoproposito != null)
			tipoproposito = tipoproposito.trim();
		this.tipoproposito = tipoproposito;
	}
	
	@Column(name = "tipo_edad_min", length = 255)
	@Length(max = 255)
	public String getTipoEdadMin() {
		return this.tipoEdadMin;
	}

	public void setTipoEdadMin(String tipoEdadMin) {
		if (tipoEdadMin != null)
			tipoEdadMin = tipoEdadMin.trim();
		this.tipoEdadMin = tipoEdadMin;
	}
	
	@Column(name = "tipo_edad_max", length = 255)
	@Length(max = 255)
	public String getTipoEdadMax() {
		return this.tipoEdadMax;
	}

	public void setTipoEdadMax(String tipoEdadMax) {
		if (tipoEdadMax != null)
			tipoEdadMax = tipoEdadMax.trim();
		this.tipoEdadMax = tipoEdadMax;
	}
	
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	public Set<EIntervencion_ensayo> getEIntervencions() {
		return this.EIntervencions;
	}

	public void setEIntervencions(Set<EIntervencion_ensayo> EIntervencions) {
		this.EIntervencions = EIntervencions;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	public Set<EProducto_ensayo> getEProductos() {
		return this.EProductos;
	}

	public void setEProductos(Set<EProducto_ensayo> EProductos) {
		this.EProductos = EProductos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "estudio")
	@OrderBy("nombreGrupo")
	public Set<GrupoSujetos_ensayo> getGrupoSujetoses() {
		return this.grupoSujetoses;
	}

	public void setGrupoSujetoses(Set<GrupoSujetos_ensayo> grupoSujetoses) {
		this.grupoSujetoses = grupoSujetoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	public Set<HojaCrd_ensayo> getHojaCrds() {
		return this.hojaCrds;
	}

	public void setHojaCrds(Set<HojaCrd_ensayo> hojaCrds) {
		this.hojaCrds = hojaCrds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	public Set<EstudioEntidad_ensayo> getEstudioEntidads() {
		return this.estudioEntidads;
	}

	public void setEstudioEntidads(Set<EstudioEntidad_ensayo> estudioEntidads) {
		this.estudioEntidads = estudioEntidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	public Set<ConjuntoDatos_ensayo> getConjuntoDatoses() {
		return this.conjuntoDatoses;
	}

	public void setConjuntoDatoses(Set<ConjuntoDatos_ensayo> conjuntoDatoses) {
		this.conjuntoDatoses = conjuntoDatoses;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	public Set<Causa_ensayo> getCausas() {
		return this.causas;
	}

	public void setCausas(Set<Causa_ensayo> causas) {
		this.causas = causas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudio")
	public Set<EEnfermedadCie_ensayo> getEEnfermedadCies() {
		return this.eEnfermedadCies;
	}

	public void setEEnfermedadCies(Set<EEnfermedadCie_ensayo> eEnfermedadCies) {
		this.eEnfermedadCies = eEnfermedadCies;
	}

	

}
