package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * EstudioEntidad generated by hbm2java
 */
@Entity
@Table(name = "estudio_entidad", schema = "ensayo")
public class EstudioEntidad_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Entidad_ensayo entidad;
	private Estudio_ensayo estudio;
	private Long cid;
	private Boolean eliminado;
	private Set<UsuarioEstudio_ensayo> usuarioEstudios = new HashSet<UsuarioEstudio_ensayo>(
			0);

	public EstudioEntidad_ensayo() {
	}

	public EstudioEntidad_ensayo(long id, Entidad_ensayo entidad,
			Estudio_ensayo estudio) {
		this.id = id;
		this.entidad = entidad;
		this.estudio = estudio;
	}

	public EstudioEntidad_ensayo(long id, Entidad_ensayo entidad,
			Estudio_ensayo estudio, Long cid, Boolean eliminado,
			Set<UsuarioEstudio_ensayo> usuarioEstudios) {
		this.id = id;
		this.entidad = entidad;
		this.estudio = estudio;
		this.cid = cid;
		this.eliminado = eliminado;
		this.usuarioEstudios = usuarioEstudios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad", nullable = false)
	@NotNull
	public Entidad_ensayo getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_ensayo entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudio", nullable = false)
	@NotNull
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudioEntidad")
	public Set<UsuarioEstudio_ensayo> getUsuarioEstudios() {
		return this.usuarioEstudios;
	}

	public void setUsuarioEstudios(Set<UsuarioEstudio_ensayo> usuarioEstudios) {
		this.usuarioEstudios = usuarioEstudios;
	}

}
