package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Etapa generated by hbm2java
 */
@Entity
@Table(name = "etapa", schema = "ensayo")
public class Etapa_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Cronograma_ensayo cronograma;
	private Usuario_ensayo usuario;
	private String nombreEtapa;
	private Integer inicioEtapa;
	private Integer finEtapa;
	private String descripcion;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Long cid;

	public Etapa_ensayo() {
	}

	public Etapa_ensayo(long id, Cronograma_ensayo cronograma) {
		this.id = id;
		this.cronograma = cronograma;
	}

	public Etapa_ensayo(long id, Cronograma_ensayo cronograma, Usuario_ensayo usuario,
			String nombreEtapa, Integer inicioEtapa, Integer finEtapa,
			String descripcion, Date fechaCreacion, Date fechaActualizacion,
			Long cid) {
		this.id = id;
		this.cronograma = cronograma;
		this.nombreEtapa = nombreEtapa;
		this.inicioEtapa = inicioEtapa;
		this.finEtapa = finEtapa;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuario = usuario;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cronograma", nullable = false)
	@NotNull
	public Cronograma_ensayo getCronograma() {
		return this.cronograma;
	}

	public void setCronograma(Cronograma_ensayo cronograma) {
		this.cronograma = cronograma;
	}

	@Column(name = "nombre_etapa")
	public String getNombreEtapa() {
		return this.nombreEtapa;
	}

	public void setNombreEtapa(String nombreEtapa) {
		if (nombreEtapa != null)
			nombreEtapa = nombreEtapa.trim();
		this.nombreEtapa = nombreEtapa;
	}

	@Column(name = "inicio_etapa")
	public Integer getInicioEtapa() {
		return this.inicioEtapa;
	}

	public void setInicioEtapa(Integer inicioEtapa) {
		this.inicioEtapa = inicioEtapa;
	}

	@Column(name = "fin_etapa")
	public Integer getFinEtapa() {
		return this.finEtapa;
	}

	public void setFinEtapa(Integer finEtapa) {
		this.finEtapa = finEtapa;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

}
