package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ETipoIntervencion generated by hbm2java
 */
@Entity
@Table(name = "e_tipo_intervencion", schema = "ensayo")
public class ETipoIntervencion_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String nombre;
	private String descripcion;
	private Boolean eliminado;
	private Long codigo;
	private Set<EIntervencion_ensayo> EIntervencions = new HashSet<EIntervencion_ensayo>(
			0);

	public ETipoIntervencion_ensayo() {
	}

	public ETipoIntervencion_ensayo(long id) {
		this.id = id;
	}

	public ETipoIntervencion_ensayo(long id, String nombre, String descripcion,
			Boolean eliminado, Long codigo,
			Set<EIntervencion_ensayo> EIntervencions) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.eliminado = eliminado;
		this.codigo = codigo;
		this.EIntervencions = EIntervencions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	@Length(max = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "codigo")
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ETipoIntervencion")
	public Set<EIntervencion_ensayo> getEIntervencions() {
		return this.EIntervencions;
	}

	public void setEIntervencions(Set<EIntervencion_ensayo> EIntervencions) {
		this.EIntervencions = EIntervencions;
	}

}
