package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ETipoProtocolo generated by hbm2java
 */
@Entity
@Table(name = "e_tipo_protocolo", schema = "ensayo")
public class ETipoProtocolo_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String nombre;
	private String descripcion;
	private Boolean eliminado;
	private Long codigo;
	private Set<EProposito_ensayo> EPropositos = new HashSet<EProposito_ensayo>(
			0);
	private Set<Estudio_ensayo> estudios = new HashSet<Estudio_ensayo>(0);

	public ETipoProtocolo_ensayo() {
	}

	public ETipoProtocolo_ensayo(long id) {
		this.id = id;
	}

	public ETipoProtocolo_ensayo(long id, String nombre, String descripcion,
			Boolean eliminado, Long codigo, Set<EProposito_ensayo> EPropositos,
			Set<Estudio_ensayo> estudios) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.eliminado = eliminado;
		this.codigo = codigo;
		this.EPropositos = EPropositos;
		this.estudios = estudios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	@Length(max = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "codigo")
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ETipoProtocolo")
	public Set<EProposito_ensayo> getEPropositos() {
		return this.EPropositos;
	}

	public void setEPropositos(Set<EProposito_ensayo> EPropositos) {
		this.EPropositos = EPropositos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ETipoProtocolo")
	public Set<Estudio_ensayo> getEstudios() {
		return this.estudios;
	}

	public void setEstudios(Set<Estudio_ensayo> estudios) {
		this.estudios = estudios;
	}

}
