package gehos.ensayo.entity;

// Generated 09-sep-2016 16:12:22 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * GrupoVariables generated by hbm2java
 */
@Entity
@Table(name = "grupo_variables", schema = "ensayo")
public class GrupoVariables_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Seccion_ensayo seccion;
	private String etiquetaGrupo;
	private String descripcionGrupo;
	private String encabezado;
	private Integer numRepeticiones;
	private Integer numMaxRepeticiones;
	private String estadoGrupo;
	private Boolean eliminado;
	private Long cid;
	private Boolean habilitado;
	private Set<Variable_ensayo> variables = new HashSet<Variable_ensayo>(0);

	public GrupoVariables_ensayo() {
	}

	public GrupoVariables_ensayo(long id) {
		this.id = id;
	}

	public GrupoVariables_ensayo(long id, Seccion_ensayo seccion,
			String etiquetaGrupo, String descripcionGrupo, String encabezado,
			Integer numRepeticiones, Integer numMaxRepeticiones,
			String estadoGrupo, Boolean eliminado, Long cid,
			Boolean habilitado, Set<Variable_ensayo> variables) {
		this.id = id;
		this.seccion = seccion;
		this.etiquetaGrupo = etiquetaGrupo;
		this.descripcionGrupo = descripcionGrupo;
		this.encabezado = encabezado;
		this.numRepeticiones = numRepeticiones;
		this.numMaxRepeticiones = numMaxRepeticiones;
		this.estadoGrupo = estadoGrupo;
		this.eliminado = eliminado;
		this.cid = cid;
		this.habilitado = habilitado;
		this.variables = variables;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_seccion")
	public Seccion_ensayo getSeccion() {
		return this.seccion;
	}

	public void setSeccion(Seccion_ensayo seccion) {
		this.seccion = seccion;
	}

	@Column(name = "etiqueta_grupo")
	public String getEtiquetaGrupo() {
		return this.etiquetaGrupo;
	}

	public void setEtiquetaGrupo(String etiquetaGrupo) {
		if (etiquetaGrupo != null)
			etiquetaGrupo = etiquetaGrupo.trim();
		this.etiquetaGrupo = etiquetaGrupo;
	}

	@Column(name = "descripcion_grupo")
	public String getDescripcionGrupo() {
		return this.descripcionGrupo;
	}

	public void setDescripcionGrupo(String descripcionGrupo) {
		if (descripcionGrupo != null)
			descripcionGrupo = descripcionGrupo.trim();
		if (descripcionGrupo == "")
			descripcionGrupo = null;
		this.descripcionGrupo = descripcionGrupo;
	}

	@Column(name = "encabezado")
	public String getEncabezado() {
		return this.encabezado;
	}

	public void setEncabezado(String encabezado) {
		if (encabezado != null)
			encabezado = encabezado.trim();
		this.encabezado = encabezado;
	}

	@Column(name = "num_repeticiones")
	public Integer getNumRepeticiones() {
		return this.numRepeticiones;
	}

	public void setNumRepeticiones(Integer numRepeticiones) {
		this.numRepeticiones = numRepeticiones;
	}

	@Column(name = "num_max_repeticiones")
	public Integer getNumMaxRepeticiones() {
		return this.numMaxRepeticiones;
	}

	public void setNumMaxRepeticiones(Integer numMaxRepeticiones) {
		this.numMaxRepeticiones = numMaxRepeticiones;
	}

	@Column(name = "estado_grupo", length = 500)
	@Length(max = 500)
	public String getEstadoGrupo() {
		return this.estadoGrupo;
	}

	public void setEstadoGrupo(String estadoGrupo) {
		if (estadoGrupo != null)
			estadoGrupo = estadoGrupo.trim();
		if (estadoGrupo == "")
			estadoGrupo = null;
		this.estadoGrupo = estadoGrupo;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "habilitado")
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "grupoVariables")
	public Set<Variable_ensayo> getVariables() {
		return this.variables;
	}

	public void setVariables(Set<Variable_ensayo> variables) {
		this.variables = variables;
	}

}
