package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * GrupoSujetos generated by hbm2java
 */
@Entity
@Table(name = "grupo_sujetos", schema = "ensayo")
public class GrupoSujetos_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Estudio_ensayo estudio;
	private EstadoGruposujeto_ensayo estadoGruposujeto;
	private String nombreGrupo;
	private String descripcion;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Long cid;
	private Boolean eliminado;
	private Boolean habilitado;
	private Usuario_ensayo usuario;
	private Set<Sujeto_ensayo> sujetos = new HashSet<Sujeto_ensayo>(0);
	private Set<Cronograma_ensayo> cronogramas = new HashSet<Cronograma_ensayo>(
			0);
	private Set<NotaGeneral_ensayo> notaGenerals = new HashSet<NotaGeneral_ensayo>(
			0);

	public GrupoSujetos_ensayo() {
	}

	public GrupoSujetos_ensayo(long id, Estudio_ensayo estudio) {
		this.id = id;
		this.estudio = estudio;
	}

	public GrupoSujetos_ensayo(long id, Estudio_ensayo estudio,
			EstadoGruposujeto_ensayo estadoGruposujeto, String nombreGrupo,
			String descripcion, Date fechaCreacion, Date fechaActualizacion,
			Long cid, Boolean eliminado, Boolean habilitado, Usuario_ensayo usuario,
			Set<Sujeto_ensayo> sujetos, Set<Cronograma_ensayo> cronogramas,Set<NotaGeneral_ensayo> notaGenerals) {
		this.id = id;
		this.estudio = estudio;
		this.estadoGruposujeto = estadoGruposujeto;
		this.nombreGrupo = nombreGrupo;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.cid = cid;
		this.eliminado = eliminado;
		this.habilitado = habilitado;
		this.sujetos = sujetos;
		this.cronogramas = cronogramas;
		this.notaGenerals = notaGenerals;
		this.usuario = usuario;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudio", nullable = false)
	@NotNull
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado")
	public EstadoGruposujeto_ensayo getEstadoGruposujeto() {
		return this.estadoGruposujeto;
	}

	public void setEstadoGruposujeto(EstadoGruposujeto_ensayo estadoGruposujeto) {
		this.estadoGruposujeto = estadoGruposujeto;
	}

	@Column(name = "nombre_grupo")
	public String getNombreGrupo() {
		return this.nombreGrupo;
	}

	public void setNombreGrupo(String nombreGrupo) {
		if (nombreGrupo != null)
			nombreGrupo = nombreGrupo.trim();
		this.nombreGrupo = nombreGrupo;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "habilitado")
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoSujetos")
	public Set<NotaGeneral_ensayo> getNotaGenerals() {
		return this.notaGenerals;
	}

	public void setNotaGenerals(Set<NotaGeneral_ensayo> notaGenerals) {
		this.notaGenerals = notaGenerals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoSujetos")
	public Set<Sujeto_ensayo> getSujetos() {
		return this.sujetos;
	}

	public void setSujetos(Set<Sujeto_ensayo> sujetos) {
		this.sujetos = sujetos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "grupoSujetos")
	public Set<Cronograma_ensayo> getCronogramas() {
		return this.cronogramas;
	}

	public void setCronogramas(Set<Cronograma_ensayo> cronogramas) {
		this.cronogramas = cronogramas;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

}
