package gehos.ensayo.entity;

// Generated 09-sep-2016 16:12:22 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * HojaCrd generated by hbm2java
 */
@Entity
@Table(name = "hoja_crd", schema = "ensayo")
public class HojaCrd_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private HojaCrd_ensayo hojaCrd;
	private Estudio_ensayo estudio;
	private EstadoHojaCrd_ensayo estadoHojaCrd;
	private Usuario_ensayo usuario;
	private String nombreHoja;
	private String descripcion;
	private Long cid;
	private Boolean eliminado;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Set<Seccion_ensayo> seccions = new HashSet<Seccion_ensayo>(0);
	private Set<HojaCrd_ensayo> hojaCrds = new HashSet<HojaCrd_ensayo>(0);
	private Set<MomentoSeguimientoGeneralHojaCrd_ensayo> momentoSeguimientoGeneralHojaCrds = new HashSet<MomentoSeguimientoGeneralHojaCrd_ensayo>(
			0);
	private Set<CrdEspecifico_ensayo> crdEspecificos = new HashSet<CrdEspecifico_ensayo>(
			0);

	public HojaCrd_ensayo() {
	}

	public HojaCrd_ensayo(long id) {
		this.id = id;
	}

	public HojaCrd_ensayo(
			long id,
			HojaCrd_ensayo hojaCrd,
			Estudio_ensayo estudio,
			EstadoHojaCrd_ensayo estadoHojaCrd,
			NotaGeneral_ensayo notaGeneral,
			Usuario_ensayo usuario,
			String nombreHoja,
			String descripcion,
			Long cid,
			Boolean eliminado,
			Date fechaCreacion,
			Date fechaActualizacion,
			Set<Seccion_ensayo> seccions,
			Set<HojaCrd_ensayo> hojaCrds,
			Set<MomentoSeguimientoGeneralHojaCrd_ensayo> momentoSeguimientoGeneralHojaCrds,
			Set<CrdEspecifico_ensayo> crdEspecificos) {
		this.id = id;
		this.hojaCrd = hojaCrd;
		this.estudio = estudio;
		this.estadoHojaCrd = estadoHojaCrd;
		this.usuario = usuario;
		this.nombreHoja = nombreHoja;
		this.descripcion = descripcion;
		this.cid = cid;
		this.eliminado = eliminado;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.seccions = seccions;
		this.hojaCrds = hojaCrds;
		this.momentoSeguimientoGeneralHojaCrds = momentoSeguimientoGeneralHojaCrds;
		this.crdEspecificos = crdEspecificos;
	}

	@Id
	@Column(name = "id", unique = true)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hoja_padre")
	public HojaCrd_ensayo getHojaCrd() {
		return this.hojaCrd;
	}

	public void setHojaCrd(HojaCrd_ensayo hojaCrd) {
		this.hojaCrd = hojaCrd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudio")
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_hoja")
	public EstadoHojaCrd_ensayo getEstadoHojaCrd() {
		return this.estadoHojaCrd;
	}

	public void setEstadoHojaCrd(EstadoHojaCrd_ensayo estadoHojaCrd) {
		this.estadoHojaCrd = estadoHojaCrd;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre_hoja", length = 500)
	@Length(max = 500)
	public String getNombreHoja() {
		return this.nombreHoja;
	}

	public void setNombreHoja(String nombreHoja) {
		if (nombreHoja != null)
			nombreHoja = nombreHoja.trim();
		this.nombreHoja = nombreHoja;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		if (descripcion == "")
			descripcion = null;
		this.descripcion = descripcion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "hojaCrd")
	public Set<Seccion_ensayo> getSeccions() {
		return this.seccions;
	}

	public void setSeccions(Set<Seccion_ensayo> seccions) {
		this.seccions = seccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hojaCrd")
	public Set<HojaCrd_ensayo> getHojaCrds() {
		return this.hojaCrds;
	}

	public void setHojaCrds(Set<HojaCrd_ensayo> hojaCrds) {
		this.hojaCrds = hojaCrds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hojaCrd")
	public Set<MomentoSeguimientoGeneralHojaCrd_ensayo> getMomentoSeguimientoGeneralHojaCrds() {
		return this.momentoSeguimientoGeneralHojaCrds;
	}

	public void setMomentoSeguimientoGeneralHojaCrds(
			Set<MomentoSeguimientoGeneralHojaCrd_ensayo> momentoSeguimientoGeneralHojaCrds) {
		this.momentoSeguimientoGeneralHojaCrds = momentoSeguimientoGeneralHojaCrds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hojaCrd")
	public Set<CrdEspecifico_ensayo> getCrdEspecificos() {
		return this.crdEspecificos;
	}

	public void setCrdEspecificos(Set<CrdEspecifico_ensayo> crdEspecificos) {
		this.crdEspecificos = crdEspecificos;
	}

}