package gehos.ensayo.entity;

// Generated 24-may-2019 9:24:45 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LogEventosConduccion generated by hbm2java
 */
@Entity
@Table(name = "log_eventos_conduccion", schema = "ensayo")
public class LogEventosConduccion_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String tablaAuditada;
	private Long idTabla;
	private String nombreAplicacion;
	private Long tipoAuditoria;
	private String atributoModificado;
	private String oldValue;
	private String newValue;
	private Boolean eliminado;
	private Long cid;
	private String usuarioNombre;
	private String estudioNombre;
	private String gsNombre;
	private String sujeto;
	private String mseNombre;
	private String hojaCrd;
	private String seccion;
	private String variableNombre;
	private String variableDatoValor;
	private Date fechaAuditoria;
	private String hora;
	private Long idEst;

	public LogEventosConduccion_ensayo() {
	}

	public LogEventosConduccion_ensayo(long id, String tablaAuditada) {
		this.id = id;
		this.tablaAuditada = tablaAuditada;
	}

	public LogEventosConduccion_ensayo(long id, String tablaAuditada,
			Long idTabla, String nombreAplicacion, Long tipoAuditoria,
			String atributoModificado, String oldValue, String newValue,
			Boolean eliminado, Long cid, String usuarioNombre,
			String estudioNombre, String gsNombre, String sujeto,
			String mseNombre, String hojaCrd, String seccion,
			String variableNombre, String variableDatoValor,
			Date fechaAuditoria, String hora, Long idEst) {
		this.id = id;
		this.tablaAuditada = tablaAuditada;
		this.idTabla = idTabla;
		this.nombreAplicacion = nombreAplicacion;
		this.tipoAuditoria = tipoAuditoria;
		this.atributoModificado = atributoModificado;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.eliminado = eliminado;
		this.cid = cid;
		this.usuarioNombre = usuarioNombre;
		this.estudioNombre = estudioNombre;
		this.gsNombre = gsNombre;
		this.sujeto = sujeto;
		this.mseNombre = mseNombre;
		this.hojaCrd = hojaCrd;
		this.seccion = seccion;
		this.variableNombre = variableNombre;
		this.variableDatoValor = variableDatoValor;
		this.fechaAuditoria = fechaAuditoria;
		this.hora = hora;
		this.idEst = idEst;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "tabla_auditada", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getTablaAuditada() {
		return this.tablaAuditada;
	}

	public void setTablaAuditada(String tablaAuditada) {
		if (tablaAuditada != null)
			tablaAuditada = tablaAuditada.trim();
		this.tablaAuditada = tablaAuditada;
	}

	@Column(name = "id_tabla")
	public Long getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(Long idTabla) {
		this.idTabla = idTabla;
	}

	@Column(name = "nombre_aplicacion")
	public String getNombreAplicacion() {
		return this.nombreAplicacion;
	}

	public void setNombreAplicacion(String nombreAplicacion) {
		if (nombreAplicacion != null)
			nombreAplicacion = nombreAplicacion.trim();
		this.nombreAplicacion = nombreAplicacion;
	}

	@Column(name = "tipo_auditoria")
	public Long getTipoAuditoria() {
		return this.tipoAuditoria;
	}

	public void setTipoAuditoria(Long tipoAuditoria) {
		this.tipoAuditoria = tipoAuditoria;
	}

	@Column(name = "atributo_modificado", length = 500)
	@Length(max = 500)
	public String getAtributoModificado() {
		return this.atributoModificado;
	}

	public void setAtributoModificado(String atributoModificado) {
		if (atributoModificado != null)
			atributoModificado = atributoModificado.trim();
		this.atributoModificado = atributoModificado;
	}

	@Column(name = "old_value", length = 2000)
	@Length(max = 2000)
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		if (oldValue != null)
			oldValue = oldValue.trim();
		this.oldValue = oldValue;
	}

	@Column(name = "new_value", length = 2000)
	@Length(max = 2000)
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		if (newValue != null)
			newValue = newValue.trim();
		this.newValue = newValue;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "usuario_nombre")
	public String getUsuarioNombre() {
		return this.usuarioNombre;
	}

	public void setUsuarioNombre(String usuarioNombre) {
		if (usuarioNombre != null)
			usuarioNombre = usuarioNombre.trim();
		this.usuarioNombre = usuarioNombre;
	}

	@Column(name = "estudio_nombre")
	public String getEstudioNombre() {
		return this.estudioNombre;
	}

	public void setEstudioNombre(String estudioNombre) {
		if (estudioNombre != null)
			estudioNombre = estudioNombre.trim();
		this.estudioNombre = estudioNombre;
	}

	@Column(name = "gs_nombre")
	public String getGsNombre() {
		return this.gsNombre;
	}

	public void setGsNombre(String gsNombre) {
		if (gsNombre != null)
			gsNombre = gsNombre.trim();
		this.gsNombre = gsNombre;
	}

	@Column(name = "sujeto")
	public String getSujeto() {
		return this.sujeto;
	}

	public void setSujeto(String sujeto) {
		if (sujeto != null)
			sujeto = sujeto.trim();
		this.sujeto = sujeto;
	}

	@Column(name = "mse_nombre")
	public String getMseNombre() {
		return this.mseNombre;
	}

	public void setMseNombre(String mseNombre) {
		if (mseNombre != null)
			mseNombre = mseNombre.trim();
		this.mseNombre = mseNombre;
	}

	@Column(name = "hoja_crd")
	public String getHojaCrd() {
		return this.hojaCrd;
	}

	public void setHojaCrd(String hojaCrd) {
		if (hojaCrd != null)
			hojaCrd = hojaCrd.trim();
		this.hojaCrd = hojaCrd;
	}

	@Column(name = "seccion")
	public String getSeccion() {
		return this.seccion;
	}

	public void setSeccion(String seccion) {
		if (seccion != null)
			seccion = seccion.trim();
		this.seccion = seccion;
	}

	@Column(name = "variable_nombre")
	public String getVariableNombre() {
		return this.variableNombre;
	}

	public void setVariableNombre(String variableNombre) {
		if (variableNombre != null)
			variableNombre = variableNombre.trim();
		this.variableNombre = variableNombre;
	}

	@Column(name = "variable_dato_valor")
	public String getVariableDatoValor() {
		return this.variableDatoValor;
	}

	public void setVariableDatoValor(String variableDatoValor) {
		if (variableDatoValor != null)
			variableDatoValor = variableDatoValor.trim();
		this.variableDatoValor = variableDatoValor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_auditoria", length = 13)
	public Date getFechaAuditoria() {
		return this.fechaAuditoria;
	}

	public void setFechaAuditoria(Date fechaAuditoria) {
		this.fechaAuditoria = fechaAuditoria;
	}

	@Column(name = "hora")
	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		if (hora != null)
			hora = hora.trim();
		this.hora = hora;
	}

	@Column(name = "id_est")
	public Long getIdEst() {
		return this.idEst;
	}

	public void setIdEst(Long idEst) {
		this.idEst = idEst;
	}

}
