package gehos.ensayo.entity;

// Generated 16-mar-2017 12:25:15 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.sql.Time;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LogEventosAuditoria generated by hbm2java
 */
@Entity
@Table(name = "log_eventos_auditoria", schema = "ensayo")
public class LogEventosAuditoria_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private LogTipoAuditoria_ensayo logTipoAuditoria;
	private Date fechaAuditoria;
	private String hora;
	private String tablaAuditada;
	private Usuario_ensayo usuario;
	private Long idTabla;
	private String nombreAplicacion;
	private String atributoModificado;
	private String oldValue;
	private String newValue;
	private Estudio_ensayo estudio;
	private Sujeto_ensayo sujeto;
	private MomentoSeguimientoEspecifico_ensayo msEspecifico;
	private CrdEspecifico_ensayo crdEspecifico;
	private String tablaEstado;
	private Cronograma_ensayo cronograma;
	private MomentoSeguimientoGeneral_ensayo msGnral;
	private Variable_ensayo variable;
	private Boolean eliminado;
	private Long cid;
	private String usuarioNombre;
	private String estudioNombre;
	private String gsNombre;
	private String sujetoNombre;
	private String msgNombre;
	private String variableNombre;
	private String hojaCrd;

	public LogEventosAuditoria_ensayo() {
	}

	public LogEventosAuditoria_ensayo(long id, String tablaAuditada) {
		this.id = id;
		this.tablaAuditada = tablaAuditada;
	}

	public LogEventosAuditoria_ensayo(long id,
			LogTipoAuditoria_ensayo logTipoAuditoria, Date fechaAuditoria, String hora,
			String tablaAuditada, Usuario_ensayo usuario, Long idTabla,
			String nombreAplicacion, String atributoModificado,
			String oldValue, String newValue, Estudio_ensayo estudio,
			Sujeto_ensayo sujeto,
			MomentoSeguimientoEspecifico_ensayo msEspecifico,
			CrdEspecifico_ensayo crdEspecifico, String tablaEstado,
			Cronograma_ensayo cronograma,
			MomentoSeguimientoGeneral_ensayo msGnral, Variable_ensayo variable,
			Boolean eliminado, Long cid, String usuarioNombre,
			String estudioNombre, String gsNombre, String sujetoNombre,
			String msgNombre, String variableNombre, String hojaCrd) {
		this.id = id;
		this.logTipoAuditoria = logTipoAuditoria;
		this.fechaAuditoria = fechaAuditoria;
		this.hora = hora;
		this.tablaAuditada = tablaAuditada;
		this.usuario = usuario;
		this.idTabla = idTabla;
		this.nombreAplicacion = nombreAplicacion;
		this.atributoModificado = atributoModificado;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.estudio = estudio;
		this.sujeto = sujeto;
		this.msEspecifico = msEspecifico;
		this.crdEspecifico = crdEspecifico;
		this.tablaEstado = tablaEstado;
		this.cronograma = cronograma;
		this.msGnral = msGnral;
		this.variable = variable;
		this.eliminado = eliminado;
		this.cid = cid;
		this.usuarioNombre = usuarioNombre;
		this.estudioNombre = estudioNombre;
		this.gsNombre = gsNombre;
		this.sujetoNombre = sujetoNombre;
		this.msgNombre = msgNombre;
		this.variableNombre = variableNombre;
		this.hojaCrd = hojaCrd;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_auditoria")
	public LogTipoAuditoria_ensayo getLogTipoAuditoria() {
		return this.logTipoAuditoria;
	}

	public void setLogTipoAuditoria(LogTipoAuditoria_ensayo logTipoAuditoria) {
		this.logTipoAuditoria = logTipoAuditoria;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_auditoria", length = 29)
	public Date getFechaAuditoria() {
		return this.fechaAuditoria;
	}

	public void setFechaAuditoria(Date fechaAuditoria) {
		this.fechaAuditoria = fechaAuditoria;
	}
	
	
	@Column(name = "hora")
	public String getHora() {
		return this.hora;
	}

	public void setHora(String Hora) {
		this.hora = Hora;
	}

	@Column(name = "tabla_auditada", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getTablaAuditada() {
		return this.tablaAuditada;
	}

	public void setTablaAuditada(String tablaAuditada) {
		if (tablaAuditada != null)
			tablaAuditada = tablaAuditada.trim();
		this.tablaAuditada = tablaAuditada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@Column(name = "id_tabla")
	public Long getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(Long idTabla) {
		this.idTabla = idTabla;
	}

	@Column(name = "nombre_aplicacion")
	public String getNombreAplicacion() {
		return this.nombreAplicacion;
	}

	public void setNombreAplicacion(String nombreAplicacion) {
		if (nombreAplicacion != null)
			nombreAplicacion = nombreAplicacion.trim();
		this.nombreAplicacion = nombreAplicacion;
	}

	@Column(name = "usuario_nombre")
	public String getUsuarioNombre() {
		return this.usuarioNombre;
	}

	public void setUsuarioNombre(String usuarioNombre) {
		if (usuarioNombre != null)
			usuarioNombre = usuarioNombre.trim();
		this.usuarioNombre = usuarioNombre;
	}

	@Column(name = "estudio_nombre")
	public String getEstudioNombre() {
		return this.estudioNombre;
	}

	public void setEstudioNombre(String estudioNombre) {
		if (estudioNombre != null)
			estudioNombre = estudioNombre.trim();
		this.estudioNombre = estudioNombre;
	}

	@Column(name = "gs_nombre")
	public String getGsNombre() {
		return this.gsNombre;
	}

	public void setGsNombre(String gsNombre) {
		if (gsNombre != null)
			gsNombre = gsNombre.trim();
		this.gsNombre = gsNombre;
	}

	@Column(name = "sujeto_nombre")
	public String getSujetoNombre() {
		return this.sujetoNombre;
	}

	public void setSujetoNombre(String sujetoNombre) {
		if (sujetoNombre != null)
			sujetoNombre = sujetoNombre.trim();
		this.sujetoNombre = sujetoNombre;
	}

	@Column(name = "msg_nombre")
	public String getMsgNombre() {
		return this.msgNombre;
	}

	public void setMsgNombre(String msgNombre) {
		if (msgNombre != null)
			msgNombre = msgNombre.trim();
		this.msgNombre = msgNombre;
	}

	@Column(name = "variable_nombre")
	public String getVariableNombre() {
		return this.variableNombre;
	}

	public void setVariableNombre(String variableNombre) {
		if (variableNombre != null)
			variableNombre = variableNombre.trim();
		this.variableNombre = variableNombre;
	}

	@Column(name = "hoja_crd")
	public String getHojaCrd() {
		return this.hojaCrd;
	}

	public void setHojaCrd(String hojaCrd) {
		if (hojaCrd != null)
			hojaCrd = hojaCrd.trim();
		this.hojaCrd = hojaCrd;
	}

	@Column(name = "atributo_modificado", length = 500)
	@Length(max = 500)
	public String getAtributoModificado() {
		return this.atributoModificado;
	}

	public void setAtributoModificado(String atributoModificado) {
		if (atributoModificado != null)
			atributoModificado = atributoModificado.trim();
		this.atributoModificado = atributoModificado;
	}

	@Column(name = "old_value", length = 2000)
	@Length(max = 2000)
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		if (oldValue != null)
			oldValue = oldValue.trim();
		this.oldValue = oldValue;
	}

	@Column(name = "new_value", length = 2000)
	@Length(max = 2000)
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		if (newValue != null)
			newValue = newValue.trim();
		this.newValue = newValue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estudio")
	public Estudio_ensayo getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio_ensayo estudio) {
		this.estudio = estudio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sujeto")
	public Sujeto_ensayo getSujeto() {
		return this.sujeto;
	}

	public void setSujeto(Sujeto_ensayo sujeto) {
		this.sujeto = sujeto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ms_especifico")
	public MomentoSeguimientoEspecifico_ensayo getMsEspecifico() {
		return this.msEspecifico;
	}

	public void setMsEspecifico(MomentoSeguimientoEspecifico_ensayo msEspecifico) {
		this.msEspecifico = msEspecifico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "crd_especifico")
	public CrdEspecifico_ensayo getCrdEspecifico() {
		return this.crdEspecifico;
	}

	public void setCrdEspecifico(CrdEspecifico_ensayo crdEspecifico) {
		this.crdEspecifico = crdEspecifico;
	}

	@Column(name = "tabla_estado")
	public String getTablaEstado() {
		return this.tablaEstado;
	}

	public void setTablaEstado(String tablaEstado) {
		if (tablaEstado != null)
			tablaEstado = tablaEstado.trim();
		this.tablaEstado = tablaEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cronograma")
	public Cronograma_ensayo getCronograma() {
		return this.cronograma;
	}

	public void setCronograma(Cronograma_ensayo cronograma) {
		this.cronograma = cronograma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ms_gnral")
	public MomentoSeguimientoGeneral_ensayo getMsGnral() {
		return this.msGnral;
	}

	public void setMsGnral(MomentoSeguimientoGeneral_ensayo msGnral) {
		this.msGnral = msGnral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "variable")
	public Variable_ensayo getVariable() {
		return this.variable;
	}

	public void setVariable(Variable_ensayo variable) {
		this.variable = variable;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}