package gehos.ensayo.entity;

// Generated 16-mar-2017 12:25:15 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * LogTipoAuditoria generated by hbm2java
 */
@Entity
@Table(name = "log_tipo_auditoria", schema = "ensayo")
public class LogTipoAuditoria_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String nombre;
	private Boolean eliminado;
	private Long cid;
	private Boolean habilitado;
	private Set<LogEventosAuditoria_ensayo> logEventosAuditorias = new HashSet<LogEventosAuditoria_ensayo>(
			0);

	public LogTipoAuditoria_ensayo() {
	}

	public LogTipoAuditoria_ensayo(long id) {
		this.id = id;
	}

	public LogTipoAuditoria_ensayo(long id, String nombre, Boolean eliminado,
			Long cid, Boolean habilitado,
			Set<LogEventosAuditoria_ensayo> logEventosAuditorias) {
		this.id = id;
		this.nombre = nombre;
		this.eliminado = eliminado;
		this.cid = cid;
		this.habilitado = habilitado;
		this.logEventosAuditorias = logEventosAuditorias;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "habilitado")
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logTipoAuditoria")
	public Set<LogEventosAuditoria_ensayo> getLogEventosAuditorias() {
		return this.logEventosAuditorias;
	}

	public void setLogEventosAuditorias(
			Set<LogEventosAuditoria_ensayo> logEventosAuditorias) {
		this.logEventosAuditorias = logEventosAuditorias;
	}

}
