package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MomentoSeguimientoGeneral generated by hbm2java
 */
@Entity
@Table(name = "momento_seguimiento_general", schema = "ensayo")
public class MomentoSeguimientoGeneral_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Cronograma_ensayo cronograma;
	private EstadoMomentoSeguimientoGeneral_ensayo estadoMomentoSeguimientoGeneral;
	private String nombre;	
	private String descripcion;
	private Boolean repetido;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private String dia;
	private Integer tiempoLlenado;
	private Long cid;
	private Boolean programado;
	private Boolean eliminado;
	private String etapa;
	private Usuario_ensayo usuario;
	private String diasEvaluacion;
	private String diasTratamiento;
	private String diasSeguimiento;

	private Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos = new HashSet<MomentoSeguimientoEspecifico_ensayo>(
			0);
	private Set<MomentoSeguimientoGeneralHojaCrd_ensayo> momentoSeguimientoGeneralHojaCrds = new HashSet<MomentoSeguimientoGeneralHojaCrd_ensayo>(
			0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);

	public MomentoSeguimientoGeneral_ensayo() {
	}

	public MomentoSeguimientoGeneral_ensayo(long id,
			Cronograma_ensayo cronograma) {
		this.id = id;
		this.cronograma = cronograma;
	}

	public MomentoSeguimientoGeneral_ensayo(
			long id,
			Cronograma_ensayo cronograma,
			EstadoMomentoSeguimientoGeneral_ensayo estadoMomentoSeguimientoGeneral,
			String nombre,
			String descripcion,
			Boolean repetido,
			Date fechaCreacion,
			Date fechaActualizacion,
			String dia,
			Integer tiempoLlenado,
			Long cid,
			Boolean programado,
			Boolean eliminado,
			String etapa,
			Usuario_ensayo usuario,
			String diasEvaluacion,
			String diasTratamiento,
			String diasSeguimiento,
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos,
			Set<MomentoSeguimientoGeneralHojaCrd_ensayo> momentoSeguimientoGeneralHojaCrds) {
		this.id = id;
		this.cronograma = cronograma;
		this.estadoMomentoSeguimientoGeneral = estadoMomentoSeguimientoGeneral;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.repetido = repetido;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.dia = dia;
		this.tiempoLlenado = tiempoLlenado;
		this.cid = cid;
		this.usuario = usuario;
		this.programado = programado;
		this.eliminado = eliminado;
		this.etapa = etapa;
		this.diasEvaluacion = diasEvaluacion;
		this.diasTratamiento = diasTratamiento;
		this.diasSeguimiento = diasSeguimiento;
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
		this.momentoSeguimientoGeneralHojaCrds = momentoSeguimientoGeneralHojaCrds;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cronograma", nullable = false)
	@NotNull
	public Cronograma_ensayo getCronograma() {
		return this.cronograma;
	}

	public void setCronograma(Cronograma_ensayo cronograma) {
		this.cronograma = cronograma;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msGnral")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_ms_general")
	public EstadoMomentoSeguimientoGeneral_ensayo getEstadoMomentoSeguimientoGeneral() {
		return this.estadoMomentoSeguimientoGeneral;
	}

	public void setEstadoMomentoSeguimientoGeneral(
			EstadoMomentoSeguimientoGeneral_ensayo estadoMomentoSeguimientoGeneral) {
		this.estadoMomentoSeguimientoGeneral = estadoMomentoSeguimientoGeneral;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "repetido")
	public Boolean getRepetido() {
		return this.repetido;
	}

	public void setRepetido(Boolean repetido) {
		this.repetido = repetido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "dia", length = 100000)
	@Length(max = 100000)
	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		if (dia != null)
			dia = dia.trim();
		this.dia = dia;
	}

	@Column(name = "tiempo_llenado")
	public Integer getTiempoLlenado() {
		return this.tiempoLlenado;
	}

	public void setTiempoLlenado(Integer tiempoLlenado) {
		this.tiempoLlenado = tiempoLlenado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "programado")
	public Boolean getProgramado() {
		return this.programado;
	}

	public void setProgramado(Boolean programado) {
		this.programado = programado;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "etapa")
	public String getEtapa() {
		return this.etapa;
	}

	public void setEtapa(String etapa) {
		if (etapa != null)
			etapa = etapa.trim();
		this.etapa = etapa;
	}

	@Column(name = "dias_evaluacion", length = 10000)
	@Length(max = 10000)
	public String getDiasEvaluacion() {
		return this.diasEvaluacion;
	}

	public void setDiasEvaluacion(String diasEvaluacion) {
		if (diasEvaluacion != null)
			diasEvaluacion = diasEvaluacion.trim();
		this.diasEvaluacion = diasEvaluacion;
	}

	@Column(name = "dias_tratamiento", length = 10000)
	@Length(max = 10000)
	public String getDiasTratamiento() {
		return this.diasTratamiento;
	}

	public void setDiasTratamiento(String diasTratamiento) {
		if (diasTratamiento != null)
			diasTratamiento = diasTratamiento.trim();
		this.diasTratamiento = diasTratamiento;
	}

	@Column(name = "dias_seguimiento", length = 10000)
	@Length(max = 10000)
	public String getDiasSeguimiento() {
		return this.diasSeguimiento;
	}

	public void setDiasSeguimiento(String diasSeguimiento) {
		if (diasSeguimiento != null)
			diasSeguimiento = diasSeguimiento.trim();
		this.diasSeguimiento = diasSeguimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "momentoSeguimientoGeneral")
	public Set<MomentoSeguimientoEspecifico_ensayo> getMomentoSeguimientoEspecificos() {
		return this.momentoSeguimientoEspecificos;
	}

	public void setMomentoSeguimientoEspecificos(
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos) {
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "momentoSeguimientoGeneral")
	public Set<MomentoSeguimientoGeneralHojaCrd_ensayo> getMomentoSeguimientoGeneralHojaCrds() {
		return this.momentoSeguimientoGeneralHojaCrds;
	}

	public void setMomentoSeguimientoGeneralHojaCrds(
			Set<MomentoSeguimientoGeneralHojaCrd_ensayo> momentoSeguimientoGeneralHojaCrds) {
		this.momentoSeguimientoGeneralHojaCrds = momentoSeguimientoGeneralHojaCrds;
	}

}
