package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * MomentoSeguimientoGeneralHojaCrd generated by hbm2java
 */
@Entity
@Table(name = "momento_seguimiento_general_hoja_crd", schema = "ensayo")
public class MomentoSeguimientoGeneralHojaCrd_ensayo implements
		java.io.Serializable {

	private long id;
	private Integer version;
	private HojaCrd_ensayo hojaCrd;
	private MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral;
	private Long cid;
	private Boolean eliminado;

	public MomentoSeguimientoGeneralHojaCrd_ensayo() {
	}

	public MomentoSeguimientoGeneralHojaCrd_ensayo(long id,
			HojaCrd_ensayo hojaCrd,
			MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral) {
		this.id = id;
		this.hojaCrd = hojaCrd;
		this.momentoSeguimientoGeneral = momentoSeguimientoGeneral;
	}

	public MomentoSeguimientoGeneralHojaCrd_ensayo(long id,
			HojaCrd_ensayo hojaCrd,
			MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral,
			Long cid, Boolean eliminado) {
		this.id = id;
		this.hojaCrd = hojaCrd;
		this.momentoSeguimientoGeneral = momentoSeguimientoGeneral;
		this.cid = cid;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_hoja_crd", nullable = false)
	@NotNull
	public HojaCrd_ensayo getHojaCrd() {
		return this.hojaCrd;
	}

	public void setHojaCrd(HojaCrd_ensayo hojaCrd) {
		this.hojaCrd = hojaCrd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_momento_seguimiento_general", nullable = false)
	@NotNull
	public MomentoSeguimientoGeneral_ensayo getMomentoSeguimientoGeneral() {
		return this.momentoSeguimientoGeneral;
	}

	public void setMomentoSeguimientoGeneral(
			MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral) {
		this.momentoSeguimientoGeneral = momentoSeguimientoGeneral;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
