package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.NotNull;

/**
 * MomentoSeguimientoEspecifico generated by hbm2java
 */
@Entity
@Table(name = "momento_seguimiento_especifico", schema = "ensayo")
public class MomentoSeguimientoEspecifico_ensayo implements
		java.io.Serializable {

	private long id;
	private Integer version;
	private MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral;
	private Sujeto_ensayo sujeto;
	private EstadoMomentoSeguimiento_ensayo estadoMomentoSeguimiento;
	private EstadoMonitoreo_ensayo estadoMonitoreo;
	private Date fechaInicio;
	private Usuario_ensayo usuario;
	private Date fechaFin;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Integer dia;
	private Long cid;
	private Boolean eliminado;
	private Set<CrdEspecifico_ensayo> crdEspecificos = new HashSet<CrdEspecifico_ensayo>(
			0);
	private Set<Causa_ensayo> causas = new HashSet<Causa_ensayo>(0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);

	public MomentoSeguimientoEspecifico_ensayo() {
	}

	public MomentoSeguimientoEspecifico_ensayo(long id,
			MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral,
			EstadoMomentoSeguimiento_ensayo estadoMomentoSeguimiento) {
		this.id = id;
		this.momentoSeguimientoGeneral = momentoSeguimientoGeneral;
		this.estadoMomentoSeguimiento = estadoMomentoSeguimiento;
	}

	public MomentoSeguimientoEspecifico_ensayo(long id,
			MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral,
			Sujeto_ensayo sujeto,
			EstadoMomentoSeguimiento_ensayo estadoMomentoSeguimiento,
			EstadoMonitoreo_ensayo estadoMonitoreo, Date fechaInicio,
			Date fechaFin, Date fechaCreacion, Date fechaActualizacion,
			Integer dia, Long cid, Usuario_ensayo usuario, Boolean eliminado,
			Set<CrdEspecifico_ensayo> crdEspecificos, Set<Causa_ensayo> causas) {
		this.id = id;
		this.momentoSeguimientoGeneral = momentoSeguimientoGeneral;
		this.sujeto = sujeto;
		this.estadoMomentoSeguimiento = estadoMomentoSeguimiento;
		this.estadoMonitoreo = estadoMonitoreo;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.dia = dia;
		this.cid = cid;
		this.usuario = usuario;
		this.eliminado = eliminado;
		this.crdEspecificos = crdEspecificos;
		this.causas = causas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msEspecifico")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_momento_seguimiento_g", nullable = false)
	@NotNull
	public MomentoSeguimientoGeneral_ensayo getMomentoSeguimientoGeneral() {
		return this.momentoSeguimientoGeneral;
	}

	public void setMomentoSeguimientoGeneral(
			MomentoSeguimientoGeneral_ensayo momentoSeguimientoGeneral) {
		this.momentoSeguimientoGeneral = momentoSeguimientoGeneral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sujeto")
	public Sujeto_ensayo getSujeto() {
		return this.sujeto;
	}

	public void setSujeto(Sujeto_ensayo sujeto) {
		this.sujeto = sujeto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_momento_s", nullable = false)
	@NotNull
	public EstadoMomentoSeguimiento_ensayo getEstadoMomentoSeguimiento() {
		return this.estadoMomentoSeguimiento;
	}

	public void setEstadoMomentoSeguimiento(
			EstadoMomentoSeguimiento_ensayo estadoMomentoSeguimiento) {
		this.estadoMomentoSeguimiento = estadoMomentoSeguimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_monitoreo")
	public EstadoMonitoreo_ensayo getEstadoMonitoreo() {
		return this.estadoMonitoreo;
	}

	public void setEstadoMonitoreo(EstadoMonitoreo_ensayo estadoMonitoreo) {
		this.estadoMonitoreo = estadoMonitoreo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "dia")
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "momentoSeguimientoEspecifico")
	public Set<CrdEspecifico_ensayo> getCrdEspecificos() {
		return this.crdEspecificos;
	}

	public void setCrdEspecificos(Set<CrdEspecifico_ensayo> crdEspecificos) {
		this.crdEspecificos = crdEspecificos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "momentoSeguimientoEspecifico")
	public Set<Causa_ensayo> getCausas() {
		return this.causas;
	}

	public void setCausas(Set<Causa_ensayo> causas) {
		this.causas = causas;
	}

}
