package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "municipio", schema = "nomencladores", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Municipio_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Estado_ensayo estado;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private Set<Entidad_ensayo> entidads = new HashSet<Entidad_ensayo>(0);

	public Municipio_ensayo() {
	}

	public Municipio_ensayo(long id, Estado_ensayo estado, String valor) {
		this.id = id;
		this.estado = estado;
		this.valor = valor;
	}

	public Municipio_ensayo(long id, Estado_ensayo estado, String valor,
			Boolean eliminado, Long cid, String codigo,
			Set<Entidad_ensayo> entidads) {
		this.id = id;
		this.estado = estado;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.entidads = entidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	@NotNull
	public Estado_ensayo getEstado() {
		return this.estado;
	}

	public void setEstado(Estado_ensayo estado) {
		this.estado = estado;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo", unique = true)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public Set<Entidad_ensayo> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_ensayo> entidads) {
		this.entidads = entidads;
	}

}
