package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * NomencladorValor generated by hbm2java
 */
@Entity
@Table(name = "nomenclador_valor", schema = "ensayo")
public class NomencladorValor_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Nomenclador_ensayo nomenclador;
	private Long cid;
	private Boolean eliminado;
	private String valor;
	private Integer valorCalculado;

	public NomencladorValor_ensayo() {
	}

	public NomencladorValor_ensayo(long id) {
		this.id = id;
	}

	public NomencladorValor_ensayo(long id, Nomenclador_ensayo nomenclador,
			Long cid, Boolean eliminado, String valor, Integer valorCalculado) {
		this.id = id;
		this.nomenclador = nomenclador;
		this.cid = cid;
		this.eliminado = eliminado;
		this.valor = valor;
		this.valorCalculado = valorCalculado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nomenclador")
	public Nomenclador_ensayo getNomenclador() {
		return this.nomenclador;
	}

	public void setNomenclador(Nomenclador_ensayo nomenclador) {
		this.nomenclador = nomenclador;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "valor")
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "valor_calculado")
	public Integer getValorCalculado() {
		return this.valorCalculado;
	}

	public void setValorCalculado(Integer valorCalculado) {
		this.valorCalculado = valorCalculado;
	}

}
