package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Nomenclador generated by hbm2java
 */
@Entity
@Table(name = "nomenclador", schema = "ensayo")
public class Nomenclador_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String nombre;
	private Long cid;
	private Boolean eliminado;
	private String descripcion;
	private String valorDefecto;
	private Set<Variable_ensayo> variables = new HashSet<Variable_ensayo>(0);
	private Set<NomencladorValor_ensayo> nomencladorValors = new HashSet<NomencladorValor_ensayo>(
			0);

	public Nomenclador_ensayo() {
	}

	public Nomenclador_ensayo(long id) {
		this.id = id;
	}

	public Nomenclador_ensayo(long id, String nombre, Long cid,
			Boolean eliminado, String descripcion, String valorDefecto,
			Set<Variable_ensayo> variables,
			Set<NomencladorValor_ensayo> nomencladorValors) {
		this.id = id;
		this.nombre = nombre;
		this.cid = cid;
		this.eliminado = eliminado;
		this.descripcion = descripcion;
		this.valorDefecto = valorDefecto;
		this.variables = variables;
		this.nomencladorValors = nomencladorValors;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "valor_defecto")
	public String getValorDefecto() {
		return this.valorDefecto;
	}

	public void setValorDefecto(String valorDefecto) {
		if (valorDefecto != null)
			valorDefecto = valorDefecto.trim();
		this.valorDefecto = valorDefecto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomenclador")
	public Set<Variable_ensayo> getVariables() {
		return this.variables;
	}

	public void setVariables(Set<Variable_ensayo> variables) {
		this.variables = variables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomenclador")
	public Set<NomencladorValor_ensayo> getNomencladorValors() {
		return this.nomencladorValors;
	}

	public void setNomencladorValors(
			Set<NomencladorValor_ensayo> nomencladorValors) {
		this.nomencladorValors = nomencladorValors;
	}

}
