package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * NotaGeneral generated by hbm2java
 */
@Entity
@Table(name = "nota_general", schema = "ensayo")
public class NotaGeneral_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private EstadoNota_ensayo estadoNota;
	private Entidad_ensayo entidad;
	private GrupoSujetos_ensayo grupoSujetos;
	private String descripcion;
	private String detallesNota;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private String tipoEntidad;
	private Long cid;
	private Boolean eliminado;
	private Usuario_ensayo usuario;	
	private NotaGeneral_ensayo notaGeneralPadre;
	private Set<NotaGeneral_ensayo> notaGeneralHijas = new HashSet<NotaGeneral_ensayo>(0);
	

	public NotaGeneral_ensayo() {
	}

	public NotaGeneral_ensayo(long id, Entidad_ensayo entidad) {
		this.id = id;
		this.entidad = entidad;
	}

	public NotaGeneral_ensayo(long id, EstadoNota_ensayo estadoNota,
			NotaGeneral_ensayo notaGeneralPadre, Set<NotaGeneral_ensayo> notaGeneralHijas,
			Entidad_ensayo entidad,  GrupoSujetos_ensayo grupoSujetos,String descripcion, String detallesNota,
			Date fechaCreacion, Date fechaActualizacion, String tipoEntidad,Usuario_ensayo usuario, 
			Long cid, Boolean eliminado, Set<HojaCrd_ensayo> hojaCrds) {
		this.id = id;
		this.estadoNota = estadoNota;
		this.entidad = entidad;
		this.grupoSujetos = grupoSujetos;
		this.descripcion = descripcion;
		this.detallesNota = detallesNota;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.tipoEntidad = tipoEntidad;
		this.cid = cid;
		this.eliminado = eliminado;
		this.notaGeneralPadre=notaGeneralPadre;
		this.notaGeneralHijas=notaGeneralHijas;
		this.usuario = usuario;		
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_notaG_padre")
	public NotaGeneral_ensayo getNotaGeneralPadre() {
		return this.notaGeneralPadre;
	}

	public void setNotaGeneralPadre(NotaGeneral_ensayo notaGPadre) {
		this.notaGeneralPadre = notaGPadre;
	}


	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "notaGeneralPadre")
	public Set<NotaGeneral_ensayo> getNotaGeneralHijas() {
		return this.notaGeneralHijas;
	}

	public void setNotaGeneralHijas(Set<NotaGeneral_ensayo> funs) {
		this.notaGeneralHijas = funs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado_nota")
	public EstadoNota_ensayo getEstadoNota() {
		return this.estadoNota;
	}

	public void setEstadoNota(EstadoNota_ensayo estadoNota) {
		this.estadoNota = estadoNota;
	} 
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad", nullable = false)
	@NotNull
	public Entidad_ensayo getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_ensayo entidad) {
		this.entidad = entidad;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "detalles_nota", length = 500)
	@Length(max = 500)
	public String getDetallesNota() {
		return this.detallesNota;
	}

	public void setDetallesNota(String detallesNota) {
		if (detallesNota != null)
			detallesNota = detallesNota.trim();
		this.detallesNota = detallesNota;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gruposujeto")
	public GrupoSujetos_ensayo getGrupoSujetos() {
		return this.grupoSujetos;
	}

	public void setGrupoSujetos(GrupoSujetos_ensayo grupoSujetos) {
		this.grupoSujetos = grupoSujetos;
	}
	
	@Column(name = "tipo_entidad", length = 13)
	public String getTipoEntidad() {
		return this.tipoEntidad;
	}

	public void setTipoEntidad(String tipoEntidad) {
		this.tipoEntidad = tipoEntidad;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}
}

