package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Nota generated by hbm2java
 */
@Entity
@Table(name = "nota", schema = "ensayo")
public class Nota_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private EstadoNota_ensayo estadoNota;
	private Variable_ensayo variable;
	private VariableDato_ensayo variableDato;
	private String descripcion;
	private String detallesNota;
	private CrdEspecifico_ensayo crdEspecifico;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private String tipoEntidad;
	private Long cid;
	private Boolean notaSitio;
	private Boolean eliminado;
	private Usuario_ensayo usuario;	
	private Nota_ensayo notaPadre;
	private Set<Nota_ensayo> notasHijas = new HashSet<Nota_ensayo>(0);

	public Nota_ensayo() {
	}

	public Nota_ensayo(long id) {
		this.id = id;
	}

	public Nota_ensayo(long id, EstadoNota_ensayo estadoNota,Nota_ensayo notaPadre,Set<Nota_ensayo> notasHijas,
			Variable_ensayo variable, String descripcion, String detallesNota, VariableDato_ensayo variableDato,
			Date fechaCreacion, Date fechaActualizacion, String tipoEntidad,Usuario_ensayo usuario, 
			Long cid, Boolean notaSitio, Boolean eliminado,
			CrdEspecifico_ensayo crdEspecifico) {
		this.id = id;
		this.estadoNota = estadoNota;
		this.variable = variable;
		this.descripcion = descripcion;
		this.detallesNota = detallesNota;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.tipoEntidad = tipoEntidad;
		this.cid = cid;
		this.notaSitio = notaSitio;
		this.eliminado = eliminado;
		this.variableDato = variableDato;
		this.crdEspecifico = crdEspecifico;
		this.notasHijas=notasHijas;
		this.notaPadre=notaPadre;
		this.usuario = usuario;		
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_nota_padre")
	public Nota_ensayo getNotaPadre() {
		return this.notaPadre;
	}

	public void setNotaPadre(Nota_ensayo notaGPadre) {
		this.notaPadre = notaGPadre;
	}

	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "notaPadre")
	public Set<Nota_ensayo> getNotasHijas() {
		return this.notasHijas;
	}

	public void setNotasHijas(Set<Nota_ensayo> funs) {
		this.notasHijas = funs;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}
	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_nota")
	public EstadoNota_ensayo getEstadoNota() {
		return this.estadoNota;
	}

	public void setEstadoNota(EstadoNota_ensayo estadoNota) {
		this.estadoNota = estadoNota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_crd_esp")
	public CrdEspecifico_ensayo getCrdEspecifico() {
		return this.crdEspecifico;
	}

	public void setCrdEspecifico(CrdEspecifico_ensayo crdEspecifico) {
		this.crdEspecifico = crdEspecifico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable")
	public Variable_ensayo getVariable() {
		return this.variable;
	}

	public void setVariable(Variable_ensayo variable) {
		this.variable = variable;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "detalles_nota", length = 500)
	@Length(max = 500)
	public String getDetallesNota() {
		return this.detallesNota;
	}

	public void setDetallesNota(String detallesNota) {
		if (detallesNota != null)
			detallesNota = detallesNota.trim();
		this.detallesNota = detallesNota;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "tipo_entidad")
	public String getTipoEntidad() {
		return this.tipoEntidad;
	}

	public void setTipoEntidad(String tipoEntidad) {
		if (tipoEntidad != null)
			tipoEntidad = tipoEntidad.trim();
		this.tipoEntidad = tipoEntidad;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "nota_sitio")
	public Boolean getNotaSitio() {
		return this.notaSitio;
	}

	public void setNotaSitio(Boolean notaSitio) {
		this.notaSitio = notaSitio;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable_dato")
	public VariableDato_ensayo getVariableDato() {
		return variableDato;
	}

	public void setVariableDato(VariableDato_ensayo variableDato) {
		this.variableDato = variableDato;
	}
	
}

