package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Nota generated by hbm2java
 */
@Entity
@Table(name = "notificacion", schema = "ensayo")
public class Notificacion_ensayo implements java.io.Serializable {

	private long id;
	private String tituloEst;
	private String codigoEst;
	private String identSujeto;
	private Integer edadSuj;
	private String tipoEdad;
	private String prodInv;
	private String sitioInv;
	private String investigador;
	private String promotor;
	private String fechaOcu;
	private String fechaUltA;
	private Boolean notifico;
	private String fechaNoti;
	private String descrEven;
	private String accTomada;
	private String nombreN;
	private String apellidosN;
	private String cargoN;
	private String direccN;
	private String telefonoN;
	private String opiInves;
	private Variable_ensayo variable;
	private VariableDato_ensayo variableDato;
	private CrdEspecifico_ensayo crdEspecifico;
	private Long idSujeto;
	private Long idEstudio;
	private Long idEntidad;
	private String viaNoti;
	private Usuario_ensayo usuario;
	
	
	public Notificacion_ensayo() {
	}

	public Notificacion_ensayo(long id) {
		this.id = id;
	}

	public Notificacion_ensayo(long id, String tituloEst, String codigoEst, String identSujeto, Integer edadSuj, String tipoEdad, String prodInv,
			String sitioInv,String investigador, String promotor, String fechaOcu, String fechaUltA, Boolean notifico, String fechaNoti,
			String descrEven, String accTomada, String nombreN, String apellidosN, String cargoN, String direccN, String telefonoN, String opiInves
			, VariableDato_ensayo variableDato, Variable_ensayo variable, CrdEspecifico_ensayo crdEspecifico, Long idSujeto, Long idEstudio, Long idEntidad, String viaNoti, Usuario_ensayo usuario) {
		this.id = id;
		this.tituloEst=tituloEst;
		this.codigoEst=codigoEst;
		this.identSujeto=identSujeto;
		this.edadSuj=edadSuj;
		this.tipoEdad=tipoEdad;
		this.prodInv=prodInv;
		this.sitioInv=sitioInv;
		this.investigador=investigador;
		this.promotor=promotor;
		this.fechaOcu=fechaOcu;
		this.fechaUltA=fechaUltA;
		this.notifico=notifico;
		this.fechaNoti=fechaNoti;
		this.descrEven=descrEven;
		this.accTomada=accTomada;
		this.nombreN=nombreN;
		this.apellidosN=apellidosN;
		this.cargoN=cargoN;
		this.direccN=direccN;
		this.telefonoN=telefonoN;
		this.opiInves=opiInves;	
		this.variableDato = variableDato;
		this.variable = variable;
		this.crdEspecifico=crdEspecifico;
		this.idSujeto=idSujeto;
		this.idEstudio=idEstudio;
		this.idEntidad=idEntidad;
		this.viaNoti=viaNoti;
		this.usuario = usuario;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	@Column(name = "titulo_estudio")
	public String gettituloEst() {
		return this.tituloEst;
	}

	public void settituloEst(String tituloEst) {
		if (tituloEst != null)
			tituloEst = tituloEst.trim();
		this.tituloEst = tituloEst;
	}
	
	@Column(name = "codigo_estudio")
	public String getcodigoEst() {
		return this.codigoEst;
	}

	public void setcodigoEst(String codigoEst) {
		if (codigoEst != null)
			codigoEst = codigoEst.trim();
		this.codigoEst = codigoEst;
	}
	
	@Column(name = "id_sujeto")
	public String getidentSujeto() {
		return this.identSujeto;
	}

	public void setidentSujeto(String identSujeto) {
		if (identSujeto != null)
			identSujeto = identSujeto.trim();
		this.identSujeto = identSujeto;
	}
	
	@Column(name = "edad_sujeto")
	public Integer getedadSuj() {
		return this.edadSuj;
	}

	public void setedadSuj(Integer edadSuj) {
		this.edadSuj = edadSuj;
	}
	
	@Column(name = "tipo_edad")
	public String getTipoEdad() {
		return this.tipoEdad;
	}

	public void setTipoEdad(String tipoEdad) {
		if(tipoEdad != null)
			tipoEdad = tipoEdad.trim();
		this.tipoEdad=tipoEdad;
	}
	
	@Column(name = "producto_inv")
	public String getprodInv() {
		return this.prodInv;
	}

	public void setprodInv(String prodInv) {
		if (prodInv != null)
			prodInv = prodInv.trim();
		this.prodInv = prodInv;
	}
	
	@Column(name = "sitio_inv")
	public String getsitioInv() {
		return this.sitioInv;
	}

	public void setsitioInv(String sitioInv) {
		if (sitioInv != null)
			sitioInv = sitioInv.trim();
		this.sitioInv = sitioInv;
	}
	
	@Column(name = "investigador")
	public String getinvestigador() {
		return this.investigador;
	}

	public void setinvestigador(String investigador) {
		if (investigador != null)
			investigador = investigador.trim();
		this.investigador = investigador;
	}
	
	@Column(name = "promotor")
	public String getpromotor() {
		return this.promotor;
	}

	public void setpromotor(String promotor) {
		if (promotor != null)
			promotor = promotor.trim();
		this.promotor = promotor;
	}
	
	
	@Column(name = "fecha_ocurrido")
	public String getfechaOcu() {
		return this.fechaOcu;
	}

	public void setfechaOcu(String fechaOcu) {
		this.fechaOcu = fechaOcu;
	}
	
	@Column(name = "fecha_ult_adm")
	public String getfechaUltA() {
		return this.fechaUltA;
	}

	public void setfechaUltA(String fechaUltA) {
		this.fechaUltA = fechaUltA;
	}
	
	@Column(name = "notifico")
	public Boolean getnotifico() {
		return this.notifico;
	}

	public void setnotifico(Boolean notifico) {
		this.notifico = notifico;
	}
	
	@Column(name = "fecha_notifico")
	public String getfecha_notifico() {
		return this.fechaNoti;
	}

	public void setfecha_notifico(String fechaNoti) {
		this.fechaNoti = fechaNoti;
	}

	@Column(name = "descripcion_evento", length = 1000)
	@Length(max = 1000)
	public String getdescrEven() {
		return this.descrEven;
	}

	public void setdescrEven(String descrEven) {
		if (descrEven != null)
			descrEven = descrEven.trim();
		this.descrEven = descrEven;
	}

	@Column(name = "accion_tomada", length = 1000)
	@Length(max = 1000)
	public String getaccTomada() {
		return this.accTomada;
	}

	public void setaccTomada(String accTomada) {
		if (accTomada != null)
			accTomada = accTomada.trim();
		this.accTomada = accTomada;
	}
	
	@Column(name = "nombre_n")
	public String getnombreN() {
		return this.nombreN;
	}

	public void setnombreN(String nombreN) {
		if (nombreN != null)
			nombreN = nombreN.trim();
		this.nombreN = nombreN;
	}
	
	@Column(name = "apellidos_n")
	public String getapellidosN() {
		return this.apellidosN;
	}

	public void setapellidosN(String apellidosN) {
		if (apellidosN != null)
			apellidosN = apellidosN.trim();
		this.apellidosN = apellidosN;
	}
	
	@Column(name = "cargo_n")
	public String getcargoN() {
		return this.cargoN;
	}

	public void setcargoN(String cargoN) {
		if (cargoN != null)
			cargoN = cargoN.trim();
		this.cargoN = cargoN;
	}
	
	@Column(name = "direccion_n", length = 500)
	@Length(max = 500)
	public String getdireccN() {
		return this.direccN;
	}

	public void setdireccN(String direccN) {
		if (direccN != null)
			direccN = direccN.trim();
		this.direccN = direccN;
	}
	
	@Column(name = "telefono_n")
	public String gettelefonoN() {
		return this.telefonoN;
	}

	public void settelefonoN(String telefonoN) {
		if (telefonoN != null)
			telefonoN = telefonoN.trim();
		this.telefonoN = telefonoN;
	}
	
	@Column(name = "opinion_investigador", length = 1000)
	@Length(max = 1000)
	public String getopiInves() {
		return this.opiInves;
	}

	public void setopiInves(String opiInves) {
		if (opiInves != null)
			opiInves = opiInves.trim();
		this.opiInves = opiInves;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable_dato")
	public VariableDato_ensayo getVariableDato() {
		return variableDato;
	}

	public void setVariableDato(VariableDato_ensayo variableDato) {
		this.variableDato = variableDato;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable")
	public Variable_ensayo getVariable() {
		return variable;
	}

	public void setVariable(Variable_ensayo variable) {
		this.variable = variable;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_crd_especif")
	public CrdEspecifico_ensayo getCrdEspecifico() {
		return crdEspecifico;
	}

	public void setCrdEspecifico(CrdEspecifico_ensayo crdEspecifico) {
		this.crdEspecifico = crdEspecifico;
	}
	
	@Column(name = "id_sujeto1")
	public Long getIdSujeto() {
		return this.idSujeto;
	}

	public void setIdSujeto(Long idSujeto) {
		this.idSujeto = idSujeto;
	}

	@Column(name = "id_estudio")
	public Long getIdEstudio() {
		return this.idEstudio;
	}

	public void setIdEstudio(Long idEstudio) {
		this.idEstudio = idEstudio;
	}

	@Column(name = "id_entidad")
	public Long getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Column(name = "via_notifico")
	public String getViaNoti() {
		return viaNoti;
	}

	public void setViaNoti(String viaNoti) {
		if(viaNoti !=null)
			viaNoti=viaNoti.trim();
		this.viaNoti = viaNoti;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}
	
}

