package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Parametros generated by hbm2java
 */
@Entity
@Table(name = "parametros", schema = "ensayo")
public class Parametros_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private Long cid;
	private Boolean eliminado;
	private String nombre;
	private String codigo;

	public Parametros_ensayo() {
	}

	public Parametros_ensayo(long id) {
		this.id = id;
	}

	public Parametros_ensayo(long id, Long cid, Boolean eliminado,
			String nombre, String codigo) {
		this.id = id;
		this.cid = cid;
		this.eliminado = eliminado;
		this.nombre = nombre;
		this.codigo = codigo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

}
