package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PresentacionFormulario generated by hbm2java
 */
@Entity
@Table(name = "presentacion_formulario", schema = "ensayo")
public class PresentacionFormulario_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private TipoDato_ensayo tipoDato;
	private String nombre;
	private String descripcion;
	private Long cid;
	private Boolean eliminado;
	private Set<Variable_ensayo> variables = new HashSet<Variable_ensayo>(0);

	public PresentacionFormulario_ensayo() {
	}

	public PresentacionFormulario_ensayo(long id) {
		this.id = id;
	}

	public PresentacionFormulario_ensayo(long id, TipoDato_ensayo tipoDato,
			String nombre, String descripcion, Long cid, Boolean eliminado,
			Set<Variable_ensayo> variables) {
		this.id = id;
		this.tipoDato = tipoDato;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.cid = cid;
		this.eliminado = eliminado;
		this.variables = variables;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_dato")
	public TipoDato_ensayo getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(TipoDato_ensayo tipoDato) {
		this.tipoDato = tipoDato;
	}

	@Column(name = "nombre", length = 500)
	@Length(max = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	@Length(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "presentacionFormulario")
	public Set<Variable_ensayo> getVariables() {
		return this.variables;
	}

	public void setVariables(Set<Variable_ensayo> variables) {
		this.variables = variables;
	}

}
