package gehos.ensayo.entity;

// Generated 06-mar-2017 16:39:14 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * Causa generated by hbm2java
 */
@Entity
@Table(name = "reporte_cumplimiento_datos_estudios", schema = "ensayo")
public class ReCumplimientoEstudios_ensayo implements java.io.Serializable {

	private long id;
	private String nombreEstudio;
	private int cantSujetos;
	private int planTotalMSProgramados;
	private int realFirmados;
	private int faltanFirmar;
	private float porcientoCumplimiento;
	private Date fechaActualizacion;

	public ReCumplimientoEstudios_ensayo() {
	}

	public ReCumplimientoEstudios_ensayo(long id) {
		this.id = id;
	}

	public ReCumplimientoEstudios_ensayo(long id, String nombreEstudio,
			int cantSujetos, int planTotalMSProgramados, int realFirmados,
			int faltanFirmar, float porcientoCumplimiento,
			Date fechaActualizacion) {
		super();
		this.id = id;
		this.nombreEstudio = nombreEstudio;
		this.cantSujetos = cantSujetos;
		this.planTotalMSProgramados = planTotalMSProgramados;
		this.realFirmados = realFirmados;
		this.faltanFirmar = faltanFirmar;
		this.porcientoCumplimiento = porcientoCumplimiento;
		this.fechaActualizacion = fechaActualizacion;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	@Column(name = "nombre_estudio")
	public String getNombreEstudio() {
		return nombreEstudio;
	}

	public void setNombreEstudio(String nombreEstudio) {
		this.nombreEstudio = nombreEstudio;
	}

	@Column(name = "cant_sujetos_estudio")
	public int getCantSujetos() {
		return cantSujetos;
	}

	public void setCantSujetos(int cantSujetos) {
		this.cantSujetos = cantSujetos;
	}

	@Column(name = "plan_total_ms_programados")
	public int getPlanTotalMSProgramados() {
		return planTotalMSProgramados;
	}

	public void setPlanTotalMSProgramados(int planTotalMSProgramados) {
		this.planTotalMSProgramados = planTotalMSProgramados;
	}

	@Column(name = "real_firmados")
	public int getRealFirmados() {
		return realFirmados;
	}

	public void setRealFirmados(int realFirmados) {
		this.realFirmados = realFirmados;
	}

	@Column(name = "faltan_por_firmar")
	public int getFaltanFirmar() {
		return faltanFirmar;
	}

	public void setFaltanFirmar(int faltanFirmar) {
		this.faltanFirmar = faltanFirmar;
	}

	@Column(name = "porciento_cumplimiento")
	public float getPorcientoCumplimiento() {
		return porcientoCumplimiento;
	}

	public void setPorcientoCumplimiento(float porcientoCumplimiento) {
		this.porcientoCumplimiento = porcientoCumplimiento;
	}

	@Column(name = "fecha_actualizacion")
	public Date getFechaActualizacion() {
		return fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
