package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ReDiagnostico generated by hbm2java
 */
@Entity
@Table(name = "re_diagnostico", schema = "ensayo")
public class ReDiagnostico_ensayo implements java.io.Serializable {

	private long id;
	private ReEnfermedades_ensayo reEnfermedades;
	private ReReporteexpedito_ensayo reReporteexpedito;
	private String otra;

	public ReDiagnostico_ensayo() {
	}

	public ReDiagnostico_ensayo(long id, ReEnfermedades_ensayo reEnfermedades,
			ReReporteexpedito_ensayo reReporteexpedito) {
		this.id = id;
		this.reEnfermedades = reEnfermedades;
		this.reReporteexpedito = reReporteexpedito;
	}

	public ReDiagnostico_ensayo(long id, ReEnfermedades_ensayo reEnfermedades,
			ReReporteexpedito_ensayo reReporteexpedito, String otra) {
		this.id = id;
		this.reEnfermedades = reEnfermedades;
		this.reReporteexpedito = reReporteexpedito;
		this.otra = otra;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_enfermedades", nullable = false)
	@NotNull
	public ReEnfermedades_ensayo getReEnfermedades() {
		return this.reEnfermedades;
	}

	public void setReEnfermedades(ReEnfermedades_ensayo reEnfermedades) {
		this.reEnfermedades = reEnfermedades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_reporteexpedito", nullable = false)
	@NotNull
	public ReReporteexpedito_ensayo getReReporteexpedito() {
		return this.reReporteexpedito;
	}

	public void setReReporteexpedito(ReReporteexpedito_ensayo reReporteexpedito) {
		this.reReporteexpedito = reReporteexpedito;
	}

	@Column(name = "otra")
	public String getOtra() {
		return this.otra;
	}

	public void setOtra(String otra) {
		if (otra != null)
			otra = otra.trim();
		this.otra = otra;
	}

}
