package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ReMedicacionconcomitante generated by hbm2java
 */
@Entity
@Table(name = "re_enfermedadesinter", schema = "ensayo")
public class ReEnfermedadesinter_ensayo implements java.io.Serializable {

	private long id;
	private ReReporteexpedito_ensayo reReporteexpedito;
	private ReMedicacion_ensayo reMedicacion;

	public ReEnfermedadesinter_ensayo() {
	}

	public ReEnfermedadesinter_ensayo(long id,
			ReReporteexpedito_ensayo reReporteexpedito,
			ReMedicacion_ensayo reMedicacion) {
		this.id = id;
		this.reReporteexpedito = reReporteexpedito;
		this.reMedicacion = reMedicacion;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_reporteexpedito", nullable = false)
	@NotNull
	public ReReporteexpedito_ensayo getReReporteexpedito() {
		return this.reReporteexpedito;
	}

	public void setReReporteexpedito(ReReporteexpedito_ensayo reReporteexpedito) {
		this.reReporteexpedito = reReporteexpedito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_medicacion", nullable = false)
	@NotNull
	public ReMedicacion_ensayo getReMedicacion() {
		return this.reMedicacion;
	}

	public void setReMedicacion(ReMedicacion_ensayo reMedicacion) {
		this.reMedicacion = reMedicacion;
	}

}
