package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ReEnfermedades generated by hbm2java
 */
@Entity
@Table(name = "re_enfermedades", schema = "ensayo")
public class ReEnfermedades_ensayo implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Integer codigo;
	private Set<ReDiagnostico_ensayo> reDiagnosticos = new HashSet<ReDiagnostico_ensayo>(
			0);

	public ReEnfermedades_ensayo() {
	}

	public ReEnfermedades_ensayo(long id) {
		this.id = id;
	}

	public ReEnfermedades_ensayo(long id, String descripcion, Integer codigo,
			Set<ReDiagnostico_ensayo> reDiagnosticos) {
		this.id = id;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.reDiagnosticos = reDiagnosticos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "codigo")
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reEnfermedades")
	public Set<ReDiagnostico_ensayo> getReDiagnosticos() {
		return this.reDiagnosticos;
	}

	public void setReDiagnosticos(Set<ReDiagnostico_ensayo> reDiagnosticos) {
		this.reDiagnosticos = reDiagnosticos;
	}

}
