package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Regla generated by hbm2java
 */
@Entity
@Table(name = "regla", schema = "ensayo")
public class Regla_ensayo implements java.io.Serializable {

	private long id;
	private Variable_ensayo variable;
	private EstadoRegla_ensayo estadoRegla;
	private Usuario_ensayo usuario;
	private String tipoRegla;
	private String nombre;
	private String opciones;
	private String mensajeRegla;
	private String execPhase;
	private String execEvent;

	public Regla_ensayo() {
	}

	public Regla_ensayo(long id, Variable_ensayo variable, String tipoRegla) {
		this.id = id;
		this.variable = variable;
		this.tipoRegla = tipoRegla;
	}

	public Regla_ensayo(long id, Variable_ensayo variable, Usuario_ensayo usuario,
			EstadoRegla_ensayo estadoRegla, String tipoRegla, String opciones,
			String mensajeRegla) {
		this.id = id;
		this.variable = variable;
		this.estadoRegla = estadoRegla;
		this.tipoRegla = tipoRegla;
		this.opciones = opciones;
		this.mensajeRegla = mensajeRegla;
		this.usuario = usuario;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable", nullable = false)
	@NotNull
	public Variable_ensayo getVariable() {
		return this.variable;
	}

	public void setVariable(Variable_ensayo variable) {
		this.variable = variable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_regla")
	public EstadoRegla_ensayo getEstadoRegla() {
		return this.estadoRegla;
	}

	public void setEstadoRegla(EstadoRegla_ensayo estadoRegla) {
		this.estadoRegla = estadoRegla;
	}

	@Column(name = "tipo_regla", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getTipoRegla() {
		return this.tipoRegla;
	}

	public void setTipoRegla(String tipoRegla) {
		if (tipoRegla != null)
			tipoRegla = tipoRegla.trim();
		this.tipoRegla = tipoRegla;
	}

	@Column(name = "opciones")
	public String getOpciones() {
		return this.opciones;
	}

	public void setOpciones(String opciones) {
		if (opciones != null)
			opciones = opciones.trim();
		this.opciones = opciones;
	}

	@Column(name = "mensaje_regla")
	public String getMensajeRegla() {
		return this.mensajeRegla;
	}

	public void setMensajeRegla(String mensajeRegla) {
		if (mensajeRegla != null)
			mensajeRegla = mensajeRegla.trim();
		this.mensajeRegla = mensajeRegla;
	}

	@Column(name = "exec_phase")
	public String getExecPhase() {
		return execPhase;
	}

	public void setExecPhase(String execPhase) {
		this.execPhase = execPhase;
	}

	@Column(name = "exec_event")
	public String getExecEvent() {
		return execEvent;
	}

	public void setExecEvent(String execEvent) {
		this.execEvent = execEvent;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

}
