package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * ReHistoriarelevante generated by hbm2java
 */
@Entity
@Table(name = "re_historiarelevante", schema = "ensayo")
public class ReHistoriarelevante_ensayo implements java.io.Serializable {

	private long id;
	private ReReporteexpedito_ensayo reReporteexpedito;
	private String otra;
	private long idReEnfermedades;
	//private Boolean eliminado;

	public ReHistoriarelevante_ensayo() {
	}

	public ReHistoriarelevante_ensayo(long id,
			ReReporteexpedito_ensayo reReporteexpedito, long idReEnfermedades) {
		this.id = id;
		this.reReporteexpedito = reReporteexpedito;
		this.idReEnfermedades = idReEnfermedades;
	}

	public ReHistoriarelevante_ensayo(long id,
			ReReporteexpedito_ensayo reReporteexpedito, String otra,
			long idReEnfermedades) {
		this.id = id;
		this.reReporteexpedito = reReporteexpedito;
		this.otra = otra;
		this.idReEnfermedades = idReEnfermedades;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_reporteexpedito", nullable = false)
	@NotNull
	public ReReporteexpedito_ensayo getReReporteexpedito() {
		return this.reReporteexpedito;
	}

	public void setReReporteexpedito(ReReporteexpedito_ensayo reReporteexpedito) {
		this.reReporteexpedito = reReporteexpedito;
	}

	@Column(name = "otra")
	public String getOtra() {
		return this.otra;
	}

	public void setOtra(String otra) {
		if (otra != null)
			otra = otra.trim();
		this.otra = otra;
	}

	@Column(name = "id_re_enfermedades", nullable = false)
	@NotNull
	public long getIdReEnfermedades() {
		return this.idReEnfermedades;
	}

	public void setIdReEnfermedades(long idReEnfermedades) {
		this.idReEnfermedades = idReEnfermedades;
	}

}
