package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * ReIntensidad generated by hbm2java
 */
@Entity
@Table(name = "re_intensidad", schema = "ensayo")
public class ReIntensidad_ensayo implements java.io.Serializable {

	private long id;
	private String valor;
	private Integer codigo;
	private Set<ReReporteexpedito_ensayo> reReporteexpeditos = new HashSet<ReReporteexpedito_ensayo>(
			0);

	public ReIntensidad_ensayo() {
	}

	public ReIntensidad_ensayo(long id) {
		this.id = id;
	}

	

	public ReIntensidad_ensayo(long id, String valor, Integer codigo,
			Set<ReReporteexpedito_ensayo> reReporteexpeditos) {
		super();
		this.id = id;
		this.valor = valor;
		this.codigo = codigo;
		this.reReporteexpeditos = reReporteexpeditos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "valor")
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reIntensidad")
	public Set<ReReporteexpedito_ensayo> getReReporteexpeditos() {
		return this.reReporteexpeditos;
	}
	
	@Column(name = "codigo")	
	public Integer getCodigo() {
		return codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public void setReReporteexpeditos(
			Set<ReReporteexpedito_ensayo> reReporteexpeditos) {
		this.reReporteexpeditos = reReporteexpeditos;
	}

}
