package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * ReMedicacion generated by hbm2java
 */
@Entity
@Table(name = "re_medicacion", schema = "ensayo")
public class ReMedicacion_ensayo implements java.io.Serializable {

	private long id;
	private ReViasadmi_ensayo reViasadmi;
	private String medicamento;
	private String dosisxdia;
	private String frecuencia;
	private String fechaAdm;
	private Boolean eliminado;
	private String horaAdm;
	private String presentacion;
	private String lote;
	private Set<ReMedicacionconcomitante_ensayo> reMedicacionconcomitantes = new HashSet<ReMedicacionconcomitante_ensayo>(
			0);
	private Set<ReMedicacionreciente_ensayo> reMedicacionrecientes = new HashSet<ReMedicacionreciente_ensayo>(
			0);

	public ReMedicacion_ensayo() {
	}

	public ReMedicacion_ensayo(long id) {
		this.id = id;
	}

	public ReMedicacion_ensayo(long id, ReViasadmi_ensayo reViasadmi,
			String medicamento, String dosisxdia, String frecuencia,
			String fechaAdm, Boolean eliminado, String horaAdm,
			String presentacion, String lote,
			Set<ReMedicacionconcomitante_ensayo> reMedicacionconcomitantes,
			Set<ReMedicacionreciente_ensayo> reMedicacionrecientes) {
		super();
		this.id = id;
		this.reViasadmi = reViasadmi;
		this.medicamento = medicamento;
		this.dosisxdia = dosisxdia;
		this.frecuencia = frecuencia;
		this.fechaAdm = fechaAdm;
		this.eliminado = eliminado;
		this.horaAdm = horaAdm;
		this.presentacion = presentacion;
		this.lote = lote;
		this.reMedicacionconcomitantes = reMedicacionconcomitantes;
		this.reMedicacionrecientes = reMedicacionrecientes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_viasadmi")
	public ReViasadmi_ensayo getReViasadmi() {
		return this.reViasadmi;
	}

	public void setReViasadmi(ReViasadmi_ensayo reViasadmi) {
		this.reViasadmi = reViasadmi;
	}

	@Column(name = "medicamento")
	public String getMedicamento() {
		return this.medicamento;
	}

	public void setMedicamento(String medicamento) {
		if (medicamento != null)
			medicamento = medicamento.trim();
		this.medicamento = medicamento;
	}
	
	@Column(name = "fechaadministracion")
	public String getFechaAdm() {
		return fechaAdm;
	}

	public void setFechaAdm(String fechaAdm) {
		this.fechaAdm = fechaAdm;
	}
	
	@Column(name = "dosisxdia", precision = 8, scale = 8)
	public String getDosisxdia() {
		return this.dosisxdia;
	}
	public void setDosisxdia(String dosisxdia) {
		this.dosisxdia = dosisxdia;
	}

	@Column(name = "frecuencia")
	public String getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(String frecuencia) {
		if (frecuencia != null)
			frecuencia = frecuencia.trim();
		this.frecuencia = frecuencia;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	

	@Column(name = "horaadministracion")
	public String getHoraAdm() {
		return horaAdm;
	}

	public void setHoraAdm(String horaAdm) {
		this.horaAdm = horaAdm;
	}

	@Column(name = "presentacion")
	public String getPresentacion() {
		return presentacion;
	}

	public void setPresentacion(String presentacion) {
		this.presentacion = presentacion;
	}

	@Column(name = "lote")
	public String getLote() {
		return lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reMedicacion")
	public Set<ReMedicacionconcomitante_ensayo> getReMedicacionconcomitantes() {
		return this.reMedicacionconcomitantes;
	}

	public void setReMedicacionconcomitantes(
			Set<ReMedicacionconcomitante_ensayo> reMedicacionconcomitantes) {
		this.reMedicacionconcomitantes = reMedicacionconcomitantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reMedicacion")
	public Set<ReMedicacionreciente_ensayo> getReMedicacionrecientes() {
		return this.reMedicacionrecientes;
	}

	public void setReMedicacionrecientes(
			Set<ReMedicacionreciente_ensayo> reMedicacionrecientes) {
		this.reMedicacionrecientes = reMedicacionrecientes;
	}

}
