package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ReRespuesta generated by hbm2java
 */
@Entity
@Table(name = "re_respuesta", schema = "ensayo")
public class ReRespuesta_ensayo implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Integer codigo;
	private Set<ReReporteexpedito_ensayo> reReporteexpeditosForModificacionintensidad = new HashSet<ReReporteexpedito_ensayo>(
			0);
	private Set<ReReporteexpedito_ensayo> reReporteexpeditosForReaparicionea = new HashSet<ReReporteexpedito_ensayo>(
			0);

	public ReRespuesta_ensayo() {
	}

	public ReRespuesta_ensayo(long id) {
		this.id = id;
	}

	public ReRespuesta_ensayo(
			long id,
			String descripcion,
			Integer codigo,
			Set<ReReporteexpedito_ensayo> reReporteexpeditosForModificacionintensidad,
			Set<ReReporteexpedito_ensayo> reReporteexpeditosForReaparicionea) {
		this.id = id;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.reReporteexpeditosForModificacionintensidad = reReporteexpeditosForModificacionintensidad;
		this.reReporteexpeditosForReaparicionea = reReporteexpeditosForReaparicionea;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "codigo")
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reRespuestaByModificacionintensidad")
	public Set<ReReporteexpedito_ensayo> getReReporteexpeditosForModificacionintensidad() {
		return this.reReporteexpeditosForModificacionintensidad;
	}

	public void setReReporteexpeditosForModificacionintensidad(
			Set<ReReporteexpedito_ensayo> reReporteexpeditosForModificacionintensidad) {
		this.reReporteexpeditosForModificacionintensidad = reReporteexpeditosForModificacionintensidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reRespuestaByReaparicionea")
	public Set<ReReporteexpedito_ensayo> getReReporteexpeditosForReaparicionea() {
		return this.reReporteexpeditosForReaparicionea;
	}

	public void setReReporteexpeditosForReaparicionea(
			Set<ReReporteexpedito_ensayo> reReporteexpeditosForReaparicionea) {
		this.reReporteexpeditosForReaparicionea = reReporteexpeditosForReaparicionea;
	}

}
