package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * ReReporteexpedito generated by hbm2java
 */
@Entity
@Table(name = "re_reporteexpedito", schema = "ensayo")
public class ReReporteexpedito_ensayo implements java.io.Serializable {

	private long id;
	private ReConsecuenciaspaciente_ensayo reConsecuenciaspaciente;
	private ReRespuesta_ensayo reRespuestaByReaparicionea;
	private ReIntensidad_ensayo reIntensidad;
	private ReRespuesta_ensayo reRespuestaByModificacionintensidad;
	private ReViasadmi_ensayo reViasadmi;
	private ReCrealizadaeas_ensayo reCrealizadaeas;
	private ReRecausalpea_ensayo reRecausalpea;
	private ReResultadofinal_ensayo reResultadofinal;
	private Boolean informeinicial;
	private String promotor;
	private String investigador;
	private String fechaingreso;
	private String fechaalta;
	private String fechaaltaprol;
	private String especifiqueacont;
	private String especifiqueotros;
	private String nombrereporta;
	private String direccion;
	private String otraraza;
	private String profesion;
	private String fechareporteA;
	private String fechareporteB;
	private String fechareporteC;
	private String fechareporteD;
	private String fechareportepromotor;
	private String horareportepromotor;
	private String nombreinvestigador;
	private String fechareportee;
	private Float talla;
	private String fechanacimiento;
	private String fechaCECMEDA;
	private String fechaCECMEDB;
	private String fechaCECMEDC;
	private String fechaCECMEDD;
	private String eventoadverso;
	private String dondeocurrio;
	private String otrolugar;
	private String acontecimiento;
	private String descripcionea;
	private String productoinvestigado;
	private String causalidad;
	private String fuente;
	private String otrafuente;
	private String lote;
	private String fechacaducidad;
	private String iniciotratamiento;
	private Integer dosisrecibida;
	private String ultimadosis;
	private String dosisadministrada;
	private String presentacion;
	private Boolean abndonoelsujeto;
	private String tiempoaparicion;
	private String descripcionsecuela;
	private Integer diashospitalizacion;
	private Boolean autopsia;
	private Boolean terminotratamiento;
	private Boolean tratamientoquirurgico;
	private String indicacion;
	private String especifiquetrat;
	private String descripciongeneral;
	private Boolean datoslaboratorio;
	private Boolean copiabiopsia;

	private Boolean copiaautopsia;
	private String otroscomentarios;
	private String fechainicio;
	private String horainicio;
	private String fechafinalizacion;
	private String horafinalizacion;
	private String otroshistoria;
	private Long idSujeto;
	private Long idEstudio;
	private Long idEntidad;
	private Boolean ctc;
	private Boolean oms;
	private Integer ctcVersion;
	private String secuela;
	private String edad;
	private String sexo;
	private Float peso;
	private String raza;
	private String no_dosis;
	private Variable_ensayo variable;
	private VariableDato_ensayo variableDato;
	private CrdEspecifico_ensayo crdEspecifico;
	private Usuario_ensayo usuario;

	private Set<ReHistoriarelevante_ensayo> reHistoriarelevantes = new HashSet<ReHistoriarelevante_ensayo>(
			0);
	private Set<ReDiagnostico_ensayo> reDiagnosticos = new HashSet<ReDiagnostico_ensayo>(
			0);
	private Set<ReMedicacionreciente_ensayo> reMedicacionrecientes = new HashSet<ReMedicacionreciente_ensayo>(
			0);
	private Set<ReMedicacionconcomitante_ensayo> reMedicacionconcomitantes = new HashSet<ReMedicacionconcomitante_ensayo>(
			0);
	private Set<ReTrazabilidadreporte_ensayo> reTrazabilidadreportes = new HashSet<ReTrazabilidadreporte_ensayo>(
			0);
	private Set<ReInfoproducto_ensayo> reInfoproducto = new HashSet<ReInfoproducto_ensayo>(
			0);
	private Set<ReEnfermedadesinter_ensayo> reEnfermedadesinter = new HashSet<ReEnfermedadesinter_ensayo>(
			0);

	public ReReporteexpedito_ensayo() {
	}

	public ReReporteexpedito_ensayo(long id,
			ReResultadofinal_ensayo reResultadofinal) {
		this.id = id;
		this.reResultadofinal = reResultadofinal;
	}

	

	

	public ReReporteexpedito_ensayo(long id,
			ReConsecuenciaspaciente_ensayo reConsecuenciaspaciente,
			ReRespuesta_ensayo reRespuestaByReaparicionea,
			ReIntensidad_ensayo reIntensidad,
			ReRespuesta_ensayo reRespuestaByModificacionintensidad,
			ReViasadmi_ensayo reViasadmi,
			ReCrealizadaeas_ensayo reCrealizadaeas,
			ReRecausalpea_ensayo reRecausalpea,
			ReResultadofinal_ensayo reResultadofinal, Boolean informeinicial,
			String promotor, String investigador, String fechaingreso,
			String fechaalta, String fechaaltaprol, String especifiqueacont,
			String especifiqueotros, String nombrereporta, String direccion,
			String otraraza, String profesion, String fechareporteA,
			String fechareporteB, String fechareporteC, String fechareporteD,
			String fechareportepromotor, String horareportepromotor,
			String nombreinvestigador, String fechareportee, Float talla,
			String fechanacimiento, String fechaCECMEDA, String fechaCECMEDB,
			String fechaCECMEDC, String fechaCECMEDD, String eventoadverso,
			String dondeocurrio, String otrolugar, String acontecimiento,
			String descripcionea, String productoinvestigado,
			String causalidad, String fuente, String otrafuente, String lote,
			String fechacaducidad, String iniciotratamiento,
			Integer dosisrecibida, String ultimadosis,
			String dosisadministrada, String presentacion,
			Boolean abndonoelsujeto, String tiempoaparicion,
			String descripcionsecuela, Integer diashospitalizacion,
			Boolean autopsia, Boolean terminotratamiento,
			Boolean tratamientoquirurgico, String indicacion,
			String especifiquetrat, String descripciongeneral,
			Boolean datoslaboratorio, Boolean copiabiopsia,
			Boolean copiaautopsia, String otroscomentarios, String fechainicio,
			String horainicio, String fechafinalizacion,
			String horafinalizacion, String otroshistoria, Long idSujeto,
			Long idEstudio, Long idEntidad, Boolean ctc, Boolean oms,
			Integer ctcVersion, String secuela, String edad, String sexo,
			Float peso, String raza, String no_dosis, Variable_ensayo variable,
			VariableDato_ensayo variableDato,
			CrdEspecifico_ensayo crdEspecifico, Usuario_ensayo usuario,
			Set<ReHistoriarelevante_ensayo> reHistoriarelevantes,
			Set<ReDiagnostico_ensayo> reDiagnosticos,
			Set<ReMedicacionreciente_ensayo> reMedicacionrecientes,
			Set<ReMedicacionconcomitante_ensayo> reMedicacionconcomitantes,
			Set<ReTrazabilidadreporte_ensayo> reTrazabilidadreportes,
			Set<ReInfoproducto_ensayo> reInfoproducto,
			Set<ReEnfermedadesinter_ensayo> reEnfermedadesinter) {
		super();
		this.id = id;
		this.reConsecuenciaspaciente = reConsecuenciaspaciente;
		this.reRespuestaByReaparicionea = reRespuestaByReaparicionea;
		this.reIntensidad = reIntensidad;
		this.reRespuestaByModificacionintensidad = reRespuestaByModificacionintensidad;
		this.reViasadmi = reViasadmi;
		this.reCrealizadaeas = reCrealizadaeas;
		this.reRecausalpea = reRecausalpea;
		this.reResultadofinal = reResultadofinal;
		this.informeinicial = informeinicial;
		this.promotor = promotor;
		this.investigador = investigador;
		this.fechaingreso = fechaingreso;
		this.fechaalta = fechaalta;
		this.fechaaltaprol = fechaaltaprol;
		this.especifiqueacont = especifiqueacont;
		this.especifiqueotros = especifiqueotros;
		this.nombrereporta = nombrereporta;
		this.direccion = direccion;
		this.otraraza = otraraza;
		this.profesion = profesion;
		this.fechareporteA = fechareporteA;
		this.fechareporteB = fechareporteB;
		this.fechareporteC = fechareporteC;
		this.fechareporteD = fechareporteD;
		this.fechareportepromotor = fechareportepromotor;
		this.horareportepromotor = horareportepromotor;
		this.nombreinvestigador = nombreinvestigador;
		this.fechareportee = fechareportee;
		this.talla = talla;
		this.fechanacimiento = fechanacimiento;
		this.fechaCECMEDA = fechaCECMEDA;
		this.fechaCECMEDB = fechaCECMEDB;
		this.fechaCECMEDC = fechaCECMEDC;
		this.fechaCECMEDD = fechaCECMEDD;
		this.eventoadverso = eventoadverso;
		this.dondeocurrio = dondeocurrio;
		this.otrolugar = otrolugar;
		this.acontecimiento = acontecimiento;
		this.descripcionea = descripcionea;
		this.productoinvestigado = productoinvestigado;
		this.causalidad = causalidad;
		this.fuente = fuente;
		this.otrafuente = otrafuente;
		this.lote = lote;
		this.fechacaducidad = fechacaducidad;
		this.iniciotratamiento = iniciotratamiento;
		this.dosisrecibida = dosisrecibida;
		this.ultimadosis = ultimadosis;
		this.dosisadministrada = dosisadministrada;
		this.presentacion = presentacion;
		this.abndonoelsujeto = abndonoelsujeto;
		this.tiempoaparicion = tiempoaparicion;
		this.descripcionsecuela = descripcionsecuela;
		this.diashospitalizacion = diashospitalizacion;
		this.autopsia = autopsia;
		this.terminotratamiento = terminotratamiento;
		this.tratamientoquirurgico = tratamientoquirurgico;
		this.indicacion = indicacion;
		this.especifiquetrat = especifiquetrat;
		this.descripciongeneral = descripciongeneral;
		this.datoslaboratorio = datoslaboratorio;
		this.copiabiopsia = copiabiopsia;
		this.copiaautopsia = copiaautopsia;
		this.otroscomentarios = otroscomentarios;
		this.fechainicio = fechainicio;
		this.horainicio = horainicio;
		this.fechafinalizacion = fechafinalizacion;
		this.horafinalizacion = horafinalizacion;
		this.otroshistoria = otroshistoria;
		this.idSujeto = idSujeto;
		this.idEstudio = idEstudio;
		this.idEntidad = idEntidad;
		this.ctc = ctc;
		this.oms = oms;
		this.ctcVersion = ctcVersion;
		this.secuela = secuela;
		this.edad = edad;
		this.sexo = sexo;
		this.peso = peso;
		this.raza = raza;
		this.no_dosis = no_dosis;
		this.variable = variable;
		this.variableDato = variableDato;
		this.crdEspecifico = crdEspecifico;
		this.reHistoriarelevantes = reHistoriarelevantes;
		this.reDiagnosticos = reDiagnosticos;
		this.reMedicacionrecientes = reMedicacionrecientes;
		this.reMedicacionconcomitantes = reMedicacionconcomitantes;
		this.reTrazabilidadreportes = reTrazabilidadreportes;
		this.reInfoproducto = reInfoproducto;
		this.reEnfermedadesinter = reEnfermedadesinter;
		this.usuario = usuario;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_consecuenciaspaciente")
	public ReConsecuenciaspaciente_ensayo getReConsecuenciaspaciente() {
		return this.reConsecuenciaspaciente;
	}

	public void setReConsecuenciaspaciente(
			ReConsecuenciaspaciente_ensayo reConsecuenciaspaciente) {
		this.reConsecuenciaspaciente = reConsecuenciaspaciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reaparicionea")
	public ReRespuesta_ensayo getReRespuestaByReaparicionea() {
		return this.reRespuestaByReaparicionea;
	}

	public void setReRespuestaByReaparicionea(
			ReRespuesta_ensayo reRespuestaByReaparicionea) {
		this.reRespuestaByReaparicionea = reRespuestaByReaparicionea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reintensidad")
	public ReIntensidad_ensayo getReIntensidad() {
		return this.reIntensidad;
	}

	public void setReIntensidad(ReIntensidad_ensayo reIntensidad) {
		this.reIntensidad = reIntensidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modificacionintensidad")
	public ReRespuesta_ensayo getReRespuestaByModificacionintensidad() {
		return this.reRespuestaByModificacionintensidad;
	}

	public void setReRespuestaByModificacionintensidad(
			ReRespuesta_ensayo reRespuestaByModificacionintensidad) {
		this.reRespuestaByModificacionintensidad = reRespuestaByModificacionintensidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_viasadmi")
	public ReViasadmi_ensayo getReViasadmi() {
		return this.reViasadmi;
	}

	public void setReViasadmi(ReViasadmi_ensayo reViasadmi) {
		this.reViasadmi = reViasadmi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_crealizadaeas")
	public ReCrealizadaeas_ensayo getReCrealizadaeas() {
		return this.reCrealizadaeas;
	}

	public void setReCrealizadaeas(ReCrealizadaeas_ensayo reCrealizadaeas) {
		this.reCrealizadaeas = reCrealizadaeas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_recausalpea")
	public ReRecausalpea_ensayo getReRecausalpea() {
		return this.reRecausalpea;
	}

	public void setReRecausalpea(ReRecausalpea_ensayo reRecausalpea) {
		this.reRecausalpea = reRecausalpea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_resultadofinal")
	public ReResultadofinal_ensayo getReResultadofinal() {
		return this.reResultadofinal;
	}

	public void setReResultadofinal(ReResultadofinal_ensayo reResultadofinal) {
		this.reResultadofinal = reResultadofinal;
	}

	@Column(name = "informeinicial")
	public Boolean getInformeinicial() {
		return this.informeinicial;
	}

	public void setInformeinicial(Boolean informeinicial) {
		this.informeinicial = informeinicial;
	}

	@Column(name = "fechacecmeda", length = 13)
	public String getFechaCECMEDA() {
		return fechaCECMEDA;
	}

	@Column(name = "fechacecmedb", length = 13)
	public String getFechaCECMEDB() {
		return fechaCECMEDB;
	}

	@Column(name = "fechacecmedc", length = 13)
	public String getFechaCECMEDC() {
		return fechaCECMEDC;
	}

	@Column(name = "fechacecmedd", length = 13)
	public String getFechaCECMEDD() {
		return fechaCECMEDD;
	}

	public void setFechaCECMEDA(String fechaCECMEDA) {
		this.fechaCECMEDA = fechaCECMEDA;
	}

	public void setFechaCECMEDB(String fechaCECMEDB) {
		this.fechaCECMEDB = fechaCECMEDB;
	}

	public void setFechaCECMEDC(String fechaCECMEDC) {
		this.fechaCECMEDC = fechaCECMEDC;
	}

	public void setFechaCECMEDD(String fechaCECMEDD) {
		this.fechaCECMEDD = fechaCECMEDD;
	}

	@Column(name = "fechareportea", length = 13)
	public String getFechareporteA() {
		return this.fechareporteA;
	}

	public void setFechareporteA(String fechareporte) {
		this.fechareporteA = fechareporte;
	}

	@Column(name = "fechareporteb", length = 13)
	public String getFechareporteB() {
		return fechareporteB;
	}

	public void setFechareporteB(String fechareporteB) {
		this.fechareporteB = fechareporteB;
	}

	@Column(name = "fechareportec", length = 13)
	public String getFechareporteC() {
		return fechareporteC;
	}

	public void setFechareporteC(String fechareporteC) {
		this.fechareporteC = fechareporteC;
	}

	@Column(name = "fechareported", length = 13)
	public String getFechareporteD() {
		return fechareporteD;
	}

	public void setFechareporteD(String fechareporteD) {
		this.fechareporteD = fechareporteD;
	}

	@Column(name = "eventoadverso")
	public String getEventoadverso() {
		return this.eventoadverso;
	}

	public void setEventoadverso(String eventoadverso) {
		if (eventoadverso != null)
			eventoadverso = eventoadverso.trim();
		this.eventoadverso = eventoadverso;
	}

	@Column(name = "descripcionea")
	public String getDescripcionea() {
		return this.descripcionea;
	}

	public void setDescripcionea(String descripcionea) {
		if (descripcionea != null)
			descripcionea = descripcionea.trim();
		this.descripcionea = descripcionea;
	}

	@Column(name = "productoinvestigado")
	public String getProductoinvestigado() {
		return this.productoinvestigado;
	}

	public void setProductoinvestigado(String productoinvestigado) {
		if (productoinvestigado != null)
			productoinvestigado = productoinvestigado.trim();
		this.productoinvestigado = productoinvestigado;
	}

	@Column(name = "lote")
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		if (lote != null)
			lote = lote.trim();
		this.lote = lote;
	}

	@Column(name = "fechacaducidad", length = 13)
	public String getFechacaducidad() {
		return this.fechacaducidad;
	}

	public void setFechacaducidad(String fechacaducidad) {
		this.fechacaducidad = fechacaducidad;
	}

	@Column(name = "iniciotratamiento", length = 13)
	public String getIniciotratamiento() {
		return this.iniciotratamiento;
	}

	public void setIniciotratamiento(String iniciotratamiento) {
		this.iniciotratamiento = iniciotratamiento;
	}

	@Column(name = "dosisrecibida", precision = 8, scale = 8)
	public Integer getDosisrecibida() {
		return this.dosisrecibida;
	}

	public void setDosisrecibida(Integer dosisrecibida) {
		this.dosisrecibida = dosisrecibida;
	}

	@Column(name = "ultimadosis", length = 13)
	public String getUltimadosis() {
		return this.ultimadosis;
	}

	public void setUltimadosis(String ultimadosis) {
		this.ultimadosis = ultimadosis;
	}

	@Column(name = "dosisadministrada", precision = 8, scale = 8)
	public String getDosisadministrada() {
		return this.dosisadministrada;
	}

	public void setDosisadministrada(String dosisadministrada) {
		this.dosisadministrada = dosisadministrada;
	}

	@Column(name = "tiempoaparicion", precision = 8, scale = 8)
	public String getTiempoaparicion() {
		return this.tiempoaparicion;
	}

	public void setTiempoaparicion(String tiempoaparicion) {
		this.tiempoaparicion = tiempoaparicion;
	}

	@Column(name = "descripcionsecuela")
	public String getDescripcionsecuela() {
		return this.descripcionsecuela;
	}

	public void setDescripcionsecuela(String descripcionsecuela) {
		if (descripcionsecuela != null)
			descripcionsecuela = descripcionsecuela.trim();
		this.descripcionsecuela = descripcionsecuela;
	}

	@Column(name = "diashospitalizacion")
	public Integer getDiashospitalizacion() {
		return this.diashospitalizacion;
	}

	public void setDiashospitalizacion(Integer diashospitalizacion) {
		this.diashospitalizacion = diashospitalizacion;
	}

	@Column(name = "autopsia")
	public Boolean getAutopsia() {
		return this.autopsia;
	}

	public void setAutopsia(Boolean autopsia) {
		this.autopsia = autopsia;
	}

	@Column(name = "datoslaboratorio")
	public Boolean getDatoslaboratorio() {
		return this.datoslaboratorio;
	}

	public void setDatoslaboratorio(Boolean datoslaboratorio) {
		this.datoslaboratorio = datoslaboratorio;
	}

	@Column(name = "copiabiopsia")
	public Boolean getCopiabiopsia() {
		return this.copiabiopsia;
	}

	public void setCopiabiopsia(Boolean copiabiopsia) {
		this.copiabiopsia = copiabiopsia;
	}

	@Column(name = "copiaautopsia")
	public Boolean getCopiaautopsia() {
		return this.copiaautopsia;
	}

	public void setCopiaautopsia(Boolean copiaautopsia) {
		this.copiaautopsia = copiaautopsia;
	}

	@Column(name = "otroscomentarios")
	public String getOtroscomentarios() {
		return this.otroscomentarios;
	}

	public void setOtroscomentarios(String otroscomentarios) {
		if (otroscomentarios != null)
			otroscomentarios = otroscomentarios.trim();
		this.otroscomentarios = otroscomentarios;
	}

	@Column(name = "id_sujeto")
	public Long getIdSujeto() {
		return this.idSujeto;
	}

	public void setIdSujeto(Long idSujeto) {
		this.idSujeto = idSujeto;
	}

	@Column(name = "id_estudio")
	public Long getIdEstudio() {
		return this.idEstudio;
	}

	public void setIdEstudio(Long idEstudio) {
		this.idEstudio = idEstudio;
	}

	@Column(name = "id_entidad")
	public Long getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Column(name = "ctc")
	public Boolean getCtc() {
		return this.ctc;
	}

	public void setCtc(Boolean ctc) {
		this.ctc = ctc;
	}

	@Column(name = "oms")
	public Boolean getOms() {
		return this.oms;
	}

	public void setOms(Boolean oms) {
		this.oms = oms;
	}

	@Column(name = "ctc_version")
	public Integer getCtcVersion() {
		return this.ctcVersion;
	}

	public void setCtcVersion(Integer ctcVersion) {
		this.ctcVersion = ctcVersion;
	}

	@Column(name = "secuela")
	public String getSecuela() {
		return this.secuela;
	}

	public void setSecuela(String secuela) {
		this.secuela = secuela;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reReporteexpedito")
	public Set<ReHistoriarelevante_ensayo> getReHistoriarelevantes() {
		return this.reHistoriarelevantes;
	}

	public void setReHistoriarelevantes(
			Set<ReHistoriarelevante_ensayo> reHistoriarelevantes) {
		this.reHistoriarelevantes = reHistoriarelevantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reReporteexpedito")
	public Set<ReDiagnostico_ensayo> getReDiagnosticos() {
		return this.reDiagnosticos;
	}

	public void setReDiagnosticos(Set<ReDiagnostico_ensayo> reDiagnosticos) {
		this.reDiagnosticos = reDiagnosticos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reReporteexpedito")
	public Set<ReMedicacionreciente_ensayo> getReMedicacionrecientes() {
		return this.reMedicacionrecientes;
	}

	public void setReMedicacionrecientes(
			Set<ReMedicacionreciente_ensayo> reMedicacionrecientes) {
		this.reMedicacionrecientes = reMedicacionrecientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reReporteexpedito")
	public Set<ReMedicacionconcomitante_ensayo> getReMedicacionconcomitantes() {
		return this.reMedicacionconcomitantes;
	}

	public void setReMedicacionconcomitantes(
			Set<ReMedicacionconcomitante_ensayo> reMedicacionconcomitantes) {
		this.reMedicacionconcomitantes = reMedicacionconcomitantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reReporteexpedito")
	public Set<ReTrazabilidadreporte_ensayo> getReTrazabilidadreportes() {
		return this.reTrazabilidadreportes;
	}

	public void setReTrazabilidadreportes(
			Set<ReTrazabilidadreporte_ensayo> reTrazabilidadreportes) {
		this.reTrazabilidadreportes = reTrazabilidadreportes;
	}

	@Column(name = "edad")
	public String getEdad() {
		return edad;
	}

	public void setEdad(String edad) {
		this.edad = edad;
	}

	@Column(name = "sexo")
	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "peso")
	public Float getPeso() {
		return peso;
	}

	public void setPeso(Float peso) {
		this.peso = peso;
	}

	@Column(name = "raza")
	public String getRaza() {
		return raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	@Column(name = "otroshistoria")
	public String getOtroshistoria() {
		return otroshistoria;
	}

	public void setOtroshistoria(String otroshistoria) {
		this.otroshistoria = otroshistoria;
	}

	@JoinColumn(name = "no_dosis")
	public String getNo_dosis() {
		return no_dosis;
	}

	public void setNo_dosis(String no_dosis) {
		this.no_dosis = no_dosis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable")
	public Variable_ensayo getVariable() {
		return variable;
	}

	public void setVariable(Variable_ensayo variable) {
		this.variable = variable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable_dato")
	public VariableDato_ensayo getVariableDato() {
		return variableDato;
	}

	public void setVariableDato(VariableDato_ensayo variableDato) {
		this.variableDato = variableDato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_crd_especif")
	public CrdEspecifico_ensayo getCrdEspecifico() {
		return crdEspecifico;
	}

	public void setCrdEspecifico(CrdEspecifico_ensayo crdEspecifico) {
		this.crdEspecifico = crdEspecifico;
	}

	@Column(name = "promotor", length = 13)
	public String getPromotor() {
		return promotor;
	}

	public void setPromotor(String promotor) {
		this.promotor = promotor;
	}

	@Column(name = "presentacion")
	public String getPresentacion() {
		return presentacion;
	}

	public void setPresentacion(String presentacion) {
		this.presentacion = presentacion;
	}

	@Column(name = "investigador")
	public String getInvestigador() {
		return investigador;
	}

	public void setInvestigador(String investigador) {
		this.investigador = investigador;
	}

	@Column(name = "fechaingreso")
	public String getFechaingreso() {
		return fechaingreso;
	}

	@Column(name = "fechaalta")
	public String getFechaalta() {
		return fechaalta;
	}

	@Column(name = "fechaaltaprol")
	public String getFechaaltaprol() {
		return fechaaltaprol;
	}

	@Column(name = "especifiqueacont")
	public String getEspecifiqueacont() {
		return especifiqueacont;
	}

	@Column(name = "especifiqueotros")
	public String getEspecifiqueotros() {
		return especifiqueotros;
	}

	@Column(name = "nombrereporta")
	public String getNombrereporta() {
		return nombrereporta;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return direccion;
	}

	@Column(name = "profesion")
	public String getProfesion() {
		return profesion;
	}

	public void setFechaingreso(String fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	public void setFechaalta(String fechaalta) {
		this.fechaalta = fechaalta;
	}

	public void setFechaaltaprol(String fechaaltaprol) {
		this.fechaaltaprol = fechaaltaprol;
	}

	public void setEspecifiqueacont(String especifiqueacont) {
		this.especifiqueacont = especifiqueacont;
	}

	public void setEspecifiqueotros(String especifiqueotros) {
		this.especifiqueotros = especifiqueotros;
	}

	public void setNombrereporta(String nombrereporta) {
		this.nombrereporta = nombrereporta;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	@Column(name = "fechanacimiento")
	public String getFechanacimiento() {
		return fechanacimiento;
	}

	public void setFechanacimiento(String fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "dondeocurrio")
	public String getDondeocurrio() {
		return dondeocurrio;
	}

	@Column(name = "otrolugar")
	public String getOtrolugar() {
		return otrolugar;
	}

	@Column(name = "acontecimiento")
	public String getAcontecimiento() {
		return acontecimiento;
	}

	public void setDondeocurrio(String dondeocurrio) {
		this.dondeocurrio = dondeocurrio;
	}

	public void setOtrolugar(String otrolugar) {
		this.otrolugar = otrolugar;
	}

	public void setAcontecimiento(String acontecimiento) {
		this.acontecimiento = acontecimiento;
	}

	@Column(name = "otraraza")
	public String getOtraraza() {
		return otraraza;
	}

	public void setOtraraza(String otraraza) {
		this.otraraza = otraraza;
	}

	@Column(name = "talla")
	public Float getTalla() {
		return talla;
	}

	public void setTalla(Float talla) {
		this.talla = talla;
	}

	@Column(name = "fechainicio")
	public String getFechainicio() {
		return fechainicio;
	}

	@Column(name = "horainicio")
	public String getHorainicio() {
		return horainicio;
	}

	@Column(name = "fechafinalizacion")
	public String getFechafinalizacion() {
		return fechafinalizacion;
	}

	@Column(name = "horafinalizacion")
	public String getHorafinalizacion() {
		return horafinalizacion;
	}

	public void setFechainicio(String fechainicio) {
		this.fechainicio = fechainicio;
	}

	public void setHorainicio(String horainicio) {
		this.horainicio = horainicio;
	}

	public void setFechafinalizacion(String fechafinalizacion) {
		this.fechafinalizacion = fechafinalizacion;
	}

	public void setHorafinalizacion(String horafinalizacion) {
		this.horafinalizacion = horafinalizacion;
	}

	@Column(name = "causalidad")
	public String getCausalidad() {
		return causalidad;
	}

	@Column(name = "fuente")
	public String getFuente() {
		return fuente;
	}

	@Column(name = "otrafuente")
	public String getOtrafuente() {
		return otrafuente;
	}

	public void setCausalidad(String causalidad) {
		this.causalidad = causalidad;
	}

	public void setFuente(String fuente) {
		this.fuente = fuente;
	}

	public void setOtrafuente(String otrafuente) {
		this.otrafuente = otrafuente;
	}

	@Column(name = "abndonoelsujeto")
	public Boolean getAbndonoelsujeto() {
		return abndonoelsujeto;
	}

	public void setAbndonoelsujeto(Boolean abndonoelsujeto) {
		this.abndonoelsujeto = abndonoelsujeto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reReporteexpedito")
	public Set<ReInfoproducto_ensayo> getReInfoproducto() {
		return reInfoproducto;
	}

	public void setReInfoproducto(Set<ReInfoproducto_ensayo> reInfoproducto) {
		this.reInfoproducto = reInfoproducto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reReporteexpedito")
	public Set<ReEnfermedadesinter_ensayo> getReEnfermedadesinter() {
		return reEnfermedadesinter;
	}

	public void setReEnfermedadesinter(
			Set<ReEnfermedadesinter_ensayo> reEnfermedadesinter) {
		this.reEnfermedadesinter = reEnfermedadesinter;
	}

	@Column(name = "terminotratamiento")
	public Boolean getTerminotratamiento() {
		return terminotratamiento;
	}

	public void setTerminotratamiento(Boolean terminotratamiento) {
		this.terminotratamiento = terminotratamiento;
	}

	@Column(name = "indicacion")
	public String getIndicacion() {
		return indicacion;
	}

	public void setIndicacion(String indicacion) {
		this.indicacion = indicacion;
	}

	@Column(name = "tratamientoquirurgico")
	public Boolean getTratamientoquirurgico() {
		return tratamientoquirurgico;
	}

	public void setTratamientoquirurgico(Boolean tratamientoquirurgico) {
		this.tratamientoquirurgico = tratamientoquirurgico;
	}

	@Column(name = "especifiquetrat")
	public String getEspecifiquetrat() {
		return especifiquetrat;
	}

	public void setEspecifiquetrat(String especifiquetrat) {
		this.especifiquetrat = especifiquetrat;
	}
	@Column(name = "descripciongeneral")
	public String getDescripciongeneral() {
		return descripciongeneral;
	}
	
	public void setDescripciongeneral(String descripciongeneral) {
		this.descripciongeneral = descripciongeneral;
	}
	@Column(name = "fechareportepromotor")
	public String getFechareportepromotor() {
		return fechareportepromotor;
	}
	@Column(name = "horareportepromotor")
	public String getHorareportepromotor() {
		return horareportepromotor;
	}
	@Column(name = "nombreinvestigador")
	public String getNombreinvestigador() {
		return nombreinvestigador;
	}
	@Column(name = "fechareportee")
	public String getFechareportee() {
		return fechareportee;
	}

	public void setFechareportepromotor(String fechareportepromotor) {
		this.fechareportepromotor = fechareportepromotor;
	}

	public void setHorareportepromotor(String horareportepromotor) {
		this.horareportepromotor = horareportepromotor;
	}

	public void setNombreinvestigador(String nombreinvestigador) {
		this.nombreinvestigador = nombreinvestigador;
	}

	public void setFechareportee(String fechareportee) {
		this.fechareportee = fechareportee;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

}
