package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * ReTrazabilidadreporte generated by hbm2java
 */
@Entity
@Table(name = "re_trazabilidadreporte", schema = "ensayo")
public class ReTrazabilidadreporte_ensayo implements java.io.Serializable {

	private long id;
	private ReReporteexpedito_ensayo reReporteexpedito;
	private String nombreapellido;
	private String responsabilidad;
	private String fecha;
	private String codigo;

	public ReTrazabilidadreporte_ensayo() {
	}

	public ReTrazabilidadreporte_ensayo(long id,
			ReReporteexpedito_ensayo reReporteexpedito) {
		this.id = id;
		this.reReporteexpedito = reReporteexpedito;
	}

	public ReTrazabilidadreporte_ensayo(long id,
			ReReporteexpedito_ensayo reReporteexpedito, String nombreapellido,
			String responsabilidad, String fecha, String codigo) {
		this.id = id;
		this.reReporteexpedito = reReporteexpedito;
		this.nombreapellido = nombreapellido;
		this.responsabilidad = responsabilidad;
		this.fecha = fecha;
		this.codigo = codigo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_re_reporteexpedito", nullable = false)
	@NotNull
	public ReReporteexpedito_ensayo getReReporteexpedito() {
		return this.reReporteexpedito;
	}

	public void setReReporteexpedito(ReReporteexpedito_ensayo reReporteexpedito) {
		this.reReporteexpedito = reReporteexpedito;
	}

	@Column(name = "nombreapellido")
	public String getNombreapellido() {
		return this.nombreapellido;
	}

	public void setNombreapellido(String nombreapellido) {
		if (nombreapellido != null)
			nombreapellido = nombreapellido.trim();
		this.nombreapellido = nombreapellido;
	}

	@Column(name = "responsabilidad")
	public String getResponsabilidad() {
		return this.responsabilidad;
	}

	public void setResponsabilidad(String responsabilidad) {
		if (responsabilidad != null)
			responsabilidad = responsabilidad.trim();
		this.responsabilidad = responsabilidad;
	}

	
	@Column(name = "fecha", length = 13)
	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}
	
	
	@Column(name = "codigo")
	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
