package gehos.ensayo.entity;

// Generated 02-oct-2017 11:52:20 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ReViasadmi generated by hbm2java
 */
@Entity
@Table(name = "re_viasadmi", schema = "ensayo")
public class ReViasadmi_ensayo implements java.io.Serializable {

	private long id;
	private String descripcion;
	private Integer codigo;
	private Set<ReReporteexpedito_ensayo> reReporteexpeditos = new HashSet<ReReporteexpedito_ensayo>(
			0);
	private Set<ReMedicacion_ensayo> reMedicacions = new HashSet<ReMedicacion_ensayo>(
			0);

	public ReViasadmi_ensayo() {
	}

	public ReViasadmi_ensayo(long id) {
		this.id = id;
	}

	public ReViasadmi_ensayo(long id, String descripcion, Integer codigo,
			Set<ReReporteexpedito_ensayo> reReporteexpeditos,
			Set<ReMedicacion_ensayo> reMedicacions) {
		this.id = id;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.reReporteexpeditos = reReporteexpeditos;
		this.reMedicacions = reMedicacions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "codigo")
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reViasadmi")
	public Set<ReReporteexpedito_ensayo> getReReporteexpeditos() {
		return this.reReporteexpeditos;
	}

	public void setReReporteexpeditos(
			Set<ReReporteexpedito_ensayo> reReporteexpeditos) {
		this.reReporteexpeditos = reReporteexpeditos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reViasadmi")
	public Set<ReMedicacion_ensayo> getReMedicacions() {
		return this.reMedicacions;
	}

	public void setReMedicacions(Set<ReMedicacion_ensayo> reMedicacions) {
		this.reMedicacions = reMedicacions;
	}

}
