package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Role_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String name;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private Set<Usuario_ensayo> usuarios = new HashSet<Usuario_ensayo>(0);
	private Set<UsuarioEstudio_ensayo> usuarioEstudios = new HashSet<UsuarioEstudio_ensayo>(
			0);

	public Role_ensayo() {
	}

	public Role_ensayo(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Role_ensayo(long id, String name, Boolean eliminado, Long cid,
			String codigo, Set<Usuario_ensayo> usuarios,
			Set<UsuarioEstudio_ensayo> usuarioEstudios) {
		this.id = id;
		this.name = name;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.usuarioEstudios = usuarioEstudios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		if (name != null)
			name = name.trim();
		this.name = name;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo", length = 50)
	@Length(max = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_in_role", schema = "seguridad", joinColumns = { @JoinColumn(name = "id_role", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) })
	public Set<Usuario_ensayo> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario_ensayo> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<UsuarioEstudio_ensayo> getUsuarioEstudios() {
		return this.usuarioEstudios;
	}

	public void setUsuarioEstudios(Set<UsuarioEstudio_ensayo> usuarioEstudios) {
		this.usuarioEstudios = usuarioEstudios;
	}

}
