package gehos.ensayo.entity;

// Generated 09-sep-2016 16:12:22 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Seccion generated by hbm2java
 */
@Entity
@Table(name = "seccion", schema = "ensayo")
public class Seccion_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private HojaCrd_ensayo hojaCrd;
	private Usuario_ensayo usuario;
	private String etiquetaSeccion;
	private String tituloSeccion;
	private String subtitulo;
	private String instrucciones;
	private Long cid;
	private Boolean eliminado;
	private Set<GrupoVariables_ensayo> grupoVariableses = new HashSet<GrupoVariables_ensayo>(
			0);
	private Set<Variable_ensayo> variables = new HashSet<Variable_ensayo>(0);

	public Seccion_ensayo() {
	}

	public Seccion_ensayo(long id, HojaCrd_ensayo hojaCrd) {
		this.id = id;
		this.hojaCrd = hojaCrd;
	}

	public Seccion_ensayo(long id, HojaCrd_ensayo hojaCrd, Usuario_ensayo usuario,
			String etiquetaSeccion, String tituloSeccion, String subtitulo,
			String instrucciones, Long cid, Boolean eliminado,
			Set<GrupoVariables_ensayo> grupoVariableses,
			Set<Variable_ensayo> variables) {
		this.id = id;
		this.hojaCrd = hojaCrd;
		this.etiquetaSeccion = etiquetaSeccion;
		this.tituloSeccion = tituloSeccion;
		this.subtitulo = subtitulo;
		this.instrucciones = instrucciones;
		this.cid = cid;
		this.eliminado = eliminado;
		this.grupoVariableses = grupoVariableses;
		this.variables = variables;
		this.usuario = usuario;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hoja_crd", nullable = false)
	@NotNull
	public HojaCrd_ensayo getHojaCrd() {
		return this.hojaCrd;
	}

	public void setHojaCrd(HojaCrd_ensayo hojaCrd) {
		this.hojaCrd = hojaCrd;
	}

	@Column(name = "etiqueta_seccion", length = 500)
	@Length(max = 500)
	public String getEtiquetaSeccion() {
		return this.etiquetaSeccion;
	}

	public void setEtiquetaSeccion(String etiquetaSeccion) {
		if (etiquetaSeccion != null)
			etiquetaSeccion = etiquetaSeccion.trim();
		this.etiquetaSeccion = etiquetaSeccion;
	}

	@Column(name = "titulo_seccion", length = 500)
	@Length(max = 500)
	public String getTituloSeccion() {
		return this.tituloSeccion;
	}

	public void setTituloSeccion(String tituloSeccion) {
		if (tituloSeccion != null)
			tituloSeccion = tituloSeccion.trim();
		this.tituloSeccion = tituloSeccion;
	}

	@Column(name = "subtitulo", length = 500)
	@Length(max = 500)
	public String getSubtitulo() {
		return this.subtitulo;
	}

	public void setSubtitulo(String subtitulo) {
		if (subtitulo != null)
			subtitulo = subtitulo.trim();
		if (subtitulo == "")
			subtitulo = null;
		this.subtitulo = subtitulo;
	}

	@Column(name = "instrucciones", length = 500)
	@Length(max = 500)
	public String getInstrucciones() {
		return this.instrucciones;
	}

	public void setInstrucciones(String instrucciones) {
		if (instrucciones != null)
			instrucciones = instrucciones.trim();
		if (instrucciones == "")
			instrucciones = null;
		this.instrucciones = instrucciones;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "seccion")
	public Set<GrupoVariables_ensayo> getGrupoVariableses() {
		return this.grupoVariableses;
	}

	public void setGrupoVariableses(Set<GrupoVariables_ensayo> grupoVariableses) {
		this.grupoVariableses = grupoVariableses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "seccion")
	public Set<Variable_ensayo> getVariables() {
		return this.variables;
	}

	public void setVariables(Set<Variable_ensayo> variables) {
		this.variables = variables;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

}
