package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Sujeto generated by hbm2java
 */
@Entity
@Table(name = "sujeto", schema = "ensayo")
public class Sujeto_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private EstadoTratamiento_ensayo estadoTratamiento;
	private Sexo_ensayo sexo;
	private Entidad_ensayo entidad;
	private EstadoInclusion_ensayo estadoInclusion;
	private GrupoSujetos_ensayo grupoSujetos;
	private EstadoSujeto_ensayo estadoSujeto;
	private String nombre;
	private Date fechaNacimiento;
	private Date fechaCreacion;
	private Date fechaActualizacion;
	private Long cid;
	private String codigoPaciente;
	private String inicialesCentro;
	private String inicialesPaciente;
	private Long numeroInclucion;
	private Usuario_ensayo usuario;
	private String fechaInclucion;
	private Boolean eliminado;
	private Date fechaInterrupcion;
	private Date fechaInicronograma;
	private Boolean cronogramaEspecifico;

	private Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos = new HashSet<MomentoSeguimientoEspecifico_ensayo>(
			0);
	private Set<Causa_ensayo> causas = new HashSet<Causa_ensayo>(0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);

	public Sujeto_ensayo() {
	}

	public Sujeto_ensayo(long id) {
		this.id = id;
	}

	public Sujeto_ensayo(
			long id,
			EstadoTratamiento_ensayo estadoTratamiento,
			Sexo_ensayo sexo,
			Entidad_ensayo entidad,
			EstadoInclusion_ensayo estadoInclusion,
			GrupoSujetos_ensayo grupoSujetos,
			EstadoSujeto_ensayo estadoSujeto,
			String nombre,
			Date fechaNacimiento,
			Date fechaCreacion,
			Date fechaActualizacion,
			Long cid,
			String codigoPaciente,
			String inicialesCentro,
			String inicialesPaciente,
			Long numeroInclucion,
			String fechaInclucion,
			Boolean eliminado,
			Date fechaInterrupcion,
			Usuario_ensayo usuario,
			Date fechaInicronograma,
			Boolean cronogramaEspecifico,
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos,
			Set<Causa_ensayo> causas,
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.id = id;
		this.estadoTratamiento = estadoTratamiento;
		this.sexo = sexo;
		this.entidad = entidad;
		this.estadoInclusion = estadoInclusion;
		this.grupoSujetos = grupoSujetos;
		this.estadoSujeto = estadoSujeto;
		this.nombre = nombre;
		this.fechaNacimiento = fechaNacimiento;
		this.fechaCreacion = fechaCreacion;
		this.fechaActualizacion = fechaActualizacion;
		this.cid = cid;
		this.codigoPaciente = codigoPaciente;
		this.inicialesCentro = inicialesCentro;
		this.usuario = usuario;
		this.inicialesPaciente = inicialesPaciente;
		this.numeroInclucion = numeroInclucion;
		this.fechaInclucion = fechaInclucion;
		this.eliminado = eliminado;
		this.fechaInterrupcion = fechaInterrupcion;
		this.fechaInicronograma = fechaInicronograma;
		this.cronogramaEspecifico = cronogramaEspecifico;
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
		this.causas = causas;
		this.setLogEventosAuditoria(logEventosAuditoria);
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_tratamiento")
	public EstadoTratamiento_ensayo getEstadoTratamiento() {
		return this.estadoTratamiento;
	}

	public void setEstadoTratamiento(EstadoTratamiento_ensayo estadoTratamiento) {
		this.estadoTratamiento = estadoTratamiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sexo")
	public Sexo_ensayo getSexo() {
		return this.sexo;
	}

	public void setSexo(Sexo_ensayo sexo) {
		this.sexo = sexo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_ensayo getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_ensayo entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_inclusion")
	public EstadoInclusion_ensayo getEstadoInclusion() {
		return this.estadoInclusion;
	}

	public void setEstadoInclusion(EstadoInclusion_ensayo estadoInclusion) {
		this.estadoInclusion = estadoInclusion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_sujetos")
	public GrupoSujetos_ensayo getGrupoSujetos() {
		return this.grupoSujetos;
	}

	public void setGrupoSujetos(GrupoSujetos_ensayo grupoSujetos) {
		this.grupoSujetos = grupoSujetos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_sujeto")
	public EstadoSujeto_ensayo getEstadoSujeto() {
		return this.estadoSujeto;
	}

	public void setEstadoSujeto(EstadoSujeto_ensayo estadoSujeto) {
		this.estadoSujeto = estadoSujeto;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualizacion", length = 13)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo_paciente", length = 500)
	@Length(max = 500)
	public String getCodigoPaciente() {
		return this.codigoPaciente;
	}

	public void setCodigoPaciente(String codigoPaciente) {
		if (codigoPaciente != null)
			codigoPaciente = codigoPaciente.trim();
		this.codigoPaciente = codigoPaciente;
	}

	@Column(name = "iniciales_centro")
	public String getInicialesCentro() {
		return this.inicialesCentro;
	}

	public void setInicialesCentro(String inicialesCentro) {
		if (inicialesCentro != null)
			inicialesCentro = inicialesCentro.trim();
		this.inicialesCentro = inicialesCentro;
	}

	@Column(name = "iniciales_paciente")
	public String getInicialesPaciente() {
		return this.inicialesPaciente;
	}

	public void setInicialesPaciente(String inicialesPaciente) {
		if (inicialesPaciente != null)
			inicialesPaciente = inicialesPaciente.trim();
		this.inicialesPaciente = inicialesPaciente;
	}

	@Column(name = "numero_inclucion")
	public Long getNumeroInclucion() {
		return this.numeroInclucion;
	}

	public void setNumeroInclucion(Long numeroInclucion) {
		this.numeroInclucion = numeroInclucion;
	}

	
	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_interrupcion", length = 13)
	public Date getFechaInterrupcion() {
		return this.fechaInterrupcion;
	}

	public void setFechaInterrupcion(Date fechaInterrupcion) {
		this.fechaInterrupcion = fechaInterrupcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicronograma", length = 13)
	public Date getFechaInicronograma() {
		return this.fechaInicronograma;
	}

	public void setFechaInicronograma(Date fechaInicronograma) {
		this.fechaInicronograma = fechaInicronograma;
	}

	@Column(name = "cronograma_especifico")
	public Boolean getCronogramaEspecifico() {
		return this.cronogramaEspecifico;
	}

	public void setCronogramaEspecifico(Boolean cronogramaEspecifico) {
		this.cronogramaEspecifico = cronogramaEspecifico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sujeto")
	public Set<MomentoSeguimientoEspecifico_ensayo> getMomentoSeguimientoEspecificos() {
		return this.momentoSeguimientoEspecificos;
	}

	public void setMomentoSeguimientoEspecificos(
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos) {
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sujeto")
	public Set<Causa_ensayo> getCausas() {
		return this.causas;
	}

	public void setCausas(Set<Causa_ensayo> causas) {
		this.causas = causas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sujeto")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}

	@Column(name = "fecha_inclucion")
	public String getFechaInclucion() {
		return fechaInclucion;
	}

	public void setFechaInclucion(String fechaInclucion) {
		this.fechaInclucion = fechaInclucion;
	}

}
