package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * TipoEntidad generated by hbm2java
 */
@Entity
@Table(name = "tipo_entidad", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "valor"))
public class TipoEntidad_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private Set<Entidad_ensayo> entidads = new HashSet<Entidad_ensayo>(0);

	public TipoEntidad_ensayo() {
	}

	public TipoEntidad_ensayo(long id, String valor) {
		this.id = id;
		this.valor = valor;
	}

	public TipoEntidad_ensayo(long id, String valor, Boolean eliminado,
			Long cid, Set<Entidad_ensayo> entidads) {
		this.id = id;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.entidads = entidads;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEntidad")
	public Set<Entidad_ensayo> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad_ensayo> entidads) {
		this.entidads = entidads;
	}

}
