package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * TipoDato generated by hbm2java
 */
@Entity
@Table(name = "tipo_dato", schema = "ensayo")
public class TipoDato_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String codigo;
	private String nombre;
	private String descripcion;
	private Long cid;
	private Boolean eliminado;
	private Set<Variable_ensayo> variables = new HashSet<Variable_ensayo>(0);
	private Set<PresentacionFormulario_ensayo> presentacionFormularios = new HashSet<PresentacionFormulario_ensayo>(
			0);

	public TipoDato_ensayo() {
	}

	public TipoDato_ensayo(long id) {
		this.id = id;
	}

	public TipoDato_ensayo(long id, String codigo, String nombre,
			String descripcion, Long cid, Boolean eliminado,
			Set<Variable_ensayo> variables,
			Set<PresentacionFormulario_ensayo> presentacionFormularios) {
		this.id = id;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.cid = cid;
		this.eliminado = eliminado;
		this.variables = variables;
		this.presentacionFormularios = presentacionFormularios;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if (descripcion != null)
			descripcion = descripcion.trim();
		this.descripcion = descripcion;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDato")
	public Set<Variable_ensayo> getVariables() {
		return this.variables;
	}

	public void setVariables(Set<Variable_ensayo> variables) {
		this.variables = variables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDato")
	public Set<PresentacionFormulario_ensayo> getPresentacionFormularios() {
		return this.presentacionFormularios;
	}

	public void setPresentacionFormularios(
			Set<PresentacionFormulario_ensayo> presentacionFormularios) {
		this.presentacionFormularios = presentacionFormularios;
	}

}
