package gehos.ensayo.entity;

// Generated Jun 4, 2012 4:59:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoCie generated by hbm2java
 */
@Entity
@Table(name = "tipo_cie", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "codigo"),
		@UniqueConstraint(columnNames = "valor") })
public class TipoCie_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String valor;
	private String codigo;
	private Boolean eliminado;
	private Long cid;
	private Set<Cie_ensayo> cies = new HashSet<Cie_ensayo>(0);

	public TipoCie_ensayo() {
	}

	public TipoCie_ensayo(long id, String valor, String codigo) {
		this.id = id;
		this.valor = valor;
		this.codigo = codigo;
	}

	public TipoCie_ensayo(long id, String valor, String codigo,
			Boolean eliminado, Long cid, Set<Cie_ensayo> cies) {
		this.id = id;
		this.valor = valor;
		this.codigo = codigo;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cies = cies;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", unique = true, nullable = false, length = 25)
	@NotNull
	@Length(max = 25)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "codigo", unique = true, nullable = false)
	@NotNull
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCie")
	public Set<Cie_ensayo> getCies() {
		return this.cies;
	}

	public void setCies(Set<Cie_ensayo> cies) {
		this.cies = cies;
	}

}
