package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TrazaSession generated by hbm2java
 */
@Entity
@Table(name = "traza_session", schema = "bitacora")
public class TrazaSession_ensayo implements java.io.Serializable {

	private long id;
	private Usuario_ensayo usuario;
	private Date fechaInicio;
	private Date horaInicio;
	private String direccionIp;
	private Integer anno;
	private Integer mes;
	private Integer dia;
	private Set<TrazaModuloAccedido_ensayo> trazaModuloAccedidos = new HashSet<TrazaModuloAccedido_ensayo>(
			0);
	private Set<TrazaModuloAccedido_ensayo> trazaModuloAccedidos_1 = new HashSet<TrazaModuloAccedido_ensayo>(
			0);

	public TrazaSession_ensayo() {
	}

	public TrazaSession_ensayo(long id) {
		this.id = id;
	}

	public TrazaSession_ensayo(long id, Usuario_ensayo usuario,
			Date fechaInicio, Date horaInicio, String direccionIp,
			Integer anno, Integer mes, Integer dia,
			Set<TrazaModuloAccedido_ensayo> trazaModuloAccedidos,
			Set<TrazaModuloAccedido_ensayo> trazaModuloAccedidos_1) {
		this.id = id;
		this.usuario = usuario;
		this.fechaInicio = fechaInicio;
		this.horaInicio = horaInicio;
		this.direccionIp = direccionIp;
		this.anno = anno;
		this.mes = mes;
		this.dia = dia;
		this.trazaModuloAccedidos = trazaModuloAccedidos;
		this.trazaModuloAccedidos_1 = trazaModuloAccedidos_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Column(name = "direccion_ip", length = 23)
	@Length(max = 23)
	public String getDireccionIp() {
		return this.direccionIp;
	}

	public void setDireccionIp(String direccionIp) {
		if (direccionIp != null)
			direccionIp = direccionIp.trim();
		this.direccionIp = direccionIp;
	}

	@Column(name = "anno")
	public Integer getAnno() {
		return this.anno;
	}

	public void setAnno(Integer anno) {
		this.anno = anno;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "dia")
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trazaSession")
	public Set<TrazaModuloAccedido_ensayo> getTrazaModuloAccedidos() {
		return this.trazaModuloAccedidos;
	}

	public void setTrazaModuloAccedidos(
			Set<TrazaModuloAccedido_ensayo> trazaModuloAccedidos) {
		this.trazaModuloAccedidos = trazaModuloAccedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trazaSession")
	public Set<TrazaModuloAccedido_ensayo> getTrazaModuloAccedidos_1() {
		return this.trazaModuloAccedidos_1;
	}

	public void setTrazaModuloAccedidos_1(
			Set<TrazaModuloAccedido_ensayo> trazaModuloAccedidos_1) {
		this.trazaModuloAccedidos_1 = trazaModuloAccedidos_1;
	}

}
