package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * TrazaModuloAccedido generated by hbm2java
 */
@Entity
@Table(name = "traza_modulo_accedido", schema = "bitacora")
public class TrazaModuloAccedido_ensayo implements java.io.Serializable {

	private long id;
	private TrazaSession_ensayo trazaSession;
	private Long modulo;
	private Date hora;
	private Set<TrazaAccion_ensayo> trazaAccions = new HashSet<TrazaAccion_ensayo>(
			0);
	private Set<TrazaAccion_ensayo> trazaAccions_1 = new HashSet<TrazaAccion_ensayo>(
			0);

	public TrazaModuloAccedido_ensayo() {
	}

	public TrazaModuloAccedido_ensayo(long id) {
		this.id = id;
	}

	public TrazaModuloAccedido_ensayo(long id,
			TrazaSession_ensayo trazaSession, Long modulo, Date hora,
			Set<TrazaAccion_ensayo> trazaAccions,
			Set<TrazaAccion_ensayo> trazaAccions_1) {
		this.id = id;
		this.trazaSession = trazaSession;
		this.modulo = modulo;
		this.hora = hora;
		this.trazaAccions = trazaAccions;
		this.trazaAccions_1 = trazaAccions_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session")
	public TrazaSession_ensayo getTrazaSession() {
		return this.trazaSession;
	}

	public void setTrazaSession(TrazaSession_ensayo trazaSession) {
		this.trazaSession = trazaSession;
	}

	@Column(name = "modulo")
	public Long getModulo() {
		return this.modulo;
	}

	public void setModulo(Long modulo) {
		this.modulo = modulo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trazaModuloAccedido")
	public Set<TrazaAccion_ensayo> getTrazaAccions() {
		return this.trazaAccions;
	}

	public void setTrazaAccions(Set<TrazaAccion_ensayo> trazaAccions) {
		this.trazaAccions = trazaAccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trazaModuloAccedido")
	public Set<TrazaAccion_ensayo> getTrazaAccions_1() {
		return this.trazaAccions_1;
	}

	public void setTrazaAccions_1(Set<TrazaAccion_ensayo> trazaAccions_1) {
		this.trazaAccions_1 = trazaAccions_1;
	}

}
