package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TrazaAtributoModificado generated by hbm2java
 */
@Entity
@Table(name = "traza_atributo_modificado", schema = "bitacora")
public class TrazaAtributoModificado_ensayo implements java.io.Serializable {

	private long id;
	private TrazaAccion_ensayo trazaAccion;
	private String entidad;
	private Long idEntidad;
	private String atributo;
	private String valorAntes;
	private String valorDespues;

	public TrazaAtributoModificado_ensayo() {
	}

	public TrazaAtributoModificado_ensayo(long id) {
		this.id = id;
	}

	public TrazaAtributoModificado_ensayo(long id,
			TrazaAccion_ensayo trazaAccion, String entidad, Long idEntidad,
			String atributo, String valorAntes, String valorDespues) {
		this.id = id;
		this.trazaAccion = trazaAccion;
		this.entidad = entidad;
		this.idEntidad = idEntidad;
		this.atributo = atributo;
		this.valorAntes = valorAntes;
		this.valorDespues = valorDespues;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accion_realizada")
	public TrazaAccion_ensayo getTrazaAccion() {
		return this.trazaAccion;
	}

	public void setTrazaAccion(TrazaAccion_ensayo trazaAccion) {
		this.trazaAccion = trazaAccion;
	}

	@Column(name = "entidad", length = 75)
	@Length(max = 75)
	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		if (entidad != null)
			entidad = entidad.trim();
		this.entidad = entidad;
	}

	@Column(name = "id_entidad")
	public Long getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Column(name = "atributo", length = 75)
	@Length(max = 75)
	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		if (atributo != null)
			atributo = atributo.trim();
		this.atributo = atributo;
	}

	@Column(name = "valor_antes")
	public String getValorAntes() {
		return this.valorAntes;
	}

	public void setValorAntes(String valorAntes) {
		if (valorAntes != null)
			valorAntes = valorAntes.trim();
		this.valorAntes = valorAntes;
	}

	@Column(name = "valor_despues")
	public String getValorDespues() {
		return this.valorDespues;
	}

	public void setValorDespues(String valorDespues) {
		if (valorDespues != null)
			valorDespues = valorDespues.trim();
		this.valorDespues = valorDespues;
	}

}
