package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * TrazaAccion generated by hbm2java
 */
@Entity
@Table(name = "traza_accion", schema = "bitacora")
public class TrazaAccion_ensayo implements java.io.Serializable {

	private long id;
	private TrazaModuloAccedido_ensayo trazaModuloAccedido;
	private Date horaFin;
	private String accionRealizada;
	private Date horaInicio;
	private Set<TrazaAtributoModificado_ensayo> trazaAtributoModificados = new HashSet<TrazaAtributoModificado_ensayo>(
			0);
	private Set<TrazaAtributoModificado_ensayo> trazaAtributoModificados_1 = new HashSet<TrazaAtributoModificado_ensayo>(
			0);

	public TrazaAccion_ensayo() {
	}

	public TrazaAccion_ensayo(long id) {
		this.id = id;
	}

	public TrazaAccion_ensayo(long id,
			TrazaModuloAccedido_ensayo trazaModuloAccedido, Date horaFin,
			String accionRealizada, Date horaInicio,
			Set<TrazaAtributoModificado_ensayo> trazaAtributoModificados,
			Set<TrazaAtributoModificado_ensayo> trazaAtributoModificados_1) {
		this.id = id;
		this.trazaModuloAccedido = trazaModuloAccedido;
		this.horaFin = horaFin;
		this.accionRealizada = accionRealizada;
		this.horaInicio = horaInicio;
		this.trazaAtributoModificados = trazaAtributoModificados;
		this.trazaAtributoModificados_1 = trazaAtributoModificados_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modulo_accedido")
	public TrazaModuloAccedido_ensayo getTrazaModuloAccedido() {
		return this.trazaModuloAccedido;
	}

	public void setTrazaModuloAccedido(
			TrazaModuloAccedido_ensayo trazaModuloAccedido) {
		this.trazaModuloAccedido = trazaModuloAccedido;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_fin", length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "accion_realizada")
	public String getAccionRealizada() {
		return this.accionRealizada;
	}

	public void setAccionRealizada(String accionRealizada) {
		if (accionRealizada != null)
			accionRealizada = accionRealizada.trim();
		this.accionRealizada = accionRealizada;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trazaAccion")
	public Set<TrazaAtributoModificado_ensayo> getTrazaAtributoModificados() {
		return this.trazaAtributoModificados;
	}

	public void setTrazaAtributoModificados(
			Set<TrazaAtributoModificado_ensayo> trazaAtributoModificados) {
		this.trazaAtributoModificados = trazaAtributoModificados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trazaAccion")
	public Set<TrazaAtributoModificado_ensayo> getTrazaAtributoModificados_1() {
		return this.trazaAtributoModificados_1;
	}

	public void setTrazaAtributoModificados_1(
			Set<TrazaAtributoModificado_ensayo> trazaAtributoModificados_1) {
		this.trazaAtributoModificados_1 = trazaAtributoModificados_1;
	}

}
