package gehos.ensayo.entity;

// Generated 29-abr-2016 12:17:50 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "comun")
public class Usuario_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String nombre;
	private String username;
	private String password;
	private Date fechaNacimiento;
	private Boolean eliminado;
	private Long cid;
	private Long idPersona;
	private Boolean cuentaHabilitada;
	private String primerApellido;
	private String segundoApellido;
	private String direccionParticular;
	private String cedula;
	private String pasaporte;
	private String telefono;
	private Set<UsuarioEstudio_ensayo> usuarioEstudios = new HashSet<UsuarioEstudio_ensayo>(
			0);
	private Set<Role_ensayo> roles = new HashSet<Role_ensayo>(0);
	private Set<TrazaSession_ensayo> trazaSessions = new HashSet<TrazaSession_ensayo>(
			0);
	private Set<TrazaSession_ensayo> trazaSessions_1 = new HashSet<TrazaSession_ensayo>(
			0);
	private Set<HojaCrd_ensayo> hojaCrds = new HashSet<HojaCrd_ensayo>(0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);
	private Set<ConjuntoDatos_ensayo> conjuntoDatoses = new HashSet<ConjuntoDatos_ensayo>(
			0);
	private Set<Nota_ensayo> notas = new HashSet<Nota_ensayo>(
			0);
	private Set<NotaGeneral_ensayo> notaGenerales = new HashSet<NotaGeneral_ensayo>(
			0);
	private Set<Cronograma_ensayo> cronogramas = new HashSet<Cronograma_ensayo>(
			0);
	private Set<VariableDato_ensayo> variableDatos = new HashSet<VariableDato_ensayo>(
			0);
	private Set<Sujeto_ensayo> sujetos = new HashSet<Sujeto_ensayo>(0);
	private Set<MomentoSeguimientoGeneral_ensayo> momentoSeguimientosG = new HashSet<MomentoSeguimientoGeneral_ensayo>(
			0);
	private Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos = new HashSet<MomentoSeguimientoEspecifico_ensayo>(
			0);
	private Set<Estudio_ensayo> estudios = new HashSet<Estudio_ensayo>(0);
	private Set<CrdEspecifico_ensayo> crdEspecificos = new HashSet<CrdEspecifico_ensayo>(
			0);
	private Set<Causa_ensayo> causas = new HashSet<Causa_ensayo>(
			0);

	public Usuario_ensayo() {
	}

	public Usuario_ensayo(long id, String nombre, String username,
			String password) {
		this.id = id;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
	}

	public Usuario_ensayo(
			long id,
			String nombre,
			String username,
			String password,
			Date fechaNacimiento,
			Boolean eliminado,
			Long cid,
			Long idPersona,
			Boolean cuentaHabilitada,
			String primerApellido,
			String segundoApellido,
			String direccionParticular,
			String cedula,
			String pasaporte,
			String telefono,
			Set<Nota_ensayo> notas,
			Set<NotaGeneral_ensayo> notaGenerales,
			Set<UsuarioEstudio_ensayo> usuarioEstudios,
			Set<Role_ensayo> roles,
			Set<TrazaSession_ensayo> trazaSessions,
			Set<TrazaSession_ensayo> trazaSessions_1,
			Set<HojaCrd_ensayo> hojaCrds,
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria,
			Set<ConjuntoDatos_ensayo> conjuntoDatoses,
			Set<Cronograma_ensayo> cronogramas,
			Set<Estudio_ensayo> estudios,
			Set<CrdEspecifico_ensayo> crdEspecificos,
			Set<Causa_ensayo> causas,
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos,
			Set<MomentoSeguimientoGeneral_ensayo> momentoSeguimientosG,
			Set<VariableDato_ensayo> variableDatos, Set<Sujeto_ensayo> sujetos) {
		this.id = id;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
		this.fechaNacimiento = fechaNacimiento;
		this.eliminado = eliminado;
		this.cid = cid;
		this.idPersona = idPersona;
		this.cuentaHabilitada = cuentaHabilitada;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.direccionParticular = direccionParticular;
		this.cedula = cedula;
		this.pasaporte = pasaporte;
		this.telefono = telefono;
		this.usuarioEstudios = usuarioEstudios;
		this.roles = roles;
		this.trazaSessions = trazaSessions;
		this.trazaSessions_1 = trazaSessions_1;
		this.hojaCrds = hojaCrds;
		this.logEventosAuditoria = logEventosAuditoria;
		this.conjuntoDatoses = conjuntoDatoses;
		this.cronogramas = cronogramas;
		this.sujetos = sujetos;
		this.crdEspecificos = crdEspecificos;
		this.estudios = estudios;
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
		this.momentoSeguimientosG = momentoSeguimientosG;
		this.variableDatos = variableDatos;
		this.causas=causas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "id_persona")
	public Long getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Long idPersona) {
		this.idPersona = idPersona;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		if (nombre != null)
			nombre = nombre.trim();
		this.nombre = nombre;
	}

	@Column(name = "username",  nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		if (username != null)
			username = username.trim();
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		if (password != null)
			password = password.trim();
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "cuenta_habilitada")
	public Boolean getCuentaHabilitada() {
		return this.cuentaHabilitada;
	}

	public void setCuentaHabilitada(Boolean cuentaHabilitada) {
		this.cuentaHabilitada = cuentaHabilitada;
	}

	@Column(name = "primer_apellido")
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		if (primerApellido != null)
			primerApellido = primerApellido.trim();
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido")
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		if (segundoApellido != null)
			segundoApellido = segundoApellido.trim();
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "direccion_particular")
	public String getDireccionParticular() {
		return this.direccionParticular;
	}

	public void setDireccionParticular(String direccionParticular) {
		if (direccionParticular != null)
			direccionParticular = direccionParticular.trim();
		this.direccionParticular = direccionParticular;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		if (cedula != null)
			cedula = cedula.trim();
		this.cedula = cedula;
	}

	@Column(name = "pasaporte")
	public String getPasaporte() {
		return this.pasaporte;
	}

	public void setPasaporte(String pasaporte) {
		if (pasaporte != null)
			pasaporte = pasaporte.trim();
		this.pasaporte = pasaporte;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		if (telefono != null)
			telefono = telefono.trim();
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioEstudio_ensayo> getUsuarioEstudios() {
		return this.usuarioEstudios;
	}

	public void setUsuarioEstudios(Set<UsuarioEstudio_ensayo> usuarioEstudios) {
		this.usuarioEstudios = usuarioEstudios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_in_role", schema = "seguridad", joinColumns = { @JoinColumn(name = "id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_role", nullable = false, updatable = false) })
	public Set<Role_ensayo> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role_ensayo> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<TrazaSession_ensayo> getTrazaSessions() {
		return this.trazaSessions;
	}

	public void setTrazaSessions(Set<TrazaSession_ensayo> trazaSessions) {
		this.trazaSessions = trazaSessions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<TrazaSession_ensayo> getTrazaSessions_1() {
		return this.trazaSessions_1;
	}

	public void setTrazaSessions_1(Set<TrazaSession_ensayo> trazaSessions_1) {
		this.trazaSessions_1 = trazaSessions_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<HojaCrd_ensayo> getHojaCrds() {
		return this.hojaCrds;
	}

	public void setHojaCrds(Set<HojaCrd_ensayo> hojaCrds) {
		this.hojaCrds = hojaCrds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ConjuntoDatos_ensayo> getConjuntoDatoses() {
		return this.conjuntoDatoses;
	}

	public void setConjuntoDatoses(Set<ConjuntoDatos_ensayo> conjuntoDatoses) {
		this.conjuntoDatoses = conjuntoDatoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Cronograma_ensayo> getCronogramas() {
		return this.cronogramas;
	}

	public void setCronogramas(Set<Cronograma_ensayo> cronogramas) {
		this.cronogramas = cronogramas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Nota_ensayo> getNotas() {
		return this.notas;
	}

	public void setNotas(Set<Nota_ensayo> notas) {
		this.notas = notas;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<NotaGeneral_ensayo> getNotaGenerales() {
		return this.notaGenerales;
	}

	public void setNotaGenerales(Set<NotaGeneral_ensayo> notaGenerales) {
		this.notaGenerales = notaGenerales;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Sujeto_ensayo> getSujetos() {
		return this.sujetos;
	}

	public void setSujetos(Set<Sujeto_ensayo> sujetos) {
		this.sujetos = sujetos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Estudio_ensayo> getEstudios() {
		return this.estudios;
	}

	public void setEstudios(Set<Estudio_ensayo> estudios) {
		this.estudios = estudios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<VariableDato_ensayo> getVariableDatos() {
		return this.variableDatos;
	}

	public void setVariableDatos(Set<VariableDato_ensayo> variableDatos) {
		this.variableDatos = variableDatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<MomentoSeguimientoGeneral_ensayo> getMomentoSeguimientosG() {
		return this.momentoSeguimientosG;
	}

	public void setMomentoSeguimientosG(
			Set<MomentoSeguimientoGeneral_ensayo> momentoSeguimientosG) {
		this.momentoSeguimientosG = momentoSeguimientosG;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<MomentoSeguimientoEspecifico_ensayo> getMomentoSeguimientoEspecificos() {
		return this.momentoSeguimientoEspecificos;
	}

	public void setMomentoSeguimientoEspecificos(
			Set<MomentoSeguimientoEspecifico_ensayo> momentoSeguimientoEspecificos) {
		this.momentoSeguimientoEspecificos = momentoSeguimientoEspecificos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<CrdEspecifico_ensayo> getCrdEspecificos() {
		return this.crdEspecificos;
	}

	public void setCrdEspecificos(Set<CrdEspecifico_ensayo> crdEspecificos) {
		this.crdEspecificos = crdEspecificos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Causa_ensayo> getCausas() {
		return this.causas;
	}

	public void setCausas(Set<Causa_ensayo> causas) {
		this.causas = causas;
	}

}
