package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * UsuarioEstudio generated by hbm2java
 */
@Entity
@Table(name = "usuario_estudio", schema = "ensayo")
public class UsuarioEstudio_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private EstudioEntidad_ensayo estudioEntidad;
	private Usuario_ensayo usuario;
	private Role_ensayo role;
	private Long cid;
	private Boolean eliminado;

	public UsuarioEstudio_ensayo() {
	}

	public UsuarioEstudio_ensayo(long id, EstudioEntidad_ensayo estudioEntidad,
			Usuario_ensayo usuario) {
		this.id = id;
		this.estudioEntidad = estudioEntidad;
		this.usuario = usuario;
	}

	public UsuarioEstudio_ensayo(long id, EstudioEntidad_ensayo estudioEntidad,
			Usuario_ensayo usuario, Role_ensayo role, Long cid,
			Boolean eliminado) {
		this.id = id;
		this.estudioEntidad = estudioEntidad;
		this.usuario = usuario;
		this.role = role;
		this.cid = cid;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estudio", nullable = false)
	@NotNull
	public EstudioEntidad_ensayo getEstudioEntidad() {
		return this.estudioEntidad;
	}

	public void setEstudioEntidad(EstudioEntidad_ensayo estudioEntidad) {
		this.estudioEntidad = estudioEntidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	@NotNull
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol")
	public Role_ensayo getRole() {
		return this.role;
	}

	public void setRole(Role_ensayo role) {
		this.role = role;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
