package gehos.ensayo.entity;

// Generated 09-sep-2016 16:12:22 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Variable generated by hbm2java
 */
@Entity
@Table(name = "variable", schema = "ensayo")
public class Variable_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private EstadoVariable_ensayo estadoVariable;
	private GrupoVariables_ensayo grupoVariables;
	private Usuario_ensayo usuario;
	private PresentacionFormulario_ensayo presentacionFormulario;
	private TipoDato_ensayo tipoDato;
	private Seccion_ensayo seccion;
	private Nomenclador_ensayo nomenclador;
	private String nombreVariable;
	private String descripcionVariable;
	private String textoIzquierdaVariable;
	private String unidadesVariable;
	private Long idClinica; 
	private String textoDerechaVariable;
	private String encabezadoVariable;
	private String subencabezadoVariable;
	private Long numeroColumna;
	private Float numeroPregunta;
	private Long cid;
	private Boolean eliminado;
	private String ubicacionRespuesta;
	private Boolean requerido;
	private Boolean unica;
	private Boolean critica;
	private String visibilidadVariable;
	private String condicionVisibilidadVariable;
	private Set<Regla_ensayo> reglas = new HashSet<Regla_ensayo>(0);
	private Set<Nota_ensayo> notas = new HashSet<Nota_ensayo>(0);
	private Set<LogEventosAuditoria_ensayo> logEventosAuditoria = new HashSet<LogEventosAuditoria_ensayo>(
			0);
	public Variable_ensayo() {
	}

	public Variable_ensayo(long id,
			PresentacionFormulario_ensayo presentacionFormulario,
			TipoDato_ensayo tipoDato, Seccion_ensayo seccion) {
		this.id = id;
		this.presentacionFormulario = presentacionFormulario;
		this.tipoDato = tipoDato;
		this.seccion = seccion;
	}

	public Variable_ensayo(long id, EstadoVariable_ensayo estadoVariable,
			GrupoVariables_ensayo grupoVariables, Usuario_ensayo usuario,
			PresentacionFormulario_ensayo presentacionFormulario,
			TipoDato_ensayo tipoDato, Seccion_ensayo seccion,
			Nomenclador_ensayo nomenclador, String nombreVariable,
			String descripcionVariable, String textoIzquierdaVariable,
			String unidadesVariable, String textoDerechaVariable,
			String encabezadoVariable, String subencabezadoVariable,
			 Long numeroColumna, Long idClinica, Float numeroPregunta, Long cid, 
			Boolean eliminado, Boolean unica, String ubicacionRespuesta, Boolean requerido, Boolean critica,
			String visibilidadVariable, String condicionVisibilidadVariable,
			
			Set<Regla_ensayo> reglas,
			
			Set<Nota_ensayo> notas) {
		this.id = id;
		this.estadoVariable = estadoVariable;
		this.grupoVariables = grupoVariables;
		this.presentacionFormulario = presentacionFormulario;
		this.tipoDato = tipoDato;
		this.seccion = seccion;
		this.idClinica = idClinica; 
		this.nomenclador = nomenclador;
		this.nombreVariable = nombreVariable;
		this.descripcionVariable = descripcionVariable;
		this.textoIzquierdaVariable = textoIzquierdaVariable;
		this.unidadesVariable = unidadesVariable;
		this.textoDerechaVariable = textoDerechaVariable;
		this.encabezadoVariable = encabezadoVariable;
		this.subencabezadoVariable = subencabezadoVariable;
		this.numeroColumna = numeroColumna;
		this.numeroPregunta = numeroPregunta;
		this.cid = cid;
		this.eliminado = eliminado;
		this.unica=unica;
		this.ubicacionRespuesta = ubicacionRespuesta;
		this.requerido = requerido;
		this.critica = critica;
		this.visibilidadVariable = visibilidadVariable;
		this.condicionVisibilidadVariable = condicionVisibilidadVariable;
		this.usuario = usuario;

		this.reglas = reglas;

		this.notas = notas;

	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_variable")
	public EstadoVariable_ensayo getEstadoVariable() {
		return this.estadoVariable;
	}

	public void setEstadoVariable(EstadoVariable_ensayo estadoVariable) {
		this.estadoVariable = estadoVariable;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "variable")
	private Set<LogEventosAuditoria_ensayo> getLogEventosAuditoria() {
		return logEventosAuditoria;
	}

	private void setLogEventosAuditoria(
			Set<LogEventosAuditoria_ensayo> logEventosAuditoria) {
		this.logEventosAuditoria = logEventosAuditoria;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_variables")
	public GrupoVariables_ensayo getGrupoVariables() {
		return this.grupoVariables;
	}

	public void setGrupoVariables(GrupoVariables_ensayo grupoVariables) {
		this.grupoVariables = grupoVariables;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_presentacion_formulario", nullable = false)
	@NotNull
	public PresentacionFormulario_ensayo getPresentacionFormulario() {
		return this.presentacionFormulario;
	}

	public void setPresentacionFormulario(
			PresentacionFormulario_ensayo presentacionFormulario) {
		this.presentacionFormulario = presentacionFormulario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tipo_dato", nullable = false)
	@NotNull
	public TipoDato_ensayo getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(TipoDato_ensayo tipoDato) {
		this.tipoDato = tipoDato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_seccion", nullable = false)
	@NotNull
	public Seccion_ensayo getSeccion() {
		return this.seccion;
	}

	public void setSeccion(Seccion_ensayo seccion) {
		this.seccion = seccion;
	}
	
	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "id_nomenclador")
	public Nomenclador_ensayo getNomenclador() {
		return this.nomenclador;
	}

	public void setNomenclador(Nomenclador_ensayo nomenclador) {
		this.nomenclador = nomenclador;
	}

	@Column(name = "nombre_variable", length = 4000)
	@Length(max = 4000)
	public String getNombreVariable() {
		return this.nombreVariable;
	}

	public void setNombreVariable(String nombreVariable) {
		if (nombreVariable != null)
			nombreVariable = nombreVariable.trim();
		this.nombreVariable = nombreVariable;
	}

	@Column(name = "descripcion_variable", length = 4000)
	@Length(max = 4000)
	public String getDescripcionVariable() {
		return this.descripcionVariable;
	}

	public void setDescripcionVariable(String descripcionVariable) {
		if (descripcionVariable != null)
			descripcionVariable = descripcionVariable.trim();
		this.descripcionVariable = descripcionVariable;
	}

	@Column(name = "texto_izquierda_variable", length = 4000)
	@Length(max = 4000)
	public String getTextoIzquierdaVariable() {
		return this.textoIzquierdaVariable;
	}

	public void setTextoIzquierdaVariable(String textoIzquierdaVariable) {
		if (textoIzquierdaVariable != null)
			textoIzquierdaVariable = textoIzquierdaVariable.trim();
		if (textoIzquierdaVariable == "")
			textoIzquierdaVariable = null;
		this.textoIzquierdaVariable = textoIzquierdaVariable;
	}

	@Column(name = "unidades_variable", length = 4000)
	@Length(max = 4000)
	public String getUnidadesVariable() {
		return this.unidadesVariable;
	}

	public void setUnidadesVariable(String unidadesVariable) {
		if (unidadesVariable != null)
			unidadesVariable = unidadesVariable.trim();
		if (unidadesVariable == "")
			unidadesVariable = null;
		this.unidadesVariable = unidadesVariable;
	}

	@Column(name = "texto_derecha_variable", length = 4000)
	@Length(max = 4000)
	public String getTextoDerechaVariable() {
		return this.textoDerechaVariable;
	}

	public void setTextoDerechaVariable(String textoDerechaVariable) {
		if (textoDerechaVariable != null)
			textoDerechaVariable = textoDerechaVariable.trim();
		if (textoDerechaVariable == "")
			textoDerechaVariable = null;
		this.textoDerechaVariable = textoDerechaVariable;
	}

	@Column(name = "encabezado_variable", length = 4000)
	@Length(max = 4000)
	public String getEncabezadoVariable(){
		if(this.encabezadoVariable != null && this.encabezadoVariable.contains(":") && this.encabezadoVariable.indexOf(":") == (this.encabezadoVariable.length() - 1))			
			this.encabezadoVariable = this.encabezadoVariable.substring(0, this.encabezadoVariable.length() - 1);
		return this.encabezadoVariable;
	}

	public void setEncabezadoVariable(String encabezadoVariable) {
		if (encabezadoVariable != null)
			encabezadoVariable = encabezadoVariable.trim();
		if (encabezadoVariable == "")
			encabezadoVariable = null;
		this.encabezadoVariable = encabezadoVariable;
	}

	@Column(name = "subencabezado_variable", length = 4000)
	@Length(max = 4000)
	public String getSubencabezadoVariable() {
		return this.subencabezadoVariable;
	}

	public void setSubencabezadoVariable(String subencabezadoVariable) {
		if (subencabezadoVariable != null)
			subencabezadoVariable = subencabezadoVariable.trim();
		if (subencabezadoVariable == "")
			subencabezadoVariable = null;
		this.subencabezadoVariable = subencabezadoVariable;
	}

	@Column(name = "numero_columna")
	public Long getNumeroColumna() {
		return this.numeroColumna;
	}

	public void setNumeroColumna(Long numeroColumna) {
		this.numeroColumna = numeroColumna;
	}

	@Column(name = "numero_pregunta")
	public Float getNumeroPregunta() {
		return this.numeroPregunta;
	}

	public void setNumeroPregunta(Float numeroPregunta) {
		this.numeroPregunta = numeroPregunta;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}
	
	@Column(name = "id_clinicas") 
	  public Long getIdClinica() { 
	    return idClinica; 
	  } 
	 
	  public void setIdClinica(Long idClinica) { 
	    this.idClinica = idClinica; 
	  } 

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}
	
	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}
	

	@Column(name = "unica")
	public Boolean getUnica() {
		return this.unica;
	}

	public void setUnica(Boolean unica) {
		this.unica = unica;
	}

	@Column(name = "ubicacion_respuesta", length = 20)
	@Length(max = 20)
	public String getUbicacionRespuesta() {
		return this.ubicacionRespuesta;
	}

	public void setUbicacionRespuesta(String ubicacionRespuesta) {
		if (ubicacionRespuesta != null)
			ubicacionRespuesta = ubicacionRespuesta.trim();
		if (ubicacionRespuesta == "")
			ubicacionRespuesta = null;
		this.ubicacionRespuesta = ubicacionRespuesta;
	}

	@Column(name = "requerido")
	public Boolean getRequerido() {
		return this.requerido;
	}

	public void setRequerido(Boolean requerido) {
		this.requerido = requerido;
	}
	@Column(name = "critica")
	public Boolean getCritica() {
		return this.critica;
	}
	public void setCritica(Boolean critica) {
		this.critica = critica;
		}
	@Column(name = "visibilidad_variable", length = 10)
	@Length(max = 10)
	public String getVisibilidadVariable() {
		return this.visibilidadVariable;
	}

	public void setVisibilidadVariable(String visibilidadVariable) {
		if (visibilidadVariable != null)
			visibilidadVariable = visibilidadVariable.trim();
		if (visibilidadVariable == "")
			visibilidadVariable = null;
		this.visibilidadVariable = visibilidadVariable;
	}

	@Column(name = "condicion_visibilidad_variable")
	public String getCondicionVisibilidadVariable() {
		return this.condicionVisibilidadVariable;
	}

	public void setCondicionVisibilidadVariable(
			String condicionVisibilidadVariable) {
		if (condicionVisibilidadVariable != null)
			condicionVisibilidadVariable = condicionVisibilidadVariable.trim();
		if (condicionVisibilidadVariable == "")
			condicionVisibilidadVariable = null;
		this.condicionVisibilidadVariable = condicionVisibilidadVariable;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "variable")
	public Set<Regla_ensayo> getReglas() {
		return this.reglas;
	}

	public void setReglas(Set<Regla_ensayo> reglas) {
		this.reglas = reglas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "variable")
	public Set<Nota_ensayo> getNotas() {
		return this.notas;
	}

	public void setNotas(Set<Nota_ensayo> notas) {
		this.notas = notas;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@Override
	public int hashCode(){
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idClinica == null) ? 0 : idClinica.hashCode());
		result = prime * result + ((nombreVariable == null) ? 0 : nombreVariable.hashCode());
		result = prime * result + ((numeroColumna == null) ? 0 : numeroColumna.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj){
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Variable_ensayo other = (Variable_ensayo) obj;
		if (idClinica == null){
			if (other.idClinica != null)
				return false;
		} else if (!idClinica.equals(other.idClinica))
			return false;
		if (nombreVariable == null) {
			if (other.nombreVariable != null)
				return false;
		} else if (!nombreVariable.equals(other.nombreVariable))
			return false;
		if (numeroColumna == null) {
			if (other.numeroColumna != null)
				return false;
		} else if (!numeroColumna.equals(other.numeroColumna))
			return false;
		return true;
	}

}
