package gehos.ensayo.entity;

// Generated 25-oct-2016 17:20:41 by Hibernate Tools 3.4.0.CR1
// Yasmani Ledesma Valdes  ylvaldes@uci.cu

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * VariableDato generated by hbm2java
 */
@Entity
@Table(name = "variable_dato", schema = "ensayo")
public class VariableDato_ensayo implements java.io.Serializable {

	private long id;
	private Integer version;
	private EstadoVariableDato_ensayo estadoVariableDato;
	private CrdEspecifico_ensayo crdEspecifico;
	private Variable_ensayo variable;
	private Long cid;
	private Usuario_ensayo usuario;
	private Boolean eliminado;
	private Integer contGrupo;
	private String valor;
	private Long idEstadoDato;	
	private Set<Nota_ensayo> notas = new HashSet<Nota_ensayo>(0);

	public VariableDato_ensayo() {
	}

	public VariableDato_ensayo(long id, Variable_ensayo variable) {
		this.id = id;
		this.variable = variable;
	}

	public VariableDato_ensayo(long id,
			EstadoVariableDato_ensayo estadoVariableDato,
			CrdEspecifico_ensayo crdEspecifico, Usuario_ensayo usuario,
			Variable_ensayo variable, Long cid, Boolean eliminado,
			Integer contGrupo, String valor, Long idEstadoDato,Set<Nota_ensayo> notas) {
		this.id = id;
		this.estadoVariableDato = estadoVariableDato;
		this.crdEspecifico = crdEspecifico;
		this.variable = variable;
		this.cid = cid;
		this.usuario = usuario;
		this.eliminado = eliminado;
		this.contGrupo = contGrupo;
		this.valor = valor;
		this.idEstadoDato = idEstadoDato;
		this.notas = notas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_variable_dato")
	public EstadoVariableDato_ensayo getEstadoVariableDato() {
		return this.estadoVariableDato;
	}

	public void setEstadoVariableDato(
			EstadoVariableDato_ensayo estadoVariableDato) {
		this.estadoVariableDato = estadoVariableDato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario_ensayo getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_ensayo usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_crd_esp")
	public CrdEspecifico_ensayo getCrdEspecifico() {
		return this.crdEspecifico;
	}

	public void setCrdEspecifico(CrdEspecifico_ensayo crdEspecifico) {
		this.crdEspecifico = crdEspecifico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_variable", nullable = false)
	@NotNull
	public Variable_ensayo getVariable() {
		return this.variable;
	}

	public void setVariable(Variable_ensayo variable) {
		this.variable = variable;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cont_grupo")
	public Integer getContGrupo() {
		return this.contGrupo;
	}

	public void setContGrupo(Integer contGrupo) {
		this.contGrupo = contGrupo;
	}

	@Column(name = "valor", length = 500)
	@Length(max = 500)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "id_estado_dato")
	public Long getIdEstadoDato() {
		return this.idEstadoDato;
	}

	public void setIdEstadoDato(Long idEstadoDato) {
		this.idEstadoDato = idEstadoDato;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "variableDato")
	public Set<Nota_ensayo> getNotas() {
		return notas;
	}

	public void setNotas(Set<Nota_ensayo> notas) {
		this.notas = notas;
	}

}
