package comun

import gehos.autenticacion.session.custom.PasswordStrength;
#Weaker, Weak, Medium, Strong

rule "PasswordStrengthType"

	when		
		$limit: PasswordStrength()
	then
		$limit.setPasswordStrengthType("Strong");
end

rule "LifeCicle"

	when		
		$limit: PasswordStrength()
	then
		$limit.setPasswordLifeCicle(90);
end

rule "PasswordStrengthRegex Strong"

	when		
		PasswordStrength(passwordStrengthType=="Strong")
		$limit: PasswordStrength()
	then
		$limit.setPasswordStrengthRegex("password_strong");
end

rule "PasswordStrengthRegex Medium"

	when		
		PasswordStrength(passwordStrengthType=="Medium")
		$limit: PasswordStrength()
	then
		$limit.setPasswordStrengthRegex("password_medium");
end

rule "PasswordStrengthRegex Weak"

	when		
		PasswordStrength(passwordStrengthType=="Weak")
		$limit: PasswordStrength()
	then
		$limit.setPasswordStrengthRegex("password_weak");
end

rule "PasswordStrengthRegex Weaker"

	when		
		PasswordStrength(passwordStrengthType=="Weaker")
		$limit: PasswordStrength()
	then
		$limit.setPasswordStrengthRegex("password_weaker");
end

rule "Length"

	when		
		$limit: PasswordStrength()
	then
		$limit.setPasswordLength(8);
end