package gehos.notificaciones.entity;

// Generated 29-may-2009 19:27:42 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Notificacion generated by hbm2java
 */
@Entity
@Table(name = "notificacion", schema = "seguridad")
public class Notificacion implements java.io.Serializable {

	private Long id;
	private TipoNotificacion tipoNotificacion;
	private Usuario_notifications usuario;
	private Boolean importante;
	private Date fecha;
	private Date hora;
	private Long paramValue;
	private Set<NotificacionInUser> notificacionInUsers = new HashSet<NotificacionInUser>(
			0);

	public Notificacion() {
	}

	public Notificacion(Long id) {
		this.id = id;
	}

	public Notificacion(Long id, TipoNotificacion tipoNotificacion,
			Usuario_notifications usuario, Date fecha, Date hora, Long paramValue,
			Set<NotificacionInUser> notificacionInUsers) {
		this.id = id;
		this.tipoNotificacion = tipoNotificacion;
		this.usuario = usuario;
		this.fecha = fecha;
		this.hora = hora;
		this.paramValue = paramValue;
		this.notificacionInUsers = notificacionInUsers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tipo_notificacion")
	public TipoNotificacion getTipoNotificacion() {
		return this.tipoNotificacion;
	}

	public void setTipoNotificacion(TipoNotificacion tipoNotificacion) {
		this.tipoNotificacion = tipoNotificacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "creador")
	public Usuario_notifications getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_notifications usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "param_value")
	public Long getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(Long paramValue) {
		this.paramValue = paramValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificacion")
	public Set<NotificacionInUser> getNotificacionInUsers() {
		return this.notificacionInUsers;
	}

	public void setNotificacionInUsers(
			Set<NotificacionInUser> notificacionInUsers) {
		this.notificacionInUsers = notificacionInUsers;
	}

	@Column(name = "importante")
	public Boolean getImportante() {
		return importante;
	}

	public void setImportante(Boolean importante) {
		this.importante = importante;
	}

}
