package gehos.notificaciones.entity;

// Generated 29-may-2009 19:27:42 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

/**
 * TipoNotificacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_notificacion", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class TipoNotificacion implements java.io.Serializable {

	private Long id;
	private String descripcion;
	private String codigo;
	private String url;
	private Long idModulo;
	private Set<Notificacion> notificacions = new HashSet<Notificacion>(0);

	public TipoNotificacion() {
	}

	public TipoNotificacion(Long id) {
		this.id = id;
	}

	public TipoNotificacion(Long id, String descripcion, String codigo,
			String url, Long idModulo, Set<Notificacion> notificacions) {
		this.id = id;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.url = url;
		this.idModulo = idModulo;
		this.notificacions = notificacions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "codigo", unique = true)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "id_modulo")
	public Long getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(Long idModulo) {
		this.idModulo = idModulo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoNotificacion")
	public Set<Notificacion> getNotificacions() {
		return this.notificacions;
	}

	public void setNotificacions(Set<Notificacion> notificacions) {
		this.notificacions = notificacions;
	}

}
