package gehos.autorizacion.entity;

// Generated 21-mar-2009 16:00:24 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Funcionalidad generated by hbm2java
 */
@Entity
@Table(name = "funcionalidad", schema = "seguridad")
public class Funcionalidad_permissions implements java.io.Serializable {

	private Long id;
	private Integer version;
	private MenuItem menuItem;
	private String label;
	private String nombre;
	private String url;
	private Boolean eliminado;
	private Long cid;
	private int orden;
	private String imagen;
	

	public Funcionalidad_permissions() {
	}

	public Funcionalidad_permissions(Long id, int orden) {
		this.id = id;
		this.orden = orden;
	}

	public Funcionalidad_permissions(Long id, String label, String url,
			Boolean eliminado, Long cid, int orden, String imagen) {
		this.id = id;
		/*this.modulo = modulo;*/
		this.label = label;
		this.url = url;
		this.eliminado = eliminado;
		this.cid = cid;
		this.orden = orden;
		this.imagen = imagen;
		
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	


	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	@Column(name = "label", length = 150)
	@Length(max = 150)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "url", length = 200)
	@Length(max = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "orden", nullable = false)
	@NotNull
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "imagen")
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "funcionalidad")
	public MenuItem getMenuItem() {
		return menuItem;
	}

	public void setMenuItem(MenuItem menuItem) {
		this.menuItem = menuItem;
	}

}
