package gehos.autorizacion.entity;

// Generated 21-mar-2009 16:00:24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * MenuItem generated by hbm2java
 */
@Entity
@Table(name = "menu_item", schema = "seguridad")
public class MenuItem implements java.io.Serializable {

	private Long id;
	private Integer version;
	//private Long functionalityId;
	private Boolean eliminado;
	private Funcionalidad_permissions funcionalidad;
	private Long cid;
	private Set<UserMenuitemPermission> userMenuitemPermissions = new HashSet<UserMenuitemPermission>(
			0);
	private Set<RoleMenuitemPermission> roleMenuitemPermissions = new HashSet<RoleMenuitemPermission>(
			0);

	public MenuItem() {
	}

	public MenuItem(Long id) {
		this.id = id;
	}

	public MenuItem(Long id, Long functionalityId, Boolean eliminado,
			Long cid, Set<UserMenuitemPermission> userMenuitemPermissions,
			Set<RoleMenuitemPermission> roleMenuitemPermissions) {
		this.id = id;
	/*	this.functionalityId = functionalityId;*/
		this.eliminado = eliminado;
		this.cid = cid;
		this.userMenuitemPermissions = userMenuitemPermissions;
		this.roleMenuitemPermissions = roleMenuitemPermissions;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "funcionalidad"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

/*	@Column(name = "functionality_id", unique = true)
	public Long getFunctionalityId() {
		return this.functionalityId;
	}

	public void setFunctionalityId(Long functionalityId) {
		this.functionalityId = functionalityId;
	}*/

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Fetch(FetchMode.SUBSELECT)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItem")
	public Set<UserMenuitemPermission> getUserMenuitemPermissions() {
		return this.userMenuitemPermissions;
	}

	public void setUserMenuitemPermissions(
			Set<UserMenuitemPermission> userMenuitemPermissions) {
		this.userMenuitemPermissions = userMenuitemPermissions;
	}

	@Fetch(FetchMode.SUBSELECT)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuItem")
	public Set<RoleMenuitemPermission> getRoleMenuitemPermissions() {
		return this.roleMenuitemPermissions;
	}

	public void setRoleMenuitemPermissions(
			Set<RoleMenuitemPermission> roleMenuitemPermissions) {
		this.roleMenuitemPermissions = roleMenuitemPermissions;
	}

    @OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Funcionalidad_permissions getFuncionalidad() {
		return funcionalidad;
	}

	public void setFuncionalidad(Funcionalidad_permissions funcionalidad) {
		this.funcionalidad = funcionalidad;
	}

}
