package gehos.autorizacion.entity;

// Generated 21-mar-2009 16:00:24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.validator.NotNull;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "virtual_path"))
public class Resource implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String virtualPath;
	private Boolean eliminado;
	private Long cid;
	private Set<RoleResourcePermission> roleResourcePermissions = new HashSet<RoleResourcePermission>(
			0);
	private Set<UserResourcePermission> userResourcePermissions = new HashSet<UserResourcePermission>(
			0);

	public Resource() {
	}

	public Resource(Long id) {
		this.id = id;
	}

	public Resource(Long id, String virtualPath, Boolean eliminado, Long cid,
			Set<RoleResourcePermission> roleResourcePermissions,
			Set<UserResourcePermission> userResourcePermissions) {
		this.id = id;
		this.virtualPath = virtualPath;
		this.eliminado = eliminado;
		this.cid = cid;
		this.roleResourcePermissions = roleResourcePermissions;
		this.userResourcePermissions = userResourcePermissions;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "virtual_path", unique = true)
	public String getVirtualPath() {
		return this.virtualPath;
	}

	public void setVirtualPath(String virtualPath) {
		this.virtualPath = virtualPath;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Fetch(FetchMode.SUBSELECT)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<RoleResourcePermission> getRoleResourcePermissions() {
		return this.roleResourcePermissions;
	}

	public void setRoleResourcePermissions(
			Set<RoleResourcePermission> roleResourcePermissions) {
		this.roleResourcePermissions = roleResourcePermissions;
	}

	@Fetch(FetchMode.SUBSELECT)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<UserResourcePermission> getUserResourcePermissions() {
		return this.userResourcePermissions;
	}

	public void setUserResourcePermissions(
			Set<UserResourcePermission> userResourcePermissions) {
		this.userResourcePermissions = userResourcePermissions;
	}

}
