package gehos.autorizacion.entity;

// Generated 21-mar-2009 16:00:24 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.validator.NotNull;

/**
 * RoleResourcePermission generated by hbm2java
 */
@Entity
@Table(name = "role_resource_permission", schema = "seguridad")
public class RoleResourcePermission implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Role_permissions role;
	private Resource resource;
	
	private boolean allowed;
	private Boolean eliminado;
	private Long cid;

	public RoleResourcePermission() {
	}

	public RoleResourcePermission(Long id, boolean allowed) {
		this.id = id;
		this.allowed = allowed;
	}

	public RoleResourcePermission(Long id, Role_permissions role, Resource resource,
			boolean allowed, Boolean eliminado, Long cid) {
		this.id = id;
		this.role = role;
		this.resource = resource;
		
		this.allowed = allowed;
		this.eliminado = eliminado;
		this.cid = cid;
	}

/*	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull*/
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Fetch(FetchMode.JOIN)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id")
	public Role_permissions getRole() {
		return this.role;
	}

	public void setRole(Role_permissions role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_id")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}



	@Column(name = "allowed", nullable = false)
	@NotNull
	public boolean isAllowed() {
		return this.allowed;
	}

	public void setAllowed(boolean allowed) {
		this.allowed = allowed;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
