package gehos.autorizacion.entity;

// Generated 21-mar-2009 16:00:24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Role_permissions implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String name;
	private Boolean eliminado;
	private Long cid;
	private Set<RoleResourcePermission> roleResourcePermissions = new HashSet<RoleResourcePermission>(
			0);
	private Set<RoleMenuitemPermission> roleMenuitemPermissions = new HashSet<RoleMenuitemPermission>(
			0);

	public Role_permissions() {
	}

	public Role_permissions(Long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Role_permissions(Long id, String name, Boolean eliminado, Long cid,
			Set<RoleResourcePermission> roleResourcePermissions,
			Set<RoleMenuitemPermission> roleMenuitemPermissions) {
		this.id = id;
		this.name = name;
		this.eliminado = eliminado;
		this.cid = cid;
		this.roleResourcePermissions = roleResourcePermissions;
		this.roleMenuitemPermissions = roleMenuitemPermissions;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RoleResourcePermission> getRoleResourcePermissions() {
		return this.roleResourcePermissions;
	}

	public void setRoleResourcePermissions(
			Set<RoleResourcePermission> roleResourcePermissions) {
		this.roleResourcePermissions = roleResourcePermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RoleMenuitemPermission> getRoleMenuitemPermissions() {
		return this.roleMenuitemPermissions;
	}

	public void setRoleMenuitemPermissions(
			Set<RoleMenuitemPermission> roleMenuitemPermissions) {
		this.roleMenuitemPermissions = roleMenuitemPermissions;
	}

}
