package gehos.autorizacion.entity;

// Generated 21-mar-2009 16:00:24 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.validator.NotNull;

/**
 * UserMenuitemPermission generated by hbm2java
 */
@Entity
@Table(name = "user_menuitem_permission", schema = "seguridad")
public class UserMenuitemPermission implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Usuario_permissions usuario;
	private Funcionalidad_permissions modulo;
	private MenuItem menuItem;
	private Boolean allowed;
	private Boolean eliminado;
	private Long cid;

	public UserMenuitemPermission() {
	}

	public UserMenuitemPermission(Long id) {
		this.id = id;
	}

	public UserMenuitemPermission(Long id, Usuario_permissions usuario, Funcionalidad_permissions modulo,
			MenuItem menuItem, Boolean allowed, Boolean eliminado, Long cid) {
		this.id = id;
		this.usuario = usuario;
		this.modulo = modulo;
		this.menuItem = menuItem;
		this.allowed = allowed;
		this.eliminado = eliminado;
		this.cid = cid;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Fetch(FetchMode.JOIN)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public Usuario_permissions getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario_permissions usuario) {
		this.usuario = usuario;
	}

	@Fetch(FetchMode.JOIN)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "module_id")
	public Funcionalidad_permissions getModulo() {
		return this.modulo;
	}

	public void setModulo(Funcionalidad_permissions modulo) {
		this.modulo = modulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_item_id")
	public MenuItem getMenuItem() {
		return this.menuItem;
	}

	public void setMenuItem(MenuItem menuItem) {
		this.menuItem = menuItem;
	}

	@Column(name = "allowed")
	public Boolean getAllowed() {
		return this.allowed;
	}

	public void setAllowed(Boolean allowed) {
		this.allowed = allowed;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
