package gehos.autorizacion.entity;

// Generated 21-mar-2009 16:00:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "comun", uniqueConstraints = {
		@UniqueConstraint(columnNames = "username"),
		@UniqueConstraint(columnNames = "nombre") })
public class Usuario_permissions implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String nombre;
	private String username;
	private String password;
	private Date fechaNacimiento;
	private Boolean eliminado;
	private Long cid;
	private Boolean cuentaHabilitada;
	private String primerApellido;
	private String segundoApellido;
	private String direccionParticular;
	private String cedula;
	private String pasaporte;
	private String telefono;
	private Long idTipoIdentidad;
	private Long idProfile;
	private Set<UserMenuitemPermission> userMenuitemPermissions = new HashSet<UserMenuitemPermission>(
			0);
	private Set<UserResourcePermission> userResourcePermissions = new HashSet<UserResourcePermission>(
			0);
	private Set<UserEntityPermission> userEntityPermissions = new HashSet<UserEntityPermission>(
			0);

	public Usuario_permissions() {
	}

	public Usuario_permissions(Long id, String nombre, String username, String password) {
		this.id = id;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
	}

	public Usuario_permissions(Long id, String nombre, String username, String password,
			Date fechaNacimiento, Boolean eliminado, Long cid,
			Boolean cuentaHabilitada, String primerApellido,
			String segundoApellido, String direccionParticular, String cedula,
			String pasaporte, String telefono, Long idTipoIdentidad,
			Long idProfile,
			Set<UserMenuitemPermission> userMenuitemPermissions,
			Set<UserResourcePermission> userResourcePermissions) {
		this.id = id;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
		this.fechaNacimiento = fechaNacimiento;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cuentaHabilitada = cuentaHabilitada;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.direccionParticular = direccionParticular;
		this.cedula = cedula;
		this.pasaporte = pasaporte;
		this.telefono = telefono;
		this.idTipoIdentidad = idTipoIdentidad;
		this.idProfile = idProfile;
		this.userMenuitemPermissions = userMenuitemPermissions;
		this.userResourcePermissions = userResourcePermissions;
	}

/*	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull*/
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "username", unique = true, nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "cuenta_habilitada")
	public Boolean getCuentaHabilitada() {
		return this.cuentaHabilitada;
	}

	public void setCuentaHabilitada(Boolean cuentaHabilitada) {
		this.cuentaHabilitada = cuentaHabilitada;
	}

	@Column(name = "primer_apellido")
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido")
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "direccion_particular")
	public String getDireccionParticular() {
		return this.direccionParticular;
	}

	public void setDireccionParticular(String direccionParticular) {
		this.direccionParticular = direccionParticular;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "pasaporte")
	public String getPasaporte() {
		return this.pasaporte;
	}

	public void setPasaporte(String pasaporte) {
		this.pasaporte = pasaporte;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "id_tipo_identidad")
	public Long getIdTipoIdentidad() {
		return this.idTipoIdentidad;
	}

	public void setIdTipoIdentidad(Long idTipoIdentidad) {
		this.idTipoIdentidad = idTipoIdentidad;
	}

	@Column(name = "id_profile")
	public Long getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(Long idProfile) {
		this.idProfile = idProfile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UserMenuitemPermission> getUserMenuitemPermissions() {
		return this.userMenuitemPermissions;
	}

	public void setUserMenuitemPermissions(
			Set<UserMenuitemPermission> userMenuitemPermissions) {
		this.userMenuitemPermissions = userMenuitemPermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UserResourcePermission> getUserResourcePermissions() {
		return this.userResourcePermissions;
	}

	public void setUserResourcePermissions(
			Set<UserResourcePermission> userResourcePermissions) {
		this.userResourcePermissions = userResourcePermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UserEntityPermission> getUserEntityPermissions() {
		return userEntityPermissions;
	}

	public void setUserEntityPermissions(
			Set<UserEntityPermission> userEntityPermissions) {
		this.userEntityPermissions = userEntityPermissions;
	}

}
