package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * DatosLaborales generated by hbm2java
 */
@Entity
@Table(name = "datos_laborales", schema = "hc_local")
public class DatosLaborales_update implements java.io.Serializable {

	private long id;
	private Integer version;
	private DivisionPersonal_update divisionPersonal;
	private Sociedad_update sociedad;
	private Division_update division;
	private SubdivisionPersonal_update subdivisionPersonal;
	private GrupoPersonal_update grupoPersonal;
	private EstadoLaboral_update estadoLaboral;
	private Formacion_update formacion;
	private TipoNomina_update tipoNomina;
	private UnidadOrganizativa_update unidadOrganizativa;
	private ManoDominante_update manoDominante;
	private TipoZonaLaboral_update tipoZonaLaboral;
	private Posicion_update posicion;
	private String telefonoOficina;
	private String numeroPersonal;
	private Boolean aseguradoIvss;
	private Integer numHijos;
	private Long cid;
	private Date tiempoServicio;
	private Boolean eliminado;
	private Set<Persona_update> personas = new HashSet<Persona_update>(
			0);

	public DatosLaborales_update() {
	}

	public DatosLaborales_update(long id) {
		this.id = id;
	}

	public DatosLaborales_update(long id,
			DivisionPersonal_update divisionPersonal,
			Sociedad_update sociedad, Division_update division,
			SubdivisionPersonal_update subdivisionPersonal,
			GrupoPersonal_update grupoPersonal,
			EstadoLaboral_update estadoLaboral,
			Formacion_update formacion,
			TipoNomina_update tipoNomina,
			UnidadOrganizativa_update unidadOrganizativa,
			ManoDominante_update manoDominante,
			TipoZonaLaboral_update tipoZonaLaboral,
			Posicion_update posicion, String telefonoOficina,
			String numeroPersonal, Boolean aseguradoIvss, Integer numHijos,
			Long cid, Date tiempoServicio, Boolean eliminado,
			Set<Persona_update> personas) {
		this.id = id;
		this.divisionPersonal = divisionPersonal;
		this.sociedad = sociedad;
		this.division = division;
		this.subdivisionPersonal = subdivisionPersonal;
		this.grupoPersonal = grupoPersonal;
		this.estadoLaboral = estadoLaboral;
		this.formacion = formacion;
		this.tipoNomina = tipoNomina;
		this.unidadOrganizativa = unidadOrganizativa;
		this.manoDominante = manoDominante;
		this.tipoZonaLaboral = tipoZonaLaboral;
		this.posicion = posicion;
		this.telefonoOficina = telefonoOficina;
		this.numeroPersonal = numeroPersonal;
		this.aseguradoIvss = aseguradoIvss;
		this.numHijos = numHijos;
		this.cid = cid;
		this.tiempoServicio = tiempoServicio;
		this.eliminado = eliminado;
		this.personas = personas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_division_personal")
	public DivisionPersonal_update getDivisionPersonal() {
		return this.divisionPersonal;
	}

	public void setDivisionPersonal(
			DivisionPersonal_update divisionPersonal) {
		this.divisionPersonal = divisionPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sociedad")
	public Sociedad_update getSociedad() {
		return this.sociedad;
	}

	public void setSociedad(Sociedad_update sociedad) {
		this.sociedad = sociedad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_division")
	public Division_update getDivision() {
		return this.division;
	}

	public void setDivision(Division_update division) {
		this.division = division;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_subdivision_personal")
	public SubdivisionPersonal_update getSubdivisionPersonal() {
		return this.subdivisionPersonal;
	}

	public void setSubdivisionPersonal(
			SubdivisionPersonal_update subdivisionPersonal) {
		this.subdivisionPersonal = subdivisionPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_personal")
	public GrupoPersonal_update getGrupoPersonal() {
		return this.grupoPersonal;
	}

	public void setGrupoPersonal(GrupoPersonal_update grupoPersonal) {
		this.grupoPersonal = grupoPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_laboral")
	public EstadoLaboral_update getEstadoLaboral() {
		return this.estadoLaboral;
	}

	public void setEstadoLaboral(EstadoLaboral_update estadoLaboral) {
		this.estadoLaboral = estadoLaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formacion")
	public Formacion_update getFormacion() {
		return this.formacion;
	}

	public void setFormacion(Formacion_update formacion) {
		this.formacion = formacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_area_personal")
	public TipoNomina_update getTipoNomina() {
		return this.tipoNomina;
	}

	public void setTipoNomina(TipoNomina_update tipoNomina) {
		this.tipoNomina = tipoNomina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidad_organizativa")
	public UnidadOrganizativa_update getUnidadOrganizativa() {
		return this.unidadOrganizativa;
	}

	public void setUnidadOrganizativa(
			UnidadOrganizativa_update unidadOrganizativa) {
		this.unidadOrganizativa = unidadOrganizativa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mano_dominante")
	public ManoDominante_update getManoDominante() {
		return this.manoDominante;
	}

	public void setManoDominante(ManoDominante_update manoDominante) {
		this.manoDominante = manoDominante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_zona_laboral")
	public TipoZonaLaboral_update getTipoZonaLaboral() {
		return this.tipoZonaLaboral;
	}

	public void setTipoZonaLaboral(TipoZonaLaboral_update tipoZonaLaboral) {
		this.tipoZonaLaboral = tipoZonaLaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_posicion")
	public Posicion_update getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion_update posicion) {
		this.posicion = posicion;
	}

	@Column(name = "telefono_oficina")
	public String getTelefonoOficina() {
		return this.telefonoOficina;
	}

	public void setTelefonoOficina(String telefonoOficina) {
		if (telefonoOficina != null)
			telefonoOficina = telefonoOficina.trim();
		this.telefonoOficina = telefonoOficina;
	}

	@Column(name = "numero_personal")
	public String getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(String numeroPersonal) {
		if (numeroPersonal != null)
			numeroPersonal = numeroPersonal.trim();
		this.numeroPersonal = numeroPersonal;
	}

	@Column(name = "asegurado_ivss")
	public Boolean getAseguradoIvss() {
		return this.aseguradoIvss;
	}

	public void setAseguradoIvss(Boolean aseguradoIvss) {
		this.aseguradoIvss = aseguradoIvss;
	}

	@Column(name = "num_hijos")
	public Integer getNumHijos() {
		return this.numHijos;
	}

	public void setNumHijos(Integer numHijos) {
		this.numHijos = numHijos;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tiempo_servicio", length = 13)
	public Date getTiempoServicio() {
		return this.tiempoServicio;
	}

	public void setTiempoServicio(Date tiempoServicio) {
		this.tiempoServicio = tiempoServicio;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosLaborales")
	public Set<Persona_update> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona_update> personas) {
		this.personas = personas;
	}

}
