package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", schema = "hc_local")
public class Direccion_update implements java.io.Serializable {

	private long id;
	private Integer version;
	private Nacion_update nacion;
	private String localidad;
	private String nombreVia;
	private Long idEstado;
	private Long idMunicipio;
	private Long idParroquia;
	private Long idTipoZona;
	private Long idTipoVia;
	private Long idTipoEdificacion;
	private Boolean eliminado;
	private Long cid;
	private String codigoPostal;
	private String puntoReferencia;
	private String nombreZona;
	private String nombreEdificacion;
	private String piso;
	private String numero;
	private Set<Persona_update> personasForIdLugarNacimiento = new HashSet<Persona_update>(
			0);
	private Set<Persona_update> personasForIdDireccionParticular = new HashSet<Persona_update>(
			0);
	private Set<Persona_update> personasForIdLugarResidencia = new HashSet<Persona_update>(
			0);
	private Set<PersonaHist_update> personaHistsForIdLugarResidencia = new HashSet<PersonaHist_update>(
			0);
	private Set<PersonaHist_update> personaHistsForIdLugarNacimiento = new HashSet<PersonaHist_update>(
			0);
	private Set<PersonaHist_update> personaHistsForIdDireccionParticular = new HashSet<PersonaHist_update>(
			0);

	public Direccion_update() {
	}

	public Direccion_update(long id) {
		this.id = id;
	}

	public Direccion_update(long id, Nacion_update nacion,
			String localidad, String nombreVia, Long idEstado,
			Long idMunicipio, Long idParroquia, Long idTipoZona,
			Long idTipoVia, Long idTipoEdificacion, Boolean eliminado,
			Long cid, String codigoPostal, String puntoReferencia,
			String nombreZona, String nombreEdificacion, String piso,
			String numero,
			Set<Persona_update> personasForIdLugarNacimiento,
			Set<Persona_update> personasForIdDireccionParticular,
			Set<Persona_update> personasForIdLugarResidencia,
			Set<PersonaHist_update> personaHistsForIdLugarResidencia,
			Set<PersonaHist_update> personaHistsForIdLugarNacimiento,
			Set<PersonaHist_update> personaHistsForIdDireccionParticular) {
		this.id = id;
		this.nacion = nacion;
		this.localidad = localidad;
		this.nombreVia = nombreVia;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idParroquia = idParroquia;
		this.idTipoZona = idTipoZona;
		this.idTipoVia = idTipoVia;
		this.idTipoEdificacion = idTipoEdificacion;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigoPostal = codigoPostal;
		this.puntoReferencia = puntoReferencia;
		this.nombreZona = nombreZona;
		this.nombreEdificacion = nombreEdificacion;
		this.piso = piso;
		this.numero = numero;
		this.personasForIdLugarNacimiento = personasForIdLugarNacimiento;
		this.personasForIdDireccionParticular = personasForIdDireccionParticular;
		this.personasForIdLugarResidencia = personasForIdLugarResidencia;
		this.personaHistsForIdLugarResidencia = personaHistsForIdLugarResidencia;
		this.personaHistsForIdLugarNacimiento = personaHistsForIdLugarNacimiento;
		this.personaHistsForIdDireccionParticular = personaHistsForIdDireccionParticular;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nacion")
	public Nacion_update getNacion() {
		return this.nacion;
	}

	public void setNacion(Nacion_update nacion) {
		this.nacion = nacion;
	}

	@Column(name = "localidad")
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		if (localidad != null)
			localidad = localidad.trim();
		this.localidad = localidad;
	}

	@Column(name = "nombre_via")
	public String getNombreVia() {
		return this.nombreVia;
	}

	public void setNombreVia(String nombreVia) {
		if (nombreVia != null)
			nombreVia = nombreVia.trim();
		this.nombreVia = nombreVia;
	}

	@Column(name = "id_estado")
	public Long getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Long idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "id_municipio")
	public Long getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Long idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "id_parroquia")
	public Long getIdParroquia() {
		return this.idParroquia;
	}

	public void setIdParroquia(Long idParroquia) {
		this.idParroquia = idParroquia;
	}

	@Column(name = "id_tipo_zona")
	public Long getIdTipoZona() {
		return this.idTipoZona;
	}

	public void setIdTipoZona(Long idTipoZona) {
		this.idTipoZona = idTipoZona;
	}

	@Column(name = "id_tipo_via")
	public Long getIdTipoVia() {
		return this.idTipoVia;
	}

	public void setIdTipoVia(Long idTipoVia) {
		this.idTipoVia = idTipoVia;
	}

	@Column(name = "id_tipo_edificacion")
	public Long getIdTipoEdificacion() {
		return this.idTipoEdificacion;
	}

	public void setIdTipoEdificacion(Long idTipoEdificacion) {
		this.idTipoEdificacion = idTipoEdificacion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo_postal")
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		if (codigoPostal != null)
			codigoPostal = codigoPostal.trim();
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "punto_referencia")
	public String getPuntoReferencia() {
		return this.puntoReferencia;
	}

	public void setPuntoReferencia(String puntoReferencia) {
		if (puntoReferencia != null)
			puntoReferencia = puntoReferencia.trim();
		this.puntoReferencia = puntoReferencia;
	}

	@Column(name = "nombre_zona")
	public String getNombreZona() {
		return this.nombreZona;
	}

	public void setNombreZona(String nombreZona) {
		if (nombreZona != null)
			nombreZona = nombreZona.trim();
		this.nombreZona = nombreZona;
	}

	@Column(name = "nombre_edificacion")
	public String getNombreEdificacion() {
		return this.nombreEdificacion;
	}

	public void setNombreEdificacion(String nombreEdificacion) {
		if (nombreEdificacion != null)
			nombreEdificacion = nombreEdificacion.trim();
		this.nombreEdificacion = nombreEdificacion;
	}

	@Column(name = "piso")
	public String getPiso() {
		return this.piso;
	}

	public void setPiso(String piso) {
		if (piso != null)
			piso = piso.trim();
		this.piso = piso;
	}

	@Column(name = "numero")
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		if (numero != null)
			numero = numero.trim();
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccionByIdLugarNacimiento")
	public Set<Persona_update> getPersonasForIdLugarNacimiento() {
		return this.personasForIdLugarNacimiento;
	}

	public void setPersonasForIdLugarNacimiento(
			Set<Persona_update> personasForIdLugarNacimiento) {
		this.personasForIdLugarNacimiento = personasForIdLugarNacimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccionByIdDireccionParticular")
	public Set<Persona_update> getPersonasForIdDireccionParticular() {
		return this.personasForIdDireccionParticular;
	}

	public void setPersonasForIdDireccionParticular(
			Set<Persona_update> personasForIdDireccionParticular) {
		this.personasForIdDireccionParticular = personasForIdDireccionParticular;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccionByIdLugarResidencia")
	public Set<Persona_update> getPersonasForIdLugarResidencia() {
		return this.personasForIdLugarResidencia;
	}

	public void setPersonasForIdLugarResidencia(
			Set<Persona_update> personasForIdLugarResidencia) {
		this.personasForIdLugarResidencia = personasForIdLugarResidencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccionByIdLugarResidencia")
	public Set<PersonaHist_update> getPersonaHistsForIdLugarResidencia() {
		return this.personaHistsForIdLugarResidencia;
	}

	public void setPersonaHistsForIdLugarResidencia(
			Set<PersonaHist_update> personaHistsForIdLugarResidencia) {
		this.personaHistsForIdLugarResidencia = personaHistsForIdLugarResidencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccionByIdLugarNacimiento")
	public Set<PersonaHist_update> getPersonaHistsForIdLugarNacimiento() {
		return this.personaHistsForIdLugarNacimiento;
	}

	public void setPersonaHistsForIdLugarNacimiento(
			Set<PersonaHist_update> personaHistsForIdLugarNacimiento) {
		this.personaHistsForIdLugarNacimiento = personaHistsForIdLugarNacimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccionByIdDireccionParticular")
	public Set<PersonaHist_update> getPersonaHistsForIdDireccionParticular() {
		return this.personaHistsForIdDireccionParticular;
	}

	public void setPersonaHistsForIdDireccionParticular(
			Set<PersonaHist_update> personaHistsForIdDireccionParticular) {
		this.personaHistsForIdDireccionParticular = personaHistsForIdDireccionParticular;
	}

}
