package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * GrupoSanguineo generated by hbm2java
 */
@Entity
@Table(name = "grupo_sanguineo", schema = "nomencladores")
public class GrupoSanguineo_update implements java.io.Serializable {

	private long id;
	private int version;
	private FactorSanguineo_update factorSanguineo;
	private String valor;
	private long cid;
	private boolean eliminado;
	private String codigo;
	private Set<PersonaHist_update> personaHists = new HashSet<PersonaHist_update>(
			0);
	private Set<HojaFrontal_update> hojaFrontals = new HashSet<HojaFrontal_update>(
			0);

	public GrupoSanguineo_update() {
	}

	public GrupoSanguineo_update(long id,
			FactorSanguineo_update factorSanguineo, String valor,
			long cid, boolean eliminado) {
		this.id = id;
		this.factorSanguineo = factorSanguineo;
		this.valor = valor;
		this.cid = cid;
		this.eliminado = eliminado;
	}

	public GrupoSanguineo_update(long id,
			FactorSanguineo_update factorSanguineo, String valor,
			long cid, boolean eliminado, String codigo,
			Set<PersonaHist_update> personaHists,
			Set<HojaFrontal_update> hojaFrontals) {
		this.id = id;
		this.factorSanguineo = factorSanguineo;
		this.valor = valor;
		this.cid = cid;
		this.eliminado = eliminado;
		this.codigo = codigo;
		this.personaHists = personaHists;
		this.hojaFrontals = hojaFrontals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	@NotNull
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_factor", nullable = false)
	@NotNull
	public FactorSanguineo_update getFactorSanguineo() {
		return this.factorSanguineo;
	}

	public void setFactorSanguineo(FactorSanguineo_update factorSanguineo) {
		this.factorSanguineo = factorSanguineo;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "cid", nullable = false)
	@NotNull
	public long getCid() {
		return this.cid;
	}

	public void setCid(long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado", nullable = false)
	@NotNull
	public boolean isEliminado() {
		return this.eliminado;
	}

	public void setEliminado(boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoSanguineo")
	public Set<PersonaHist_update> getPersonaHists() {
		return this.personaHists;
	}

	public void setPersonaHists(Set<PersonaHist_update> personaHists) {
		this.personaHists = personaHists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoSanguineo")
	public Set<HojaFrontal_update> getHojaFrontals() {
		return this.hojaFrontals;
	}

	public void setHojaFrontals(Set<HojaFrontal_update> hojaFrontals) {
		this.hojaFrontals = hojaFrontals;
	}

}
