package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * HojaFrontal generated by hbm2java
 */
@Entity
@Table(name = "hoja_frontal", schema = "hc_local")
public class HojaFrontal_update implements java.io.Serializable {

	private long id;
	private Integer version;
	private TipoHojaFrontal_update tipoHojaFrontal;
	private FactorSanguineo_update factorSanguineo;
	private GrupoSanguineo_update grupoSanguineo;
	private Persona_update personaById;
	private Status_update status;
	private Persona_update personaByIdAvisarEmergencia;
	private String puntoReferencia;
	private Integer tiempoResidencia;
	private Long idAntPrenatObst;
	private Long idPeriodoNeonatal;
	private Long idAlimentacion;
	private Long idDesarrollo;
	private Long idAntSexReprod;
	private Long cid;
	private Boolean eliminado;
	private Long idAntGinecoObstetrico;
	private Long idAntHematoOnc;
	private Boolean estaEmbarazada;
	private String descripcionDesconocido;
	private Date fechaCreada;
	private boolean desconocido;
	private Integer idRis;
	private Long idProblemasDetectados;
	private String numeroHc;
	private Boolean tieneCda;

	public HojaFrontal_update() {
	}

	public HojaFrontal_update(
			TipoHojaFrontal_update tipoHojaFrontal,
			Persona_update personaById, Date fechaCreada,
			boolean desconocido, String numeroHc) {
		this.tipoHojaFrontal = tipoHojaFrontal;
		this.personaById = personaById;
		this.fechaCreada = fechaCreada;
		this.desconocido = desconocido;
		this.numeroHc = numeroHc;
	}

	public HojaFrontal_update(
			TipoHojaFrontal_update tipoHojaFrontal,
			FactorSanguineo_update factorSanguineo,
			GrupoSanguineo_update grupoSanguineo,
			Persona_update personaById, Status_update status,
			Persona_update personaByIdAvisarEmergencia,
			String puntoReferencia, Integer tiempoResidencia,
			Long idAntPrenatObst, Long idPeriodoNeonatal, Long idAlimentacion,
			Long idDesarrollo, Long idAntSexReprod, Long cid,
			Boolean eliminado, Long idAntGinecoObstetrico, Long idAntHematoOnc,
			Boolean estaEmbarazada, String descripcionDesconocido,
			Date fechaCreada, boolean desconocido, Integer idRis,
			Long idProblemasDetectados, String numeroHc, Boolean tieneCda) {
		this.tipoHojaFrontal = tipoHojaFrontal;
		this.factorSanguineo = factorSanguineo;
		this.grupoSanguineo = grupoSanguineo;
		this.personaById = personaById;
		this.status = status;
		this.personaByIdAvisarEmergencia = personaByIdAvisarEmergencia;
		this.puntoReferencia = puntoReferencia;
		this.tiempoResidencia = tiempoResidencia;
		this.idAntPrenatObst = idAntPrenatObst;
		this.idPeriodoNeonatal = idPeriodoNeonatal;
		this.idAlimentacion = idAlimentacion;
		this.idDesarrollo = idDesarrollo;
		this.idAntSexReprod = idAntSexReprod;
		this.cid = cid;
		this.eliminado = eliminado;
		this.idAntGinecoObstetrico = idAntGinecoObstetrico;
		this.idAntHematoOnc = idAntHematoOnc;
		this.estaEmbarazada = estaEmbarazada;
		this.descripcionDesconocido = descripcionDesconocido;
		this.fechaCreada = fechaCreada;
		this.desconocido = desconocido;
		this.idRis = idRis;
		this.idProblemasDetectados = idProblemasDetectados;
		this.numeroHc = numeroHc;
		this.tieneCda = tieneCda;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personaById"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_hoja_frontal", nullable = false)
	@NotNull
	public TipoHojaFrontal_update getTipoHojaFrontal() {
		return this.tipoHojaFrontal;
	}

	public void setTipoHojaFrontal(TipoHojaFrontal_update tipoHojaFrontal) {
		this.tipoHojaFrontal = tipoHojaFrontal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_factor_sanguineo")
	public FactorSanguineo_update getFactorSanguineo() {
		return this.factorSanguineo;
	}

	public void setFactorSanguineo(FactorSanguineo_update factorSanguineo) {
		this.factorSanguineo = factorSanguineo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_sanguineo")
	public GrupoSanguineo_update getGrupoSanguineo() {
		return this.grupoSanguineo;
	}

	public void setGrupoSanguineo(GrupoSanguineo_update grupoSanguineo) {
		this.grupoSanguineo = grupoSanguineo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public Persona_update getPersonaById() {
		return this.personaById;
	}

	public void setPersonaById(Persona_update personaById) {
		this.personaById = personaById;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_status")
	public Status_update getStatus() {
		return this.status;
	}

	public void setStatus(Status_update status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_avisar_emergencia")
	public Persona_update getPersonaByIdAvisarEmergencia() {
		return this.personaByIdAvisarEmergencia;
	}

	public void setPersonaByIdAvisarEmergencia(
			Persona_update personaByIdAvisarEmergencia) {
		this.personaByIdAvisarEmergencia = personaByIdAvisarEmergencia;
	}

	@Column(name = "punto_referencia", length = 100)
	@Length(max = 100)
	public String getPuntoReferencia() {
		return this.puntoReferencia;
	}

	public void setPuntoReferencia(String puntoReferencia) {
		if (puntoReferencia != null)
			puntoReferencia = puntoReferencia.trim();
		this.puntoReferencia = puntoReferencia;
	}

	@Column(name = "tiempo_residencia")
	public Integer getTiempoResidencia() {
		return this.tiempoResidencia;
	}

	public void setTiempoResidencia(Integer tiempoResidencia) {
		this.tiempoResidencia = tiempoResidencia;
	}

	@Column(name = "id_ant_prenat_obst")
	public Long getIdAntPrenatObst() {
		return this.idAntPrenatObst;
	}

	public void setIdAntPrenatObst(Long idAntPrenatObst) {
		this.idAntPrenatObst = idAntPrenatObst;
	}

	@Column(name = "id_periodo_neonatal")
	public Long getIdPeriodoNeonatal() {
		return this.idPeriodoNeonatal;
	}

	public void setIdPeriodoNeonatal(Long idPeriodoNeonatal) {
		this.idPeriodoNeonatal = idPeriodoNeonatal;
	}

	@Column(name = "id_alimentacion")
	public Long getIdAlimentacion() {
		return this.idAlimentacion;
	}

	public void setIdAlimentacion(Long idAlimentacion) {
		this.idAlimentacion = idAlimentacion;
	}

	@Column(name = "id_desarrollo")
	public Long getIdDesarrollo() {
		return this.idDesarrollo;
	}

	public void setIdDesarrollo(Long idDesarrollo) {
		this.idDesarrollo = idDesarrollo;
	}

	@Column(name = "id_ant_sex_reprod")
	public Long getIdAntSexReprod() {
		return this.idAntSexReprod;
	}

	public void setIdAntSexReprod(Long idAntSexReprod) {
		this.idAntSexReprod = idAntSexReprod;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "id_ant_gineco_obstetrico")
	public Long getIdAntGinecoObstetrico() {
		return this.idAntGinecoObstetrico;
	}

	public void setIdAntGinecoObstetrico(Long idAntGinecoObstetrico) {
		this.idAntGinecoObstetrico = idAntGinecoObstetrico;
	}

	@Column(name = "id_ant_hemato_onc")
	public Long getIdAntHematoOnc() {
		return this.idAntHematoOnc;
	}

	public void setIdAntHematoOnc(Long idAntHematoOnc) {
		this.idAntHematoOnc = idAntHematoOnc;
	}

	@Column(name = "esta_embarazada")
	public Boolean getEstaEmbarazada() {
		return this.estaEmbarazada;
	}

	public void setEstaEmbarazada(Boolean estaEmbarazada) {
		this.estaEmbarazada = estaEmbarazada;
	}

	@Column(name = "descripcion_desconocido")
	public String getDescripcionDesconocido() {
		return this.descripcionDesconocido;
	}

	public void setDescripcionDesconocido(String descripcionDesconocido) {
		if (descripcionDesconocido != null)
			descripcionDesconocido = descripcionDesconocido.trim();
		this.descripcionDesconocido = descripcionDesconocido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creada", nullable = false, length = 13)
	@NotNull
	public Date getFechaCreada() {
		return this.fechaCreada;
	}

	public void setFechaCreada(Date fechaCreada) {
		this.fechaCreada = fechaCreada;
	}

	@Column(name = "desconocido", nullable = false)
	@NotNull
	public boolean isDesconocido() {
		return this.desconocido;
	}

	public void setDesconocido(boolean desconocido) {
		this.desconocido = desconocido;
	}

	@Column(name = "id_ris")
	public Integer getIdRis() {
		return this.idRis;
	}

	public void setIdRis(Integer idRis) {
		this.idRis = idRis;
	}

	@Column(name = "id_problemas_detectados")
	public Long getIdProblemasDetectados() {
		return this.idProblemasDetectados;
	}

	public void setIdProblemasDetectados(Long idProblemasDetectados) {
		this.idProblemasDetectados = idProblemasDetectados;
	}

	@Column(name = "numero_hc", nullable = false)
	@NotNull
	public String getNumeroHc() {
		return this.numeroHc;
	}

	public void setNumeroHc(String numeroHc) {
		if (numeroHc != null)
			numeroHc = numeroHc.trim();
		this.numeroHc = numeroHc;
	}

	@Column(name = "tiene_cda")
	public Boolean getTieneCda() {
		return this.tieneCda;
	}

	public void setTieneCda(Boolean tieneCda) {
		this.tieneCda = tieneCda;
	}

}
