package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Nacion generated by hbm2java
 */
@Entity
@Table(name = "nacion", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "valor"),
		@UniqueConstraint(columnNames = "nacionalidad") })
public class Nacion_update implements java.io.Serializable {

	private long id;
	private Integer version;
	private String valor;
	private String nacionalidad;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private Set<PersonaHist_update> personaHists = new HashSet<PersonaHist_update>(
			0);
	private Set<Persona_update> personas = new HashSet<Persona_update>(
			0);
	private Set<Direccion_update> direccions = new HashSet<Direccion_update>(
			0);

	public Nacion_update() {
	}

	public Nacion_update(long id, String valor, String nacionalidad) {
		this.id = id;
		this.valor = valor;
		this.nacionalidad = nacionalidad;
	}

	public Nacion_update(long id, String valor, String nacionalidad,
			Boolean eliminado, Long cid, String codigo,
			Set<PersonaHist_update> personaHists,
			Set<Persona_update> personas,
			Set<Direccion_update> direccions) {
		this.id = id;
		this.valor = valor;
		this.nacionalidad = nacionalidad;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.personaHists = personaHists;
		this.personas = personas;
		this.direccions = direccions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "nacionalidad", unique = true, nullable = false)
	@NotNull
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		if (nacionalidad != null)
			nacionalidad = nacionalidad.trim();
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nacion")
	public Set<PersonaHist_update> getPersonaHists() {
		return this.personaHists;
	}

	public void setPersonaHists(Set<PersonaHist_update> personaHists) {
		this.personaHists = personaHists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nacion")
	public Set<Persona_update> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona_update> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nacion")
	public Set<Direccion_update> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion_update> direccions) {
		this.direccions = direccions;
	}

}
