package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PersonaHist generated by hbm2java
 */
@Entity
@Table(name = "persona_hist", schema = "estadisticas")
public class PersonaHist_update implements java.io.Serializable {

	private long id;
	private Integer version;
	private Long divisionPersonal;
	private Long factorSanguineo;
	private Long sociedad;
	private Long division;
	private Long sexo;
	private Long direccionByIdLugarNacimiento;
	private Long estadoCivil;
	private Long estadoLaboral;
	private Long grupoPersonal;
	private Long tipoNomina;
	private Long persona;
	private Long direccionByIdLugarResidencia;
	private Long manoDominante;
	private Long tipoZonaLaboral;
	private Long tipoHojaFrontal;
	private Long direccionByIdDireccionParticular;
	private Long grupoSanguineo;
	private Long subdivisionPersonal;
	private Long formacion;
	private Long nacion;
	private Long unidadOrganizativa;
	private Long status;
	private Long posicion;
	private Date fechaRegistro;
	private Long cid;
	private Boolean eliminado;
	private String descripcionDesconocido;
	private Date fechaHojaFrontalCreada;
	private Boolean desconocido;
	private String noHc;
	private String cedula;
	private String telefonoOficina;
	private String numeroPersonal;
	private Boolean aseguradoIvss;
	private Integer numHijos;
	private Date tiempoServicio;
	private Date fechaNacimiento;
	private Long idRaza;
	private Long idEtnia;

	public PersonaHist_update() {
	}

	public PersonaHist_update(long id) {
		this.id = id;
	}

	public PersonaHist_update(long id,
			Long divisionPersonal,
			Long factorSanguineo,
			Long sociedad, Long division,
			Long sexo,
			Long direccionByIdLugarNacimiento,
			Long estadoCivil,
			Long estadoLaboral,
			Long grupoPersonal,
			Long tipoNomina, Long persona,
			Long direccionByIdLugarResidencia,
			Long manoDominante,
			Long tipoZonaLaboral,
			Long tipoHojaFrontal,
			Long direccionByIdDireccionParticular,
			Long grupoSanguineo,
			Long subdivisionPersonal,
			Long formacion, Long nacion,
			Long unidadOrganizativa,
			Long status, Long posicion,
			Date fechaRegistro, Long cid, Boolean eliminado,
			String descripcionDesconocido, Date fechaHojaFrontalCreada,
			Boolean desconocido, String noHc, String cedula,
			String telefonoOficina, String numeroPersonal,
			Boolean aseguradoIvss, Integer numHijos, Date tiempoServicio,
			Date fechaNacimiento, Long idRaza, Long idEtnia) {
		this.id = id;
		this.divisionPersonal = divisionPersonal;
		this.factorSanguineo = factorSanguineo;
		this.sociedad = sociedad;
		this.division = division;
		this.sexo = sexo;
		this.direccionByIdLugarNacimiento = direccionByIdLugarNacimiento;
		this.estadoCivil = estadoCivil;
		this.estadoLaboral = estadoLaboral;
		this.grupoPersonal = grupoPersonal;
		this.tipoNomina = tipoNomina;
		this.persona = persona;
		this.direccionByIdLugarResidencia = direccionByIdLugarResidencia;
		this.manoDominante = manoDominante;
		this.tipoZonaLaboral = tipoZonaLaboral;
		this.tipoHojaFrontal = tipoHojaFrontal;
		this.direccionByIdDireccionParticular = direccionByIdDireccionParticular;
		this.grupoSanguineo = grupoSanguineo;
		this.subdivisionPersonal = subdivisionPersonal;
		this.formacion = formacion;
		this.nacion = nacion;
		this.unidadOrganizativa = unidadOrganizativa;
		this.status = status;
		this.posicion = posicion;
		this.fechaRegistro = fechaRegistro;
		this.cid = cid;
		this.eliminado = eliminado;
		this.descripcionDesconocido = descripcionDesconocido;
		this.fechaHojaFrontalCreada = fechaHojaFrontalCreada;
		this.desconocido = desconocido;
		this.noHc = noHc;
		this.cedula = cedula;
		this.telefonoOficina = telefonoOficina;
		this.numeroPersonal = numeroPersonal;
		this.aseguradoIvss = aseguradoIvss;
		this.numHijos = numHijos;
		this.tiempoServicio = tiempoServicio;
		this.fechaNacimiento = fechaNacimiento;
		this.idRaza = idRaza;
		this.idEtnia = idEtnia;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	
	@Column(name = "id_division_personal")
	public Long getDivisionPersonal() {
		return this.divisionPersonal;
	}

	public void setDivisionPersonal(
			Long divisionPersonal) {
		this.divisionPersonal = divisionPersonal;
	}

	
	@Column(name = "id_factor_sanguineo")
	public Long getFactorSanguineo() {
		return this.factorSanguineo;
	}

	public void setFactorSanguineo(Long factorSanguineo) {
		this.factorSanguineo = factorSanguineo;
	}

	
	@Column(name = "id_sociedad")
	public Long getSociedad() {
		return this.sociedad;
	}

	public void setSociedad(Long sociedad) {
		this.sociedad = sociedad;
	}

	
	@Column(name = "id_division")
	public Long getDivision() {
		return this.division;
	}

	public void setDivision(Long division) {
		this.division = division;
	}

	
	@Column(name = "id_sexo")
	public Long getSexo() {
		return this.sexo;
	}

	public void setSexo(Long sexo) {
		this.sexo = sexo;
	}

	
	@Column(name = "id_lugar_nacimiento")
	public Long getDireccionByIdLugarNacimiento() {
		return this.direccionByIdLugarNacimiento;
	}

	public void setDireccionByIdLugarNacimiento(
			Long direccionByIdLugarNacimiento) {
		this.direccionByIdLugarNacimiento = direccionByIdLugarNacimiento;
	}

	
	@Column(name = "id_estado_civil")
	public Long getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(Long estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	
	@Column(name = "id_estado_laboral")
	public Long getEstadoLaboral() {
		return this.estadoLaboral;
	}

	public void setEstadoLaboral(Long estadoLaboral) {
		this.estadoLaboral = estadoLaboral;
	}

	
	@Column(name = "id_grupo_personal")
	public Long getGrupoPersonal() {
		return this.grupoPersonal;
	}

	public void setGrupoPersonal(Long grupoPersonal) {
		this.grupoPersonal = grupoPersonal;
	}

	
	@Column(name = "id_area_personal")
	public Long getTipoNomina() {
		return this.tipoNomina;
	}

	public void setTipoNomina(Long tipoNomina) {
		this.tipoNomina = tipoNomina;
	}

	
	@Column(name = "id_persona")
	public Long getPersona() {
		return this.persona;
	}

	public void setPersona(Long persona) {
		this.persona = persona;
	}

	
	@Column(name = "id_lugar_residencia")
	public Long getDireccionByIdLugarResidencia() {
		return this.direccionByIdLugarResidencia;
	}

	public void setDireccionByIdLugarResidencia(
			Long direccionByIdLugarResidencia) {
		this.direccionByIdLugarResidencia = direccionByIdLugarResidencia;
	}

	
	@Column(name = "id_mano_dominante")
	public Long getManoDominante() {
		return this.manoDominante;
	}

	public void setManoDominante(Long manoDominante) {
		this.manoDominante = manoDominante;
	}

	
	@Column(name = "id_tipo_zona_laboral")
	public Long getTipoZonaLaboral() {
		return this.tipoZonaLaboral;
	}

	public void setTipoZonaLaboral(Long tipoZonaLaboral) {
		this.tipoZonaLaboral = tipoZonaLaboral;
	}

	
	@Column(name = "id_tipo_hoja_frontal")
	public Long getTipoHojaFrontal() {
		return this.tipoHojaFrontal;
	}

	public void setTipoHojaFrontal(Long tipoHojaFrontal) {
		this.tipoHojaFrontal = tipoHojaFrontal;
	}

	
	@Column(name = "id_direccion_particular")
	public Long getDireccionByIdDireccionParticular() {
		return this.direccionByIdDireccionParticular;
	}

	public void setDireccionByIdDireccionParticular(
			Long direccionByIdDireccionParticular) {
		this.direccionByIdDireccionParticular = direccionByIdDireccionParticular;
	}

	
	@Column(name = "id_grupo_sanguineo")
	public Long getGrupoSanguineo() {
		return this.grupoSanguineo;
	}

	public void setGrupoSanguineo(Long grupoSanguineo) {
		this.grupoSanguineo = grupoSanguineo;
	}

	
	@Column(name = "id_subdivision_personal")
	public Long getSubdivisionPersonal() {
		return this.subdivisionPersonal;
	}

	public void setSubdivisionPersonal(
			Long subdivisionPersonal) {
		this.subdivisionPersonal = subdivisionPersonal;
	}

	
	@Column(name = "id_formacion")
	public Long getFormacion() {
		return this.formacion;
	}

	public void setFormacion(Long formacion) {
		this.formacion = formacion;
	}

	
	@Column(name = "id_nacion")
	public Long getNacion() {
		return this.nacion;
	}

	public void setNacion(Long nacion) {
		this.nacion = nacion;
	}

	
	@Column(name = "id_unidad_organizativa")
	public Long getUnidadOrganizativa() {
		return this.unidadOrganizativa;
	}

	public void setUnidadOrganizativa(
			Long unidadOrganizativa) {
		this.unidadOrganizativa = unidadOrganizativa;
	}

	
	@Column(name = "id_status")
	public  Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	
	@Column(name = "id_posicion")
	public Long getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Long posicion) {
		this.posicion = posicion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", length = 29)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "descripcion_desconocido")
	public String getDescripcionDesconocido() {
		return this.descripcionDesconocido;
	}

	public void setDescripcionDesconocido(String descripcionDesconocido) {
		if (descripcionDesconocido != null)
			descripcionDesconocido = descripcionDesconocido.trim();
		this.descripcionDesconocido = descripcionDesconocido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_hoja_frontal_creada", length = 13)
	public Date getFechaHojaFrontalCreada() {
		return this.fechaHojaFrontalCreada;
	}

	public void setFechaHojaFrontalCreada(Date fechaHojaFrontalCreada) {
		this.fechaHojaFrontalCreada = fechaHojaFrontalCreada;
	}

	@Column(name = "desconocido")
	public Boolean getDesconocido() {
		return this.desconocido;
	}

	public void setDesconocido(Boolean desconocido) {
		this.desconocido = desconocido;
	}

	@Column(name = "no_hc")
	public String getNoHc() {
		return this.noHc;
	}

	public void setNoHc(String noHc) {
		if (noHc != null)
			noHc = noHc.trim();
		this.noHc = noHc;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		if (cedula != null)
			cedula = cedula.trim();
		this.cedula = cedula;
	}

	@Column(name = "telefono_oficina")
	public String getTelefonoOficina() {
		return this.telefonoOficina;
	}

	public void setTelefonoOficina(String telefonoOficina) {
		if (telefonoOficina != null)
			telefonoOficina = telefonoOficina.trim();
		this.telefonoOficina = telefonoOficina;
	}

	@Column(name = "numero_personal")
	public String getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(String numeroPersonal) {
		if (numeroPersonal != null)
			numeroPersonal = numeroPersonal.trim();
		this.numeroPersonal = numeroPersonal;
	}

	@Column(name = "asegurado_ivss")
	public Boolean getAseguradoIvss() {
		return this.aseguradoIvss;
	}

	public void setAseguradoIvss(Boolean aseguradoIvss) {
		this.aseguradoIvss = aseguradoIvss;
	}

	@Column(name = "num_hijos")
	public Integer getNumHijos() {
		return this.numHijos;
	}

	public void setNumHijos(Integer numHijos) {
		this.numHijos = numHijos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tiempo_servicio", length = 13)
	public Date getTiempoServicio() {
		return this.tiempoServicio;
	}

	public void setTiempoServicio(Date tiempoServicio) {
		this.tiempoServicio = tiempoServicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "id_raza")
	public Long getIdRaza() {
		return this.idRaza;
	}

	public void setIdRaza(Long idRaza) {
		this.idRaza = idRaza;
	}

	@Column(name = "id_etnia")
	public Long getIdEtnia() {
		return this.idEtnia;
	}

	public void setIdEtnia(Long idEtnia) {
		this.idEtnia = idEtnia;
	}

}
