package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name = "sexo", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "codigo_sap"),
		@UniqueConstraint(columnNames = "abreviatura") })
public class Sexo_update implements java.io.Serializable {

	private long id;
	private Integer version;
	private String valor;
	private String abreviatura;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private String codigoSap;
	private Set<Persona_update> personas = new HashSet<Persona_update>(
			0);
	private Set<PersonaHist_update> personaHists = new HashSet<PersonaHist_update>(
			0);

	public Sexo_update() {
	}

	public Sexo_update(long id, String valor, String abreviatura) {
		this.id = id;
		this.valor = valor;
		this.abreviatura = abreviatura;
	}

	public Sexo_update(long id, String valor, String abreviatura,
			Boolean eliminado, Long cid, String codigo, String codigoSap,
			Set<Persona_update> personas,
			Set<PersonaHist_update> personaHists) {
		this.id = id;
		this.valor = valor;
		this.abreviatura = abreviatura;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.codigoSap = codigoSap;
		this.personas = personas;
		this.personaHists = personaHists;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "abreviatura", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		if (abreviatura != null)
			abreviatura = abreviatura.trim();
		this.abreviatura = abreviatura;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@Column(name = "codigo_sap", unique = true)
	public String getCodigoSap() {
		return this.codigoSap;
	}

	public void setCodigoSap(String codigoSap) {
		if (codigoSap != null)
			codigoSap = codigoSap.trim();
		this.codigoSap = codigoSap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sexo")
	public Set<Persona_update> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona_update> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sexo")
	public Set<PersonaHist_update> getPersonaHists() {
		return this.personaHists;
	}

	public void setPersonaHists(Set<PersonaHist_update> personaHists) {
		this.personaHists = personaHists;
	}

}
