package gehos.comun.triggers.entity;

// Generated Apr 23, 2012 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * TipoNomina generated by hbm2java
 */
@Entity
@Table(name = "tipo_nomina", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "codigo"),
		@UniqueConstraint(columnNames = "codigo_sap") })
public class TipoNomina_update implements java.io.Serializable {

	private long id;
	private Integer version;
	private String codigo;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private String codigoSap;
	private Set<DatosLaborales_update> datosLaboraleses = new HashSet<DatosLaborales_update>(
			0);
	private Set<PersonaHist_update> personaHists = new HashSet<PersonaHist_update>(
			0);

	public TipoNomina_update() {
	}

	public TipoNomina_update(long id, String codigo, String valor) {
		this.id = id;
		this.codigo = codigo;
		this.valor = valor;
	}

	public TipoNomina_update(long id, String codigo, String valor,
			Boolean eliminado, Long cid, String codigoSap,
			Set<DatosLaborales_update> datosLaboraleses,
			Set<PersonaHist_update> personaHists) {
		this.id = id;
		this.codigo = codigo;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigoSap = codigoSap;
		this.datosLaboraleses = datosLaboraleses;
		this.personaHists = personaHists;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "codigo", unique = true, nullable = false)
	@NotNull
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		if (codigo != null)
			codigo = codigo.trim();
		this.codigo = codigo;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		if (valor != null)
			valor = valor.trim();
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo_sap", unique = true)
	public String getCodigoSap() {
		return this.codigoSap;
	}

	public void setCodigoSap(String codigoSap) {
		if (codigoSap != null)
			codigoSap = codigoSap.trim();
		this.codigoSap = codigoSap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoNomina")
	public Set<DatosLaborales_update> getDatosLaboraleses() {
		return this.datosLaboraleses;
	}

	public void setDatosLaboraleses(
			Set<DatosLaborales_update> datosLaboraleses) {
		this.datosLaboraleses = datosLaboraleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoNomina")
	public Set<PersonaHist_update> getPersonaHists() {
		return this.personaHists;
	}

	public void setPersonaHists(Set<PersonaHist_update> personaHists) {
		this.personaHists = personaHists;
	}

}
