package gehos.comun.funcionalidades.entity.custom;

// Generated 06-abr-2009 11:47:29 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * FavoritosId generated by hbm2java
 */
@Embeddable
public class FavoritosId implements java.io.Serializable {

	private Long idUser;
	private Long idFuncionalidad;
	private Long idModulo;

	public FavoritosId() {
	}

	public FavoritosId(Long idUser, Long idFuncionalidad, Long idModulo) {
		this.idUser = idUser;
		this.idFuncionalidad = idFuncionalidad;
		this.idModulo = idModulo;
	}

	@Column(name = "id_user", nullable = false)
	@NotNull
	public Long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Long idUser) {
		this.idUser = idUser;
	}

	@Column(name = "id_funcionalidad", nullable = false)
	@NotNull
	public Long getIdFuncionalidad() {
		return this.idFuncionalidad;
	}

	public void setIdFuncionalidad(Long idFuncionalidad) {
		this.idFuncionalidad = idFuncionalidad;
	}

	@Column(name = "id_modulo", nullable = false)
	@NotNull
	public Long getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(Long idModulo) {
		this.idModulo = idModulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritosId))
			return false;
		FavoritosId castOther = (FavoritosId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdFuncionalidad() == castOther.getIdFuncionalidad())
				&& (this.getIdModulo() == castOther.getIdModulo());
	}

//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + this.getIdUser();
//		result = 37 * result + this.getIdFuncionalidad();
//		result = 37 * result + this.getIdModulo();
//		return result;
//	}

}
