package gehos.comun.funcionalidades.entity.custom;

// Generated 06-abr-2009 11:47:29 by Hibernate Tools 3.2.4.GA

import gehos.comun.funcionalidades.entity.Funcionalidad;
import gehos.comun.funcionalidades.entity.User_comun;
import gehos.configuracion.management.entity.Entidad_configuracion;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.validator.NotNull;

/**
 * Favoritos generated by hbm2java
 */
@Entity
@Table(name = "favoritos", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_user", "id_funcionalidad", "id_modulo", "id_entidad" }))
public class Favoritos implements java.io.Serializable {

	private FavoritosId id;
	private User_comun usuario;
	private Funcionalidad funcionalidadByIdFuncionalidad;
	private Funcionalidad funcionalidadByIdModulo;
	private Entidad_configuracion entidad;
	private Long cid;

	public Favoritos() {
	}

	public Favoritos(FavoritosId id, User_comun usuario,
			Funcionalidad funcionalidadByIdFuncionalidad,
			Funcionalidad funcionalidadByIdModulo, Entidad_configuracion entidad) {
		this.id = id;
		this.usuario = usuario;
		this.funcionalidadByIdFuncionalidad = funcionalidadByIdFuncionalidad;
		this.funcionalidadByIdModulo = funcionalidadByIdModulo;
		this.entidad = entidad;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)),
			@AttributeOverride(name = "idFuncionalidad", column = @Column(name = "id_funcionalidad", nullable = false)),
			@AttributeOverride(name = "idModulo", column = @Column(name = "id_modulo", nullable = false)) })
	@NotNull
	public FavoritosId getId() {
		return this.id;
	}

	public void setId(FavoritosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
	@NotNull
	public User_comun getUsuario() {
		return this.usuario;
	}

	public void setUsuario(User_comun usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_funcionalidad", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Funcionalidad getFuncionalidadByIdFuncionalidad() {
		return this.funcionalidadByIdFuncionalidad;
	}

	public void setFuncionalidadByIdFuncionalidad(
			Funcionalidad funcionalidadByIdFuncionalidad) {
		this.funcionalidadByIdFuncionalidad = funcionalidadByIdFuncionalidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modulo", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Funcionalidad getFuncionalidadByIdModulo() {
		return this.funcionalidadByIdModulo;
	}

	public void setFuncionalidadByIdModulo(Funcionalidad funcionalidadByIdModulo) {
		this.funcionalidadByIdModulo = funcionalidadByIdModulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad")
	public Entidad_configuracion getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad_configuracion entidad) {
		this.entidad = entidad;
	}

	@Column(name = "cid")
	public Long getCid() {
		return cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
