package gehos.pki.entity;

// Generated 25-may-2011 15:56:22 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * CaKeystore generated by hbm2java
 */
@Entity
@Table(name = "ca_keystore", schema = "pki")
public class CaKeystore_pki implements java.io.Serializable {

	private int id;
	private String keystore;
	private String numeroSerie;
	private Boolean eliminado;

	public CaKeystore_pki() {
	}

	public CaKeystore_pki(int id) {
		this.id = id;
	}

	public CaKeystore_pki(int id, String keystore, String numeroSerie,
			Boolean eliminado) {
		this.id = id;
		this.keystore = keystore;
		this.numeroSerie = numeroSerie;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "gen_ca_keystore")
	@SequenceGenerator(name = "gen_ca_keystore", sequenceName = "pki.ca_keystore_id_seq", allocationSize = 1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "keystore")
	public String getKeystore() {
		return this.keystore;
	}

	public void setKeystore(String keystore) {
		this.keystore = keystore;
	}

	@Column(name = "numero_serie")
	public String getNumeroSerie() {
		return this.numeroSerie;
	}

	public void setNumeroSerie(String numeroSerie) {
		this.numeroSerie = numeroSerie;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
