package gehos.pki.entity;

// Generated 25-may-2011 15:56:22 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * CertificadosConfiables generated by hbm2java
 */
@Entity
@Table(name = "certificados_confiables", schema = "pki")
public class CertificadosConfiables_pki implements java.io.Serializable {

	private int id;
	private TipoConfianza_pki tipoConfianza;
	private String certificado;
	private String certificadoC;
	private String certificadoSt;
	private String certificadoL;
	private String certificadoO;
	private String certificadoOu;
	private String certificadoCn;
	private String descripcion;
	private Boolean eliminado;

	public CertificadosConfiables_pki() {
	}

	public CertificadosConfiables_pki(int id, String certificado) {
		this.id = id;
		this.certificado = certificado;
	}

	public CertificadosConfiables_pki(int id, TipoConfianza_pki tipoConfianza,
			String certificado, String certificadoC, String certificadoSt,
			String certificadoL, String certificadoO, String certificadoOu,
			String certificadoCn, String descripcion, Boolean eliminado) {
		this.id = id;
		this.tipoConfianza = tipoConfianza;
		this.certificado = certificado;
		this.certificadoC = certificadoC;
		this.certificadoSt = certificadoSt;
		this.certificadoL = certificadoL;
		this.certificadoO = certificadoO;
		this.certificadoOu = certificadoOu;
		this.certificadoCn = certificadoCn;
		this.descripcion = descripcion;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "gen_certificados_confiables")
	@SequenceGenerator(name = "gen_certificados_confiables", sequenceName = "pki.certificados_confiables_id_seq", allocationSize = 1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_confianza")
	public TipoConfianza_pki getTipoConfianza() {
		return this.tipoConfianza;
	}

	public void setTipoConfianza(TipoConfianza_pki tipoConfianza) {
		this.tipoConfianza = tipoConfianza;
	}

	@Column(name = "certificado", nullable = false)
	@NotNull
	public String getCertificado() {
		return this.certificado;
	}

	public void setCertificado(String certificado) {
		this.certificado = certificado;
	}

	@Column(name = "certificado_c")
	public String getCertificadoC() {
		return this.certificadoC;
	}

	public void setCertificadoC(String certificadoC) {
		this.certificadoC = certificadoC;
	}

	@Column(name = "certificado_st")
	public String getCertificadoSt() {
		return this.certificadoSt;
	}

	public void setCertificadoSt(String certificadoSt) {
		this.certificadoSt = certificadoSt;
	}

	@Column(name = "certificado_l")
	public String getCertificadoL() {
		return this.certificadoL;
	}

	public void setCertificadoL(String certificadoL) {
		this.certificadoL = certificadoL;
	}

	@Column(name = "certificado_o")
	public String getCertificadoO() {
		return this.certificadoO;
	}

	public void setCertificadoO(String certificadoO) {
		this.certificadoO = certificadoO;
	}

	@Column(name = "certificado_ou")
	public String getCertificadoOu() {
		return this.certificadoOu;
	}

	public void setCertificadoOu(String certificadoOu) {
		this.certificadoOu = certificadoOu;
	}

	@Column(name = "certificado_cn")
	public String getCertificadoCn() {
		return this.certificadoCn;
	}

	public void setCertificadoCn(String certificadoCn) {
		this.certificadoCn = certificadoCn;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

}
