package gehos.pki.entity;

// Generated 25-may-2011 15:56:22 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Proxy generated by hbm2java
 */

@Entity
@Table(name = "ldap", schema = "pki")
public class Ldap implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String host;
	private String domain;
	private boolean active;
	private String description;
	
	


	public Ldap() {
	}
	

	public Ldap(int id,String host, String domain, boolean active,
			String description ) {
		this.id = id;
		this.host = host;
		this.domain = domain;
		this.active = active;
		this.description = description;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "gen_proxy")
	@SequenceGenerator(name = "gen_proxy", sequenceName = "pki.ldap_id_seq", allocationSize = 1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name = "host", nullable = false)
	@NotNull
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "domain")
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}
	
	@Column(name = "active")
	public boolean getActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	
	
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
