package gehos.pki.entity;

// Generated 25-may-2011 15:56:22 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * TipoConfianza generated by hbm2java
 */
@Entity
@Table(name = "tipo_confianza", schema = "pki")
public class TipoConfianza_pki implements java.io.Serializable {

	private int id;
	private String valor;
	private String descripcion;
	private Set<CertificadosConfiables_pki> certificadosConfiableses = new HashSet<CertificadosConfiables_pki>(
			0);

	public TipoConfianza_pki() {
	}

	public TipoConfianza_pki(int id, String valor, String descripcion) {
		this.id = id;
		this.valor = valor;
		this.descripcion = descripcion;
	}

	public TipoConfianza_pki(int id, String valor, String descripcion,
			Set<CertificadosConfiables_pki> certificadosConfiableses) {
		this.id = id;
		this.valor = valor;
		this.descripcion = descripcion;
		this.certificadosConfiableses = certificadosConfiableses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "gen_tipo_confianza")
	@SequenceGenerator(name = "gen_tipo_confianza", sequenceName = "pki.tipo_confianza_id_seq", allocationSize = 1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "descripcion", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoConfianza")
	public Set<CertificadosConfiables_pki> getCertificadosConfiableses() {
		return this.certificadosConfiableses;
	}

	public void setCertificadosConfiableses(
			Set<CertificadosConfiables_pki> certificadosConfiableses) {
		this.certificadosConfiableses = certificadosConfiableses;
	}

}
