package gehos.comun.procesos.entity;

// Generated 05-mar-2010 16:29:39 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Funcionalidad generated by hbm2java
 */
@Entity
@Table(name = "funcionalidad", schema = "seguridad", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Modulo implements java.io.Serializable {

	private Long id;
	private Integer version;
	private String label;
	private String url;
	private Boolean eliminado;
	private Long cid;
	private int orden;
	private String imagen;
	private boolean esModulo;
	private Long idFuncionalidadPadre;
	private Integer labelSize;
	private String nombre;
	private Boolean moduloFisico;
	private boolean contenedorIconos;
	private String codebase;
	private String descripcion;
	private String grupo;
	private Long idEntidad;
	private boolean necesitaActivacion;
	private boolean activo;
	private Set<ProcesoDesplegado> procesoDesplegados = new HashSet<ProcesoDesplegado>(
			0);

	public Modulo() {
	}

	public Modulo(Long id, int orden, String imagen, boolean esModulo,
			boolean contenedorIconos, boolean necesitaActivacion, boolean activo) {
		this.id = id;
		this.orden = orden;
		this.imagen = imagen;
		this.esModulo = esModulo;
		this.contenedorIconos = contenedorIconos;
		this.necesitaActivacion = necesitaActivacion;
		this.activo = activo;
	}

	public Modulo(Long id, String label, String url, Boolean eliminado,
			Long cid, int orden, String imagen, boolean esModulo,
			Long idFuncionalidadPadre, Integer labelSize, String nombre,
			Boolean moduloFisico, boolean contenedorIconos, String codebase,
			String descripcion, String grupo, Long idEntidad,
			boolean necesitaActivacion, boolean activo,
			Set<ProcesoDesplegado> procesoDesplegados) {
		this.id = id;
		this.label = label;
		this.url = url;
		this.eliminado = eliminado;
		this.cid = cid;
		this.orden = orden;
		this.imagen = imagen;
		this.esModulo = esModulo;
		this.idFuncionalidadPadre = idFuncionalidadPadre;
		this.labelSize = labelSize;
		this.nombre = nombre;
		this.moduloFisico = moduloFisico;
		this.contenedorIconos = contenedorIconos;
		this.codebase = codebase;
		this.descripcion = descripcion;
		this.grupo = grupo;
		this.idEntidad = idEntidad;
		this.necesitaActivacion = necesitaActivacion;
		this.activo = activo;
		this.procesoDesplegados = procesoDesplegados;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "label", length = 150)
	@Length(max = 150)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "orden", nullable = false)
	@NotNull
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "imagen", nullable = false)
	@NotNull
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "es_modulo", nullable = false)
	@NotNull
	public boolean isEsModulo() {
		return this.esModulo;
	}

	public void setEsModulo(boolean esModulo) {
		this.esModulo = esModulo;
	}

	@Column(name = "id_funcionalidad_padre")
	public Long getIdFuncionalidadPadre() {
		return this.idFuncionalidadPadre;
	}

	public void setIdFuncionalidadPadre(Long idFuncionalidadPadre) {
		this.idFuncionalidadPadre = idFuncionalidadPadre;
	}

	@Column(name = "label_size")
	public Integer getLabelSize() {
		return this.labelSize;
	}

	public void setLabelSize(Integer labelSize) {
		this.labelSize = labelSize;
	}

	@Column(name = "nombre", unique = true)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "modulo_fisico")
	public Boolean getModuloFisico() {
		return this.moduloFisico;
	}

	public void setModuloFisico(Boolean moduloFisico) {
		this.moduloFisico = moduloFisico;
	}

	@Column(name = "contenedor_iconos", nullable = false)
	@NotNull
	public boolean isContenedorIconos() {
		return this.contenedorIconos;
	}

	public void setContenedorIconos(boolean contenedorIconos) {
		this.contenedorIconos = contenedorIconos;
	}

	@Column(name = "codebase")
	public String getCodebase() {
		return this.codebase;
	}

	public void setCodebase(String codebase) {
		this.codebase = codebase;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "grupo")
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "id_entidad")
	public Long getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(Long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Column(name = "necesita_activacion", nullable = false)
	@NotNull
	public boolean isNecesitaActivacion() {
		return this.necesitaActivacion;
	}

	public void setNecesitaActivacion(boolean necesitaActivacion) {
		this.necesitaActivacion = necesitaActivacion;
	}

	@Column(name = "activo", nullable = false)
	@NotNull
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcionalidad")
	public Set<ProcesoDesplegado> getProcesoDesplegados() {
		return this.procesoDesplegados;
	}

	public void setProcesoDesplegados(Set<ProcesoDesplegado> procesoDesplegados) {
		this.procesoDesplegados = procesoDesplegados;
	}

}
