package gehos.comun.procesos.entity;

// Generated 05-mar-2010 16:29:39 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * ProcesoDesplegado generated by hbm2java
 */
@Entity
@Table(name = "proceso_desplegado", schema = "comun")
public class ProcesoDesplegado implements java.io.Serializable {

	private Long id;
	private Integer version;
	private Modulo funcionalidad;
	private String nombreProceso;
	private Integer revision;
	private Boolean tieneReglas;

	public ProcesoDesplegado() {
	}

	public ProcesoDesplegado(Long id) {
		this.id = id;
	}

	public ProcesoDesplegado(Long id, Modulo funcionalidad,
			String nombreProceso, Integer revision) {
		this.id = id;
		this.funcionalidad = funcionalidad;
		this.nombreProceso = nombreProceso;
		this.revision = revision;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	//@NotNull
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modulo")
	public Modulo getFuncionalidad() {
		return this.funcionalidad;
	}

	public void setFuncionalidad(Modulo funcionalidad) {
		this.funcionalidad = funcionalidad;
	}

	@Column(name = "nombre_proceso")
	public String getNombreProceso() {
		return this.nombreProceso;
	}

	public void setNombreProceso(String nombreProceso) {
		this.nombreProceso = nombreProceso;
	}

	@Column(name = "revision")
	public Integer getRevision() {
		return this.revision;
	}

	public void setRevision(Integer revision) {
		this.revision = revision;
	}

	@Column(name = "tiene_reglas")
	public Boolean getTieneReglas() {
		return tieneReglas;
	}

	public void setTieneReglas(Boolean tieneReglas) {
		this.tieneReglas = tieneReglas;
	}

}
