package gehos.comun.datoslab.entity;

// Generated Sep 1, 2011 1:40:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * DatosLaborales generated by hbm2java
 */
@Entity
@Table(name = "datos_laborales", schema = "hc_local")
public class DatosLaborales implements java.io.Serializable {

	private long id;
	private DivisionPersonal divisionPersonal;
	private Sociedad sociedad;
	private Division division;
	private SubdivisionPersonal subdivisionPersonal;
	private GrupoPersonal grupoPersonal;
	private EstadoLaboral estadoLaboral;
	private Formacion formacion;
	private TipoNomina tipoNomina;
	private UnidadOrganizativa unidadOrganizativa;
	private ManoDominante manoDominante;
	private TipoZonaLaboral tipoZonaLaboral;
	private Posicion posicion;
	private String telefonoOficina;
	private String numeroPersonal;
	private Boolean aseguradoIvss;
	private Integer numHijos;
	private Long cid;
	private Date tiempoServicio;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public DatosLaborales() {
	}

	public DatosLaborales(long id) {
		this.id = id;
	}

	public DatosLaborales(long id, DivisionPersonal divisionPersonal,
			Sociedad sociedad, Division division,
			SubdivisionPersonal subdivisionPersonal,
			GrupoPersonal grupoPersonal, EstadoLaboral estadoLaboral,
			Formacion formacion, TipoNomina tipoNomina,
			UnidadOrganizativa unidadOrganizativa, ManoDominante manoDominante,
			TipoZonaLaboral tipoZonaLaboral, Posicion posicion,
			String telefonoOficina, String numeroPersonal,
			Boolean aseguradoIvss, Integer numHijos, Long cid,
			Date tiempoServicio, Set<Persona> personas) {
		this.id = id;
		this.divisionPersonal = divisionPersonal;
		this.sociedad = sociedad;
		this.division = division;
		this.subdivisionPersonal = subdivisionPersonal;
		this.grupoPersonal = grupoPersonal;
		this.estadoLaboral = estadoLaboral;
		this.formacion = formacion;
		this.tipoNomina = tipoNomina;
		this.unidadOrganizativa = unidadOrganizativa;
		this.manoDominante = manoDominante;
		this.tipoZonaLaboral = tipoZonaLaboral;
		this.posicion = posicion;
		this.telefonoOficina = telefonoOficina;
		this.numeroPersonal = numeroPersonal;
		this.aseguradoIvss = aseguradoIvss;
		this.numHijos = numHijos;
		this.cid = cid;
		this.tiempoServicio = tiempoServicio;
		this.personas = personas;
	}

	@Id
	@Column(name = "id", unique = true)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_division_personal")
	public DivisionPersonal getDivisionPersonal() {
		return this.divisionPersonal;
	}

	public void setDivisionPersonal(DivisionPersonal divisionPersonal) {
		this.divisionPersonal = divisionPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sociedad")
	public Sociedad getSociedad() {
		return this.sociedad;
	}

	public void setSociedad(Sociedad sociedad) {
		this.sociedad = sociedad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_division")
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_subdivision_personal")
	public SubdivisionPersonal getSubdivisionPersonal() {
		return this.subdivisionPersonal;
	}

	public void setSubdivisionPersonal(SubdivisionPersonal subdivisionPersonal) {
		this.subdivisionPersonal = subdivisionPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_personal")
	public GrupoPersonal getGrupoPersonal() {
		return this.grupoPersonal;
	}

	public void setGrupoPersonal(GrupoPersonal grupoPersonal) {
		this.grupoPersonal = grupoPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_laboral")
	public EstadoLaboral getEstadoLaboral() {
		return this.estadoLaboral;
	}

	public void setEstadoLaboral(EstadoLaboral estadoLaboral) {
		this.estadoLaboral = estadoLaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formacion")
	public Formacion getFormacion() {
		return this.formacion;
	}

	public void setFormacion(Formacion formacion) {
		this.formacion = formacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_area_personal")
	public TipoNomina getTipoNomina() {
		return this.tipoNomina;
	}

	public void setTipoNomina(TipoNomina tipoNomina) {
		this.tipoNomina = tipoNomina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidad_organizativa")
	public UnidadOrganizativa getUnidadOrganizativa() {
		return this.unidadOrganizativa;
	}

	public void setUnidadOrganizativa(UnidadOrganizativa unidadOrganizativa) {
		this.unidadOrganizativa = unidadOrganizativa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mano_dominante")
	public ManoDominante getManoDominante() {
		return this.manoDominante;
	}

	public void setManoDominante(ManoDominante manoDominante) {
		this.manoDominante = manoDominante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_zona_laboral")
	public TipoZonaLaboral getTipoZonaLaboral() {
		return this.tipoZonaLaboral;
	}

	public void setTipoZonaLaboral(TipoZonaLaboral tipoZonaLaboral) {
		this.tipoZonaLaboral = tipoZonaLaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_posicion")
	public Posicion getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion posicion) {
		this.posicion = posicion;
	}

	@Column(name = "telefono_oficina")
	public String getTelefonoOficina() {
		return this.telefonoOficina;
	}

	public void setTelefonoOficina(String telefonoOficina) {
		this.telefonoOficina = telefonoOficina;
	}

	@Column(name = "numero_personal")
	public String getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(String numeroPersonal) {
		this.numeroPersonal = numeroPersonal;
	}

	@Column(name = "asegurado_ivss")
	public Boolean getAseguradoIvss() {
		return this.aseguradoIvss;
	}

	public void setAseguradoIvss(Boolean aseguradoIvss) {
		this.aseguradoIvss = aseguradoIvss;
	}

	@Column(name = "num_hijos")
	public Integer getNumHijos() {
		return this.numHijos;
	}

	public void setNumHijos(Integer numHijos) {
		this.numHijos = numHijos;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tiempo_servicio", length = 13)
	public Date getTiempoServicio() {
		return this.tiempoServicio;
	}

	public void setTiempoServicio(Date tiempoServicio) {
		this.tiempoServicio = tiempoServicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosLaborales")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
