package gehos.comun.datoslab.entity;

// Generated Sep 1, 2011 1:40:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Formacion generated by hbm2java
 */
@Entity
@Table(name = "formacion", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "codigo_sap"),
		@UniqueConstraint(columnNames = "codigo") })
public class Formacion implements java.io.Serializable {

	private long id;
	private Integer version;
	private String codigo;
	private String valor;
	private Long cid;
	private Boolean eliminado;
	private String codigoSap;
	private Set<DatosLaborales> datosLaboraleses = new HashSet<DatosLaborales>(
			0);

	public Formacion() {
	}

	public Formacion(long id, String codigo, String valor) {
		this.id = id;
		this.codigo = codigo;
		this.valor = valor;
	}

	public Formacion(long id, String codigo, String valor, Long cid,
			Boolean eliminado, String codigoSap,
			Set<DatosLaborales> datosLaboraleses) {
		this.id = id;
		this.codigo = codigo;
		this.valor = valor;
		this.cid = cid;
		this.eliminado = eliminado;
		this.codigoSap = codigoSap;
		this.datosLaboraleses = datosLaboraleses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "codigo", unique = true, nullable = false)
	@NotNull
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "valor", nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "codigo_sap", unique = true)
	public String getCodigoSap() {
		return this.codigoSap;
	}

	public void setCodigoSap(String codigoSap) {
		this.codigoSap = codigoSap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formacion")
	public Set<DatosLaborales> getDatosLaboraleses() {
		return this.datosLaboraleses;
	}

	public void setDatosLaboraleses(Set<DatosLaborales> datosLaboraleses) {
		this.datosLaboraleses = datosLaboraleses;
	}

}
