package gehos.comun.datoslab.entity;

// Generated Sep 1, 2011 1:40:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "hc_local")
public class Persona implements java.io.Serializable {

	private long id;
	private Integer version;
	private DatosLaborales datosLaborales;
	private Persona personaByIdDatosPadre;
	private Persona personaByIdDatosSupervisor;
	private Persona personaByIdDatosRepresentante;
	private Persona personaByIdDatosMadre;
	private String cedula;
	private String foto;
	private String nombres;
	private String apellido1;
	private String apellido2;
	private Date fechaNacimiento;
	private Long idRaza;
	private Long idEtnia;
	private Long idNacion;
	private Long idEstadoCivil;
	private String correoElectronico;
	private Long idLugarNacimiento;
	private Long idDireccionParticular;
	private Long idLugarResidencia;
	private String telfFijo;
	private String telfCelular;
	private Long idSexo;
	private String nombresFonetico;
	private String apellido1Fonetico;
	private String apellido2Fonetico;
	private Boolean eliminado;
	private Long cid;
	private Set<Persona> personasForIdDatosSupervisor = new HashSet<Persona>(0);
	private Set<Persona> personasForIdDatosMadre = new HashSet<Persona>(0);
	private Set<TitularBeneficiario> titularBeneficiariosForIdTitular = new HashSet<TitularBeneficiario>(
			0);
	private Set<Persona> personasForIdDatosPadre = new HashSet<Persona>(0);
	private Set<Usuario_datoslab> usuarios = new HashSet<Usuario_datoslab>(0);
	private Set<TitularBeneficiario> titularBeneficiariosForIdBeneficiario = new HashSet<TitularBeneficiario>(
			0);
	private Set<Persona> personasForIdDatosRepresentante = new HashSet<Persona>(
			0);

	public Persona() {
	}

	public Persona(long id) {
		this.id = id;
	}

	public Persona(long id, DatosLaborales datosLaborales,
			Persona personaByIdDatosPadre, Persona personaByIdDatosSupervisor,
			Persona personaByIdDatosRepresentante,
			Persona personaByIdDatosMadre, String cedula, String foto,
			String nombres, String apellido1, String apellido2,
			Date fechaNacimiento, Long idRaza, Long idEtnia, Long idNacion,
			Long idEstadoCivil, String correoElectronico,
			Long idLugarNacimiento, Long idDireccionParticular,
			Long idLugarResidencia, String telfFijo, String telfCelular,
			Long idSexo, String nombresFonetico, String apellido1Fonetico,
			String apellido2Fonetico, Boolean eliminado, Long cid,
			Set<Persona> personasForIdDatosSupervisor,
			Set<Persona> personasForIdDatosMadre,
			Set<TitularBeneficiario> titularBeneficiariosForIdTitular,
			Set<Persona> personasForIdDatosPadre, Set<Usuario_datoslab> usuarios,
			Set<TitularBeneficiario> titularBeneficiariosForIdBeneficiario,
			Set<Persona> personasForIdDatosRepresentante) {
		this.id = id;
		this.datosLaborales = datosLaborales;
		this.personaByIdDatosPadre = personaByIdDatosPadre;
		this.personaByIdDatosSupervisor = personaByIdDatosSupervisor;
		this.personaByIdDatosRepresentante = personaByIdDatosRepresentante;
		this.personaByIdDatosMadre = personaByIdDatosMadre;
		this.cedula = cedula;
		this.foto = foto;
		this.nombres = nombres;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.fechaNacimiento = fechaNacimiento;
		this.idRaza = idRaza;
		this.idEtnia = idEtnia;
		this.idNacion = idNacion;
		this.idEstadoCivil = idEstadoCivil;
		this.correoElectronico = correoElectronico;
		this.idLugarNacimiento = idLugarNacimiento;
		this.idDireccionParticular = idDireccionParticular;
		this.idLugarResidencia = idLugarResidencia;
		this.telfFijo = telfFijo;
		this.telfCelular = telfCelular;
		this.idSexo = idSexo;
		this.nombresFonetico = nombresFonetico;
		this.apellido1Fonetico = apellido1Fonetico;
		this.apellido2Fonetico = apellido2Fonetico;
		this.eliminado = eliminado;
		this.cid = cid;
		this.personasForIdDatosSupervisor = personasForIdDatosSupervisor;
		this.personasForIdDatosMadre = personasForIdDatosMadre;
		this.titularBeneficiariosForIdTitular = titularBeneficiariosForIdTitular;
		this.personasForIdDatosPadre = personasForIdDatosPadre;
		this.usuarios = usuarios;
		this.titularBeneficiariosForIdBeneficiario = titularBeneficiariosForIdBeneficiario;
		this.personasForIdDatosRepresentante = personasForIdDatosRepresentante;
	}

	@Id
	@Column(name = "id", unique = true)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_laborales")
	public DatosLaborales getDatosLaborales() {
		return this.datosLaborales;
	}

	public void setDatosLaborales(DatosLaborales datosLaborales) {
		this.datosLaborales = datosLaborales;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_padre")
	public Persona getPersonaByIdDatosPadre() {
		return this.personaByIdDatosPadre;
	}

	public void setPersonaByIdDatosPadre(Persona personaByIdDatosPadre) {
		this.personaByIdDatosPadre = personaByIdDatosPadre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_supervisor")
	public Persona getPersonaByIdDatosSupervisor() {
		return this.personaByIdDatosSupervisor;
	}

	public void setPersonaByIdDatosSupervisor(Persona personaByIdDatosSupervisor) {
		this.personaByIdDatosSupervisor = personaByIdDatosSupervisor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_representante")
	public Persona getPersonaByIdDatosRepresentante() {
		return this.personaByIdDatosRepresentante;
	}

	public void setPersonaByIdDatosRepresentante(
			Persona personaByIdDatosRepresentante) {
		this.personaByIdDatosRepresentante = personaByIdDatosRepresentante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_datos_madre")
	public Persona getPersonaByIdDatosMadre() {
		return this.personaByIdDatosMadre;
	}

	public void setPersonaByIdDatosMadre(Persona personaByIdDatosMadre) {
		this.personaByIdDatosMadre = personaByIdDatosMadre;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "foto")
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Column(name = "nombres")
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellido1")
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2")
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "id_raza")
	public Long getIdRaza() {
		return this.idRaza;
	}

	public void setIdRaza(Long idRaza) {
		this.idRaza = idRaza;
	}

	@Column(name = "id_etnia")
	public Long getIdEtnia() {
		return this.idEtnia;
	}

	public void setIdEtnia(Long idEtnia) {
		this.idEtnia = idEtnia;
	}

	@Column(name = "id_nacion")
	public Long getIdNacion() {
		return this.idNacion;
	}

	public void setIdNacion(Long idNacion) {
		this.idNacion = idNacion;
	}

	@Column(name = "id_estado_civil")
	public Long getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(Long idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	@Column(name = "correo_electronico")
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "id_lugar_nacimiento")
	public Long getIdLugarNacimiento() {
		return this.idLugarNacimiento;
	}

	public void setIdLugarNacimiento(Long idLugarNacimiento) {
		this.idLugarNacimiento = idLugarNacimiento;
	}

	@Column(name = "id_direccion_particular")
	public Long getIdDireccionParticular() {
		return this.idDireccionParticular;
	}

	public void setIdDireccionParticular(Long idDireccionParticular) {
		this.idDireccionParticular = idDireccionParticular;
	}

	@Column(name = "id_lugar_residencia")
	public Long getIdLugarResidencia() {
		return this.idLugarResidencia;
	}

	public void setIdLugarResidencia(Long idLugarResidencia) {
		this.idLugarResidencia = idLugarResidencia;
	}

	@Column(name = "telf_fijo", length = 100)
	@Length(max = 100)
	public String getTelfFijo() {
		return this.telfFijo;
	}

	public void setTelfFijo(String telfFijo) {
		this.telfFijo = telfFijo;
	}

	@Column(name = "telf_celular", length = 100)
	@Length(max = 100)
	public String getTelfCelular() {
		return this.telfCelular;
	}

	public void setTelfCelular(String telfCelular) {
		this.telfCelular = telfCelular;
	}

	@Column(name = "id_sexo")
	public Long getIdSexo() {
		return this.idSexo;
	}

	public void setIdSexo(Long idSexo) {
		this.idSexo = idSexo;
	}

	@Column(name = "nombres_fonetico", length = 100)
	@Length(max = 100)
	public String getNombresFonetico() {
		return this.nombresFonetico;
	}

	public void setNombresFonetico(String nombresFonetico) {
		this.nombresFonetico = nombresFonetico;
	}

	@Column(name = "apellido1_fonetico", length = 100)
	@Length(max = 100)
	public String getApellido1Fonetico() {
		return this.apellido1Fonetico;
	}

	public void setApellido1Fonetico(String apellido1Fonetico) {
		this.apellido1Fonetico = apellido1Fonetico;
	}

	@Column(name = "apellido2_fonetico", length = 100)
	@Length(max = 100)
	public String getApellido2Fonetico() {
		return this.apellido2Fonetico;
	}

	public void setApellido2Fonetico(String apellido2Fonetico) {
		this.apellido2Fonetico = apellido2Fonetico;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdDatosSupervisor")
	public Set<Persona> getPersonasForIdDatosSupervisor() {
		return this.personasForIdDatosSupervisor;
	}

	public void setPersonasForIdDatosSupervisor(
			Set<Persona> personasForIdDatosSupervisor) {
		this.personasForIdDatosSupervisor = personasForIdDatosSupervisor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdDatosMadre")
	public Set<Persona> getPersonasForIdDatosMadre() {
		return this.personasForIdDatosMadre;
	}

	public void setPersonasForIdDatosMadre(Set<Persona> personasForIdDatosMadre) {
		this.personasForIdDatosMadre = personasForIdDatosMadre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdTitular")
	public Set<TitularBeneficiario> getTitularBeneficiariosForIdTitular() {
		return this.titularBeneficiariosForIdTitular;
	}

	public void setTitularBeneficiariosForIdTitular(
			Set<TitularBeneficiario> titularBeneficiariosForIdTitular) {
		this.titularBeneficiariosForIdTitular = titularBeneficiariosForIdTitular;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdDatosPadre")
	public Set<Persona> getPersonasForIdDatosPadre() {
		return this.personasForIdDatosPadre;
	}

	public void setPersonasForIdDatosPadre(Set<Persona> personasForIdDatosPadre) {
		this.personasForIdDatosPadre = personasForIdDatosPadre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Usuario_datoslab> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario_datoslab> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdBeneficiario")
	public Set<TitularBeneficiario> getTitularBeneficiariosForIdBeneficiario() {
		return this.titularBeneficiariosForIdBeneficiario;
	}

	public void setTitularBeneficiariosForIdBeneficiario(
			Set<TitularBeneficiario> titularBeneficiariosForIdBeneficiario) {
		this.titularBeneficiariosForIdBeneficiario = titularBeneficiariosForIdBeneficiario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdDatosRepresentante")
	public Set<Persona> getPersonasForIdDatosRepresentante() {
		return this.personasForIdDatosRepresentante;
	}

	public void setPersonasForIdDatosRepresentante(
			Set<Persona> personasForIdDatosRepresentante) {
		this.personasForIdDatosRepresentante = personasForIdDatosRepresentante;
	}

}
