package gehos.comun.datoslab.entity;

// Generated Sep 1, 2011 1:40:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.NotNull;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "valor"),
		@UniqueConstraint(columnNames = "codigo") })
public class Status implements java.io.Serializable {

	private long id;
	private Integer version;
	private String codigo;
	private String valor;
	private Boolean eliminado;
	private Long cid;

	public Status() {
	}

	public Status(long id, String codigo, String valor) {
		this.id = id;
		this.codigo = codigo;
		this.valor = valor;
	}

	public Status(long id, String codigo, String valor, Boolean eliminado,
			Long cid) {
		this.id = id;
		this.codigo = codigo;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "codigo", unique = true, nullable = false)
	@NotNull
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

}
