package gehos.comun.datoslab.entity;

// Generated Sep 1, 2011 1:40:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * TitularBeneficiario generated by hbm2java
 */
@Entity
@Table(name = "titular_beneficiario", schema = "hc_local")
public class TitularBeneficiario implements java.io.Serializable {

	private long id;
	private Persona personaByIdBeneficiario;
	private Persona personaByIdTitular;
	private Long cid;
	private Boolean benefPlanSalud;
	private Long idParentesco;

	public TitularBeneficiario() {
	}

	public TitularBeneficiario(long id, Persona personaByIdBeneficiario,
			Persona personaByIdTitular) {
		this.id = id;
		this.personaByIdBeneficiario = personaByIdBeneficiario;
		this.personaByIdTitular = personaByIdTitular;
	}

	public TitularBeneficiario(long id, Persona personaByIdBeneficiario,
			Persona personaByIdTitular, Long cid, Boolean benefPlanSalud,
			Long idParentesco) {
		this.id = id;
		this.personaByIdBeneficiario = personaByIdBeneficiario;
		this.personaByIdTitular = personaByIdTitular;
		this.cid = cid;
		this.benefPlanSalud = benefPlanSalud;
		this.idParentesco = idParentesco;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_beneficiario", nullable = false)
	@NotNull
	public Persona getPersonaByIdBeneficiario() {
		return this.personaByIdBeneficiario;
	}

	public void setPersonaByIdBeneficiario(Persona personaByIdBeneficiario) {
		this.personaByIdBeneficiario = personaByIdBeneficiario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_titular", nullable = false)
	@NotNull
	public Persona getPersonaByIdTitular() {
		return this.personaByIdTitular;
	}

	public void setPersonaByIdTitular(Persona personaByIdTitular) {
		this.personaByIdTitular = personaByIdTitular;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "benef_plan_salud")
	public Boolean getBenefPlanSalud() {
		return this.benefPlanSalud;
	}

	public void setBenefPlanSalud(Boolean benefPlanSalud) {
		this.benefPlanSalud = benefPlanSalud;
	}

	@Column(name = "id_parentesco")
	public Long getIdParentesco() {
		return this.idParentesco;
	}

	public void setIdParentesco(Long idParentesco) {
		this.idParentesco = idParentesco;
	}

}
