package gehos.comun.datoslab.entity;

// Generated Sep 1, 2011 1:40:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * UnidadTiempo generated by hbm2java
 */
@Entity
@Table(name = "unidad_tiempo", schema = "nomencladores", uniqueConstraints = {
		@UniqueConstraint(columnNames = "valor"),
		@UniqueConstraint(columnNames = "abreviatura") })
public class UnidadTiempo implements java.io.Serializable {

	private long id;
	private Integer version;
	private String valor;
	private Boolean eliminado;
	private Long cid;
	private String codigo;
	private String abreviatura;

	public UnidadTiempo() {
	}

	public UnidadTiempo(long id, String valor, String abreviatura) {
		this.id = id;
		this.valor = valor;
		this.abreviatura = abreviatura;
	}

	public UnidadTiempo(long id, String valor, Boolean eliminado, Long cid,
			String codigo, String abreviatura) {
		this.id = id;
		this.valor = valor;
		this.eliminado = eliminado;
		this.cid = cid;
		this.codigo = codigo;
		this.abreviatura = abreviatura;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "valor", unique = true, nullable = false)
	@NotNull
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "abreviatura", unique = true, nullable = false, length = 6)
	@NotNull
	@Length(max = 6)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

}
