package gehos.comun.datoslab.entity;

// Generated Sep 1, 2011 1:40:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "comun", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Usuario_datoslab implements java.io.Serializable {

	private long id;
	private Integer version;
	private Persona persona;
	private String nombre;
	private String username;
	private String password;
	private Date fechaNacimiento;
	private Boolean eliminado;
	private Long cid;
	private Boolean cuentaHabilitada;
	private String primerApellido;
	private String segundoApellido;
	private String direccionParticular;
	private String cedula;
	private String pasaporte;
	private String telefono;
	private Long idTipoIdentidad;
	private Long idProfile;
	private String idRis;

	public Usuario_datoslab() {
	}

	public Usuario_datoslab(long id, String nombre, String username, String password) {
		this.id = id;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
	}

	public Usuario_datoslab(long id, Persona persona, String nombre, String username,
			String password, Date fechaNacimiento, Boolean eliminado, Long cid,
			Boolean cuentaHabilitada, String primerApellido,
			String segundoApellido, String direccionParticular, String cedula,
			String pasaporte, String telefono, Long idTipoIdentidad,
			Long idProfile, String idRis) {
		this.id = id;
		this.persona = persona;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
		this.fechaNacimiento = fechaNacimiento;
		this.eliminado = eliminado;
		this.cid = cid;
		this.cuentaHabilitada = cuentaHabilitada;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.direccionParticular = direccionParticular;
		this.cedula = cedula;
		this.pasaporte = pasaporte;
		this.telefono = telefono;
		this.idTipoIdentidad = idTipoIdentidad;
		this.idProfile = idProfile;
		this.idRis = idRis;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "nombre", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "username", unique = true, nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "eliminado")
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "cid")
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

	@Column(name = "cuenta_habilitada")
	public Boolean getCuentaHabilitada() {
		return this.cuentaHabilitada;
	}

	public void setCuentaHabilitada(Boolean cuentaHabilitada) {
		this.cuentaHabilitada = cuentaHabilitada;
	}

	@Column(name = "primer_apellido")
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido")
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "direccion_particular")
	public String getDireccionParticular() {
		return this.direccionParticular;
	}

	public void setDireccionParticular(String direccionParticular) {
		this.direccionParticular = direccionParticular;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "pasaporte")
	public String getPasaporte() {
		return this.pasaporte;
	}

	public void setPasaporte(String pasaporte) {
		this.pasaporte = pasaporte;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "id_tipo_identidad")
	public Long getIdTipoIdentidad() {
		return this.idTipoIdentidad;
	}

	public void setIdTipoIdentidad(Long idTipoIdentidad) {
		this.idTipoIdentidad = idTipoIdentidad;
	}

	@Column(name = "id_profile")
	public Long getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(Long idProfile) {
		this.idProfile = idProfile;
	}

	@Column(name = "id_ris", length = 36)
	@Length(max = 36)
	public String getIdRis() {
		return this.idRis;
	}

	public void setIdRis(String idRis) {
		this.idRis = idRis;
	}

}
